### ISSUE TITLE
Footer is not sticky at the bottom of the page.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#100]
![image](https://user-images.githubusercontent.com/900565/71666886-838c9300-2d6b-11ea-8012-27b373d1d3d0.png)

**Comment by kkellydesign** [comment]
This is in: 
<img width="1605" alt="Screen Shot 2020-01-03 at 9 41 33 AM" src="https://user-images.githubusercontent.com/202590/71729274-437dec80-2e0d-11ea-81a2-607f0028c8f0.png">
https://github.com/mozilla/kitsune/pull/4106
