### ISSUE TITLE
Add featured articles functionality

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#102]

**Comment by kkellydesign** [comment]
The static code for this can be found at kitsune/landings/jinja2/landings/includes/featured_articles.html – frontend is done, it just needs wired up to the backend.

**Comment by kkellydesign** [comment]
This is in: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
@akatsoulas  can you please let me know what needs to be verified here? Thanks

**Comment by kkellydesign** [comment]
@ovidiuboca1 The "Featured Articles" area of the homepage now has the correct data: 

https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
The "Featured Articles" area has the correct data, the articles have the correct links.
