### ISSUE TITLE
The UI when composing messages is broken.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#103]
Navigate to /messages when logged in. Compose a new message and try to select a user to send the message to. The UI is not rendered properly.

**Comment by kkellydesign** [comment]
All JS and CSS for this view are rendered correctly. This will be in when https://github.com/mozilla/kitsune/pull/4138 goes live.

**Comment by ovidiuboca1** [comment]
I verified this issue on the test environment https://test.sumo.mozit.cloud/en-US/messages/new , but I still see some issues related to the UI display. Please see the screen recording
https://streamable.com/tijg6

**Comment by kkellydesign** [comment]
I need an account on the testing server before I can test this thoroughly – the testing data that I have locally looks good.

**Comment by kkellydesign** [comment]
This is fixed in https://github.com/mozilla/kitsune/pull/4150

<img width="338" alt="Screen Shot 2020-01-30 at 9 01 50 AM" src="https://user-images.githubusercontent.com/202590/73489686-03ad1500-4379-11ea-95ec-373cdfbc58c6.png">

**Comment by ovidiuboca1** [comment]
I verified this and I can confirm that the user avatar is rendered correctly.
