### ISSUE TITLE
FxA Hub Page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#104]
[Project Brief ](https://docs.google.com/document/d/1Q4x9EU6U4U3g7fg96i86JYBgLnqHykv43zJXMqJXSQ0/edit?usp=sharing)

Page design using redesign template for hub pages. WIP

**Comment by jess-cook03** [comment]
Designs for this page have been created.

We have had a meeting with FxA settings team and there is a plan for implementation.

(Phil & Alex) Have confirmed with engineers to add a generic link to support.mozilla.org (glocal treatment) for 1st release of fxa settings redesign and circle back to us

- [ ] Shortly after 1st release there is a plan to update the generic support.mozilla.org link with a direct link to the fxa hubs page MVP 

- [ ] (SUMO team) To investigate if any current fxa articles need to be updated - copy, content, etc. for 1st release generic link -- Joni

- [ ] With 1st release generic link: gathering data and metrics/learnings to create insights and use this to inform any further refinements to the fxa hub page MVP designs 

- [ ] Platform team to figure out where fxa hub page will live within sumo (product on home page or be considered a hidden product linkable/searchable)

- [ ] Platform team to implement fxa hub page / go live -- generate updated link for FxA settings

**Comment by akatsoulas** [comment]
Closing this issue as stale
