### ISSUE TITLE
Highlight "Localize this page" link when visiting a non-localized page

### ISSUE THREAD

**Issue by nukeador** [mozilla/sumo-project#109]
Let's say I access the following page in Spanish:

https://activate.mozilla.community/es/commonvoice

And the content is not localized (so I get the English text).

We should show front and center a link to the pontoon project in that locale to localize the site.

**Comment by akatsoulas** [comment]
I am closing this issue per the guidelines [0] and because there is a discussion to update to fluent in the future which may affect this ticket.

[0] https://github.com/mozilla/sumo-project
