### ISSUE TITLE
White screen of Death when looking at user's profiles through support.mozilla.org/admin

### ISSUE THREAD

**Issue by rtanglao** [mozilla/sumo-project#110]
### Steps to reproduce:

1. https://support.mozilla.org/admin/ and then click on "Profiles"
2. click on any user id e.g. https://support.mozilla.org/admin/users/profile/1631414/

### Expected Results

1. You see the user's profile including their email address if they opted-in to share their email

### Actual Results

1. White Screen of Death, no error message

Tested on:

1. Firefox 66.0.3 on Windows 10 build 1809
1. Firefox 66.0.3 OS X Mojave latest 10.14.4

**Comment by mirunacurtean** [comment]
Tested on the latest FF Release (79.0 )/ Nightly (81.0a1) on Windows pro 10  and macOS Mojave 10.14.6 on Prod and Stage and this issue no longer occurs. 
Marking it it closed.

**Comment by akatsoulas** [comment]
For reference, this was happening b/c the request was timing out while the drop-down field for the FK was populated. Recently we switched to select2 inputs with autocomplete that solves this problem.
