### ISSUE TITLE
List all the community tools for the responsive redesign

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#111]
We should identify all the contributor tooling that we need to port to responsive. We also need to list all the pages that are not working properly at the moment.

**Comment by kkellydesign** [comment]
The static code for this can be found at kitsune/landings/jinja2/landings/includes/featured_articles.html – frontend is done, it just needs wired up to the backend.

**Comment by kkellydesign** [comment]
Contributor tools are listed here: https://github.com/mozilla/sumo-project/issues/28

I'm working on the editing workflow now
