### ISSUE TITLE
[mobile] Product pages are not responsive

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#120]
**STR:**
1. Navigate to https://test.sumo.mozit.cloud/en-US/
2. Select a product

**Expected:**
Responsive product page is displayed, as per [designs](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5df85c4423c6e39930f742c4)

**Actual:**
Old product page is displayed 

![photo_2020-01-13_15-34-17](https://user-images.githubusercontent.com/5293100/72260029-911f0400-361a-11ea-9a06-43725e74019a.jpg)

**Env:**
iPhone X, iOS 13.3, Chrome, Firefox and Safari

**Comment by kkellydesign** [comment]
@akatsoulas Can you take care of this, or point me in the right direction for how to disable user agent template switching? The frontend is all ready for this to be completely disabled. This is the first example that has come up, but I'm sure there will be more.

**Comment by kkellydesign** [comment]
This can be closed when #2 is addressed

**Comment by kkellydesign** [comment]
Mobile designs are ready to QA now, as django-mobility and all of the old mobile templates have been removed.

**Comment by ovidiuboca1** [comment]
I tested on mobile devices and I can confirm the fix. 

I have one question @kkellydesign and @jess-cook03 : The text alignment for the "Frequent Topics" and "Featured Articles & Threads" should be center or to the left, in the designs the text has a center alignment but on the device, the text is in the left.

**Comment by jess-cook03** [comment]
@ovidiuboca1 I working to update all mocks to be left aligned on mobile --- keep left for now -- @kkellydesign
That being said I think this issue can be closed ?

**Comment by ovidiuboca1** [comment]
Sure, we can close it.
