### ISSUE TITLE
"Contributor Tools" menu options don't match the designs 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#121]
**STR:**
1. Login to https://test.sumo.mozit.cloud/en-US/
2. Hover over the "Contributor Tools" menu item

**Expected:**
Menu options for "Discussions" and "Tools" match the ones from the [design](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5dcef6a49c67013be56bdb07) and are in the same order as in the designs

**Actual:**
Menu options for "Discussions" and "Tools" are different from the [designs](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5dcef6a49c67013be56bdb07)

![nav menu options](https://user-images.githubusercontent.com/5293100/72422191-a4e97800-378a-11ea-9e9f-d022d67157d7.png)

CC @jess-cook03

**Comment by kkellydesign** [comment]
@viorelaioia @madasan For this one, I didn't have all of the URLs in the mockups, and they didn't line up exactly with what was on production. So what I did was leave all of the old ones that had URLs, and add the new ones that did not. If you could provide a list of all of the actual URLs that you want, I'll get them added. I just didn't want to lose the code for items that you might actually need.

**Comment by jonichan** [comment]
- Advanced search: https://support.mozilla.org/search/advanced
- Knowledge Base Dashboard: https://support.mozilla.org/contributors
- Media Gallery: https://support.mozilla.org/gallery/images
- Templates: https://support.mozilla.org/kb/category/60
- Recent Revisions: https://support.mozilla.org/en-US/kb/revisions?locale=en-US&users=&start=&end=
- Tag Admin - doesn't exist yet

**Comment by kkellydesign** [comment]
@jonichan These are all in, with two exceptions. I still need URLs for the following, from the mockups: 

Social Support Forum
New Contributors

The others will be live when https://github.com/mozilla/kitsune/pull/4177 goes up.

**Comment by kkellydesign** [comment]
The only todo items here are now duplicated on https://github.com/mozilla/sumo-project/issues/165, so I think we're safe to close this one.

**Comment by ovidiuboca1** [comment]
The initial issue from the description is fixed.
