### ISSUE TITLE
[mobile+tablet] "View More" button should be removed from "Featured Articles & Threads" section

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#124]
**Env:** 
iPad Pro, iOS 13.2.3, Firefox, Safari, Chrome
iPhone 7, iOS 13, Firefox, Safari, Chrome

**STR:**
1. Navigate to https://test.sumo.mozit.cloud/en-US/
2. Scroll down to  "Featured Articles & Threads" section

**Expected:**
"View More" button is not available, as user can scroll horizontally to see all available cards

**Actual:**
"View More" button is available, even though user can scroll horizontally to see all available cards. As per [designs](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5dd8d21a8e4c1a991509cf8f), the button should be available only in desktop.

![photo_2020-01-17_11-41-14](https://user-images.githubusercontent.com/5293100/72601592-5c62c380-391e-11ea-8002-81d85f96d629.jpg)

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/4150

<img width="509" alt="Screen Shot 2020-01-30 at 1 56 13 PM" src="https://user-images.githubusercontent.com/202590/73486370-00168f80-4373-11ea-89a1-f908b0c6514c.png">

**Comment by kkellydesign** [comment]
this is ready to test: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
I tested this on iPhone 8 plus, iPad and Sony phone (Android device) and the issue is fixed.
