### ISSUE TITLE
The "Sign out" button is missing 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#127]
Prerequisites: 
1. You need to be logged into your account to be able to test this issue 

STR:
1. Go to https://test.sumo.mozit.cloud/en-US/
2. Click on the account icon -the menu items are displayed and the "Sign out" button is there
3. Scroll down the page 

ER: The "Sign out" button is there
AR: The "Sign out" button is cut out

**Comment by akatsoulas** [comment]
Is this still an issue?

**Comment by ovidiuboca1** [comment]
The issue was fixed, I will close this.
