### ISSUE TITLE
The Log in/ Sign up button label is displayed incorrectly.  

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#13]
STR:

Prerequisites: You don't need to be logged in. 

1. Go to Mozilla Support page
2. Resize the browser window, shrink it. 

ER: The Log in/ Sign up button label is displayed correctly. 
AR: The Log in/ Sign up button label is displayed incorrectly.
![Screenshot 2019-12-12 at 17 36 59](https://user-images.githubusercontent.com/54845678/70726540-eb206700-1d06-11ea-87fd-29faed98258e.png)

**Comment by ovidiuboca1** [comment]
Retested and now the "Log in/ Sign up" button is replaced with a different icon (https://imgur.com/a/RWS61j6). The new icon is not actionable.

**Comment by jess-cook03** [comment]
@kkellydesign in addition to this ^ the copy globally for those buttons should change to 'Sign In/Up' as updated in the latest navigation [here](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5dc5fb057b5ffe22b05fd22c)

**Comment by kkellydesign** [comment]
We've run out of room for all of the buttons and the search bar as the user scrolls down the page, so I just removed the buttons on scroll. Let me know if this is an acceptable fix to this problem. 

New button text: 
<img width="442" alt="Screen Shot 2020-01-17 at 1 53 52 PM" src="https://user-images.githubusercontent.com/202590/72638211-f895c600-3930-11ea-8c2d-3610fc69e0d1.png">

on scroll at tablet size: 
<img width="811" alt="Screen Shot 2020-01-17 at 1 54 00 PM" src="https://user-images.githubusercontent.com/202590/72638225-00556a80-3931-11ea-9df5-197540aee766.png">

**Comment by jess-cook03** [comment]
@kkellydesign new button looks great
-- as for the scroll on navigation as you go down the page ... I think that is fine for now, removing them, as long as they stay persistent in the nav above.

**Comment by ovidiuboca1** [comment]
Verified on the staging site and the label button and the scroll behavior are fixed.
