### ISSUE TITLE
The "Results" section from the page footer is displayed in different way from the mockups [Search pages]

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#130]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/
2. Perform a search after a word, ex. firefox 
3. Scroll to the bottom of the page

ER: The Results section is displayed like in the mockups - https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e189569853c8c01a6248a73
AR: The results section is displayed like in this print-screen 
![Screenshot 2020-01-27 at 15 07 30](https://user-images.githubusercontent.com/54845678/73177101-c47f8980-4116-11ea-8add-8a2119a8ff55.png)

**Comment by kkellydesign** [comment]
These changes will be in when this PR is deployed. Please note though that my local database doesn't have enough articles to trigger the pagination, so I sort of built this blind. I built it in the styleguide and ported the code to the correct spot. If not, please reassign to me. It'll be in when this PR goes live: https://github.com/mozilla/kitsune/pull/4150

Here's what it looks like in the styleguide

<img width="973" alt="Screen Shot 2020-01-27 at 12 20 01 PM" src="https://user-images.githubusercontent.com/202590/73197778-e91c3700-40ff-11ea-8bde-778479e161eb.png">
<img width="343" alt="Screen Shot 2020-01-27 at 12 20 07 PM" src="https://user-images.githubusercontent.com/202590/73197779-e91c3700-40ff-11ea-9d90-45d8e16cfde6.png">

**Comment by kkellydesign** [comment]
One minor fix will be in for this, where on the test server, it says "results untitled of 305." Other than that, this is ready for QA. I'll hold off on marking this as ready for now.

https://github.com/mozilla/kitsune/pull/4170

**Comment by ovidiuboca1** [comment]
This issue was tested and I can confirm the fix.
