### ISSUE TITLE
The item selected in the "Filter by product"section is deselected if the "Help Articles Only" is selected [Search pages]

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#132]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/
2. Perform a search after "firefox"
3. From the "Filter by product" section select Firefox for iOS
4. Select "Help Articles Only"

ER: The Firefox for iOS is still selected. The expected behavior is described here: https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e18956a49a6237dc1d71d20
AR: The Firefox for iOS is deselected.

**Comment by kkellydesign** [comment]
Same issue exists on production. I'm adding the "search upgrade" tag to all of these enhancements so we can discuss the plan for these tickets next week.

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4679 also fixes this

**Comment by mirunacurtean** [comment]
Verified fixed.
![no longer stuck in Help Articles](https://user-images.githubusercontent.com/53306802/108979730-9eb71200-7693-11eb-862f-d22c6df5bb4d.gif)
