### ISSUE TITLE
No results found - behaviour [Search pages]

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#134]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/
2. Perform a search after "mo"

ER: The message "Sorry! 0 results found for mo" is displayed.        mockups- https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e1cd98da87828a8c7934700
AR: The message "We couldn't find any results for ‘mo’ in ‘English’. Maybe one of these articles will be helpful? " is displayed.  
NOTE: Also the page UI is different from the one presented in the mockups.

**Comment by kkellydesign** [comment]
This layout is in and will be updated when this goes live: https://github.com/mozilla/kitsune/pull/4150


<img width="1234" alt="Screen Shot 2020-01-28 at 6 05 21 PM" src="https://user-images.githubusercontent.com/202590/73313277-cae63200-41f8-11ea-8aed-7f268fabd44b.png">

@akatsoulas I'll need a hand on the backend with this – I couldn't get the product name or "ask a question" URL to cooperate from the nunjucks template. You can see the "todo" item here: 

<img width="1222" alt="Screen Shot 2020-01-28 at 6 05 27 PM" src="https://user-images.githubusercontent.com/202590/73313278-cae63200-41f8-11ea-9fcb-5d1741ea7114.png">

**Comment by kkellydesign** [comment]
This is ready to be tested. Note the the icon links are broken currently – that will be fixed when https://github.com/mozilla/kitsune/pull/4170 goes live.

**Comment by kkellydesign** [comment]
@akatsoulas also note that this still needs some BE integration here (detailed above): https://github.com/mozilla/kitsune/blob/responsive-redesign/kitsune/sumo/static/sumo/tpl/search-results-list.html#L143-L147

**Comment by kkellydesign** [comment]
The copy was changed in the component in question, so my last todo item on this ticket isn't valid anymore. This is safe to be closed. 
<img width="738" alt="Screen Shot 2020-03-19 at 11 07 38 AM" src="https://user-images.githubusercontent.com/202590/77082086-f94ee500-69d1-11ea-9fa1-9a8adbe9743f.png">
