### ISSUE TITLE
UI Fix Volunteer/Community Module

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#135]
This component should be a direct pull from the protocol system as seen on moz.org .
- Included screenshots of testing environment, our sizing looks a little large when comparing them both. 
- Noted that the designs may have orginially specified this sizing because I had to replicate the component, but ideally it should just be 1:1 to what is already there.

![Screen Shot 2020-01-29 at 12 24 36 PM](https://user-images.githubusercontent.com/54991698/73380679-755e6380-4292-11ea-987a-88c17f244da7.png)
![Screen Shot 2020-01-29 at 12 24 29 PM](https://user-images.githubusercontent.com/54991698/73380680-755e6380-4292-11ea-960a-e54350da95c1.png)
**Illustration assets need to be provided by @jess-cook03 - Backlog item note**

**Comment by jess-cook03** [comment]
@kkellydesign another UI note with these modules --- these are Mozilla branded / content only pieces within our larger system -- they should be treated as such, meaning the type here will be Zilla Slab for these modules.

**Comment by kkellydesign** [comment]
This is fixed: 
<img width="1346" alt="Screen Shot 2020-01-31 at 3 24 17 PM" src="https://user-images.githubusercontent.com/202590/73572022-d24a4d00-443d-11ea-967f-c0b5b83971ae.png">

As is this: 
<img width="1344" alt="Screen Shot 2020-01-31 at 3 25 31 PM" src="https://user-images.githubusercontent.com/202590/73572082-f0b04880-443d-11ea-9eb8-8802a61cc508.png">

This will be in here: https://github.com/mozilla/kitsune/pull/4153

**Comment by kkellydesign** [comment]
This is in – you can see it here: https://test.sumo.mozit.cloud/en-US/

**Comment by jess-cook03** [comment]
@kkellydesign  ahhh sorry didn't see this ticket before I created a new one #183 please reference both!

**Comment by kkellydesign** [comment]
I think this one is safe to close, since there are no more action items here.

**Comment by jess-cook03** [comment]
Confirming this is done
