### ISSUE TITLE
There are some missing icons and the logo from the footer section of the Support Home page

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#14]
STR:

1. Go to Support Mozilla home page
2. Scroll to the bottom of the page

ER: In the left part you see the Mozilla logo and in the right part there are displayed the 3 icons from youtube, twitter, and Instagram.

AR: The Mozilla logo and the 3 icons from youtube, twitter, and Instagram are missing. 

Note: See the print-screen
![Screenshot 2019-12-12 at 16 15 40](https://user-images.githubusercontent.com/54845678/70724146-b9a59c80-1d02-11ea-930a-7ff69b6de774.png)

**Comment by kkellydesign** [comment]
This is related to #126 – These are all working locally. 
<img width="1311" alt="Screen Shot 2020-01-17 at 6 05 50 PM" src="https://user-images.githubusercontent.com/202590/72652263-0577e100-3954-11ea-8675-d16242de198d.png">

**Comment by kkellydesign** [comment]
ready for testing. https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
I verified this on https://test.sumo.mozit.cloud/en-US/ and the icons are in place and also the links are working.

**Comment by ovidiuboca1** [comment]
I tested this and the icons and logo are in place I also verified if they have the correct links. 

@kkellydesign  One thing that is bothering me is that when you click on any button from the footer, the entire button becomes white. Is there any way to make the button icon visible when is clicked?

**Comment by kkellydesign** [comment]
white-background active states on all footer links are disabled. ready for QA in https://github.com/mozilla/kitsune/pull/4177

**Comment by ovidiuboca1** [comment]
> white-background active states on all footer links are disabled. ready for QA
I tested this issue and the problem is still there.
