### ISSUE TITLE
AAQ // Question Form Page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#143]
Input and question submission pages 
<img width="1211" alt="Screen Shot 2020-01-31 at 5 12 42 PM" src="https://user-images.githubusercontent.com/54991698/73578155-ec3f5c00-444c-11ea-94b2-7223ac09e001.png">

**Comment by jess-cook03** [comment]
![Screen Shot 2020-01-30 at 12 08 25 PM](https://user-images.githubusercontent.com/54991698/73578049-ae423800-444c-11ea-8258-6ace93c83ee0.png)

**Comment by jess-cook03** [comment]
@kkellydesign @madasan design mock ups are now uploaded to Zeplin for this page: [see here](https://zpl.io/VK8r5kP)
Questions I have:
- [ ] @akatsoulas & @madasan can you share with me that community document that suggests any additional fields for this form? And also please comment with any thoughts on what is missing or what we can add here? Thanks!

- [ ] @kkellydesign do we have UI already for the tool tips? I know we have some smaller ones on hover (like in the forums) but specifically I'm thinking something a little bigger like whats in these mockups -- this would be something that can either be used with hover or have it open all the time (maybe conditionally for first time posters? these are just thoughts).

**Comment by jess-cook03** [comment]
Questions above have been answered -- disregard. 
@kkellydesign latest designs for this are here:[ Zeplin ](https://zpl.io/bAprXwP)
*Notes here:
-  the fields here are WIP mainly the ladder part of the page (everything under the add images section is being edited). 
- Hover/tooltip is being changed.
- adding in some type of confirmation interaction when user hits 'post' // Question here: is it possible to do something thats a quick loading - confirmed animation ... or any ideas for this?
We will have this on the next screen: https://zpl.io/VQ8AeJ5 (how it works today with the little message on top)

**Comment by akatsoulas** [comment]
This design is released in prod.
