### ISSUE TITLE
AAQ // Step 1-2 page designs + widget

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#145]
<img width="1115" alt="Screen Shot 2020-01-30 at 11 40 21 AM" src="https://user-images.githubusercontent.com/54991698/73470080-596fc600-4355-11ea-96b7-69aade274064.png">
Many pages include this new component that will directly route users to the form to submit their question, if they are not logged in/signed up they will be prompted to do so.

**Comment by jess-cook03** [comment]
Design Mockups are in for the first 2 steps of the flow & this new component! 
[See here on Zeplin](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5e56e6b6b54d1b673f33f96e)
@kkellydesign

**Comment by jess-cook03** [comment]
@kkellydesign ready to go!

**Comment by akatsoulas** [comment]
This design is released in prod.
