### ISSUE TITLE
In the search field the magnifying glass icon is missing

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#15]
STR:

1. Go to the Mozilla support page and observe the search field. 

ER: In the search field you see a magnifying glass icon. (please see the designs) 
AR: The magnifying glass icon is missing.

**Comment by kkellydesign** [comment]
This is related to https://github.com/mozilla/sumo-project/issues/126 – I'm seeing the magnifying glass locally. 

<img width="887" alt="Screen Shot 2020-01-17 at 5 51 31 PM" src="https://user-images.githubusercontent.com/202590/72651681-158ec100-3952-11ea-926d-a61be09beb72.png">
<img width="335" alt="Screen Shot 2020-01-17 at 5 51 38 PM" src="https://user-images.githubusercontent.com/202590/72651682-158ec100-3952-11ea-94be-dd3ab17a12ad.png">

**Comment by kkellydesign** [comment]
ready for testing: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
@kkellydesign 
@jess-cook03 
In the specs, https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard, the magnifying glass icon is in the left, on the testing environment is in the right. What is the expected alignment?

**Comment by kkellydesign** [comment]
Good question. I deviated from the design because I made the magnifying glass a button instead of just decoration. @jess-cook03 can have final say, but this makes more sense to me.
