### ISSUE TITLE
[Mobile] The user can't log in

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#150]
Prerequisites: 
 Use a mobile device or use the RDM to simulate a mobile device. 
You don't need to be log into your account. 

STR:

1. Go to https://test.sumo.mozit.cloud/en-US/
2. Click on the upper right icon (avatar icon) and try to log into your account 

ER: The login menu is displayed and you are able to log in. 
AR: The login menu is not displayed. 

NOTE: see the screen recording https://streamable.com/wl8q5
Maybe this issue was already logged and it is a duplicate, but I can't find it.

**Comment by ovidiuboca1** [comment]
@kkellydesign this issue is repro on your end?

**Comment by kkellydesign** [comment]
This was an issue with the javascript not working correctly on the testing server. This is ready to be tested again. This is what you should see when you click on the avatar: 

<img width="399" alt="Screen Shot 2020-02-11 at 10 53 00 AM" src="https://user-images.githubusercontent.com/202590/74253225-d0de1780-4cbc-11ea-86bf-57d872240474.png">

**Comment by ovidiuboca1** [comment]
Tested on iPhone 8 plus with FF browser and I can confirm the fix.
