### ISSUE TITLE
Use PyPI release of django-statsd-mozilla

### ISSUE THREAD

**Issue by benspaulding** [mozilla/sumo-project#152]
Our Django 2 branch is currently running on a Lincoln Loop fork of django-statsd-mozilla, but once django-statsd/django-statsd#121 is accepted and released on PyPI we should update our requirements to use that release.

**Comment by benspaulding** [comment]
@akatsoulas I assume this is a Mozilla repo because the official package name is [django-statsd-mozilla](https://pypi.org/project/django-statsd-mozilla/). Can you encourage them to move this PR to a release?

**Comment by akatsoulas** [comment]
Closing in favor of #450
