### ISSUE TITLE
[Mobile] The Log in / Sign up page is not displayed correctly

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#154]
Prerequisites:
Use a mobile device that has iOS. 
You don't need to be log into your account.

STR:

1. Go to https://test.sumo.mozit.cloud/en-US/
2. Click on the upper right icon (avatar icon) 
3. Click on "Sign in/Up" button 

ER: The login page is displayed correctly and you are able to log in.
AR: The login page is not displayed correctly. 

NOTE: The issue is not reproducible in RDM mode. 
Print screen with the issue: https://imgur.com/a/BH2bv14
This issue is reproducible only on iOS device. On Android phone, the issue is not reproducible. 

The user can't log in, the FF Accounts flow is not working and the SUMO account button can't be clicked.

**Comment by ovidiuboca1** [comment]
NOTE: This is also reproducible on tablet (iPad with FF).

**Comment by kkellydesign** [comment]
This will be in https://github.com/mozilla/kitsune/pull/4177. It was related to the 'sticky footer' code. 

<img width="469" alt="Screen Shot 2020-02-13 at 6 19 33 PM" src="https://user-images.githubusercontent.com/202590/74487423-6defaa80-4e8d-11ea-87c2-997bf9c69775.png">

**Comment by kkellydesign** [comment]
This is in – test here: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
I verified this on iPhone 8 plus and Sony, the issue is fixed.

**Comment by ovidiuboca1** [comment]
I verified this on iPhone 8 plus and Sony, the issue is fixed.
