### ISSUE TITLE
The "Views" section is missing [Responsive Redesign // Forum, thread pages]

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#155]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/questions/1206913

ER: The "Views" section is displayed. See the spec-  https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e349d0fdcdbeaaecdc2c44c
AR: The "Views" section is missing. See the attached print screen. 
![Screenshot 2020-02-12 at 15 20 58](https://user-images.githubusercontent.com/54845678/74338895-b171e800-4dab-11ea-9e08-df41dacabe3b.png)

**Comment by kkellydesign** [comment]
This conditional actually doesn't print a value very often, but it is functional. You can see it on the fourth item down in the "all" list here: https://test.sumo.mozit.cloud/en-US/questions/firefox?show=all

**Comment by ovidiuboca1** [comment]
> This conditional actually doesn't print a value very often, but it is functional. You can see it on the fourth item down in the "all" list here: https://test.sumo.mozit.cloud/en-US/questions/firefox?show=all


The link is not working on my end.

**Comment by kkellydesign** [comment]
I see, it's timing out for me too. I just tried a section with a smaller set of articles, and it's working there. You can see the 'views' items here: https://test.sumo.mozit.cloud/en-US/questions/firefox-fire-tv?show=all

**Comment by ovidiuboca1** [comment]
I verified and the view section is displayed. I don't think this is an actual issue.

**Comment by jess-cook03** [comment]
@ovidiuboca1 @kkellydesign seems like this issue can be closed?
