### ISSUE TITLE
The Search box label is incorrect [Responsive Redesign // Forum, thread pages]

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#156]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/questions/1206913
2. Observe the Search box form the right top corner. 

ER: The text of the Search box is "Search Support"
AR: The text of the Search box is "Find Help"

NOTE: If I scroll the page I will see 2 Search boxes with the same text. 
![Screenshot 2020-02-12 at 15 34 17](https://user-images.githubusercontent.com/54845678/74339644-2abe0a80-4dad-11ea-9c70-1528f3960b13.png)

**Comment by kkellydesign** [comment]
This will be in here: https://github.com/mozilla/kitsune/pull/4177

<img width="362" alt="Screen Shot 2020-02-13 at 4 50 38 PM" src="https://user-images.githubusercontent.com/202590/74481626-151a1500-4e81-11ea-9e48-9aa322d671ea.png">

**Comment by jess-cook03** [comment]
@kkellydesign your last comment ^^ that looks good to me and I can confirm this looks good on the testing server as the new PR went up yesterday. 
@ovidiuboca1 confirm that we can close this issue?

**Comment by ovidiuboca1** [comment]
I'm ok with this, we can close this.
