### ISSUE TITLE
Hide filtering in contributor forums and AAQ for non logged in users.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#157]

**Comment by kkellydesign** [comment]
This will go in with https://github.com/mozilla/kitsune/pull/4177

<img width="1320" alt="Screen Shot 2020-02-14 at 3 55 33 PM" src="https://user-images.githubusercontent.com/202590/74566883-7f46be80-4f42-11ea-86e6-7218512edc67.png">

**Comment by kkellydesign** [comment]
This is in – check this URL in private browsing vrs logged in to see: https://test.sumo.mozit.cloud/en-US/questions/firefox-private-network?show=all

**Comment by ovidiuboca1** [comment]
This is just for desktop? On mobile, the "Ask the Community" button is not displayed.

**Comment by kkellydesign** [comment]
That's correct – that button is desktop-only

**Comment by ovidiuboca1** [comment]
Thanks Kasey for the clarification. This issue was verified on Mac OS X 10.14 and Windows 10.
