### ISSUE TITLE
The "Download Firefox" button position is changed

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#158]
Prerequisites: 
Don't use the FF browser. 

STR:
1. Go to https://test.sumo.mozit.cloud/en-US/ 
2. Click on product "Firefox"

ER: The position of the "Download Firefox" button didn't change. It is near the "Sign in/Up" button. 
AR: The position of the "Download Firefox" button changed. See the print-screen. 
![Screenshot 2020-02-12 at 17 44 06](https://user-images.githubusercontent.com/54845678/74351101-50540f80-4dbf-11ea-9f80-bbe9f3127b67.png)

**Comment by kkellydesign** [comment]
I think this is working correctly as-is. Your screenshot is the Firefox support page, where there's a conditional that puts the "download" button down next to the "Frequent Topics" headline. 

On Chrome, I'm seeing this on the homepage, here: https://test.sumo.mozit.cloud/
<img width="1341" alt="Screen Shot 2020-02-13 at 4 33 02 PM" src="https://user-images.githubusercontent.com/202590/74480227-87d5c100-4e7e-11ea-88fd-053a6060d56b.png">

And then on the Firefox page, you get this: 
https://test.sumo.mozit.cloud/en-US/products/firefox
<img width="1356" alt="Screen Shot 2020-02-13 at 4 34 41 PM" src="https://user-images.githubusercontent.com/202590/74480366-c8cdd580-4e7e-11ea-82b7-70b1f534e448.png">

**Comment by ovidiuboca1** [comment]
Thanks for clearing this out, based on your comment this can be closed.
