### ISSUE TITLE
[New Message page] The markup tool buttons are not working 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#159]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/messages/new
2. Write a text in the message box
3. Select some text and apply all the options provided by the markup tool. 

ER: The desired option is applied to the selected text. 
AR: The markup tool buttons are not working. Please see this screen recording - https://streamable.com/3q9se

NOTE: If I select to see the text in the preview the markups selected are visible.

**Comment by kkellydesign** [comment]
This will be in here: https://github.com/mozilla/kitsune/pull/4177

<img width="780" alt="Screen Shot 2020-02-13 at 4 21 36 PM" src="https://user-images.githubusercontent.com/202590/74479316-f0bc3980-4e7c-11ea-9028-c83be0725023.png">

**Comment by kkellydesign** [comment]
The preview is now working on this screen as well. 

<img width="981" alt="Screen Shot 2020-02-13 at 4 30 32 PM" src="https://user-images.githubusercontent.com/202590/74480053-39282700-4e7e-11ea-8f2e-da5ee5beac32.png">

**Comment by kkellydesign** [comment]
This is in, ready to test here: https://test.sumo.mozit.cloud/en-US/messages/new

**Comment by ovidiuboca1** [comment]
The markup tool options can't be applied to the text.

**Comment by kkellydesign** [comment]
Can you be more specific? This is working for me in Chrome and Firefox. I just added this markdown with the 'link' dialog: 

<img width="462" alt="Screen Shot 2020-02-19 at 5 14 23 PM" src="https://user-images.githubusercontent.com/202590/74881463-5b68eb80-533b-11ea-9ad0-0e5fcdd60e6b.png">

**Comment by ovidiuboca1** [comment]
For example if I want to make some text bold or italic and then I decide to undo that action, I can't.

**Comment by kkellydesign** [comment]
ok, I understand. The text editor we're using hasn't been upgraded, so this is the existing functionality. Since it's a markdown editor, it works a little differently than a typical WYSIWYG. Jess had some upgrade requests on this area as well, but I suggest moving this to a later phase. There are a handful of [good markdown editors](https://ourcodeworld.com/articles/read/359/top-7-best-markdown-editors-javascript-and-jquery-plugins) that could replace this one, but it's not a quick fix.

**Comment by akatsoulas** [comment]
For this issue we need to verify that the editor is working. The upgrade part is tracked in this issue
https://github.com/mozilla/sumo-project/issues/247

**Comment by ovidiuboca1** [comment]
The editor is working on desktop but on mobile(tested on iPhone 8 plus) if I want to add a link the modal window is too large, on staging the behavior of the editor is very strange, so I will consider this as verified.
