### ISSUE TITLE
[New message page] The size of the "Send" button is different 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#161]
STR: 

1. Go to https://test.sumo.mozit.cloud/en-US/messages/new
2. Observe the "Send" button

ER: The size of the button is similar to the size of the "Preview" button. 
AR: The size of the "Send" button is different compared to the "Preview" button.

**Comment by kkellydesign** [comment]
This will be in here: https://github.com/mozilla/kitsune/pull/4177

<img width="1002" alt="Screen Shot 2020-02-13 at 4 09 53 PM" src="https://user-images.githubusercontent.com/202590/74478408-4d1e5980-4e7b-11ea-8f12-5b334adaa22f.png">

**Comment by kkellydesign** [comment]
This is in, you can see it here: https://test.sumo.mozit.cloud/en-US/messages/new

**Comment by ovidiuboca1** [comment]
I verified this on Mac OS X 10.14 and Windows 10 with Firefox v73 and Chrome v80 and I can confirm the fix.
