### ISSUE TITLE
Copy or links needed

### ISSUE THREAD

**Issue by kkellydesign** [mozilla/sumo-project#165]
Hard-coded Lorem Ipsum text needed: 
- [x] Lorem Ipsum text needs replaced under "Discussions" and "Tools" in the global main menu
- [x] **Social Support Forum** and **New Contributors** either need URLs, or need to be removed. They were on the mockup, but I'm not sure where they should go. 
- [x] There is discussion [on this thread](https://github.com/mozilla/sumo-project/issues/28#issuecomment-579380839) about which pages need to be reskinned, but please confirm whether all of those pages need to live in the navigation. There are five links that I've marked with "(remove?)" in the nav that don't exist in the mockup, but were in the site. The list in the main navigation currently pulls from the same place as the sidebar on those pages ([example](https://test.sumo.mozit.cloud/en-US/search/advanced)), but they could be different lists if you want. 

<img width="1339" alt="Screen Shot 2020-02-14 at 1 15 00 PM" src="https://user-images.githubusercontent.com/202590/74556644-81058780-4f2c-11ea-87ac-1078bf84f80d.png">

- [x] Lorem Ipsum text needs replaced under "Profile", "Settings" and "Inbox" when you hover over the user avatar in the main nav when logged in. 
<img width="1351" alt="Screen Shot 2020-02-14 at 1 25 47 PM" src="https://user-images.githubusercontent.com/202590/74557243-bbbbef80-4f2d-11ea-904d-ccff2ac75390.png">

- [ ] The "Join our community" panel on the [homepage](https://test.sumo.mozit.cloud/en-US/) has a line of lorem ipsum text
<img width="695" alt="Screen Shot 2020-02-14 at 1 20 38 PM" src="https://user-images.githubusercontent.com/202590/74556814-d6da2f80-4f2c-11ea-9bcf-267960441efe.png">

- [ ] The "Popular Searches" links under the search bar on the homepage and each of the product pages needs links. They can be the same, but they don't have to be. 
<img width="963" alt="Screen Shot 2020-02-14 at 1 21 13 PM" src="https://user-images.githubusercontent.com/202590/74556917-08eb9180-4f2d-11ea-97a7-4a1e3ba68b0b.png">
<img width="1026" alt="Screen Shot 2020-02-14 at 1 22 01 PM" src="https://user-images.githubusercontent.com/202590/74556918-08eb9180-4f2d-11ea-807f-739344719c5d.png">

- [ ] The "Volunteer" callout on [article pages](https://test.sumo.mozit.cloud/en-US/kb/how-do-i-tell-if-32-bit-or-64-bit) has lorem ipsum text. Note that we could use the exact same callout as the homepage, but they're currently different modules because the headlines were different in the mockups. 
<img width="784" alt="Screen Shot 2020-02-14 at 1 22 58 PM" src="https://user-images.githubusercontent.com/202590/74557014-418b6b00-4f2d-11ea-9943-d4af5df6d01b.png">

**Comment by madasan** [comment]
- [ ] @jonichan will help with the copy for all lorem ipsum text

- [ ] Social Support Forum: https://support.mozilla.org/en-US/forums/social-media, new Contributors: https://support.mozilla.org/en-US/forums/buddies

- [ ] Only the pages in the mockups should live in the nav. I assume we could always change that list later?

**Comment by jess-cook03** [comment]
**Re: navigation links for contributor tools**
- [ ] 'tag admin' is a future link (@jonichan please confirm)

- [ ] remove 'quickstart guide' as this already is linked in the volunteer section of nav

- [ ] remove 'KPI dashboard'

- [ ] remove 'support forum metrics' -- ? @jonichan should we replace this with something else?
All of these can be replaced with anything else from this list of pages [here](https://github.com/mozilla/sumo-project/issues/28#issuecomment-579380839) 

**Re: popular searches (hard coded)**

- [ ] @jonichan since currently these will not be pulled from real data as true 'popular searches' right now they are just hard coded in, so they can be whatever we want them to be. That being said do we want these for every product page or just keep them on the main home page search?
My thought here is for now maybe stick with just the main home page search -- otherwise we will have to provide a list of 'popular search terms' for each product.
Let me know your thoughts?

**Comment by jonichan** [comment]
Here's my suggested copy for the Lorem Ipsum text. I had a couple of questions in the doc. @jess-cook03 Please review and let me know what you  think.

**Comment by jonichan** [comment]
>     * [ ]  'tag admin' is a future link (@jonichan please confirm)
Correct.

>     * [ ]  remove 'support forum metrics' -- ? @jonichan should we replace this with something else?
>       All of these can be replaced with anything else from this list of pages [here](https://github.com/mozilla/sumo-project/issues/28#issuecomment-579380839)

Replace with Support forum home (as long as it's the all-product forum landing page)


> **Re: popular searches (hard coded)**
> 
>     * [ ]  @jonichan since currently these will not be pulled from real data as true 'popular searches' right now they are just hard coded in, so they can be whatever we want them to be. That being said do we want these for every product page or just keep them on the main home page search?
>       My thought here is for now maybe stick with just the main home page search -- otherwise we will have to provide a list of 'popular search terms' for each product.
>       Let me know your thoughts?

It would be the most helpful to people if we had popular searches for each product. I can provide the top searches for each product when you need them.

**Comment by kkellydesign** [comment]
The nav links are done, sort-of. @akatsoulas, I hard-coded these and couldn't figure out the syntax for the forum `{{ url()` tags. Leaving the language prefix off makes these redirect properly if you're in other languages, so I don't see any harm in doing it like this. And looking through the repo, there are a handful of other templates that have hard-coded links. Please let me know if this is ok. In `common_macros.html`: 

```
<li><a href="/forums/social-media">Social Support Forum</a></li>
<li><a href="{{ url('wiki.locale_discussions') }}">{{ _('Article Discussions') }}</a></li>
<li><a href="/forums/buddies">New Contributors</a></li>
```

**Comment by kkellydesign** [comment]
**Re: popular searches (hard coded)**

@jonichan I'm going to comment these out from the product pages for now so this doesn't hold up launch, but please add them to this ticket as you have them ready, for both the homepage and any product pages that should have them

**Comment by kkellydesign** [comment]
@jonichan Can you please give kasey@lincolnloop.com access to that doc?

**Comment by kkellydesign** [comment]
@jonichan ok, we're getting close – thanks for your help. Just to aggregate the missing text that's left from the above list, these are the things we still need: 
- [ ] The "Join our community" panel on the homepage has a line of lorem ipsum text
- [ ] "Popular Searches" on the homepage and product pages
- [ ] The "Volunteer" callout on article pages has lorem ipsum text. Note that we could use the exact same callout as the homepage, but they're currently different modules because the headlines were different in the mockups.

**Comment by jonichan** [comment]
Thanks @kkellydesign. I'm sorry I missed these items earlier.

I've updated the [Google Doc](https://docs.google.com/document/d/1ptL5Ag3g-oKIlKOXqnlNASHeVsFPZfTAuqwJR61pe3I/edit#) with copy for "Join our community" and "Volunteer".

Popular searches
*Homepage: firefox accounts, vpn, tracking protection
*Firefox desktop: update firefox, profiles, Firefox Sync
*Firefox for Android and Firefox Preview: firefox sync, bookmarks, send tab,
*Firefox for iOS: send tab, night mode, block images
*Firefox for Enterprise: policies, customization, extensions
*Firefox for Amazon Devices: turbo mode, voice commands, receive tabs
*Firefox Private Network Browser level: about firefox private network, install extension, limits
*Firefox Private Network Device level: choose server, subscription, android vpn, windows vpn
*Firefox Lockwise: lockwise ios, lockwise android, lockwise desktop
*Firefox Reality: voice search, bookmarks, full screen
*Firefox Lite: turbo mode, rewards, games
*Hubs: create rooms, moderate, customize avatar
*Firefox Focus: autocomplete, default search, desktop view
*Firefox Screenshot Go: organize screenshots
*Thunderbird: Thunderbird profiles, migrate, themes

**Comment by kkellydesign** [comment]
All copy updates will be in here: https://github.com/mozilla/kitsune/pull/4184

**Comment by kkellydesign** [comment]
These are all in and ready for QA. Test here: https://test.sumo.mozit.cloud/

**Comment by ovidiuboca1** [comment]
@kkellydesign @jess-cook03 

I don't see these products:
 Firefox for Amazon Devices: turbo mode, voice commands, receive tabs
Firefox Screenshot Go: organize screenshots

From these products I don't see the popular searches:
Firefox Private Network Browser level: about firefox private network, install extension, limits
Firefox Private Network Device level: choose server, subscription, android vpn, windows vpn

**Comment by akatsoulas** [comment]
These products do not exist in the dev database. Is there anything else still pending apart from the missing products?

**Comment by ovidiuboca1** [comment]
From my point of view, only that was a problem.
