### ISSUE TITLE
The user will end up in a dead end if the ”Community Discussion Only” section is visited

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#166]
STR: 
1. Go to https://test.sumo.mozit.cloud/en-US/
2. Perform a search after "cookies"
3. Click on the ”Community Discussion Only” section

ER: The action is performed and the user can still see the "View All" and "Help Articles Only" sections.
AR: The action is performed but the user doesn't have any options to go back to the previous stage.

**Comment by mirunacurtean** [comment]
No longer occurs. The user can switch between sections after filtering by section, filtering by product, using new search keywords. 

![select section fixed](https://user-images.githubusercontent.com/53306802/108966397-cb186180-7686-11eb-9537-c0b1ddd977b1.gif)
