### ISSUE TITLE
[Home Page] The Profile options (dropdown) are displayed if you hover over the "Download Firefox" button

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#168]
Prerequisites: 
You need to be logged in.
Use Chrome

STR:

1. Go to https://test.sumo.mozit.cloud/en-US/
2. Hover over the "Download Firefox" button

ER: Nothing happens. 
AR: The profile dropdown is displayed.

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4182

**Comment by kkellydesign** [comment]
ready for QA: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
Tested on Windows 10 and Mac OS X 10.14 with Chrome and Safari and I can confirm the fix.
