### ISSUE TITLE
[Search] If a search is filter after a product that doesn't have any result the user can't go back to the previous state

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#169]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/
2. Perform a search after "firefox"
3. From the "Filter by product" select "Firefox Lite"  - there are no results

ER: The user can go back to the previous stage. 
AR: The user can't go back to the previous stage. The search needs to be performed again. 

NOTE: Maybe this is related to the https://github.com/mozilla/sumo-project/issues/166

**Comment by mirunacurtean** [comment]
Checked in #714 as well, but verified more thoroughly here that the switch between filters/ search results sections is possible even when there are no results. 
![return to previous filter when there are no results](https://user-images.githubusercontent.com/53306802/108973544-22213500-768d-11eb-8fa9-bbc7eef085ca.gif)
