### ISSUE TITLE
In the Popular Searches area are only 4 items

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#17]
STR:

1. Go to Mozilla Support page
2. Observe the Popular Searches area

ER: There are be 5 items in the Popular Searches area
AR: In the Popular Searches area are only 4 items.

**Comment by kkellydesign** [comment]
I've added a fifth item, and I have this functionality working. It'll be on the test server when https://github.com/mozilla/kitsune/pull/4130 goes up. 

<img width="1250" alt="Screen Shot 2020-01-17 at 2 22 17 PM" src="https://user-images.githubusercontent.com/202590/72639960-d8680600-3934-11ea-996a-cac27761eb91.png">
<img width="1383" alt="Screen Shot 2020-01-17 at 2 22 23 PM" src="https://user-images.githubusercontent.com/202590/72639961-d8680600-3934-11ea-890a-ca415ef9d79a.png">

**Comment by jess-cook03** [comment]
@kkellydesign home page will be updated with this shift -- but search alignment -- to the left.
Show here:
<img width="844" alt="Screen Shot 2020-01-17 at 4 33 41 PM" src="https://user-images.githubusercontent.com/54991698/72647788-56cda380-3947-11ea-9b0f-9626918679b6.png">
Additional padding and inside the top page module increasing the size to the next 8px or 24px increment for large viewport: 
<img width="991" alt="Screen Shot 2020-01-17 at 4 38 23 PM" src="https://user-images.githubusercontent.com/54991698/72647962-d196be80-3947-11ea-9baf-d573e19ed73a.png">

**Comment by ovidiuboca1** [comment]
Verified on the staging site and the fifth element is there.
