### ISSUE TITLE
Responsive Redesign // Design Backlog

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#170]
- [x] global typescale - document and clean up (follow this with QA card for edits)

- [x] edit Zeplin mockups to reflect final designs

- [x] card shadow hover -- edit shadow, document show functionality 

- [x] KB articles - logged in view? (review this, any additions?)

- [x] tag logic (colors) and forum page deep dive for design QA

- [ ] Document subproducts (sub category) mental model 

**File Management**

- [x] library clean up, style changes and symbol library

- [x] update Abstract file clean up

- [x] Migrate to project to Figma 

**

- [x] Design Review w/ Marketing - Schedule this*

**

Review again how Protocol is being used with @kkellydesign so we can translate this back to Protocol team

**Comment by madasan** [comment]
@jess-cook03 can you break this into multiple tickets for Responsive Redesign V2?
