### ISSUE TITLE
Responsive Redesign // Banner Component

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#174]
@kkellydesign 
[Spec for banner here ](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/styleguide/components?cseid=5e4d679cb770a0b6b5730593)

- [x] 1 in-page banner

- [x] 1 navigation (top of page) slim banner (not sticky)

See reference:
https://www.mozilla.org/en-US/
Bottom of page and top of page after scroll
![Screen Shot 2020-02-19 at 11 53 29 AM](https://user-images.githubusercontent.com/54991698/74855269-77a26380-530e-11ea-9bd3-7c798356bfb0.png)

**Comment by jess-cook03** [comment]
@jonichan commenting and adding you here for viability -- for when this banner is created it can be flexible enough to apply to the Fennec / Firefox for Android banner if needed.

**Comment by jess-cook03** [comment]
Connecting issue #78 @akatsoulas @madasan

**Comment by kkellydesign** [comment]
This is in. I built this as a macro, similar to the other notifications. It's also in the styleguide. I've included it in the base template so the top banner is visible on every page for now, and also the document pages toward the bottom for the in-page variant. 

@akatsoulas, you can see the code [in this commit](https://github.com/lincolnloop/kitsune/commit/6567b5134dce9b97e5b765325f302fa49a5c66bf). 

The base template calls the banner with the 'hide-on-mobile' modifier:
https://github.com/lincolnloop/kitsune/commit/6567b5134dce9b97e5b765325f302fa49a5c66bf#diff-0b59efd85b03f4611418629761f2cae0R143

and the document page gets the "has-abs-close-button" modifier to change the layout slightly. Also note that each one will need a unique ID to make the close button work correctly. 
https://github.com/lincolnloop/kitsune/commit/6567b5134dce9b97e5b765325f302fa49a5c66bf#diff-e900343dc92ea15b2ebcb36bd746da54R136

This will go up with https://github.com/mozilla/kitsune/pull/4193.
inline-desktop: 
<img width="605" alt="Screen Shot 2020-02-26 at 11 46 41 PM" src="https://user-images.githubusercontent.com/202590/75413481-a8c4fa00-58f3-11ea-8bfd-2689c80dd99a.png">

inline-mobile: 
<img width="388" alt="Screen Shot 2020-02-26 at 11 46 25 PM" src="https://user-images.githubusercontent.com/202590/75413487-abbfea80-58f3-11ea-870a-0e5c0da28dad.png">

top banner desktop (disabled on mobile): 
<img width="1336" alt="Screen Shot 2020-02-26 at 11 20 16 PM" src="https://user-images.githubusercontent.com/202590/75413509-bc706080-58f3-11ea-816c-6dd53d08ea06.png">

**Comment by jess-cook03** [comment]
@kkellydesign this looks good. **The copy can be the same for both** ---> 'Unlock more from every Firefox product. Get a Firefox account.'
Couple questions:

- Is this able to sit under the navigation if we need/want it to?
- Confirming this would only show up and be visible for users that are not using FxA? @akatsoulas

**Comment by jess-cook03** [comment]
@akatsoulas also -- I don't think we will launch with having this on the homepage -- correct?

**Comment by akatsoulas** [comment]
Correct, for now it's there only for QA. After that we can decide where this is going to live and the conditions that will display it

**Comment by akatsoulas** [comment]
Regarding the FxA users, for now it will be shown to users that do not use Firefox. We are lucking the ability to know if a user is using FxA atm

**Comment by jess-cook03** [comment]
@kkellydesign functionally after I dismiss it once why does it keep appearing whenever I browse to a different page ? Assuming its a bug but not sure.

**Comment by kkellydesign** [comment]
All I did was build the design for this. There are no cookies that track whether you've dismissed it, and there is no logic around when and where it should display. That will need to be added in when you decide the particulars.

**Comment by ovidiuboca1** [comment]
@jess-cook03 I don't see this banner on a mobile device, tested with iPhone 8 plus, this is expected?
This banner should be visible on the bottom of some pages or all, I don't see it.

**Comment by jess-cook03** [comment]
@ovidiuboca1 this should be working on mobile too @kkellydesign ?
I marked as blocked for now -- we also need to decide how we want this to work for the launch @akatsoulas

**Comment by kkellydesign** [comment]
On mozilla.org, this sticky nav component is desktop-only, so that's what I did here as well. You don't want too much sticky junk on mobile. The inline component, which I only have installed on the document list page, will show up on all sizes. You can see that example at the bottom of the page here: 

https://test.sumo.mozit.cloud/en-US/products/firefox/basic-browsing-firefox

**Comment by ovidiuboca1** [comment]
I can confirm that this is working on the desktop on the document list page.
