### ISSUE TITLE
Responsive Redesign // Inbox Page? + Profile Menu items

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#177]
![Screen Shot 2020-02-18 at 4 49 49 PM](https://user-images.githubusercontent.com/54991698/74966748-aa6b5b00-53e5-11ea-8879-50513b319114.png)
@kkellydesign 
Did we design the profile page: 
https://support.mozilla.org/en-US/messages

Menu icon for inbox should be envelope and icon for profile should be person head profile icon
<img width="1103" alt="Screen Shot 2020-02-20 at 1 36 08 PM" src="https://user-images.githubusercontent.com/54991698/74966891-f8805e80-53e5-11ea-8619-38a46ffbb6a6.png">

**Comment by jess-cook03** [comment]
![Screen Shot 2020-02-20 at 2 29 50 PM](https://user-images.githubusercontent.com/54991698/74971087-857ae600-53ed-11ea-87d6-0130ea0803bf.png)
--- this link should bring you to the list if questions that you have posted
https://support.mozilla.org/en-US/search/advanced?a=1&asked_by=jecook&w=2

**Comment by kkellydesign** [comment]
@jess-cook03 yes, https://test.sumo.mozit.cloud/en-US/messages is designed. You can see what the table would look like if it were full here: https://test.sumo.mozit.cloud/en-US/messages/sent. The navigation is now linked correctly to that spot. 

User area icons have been changed. "My Questions" now goes to the correct advanced search query. 

This will go up with https://github.com/mozilla/kitsune/pull/4190

**Comment by jess-cook03** [comment]
@kkellydesign this looks good to me -- seems to be working great -- I would say we can close this or move to done
