### ISSUE TITLE
Responsive Redesign // Asset Collection

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#178]
Collection of product icons/images for the home page and product pages.

**@madasan marking items in list below with needed assets.**

List of products @jonichan can you update this list with the correct set of products we will have on the home page etc?

- [ ] - Firefox (Jess has new brand asset for this already)
- [ ] - Firefox for Android ***NEED updated asset***
- [ ] - Firefox for iOS ***NEED updated asset***
- [ ] - Firefox Focus ***NEED updated asset***
- [ ] - Firefox Lite (Jess has new brand asset for this already)
- [ ] - Firefox Lockwise (Jess has new brand asset for this already)
- [ ] - Firefox For Amazon Devices ***NEED updated asset***
- [ ] - Webmaker (Use Current) 
- [ ] - Firefox Reality (Jess has new brand asset for this already)
- [ ] - Thunderbird ***NEED updated asset*** or use current
- [ ] - Firefox Private Network Device level (Jess has new brand asset for this already)
- [ ] - Firefox Private Network Browser level (Jess has new brand asset for this already)
- [ ] - Hubs ***NEED updated asset***
- [ ] - Firefox for Enterprise ***NEED updated asset***
- [ ] - Firefox ScreenshotGo ***NEED updated asset*** or use current

**Comment by jonichan** [comment]
> List of products @jonichan can you update this list with the correct set of products we will have on the home page etc?

 -Firefox (Jess has new brand asset for this already)
- Firefox for Android NEED updated asset
- Firefox for iOS NEED updated asset
- Firefox Focus use current asset as we're no longer updating this but still displaying on home page.
- Firefox Lite (Jess has new brand asset for this already)
- Firefox Lockwise (Jess has new brand asset for this already)
- Firefox For Amazon Devices NEED updated asset
- Firefox Reality (Jess has new brand asset for this already)
- Thunderbird NEED updated asset or use current
- Firefox Private Network Device level (Jess has new brand asset for this already)
- Firefox Private Network Browser level (Jess has new brand asset for this already)
- Hubs NEED updated asset
- Firefox for Enterprise NEED updated asset
- Firefox ScreenshotGo NEED updated asset or use current

**Comment by jess-cook03** [comment]
@madasan see list above for products that we **_NEED updated assets_** 
For production -- we will need to gather these product icons listed above.
They can be uploaded here or send them to me directly

**Comment by jess-cook03** [comment]
@madasan list is now updated to the latest needs -- 
@akatsoulas where/when should I start uploading these assets ?

**Comment by shorlander** [comment]
>     * [ ]  - Firefox for Android _**NEED updated asset**_
>     * [ ]  - Firefox for iOS _**NEED updated asset**_

Hi! @jess-cook03 what are you looking for here? Right now we have the devices and a platform icon. Did you want an update for that or something different?

>     * [ ]  - Firefox Focus _**NEED updated asset**_

Same question here, but Focus has *not* been updated just yet to new branding.

>     * [ ]  - Firefox For Amazon Devices _**NEED updated asset**_

I don't think Firefox for Amazon Devices has new branding either… @athomasmoz might know.

>     * [ ]  - Firefox for Enterprise _**NEED updated asset**_

We also do not currently do anything to visually distinguish Firefox for Enterprise. Did you have something in particular in mind here?

Thanks!

**Comment by jess-cook03** [comment]
@shorlander 
Ideally would like to get away from using the device images but as of right now that seems to be not possible because its the only way to visually differentiate between the different platforms since they all share the same overall product icon, and having a bunch of repeated Firefox logos would not be successful in this case.

I am 100% open to any ideas here as well if you have better solutions in mind for any of these!! Per our quick discussion during UX systems meeting.

This is where it will live primarily:
![Screen Shot 2020-03-17 at 2 14 30 PM](https://user-images.githubusercontent.com/54991698/76888177-db5e7480-6859-11ea-9c32-d12d50d88093.png)


I'd say we need updated device + icon images for these: Fx for Android, Fx for iOS, Fx for Amazon 
For Focus: we can just use the product icon (no device)
For Enterprise: repeat use of just the Fx Browser logo (no device needed)

**Comment by shorlander** [comment]
[sumo-product-assets.zip](https://github.com/mozilla/sumo-project/files/4372313/sumo-product-assets.zip)

Assets for:

- Firefox for Android
- Firefox for iOS
- Firefox for Fire TV
- Firefox Lite

**Comment by jess-cook03** [comment]
@shorlander thank you!! looks awesome!

**Comment by jess-cook03** [comment]
This ticket can be closed :)
