### ISSUE TITLE
Respsonsive Redesign // UI fix - Need more help component

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#179]
@kkellydesign 
Can this component have two skins? One Mozilla brand and the one Firefox?
Specs for both:
- [x] Headline should be 32px
- [x] icon size for both should be 32px x 33px (right now its warped)
<img width="997" alt="Screen Shot 2020-02-21 at 2 09 31 PM" src="https://user-images.githubusercontent.com/54991698/75063886-d6eda880-54b3-11ea-9e3f-c100ab590037.png">

@kkellydesign global rule here:
**For mozilla brand the typography Zilla and body should always be black -- not Ink or grey.**
(refer to image above and styling for #183 )

Current screenshot:
![Screen Shot 2020-02-21 at 2 10 31 PM](https://user-images.githubusercontent.com/54991698/75063931-eff65980-54b3-11ea-8237-729f5ac29352.png)

**Comment by jess-cook03** [comment]
@jonichan Please post your copy recommendations here, thank you!

**Comment by jonichan** [comment]
Option A
Header: Need more help? 
We're here to help. Post a question to our support forums and get answers from our community of experts.
Button text: Ask a question

Option B
Header: Still need help?
We're here for you. Post a question to our support forums and get answers from our community of experts.
Button text: Ask a question

I'd like more feedback on what wasn't working with the old copy, then I can tweak these suggestions accordingly.

**Comment by jess-cook03** [comment]
@jonichan thank you these are great!
Main feedback was around the "Need more help?" in combination with the icon thats is being used. Does it make sense? Comment was it felt -- disconnected to the meaning.

As far as the button CTA - I apologize because I am reverting back after reminding myself why we chose that language in the first place -- I actually believe keeping 'Ask the Community' drives more continuity across the site and the support vision -- I went back to the research we did a couple months ago on why we picked that language (same language used in the nav) -- [check it out here ](https://docs.google.com/document/d/1s70xAYpmrOQc5i2NQP1gMnzoUjmTbvnJWMDxzmtoYOc/edit?usp=sharing).

This all being said :

- [ ] I really like the the body copy (subheader) in Option B.

- [ ] Lets keep the button CTA the same for now.

- [ ] That just leaves the headline --- not sure if we want to rev on it anymore right now? We can always change it/refine it later? See how it tests and then revisit?

**Comment by jess-cook03** [comment]
@kkellydesign moving to triage for you

**Comment by kkellydesign** [comment]
@jess-cook03 sure, but please provide URLs for where each example should go.

**Comment by kkellydesign** [comment]
http://localhost:3000/en-US/get-involved pages get the grey box

**Comment by kkellydesign** [comment]
These changes will all be in here: https://github.com/mozilla/kitsune/pull/4193

@jess-cook03 as far as the icon goes, can you send me the SVG file that you have? The one I used is straight from Protocol, and it looks like the right proportion to me. I did shrink it down from 36px to 32 though. Here's the raw file from protocol: 

<img width="152" alt="Screen Shot 2020-02-26 at 6 18 06 PM" src="https://user-images.githubusercontent.com/202590/75397303-810a6d80-58c4-11ea-99da-d93ccc218056.png">

**Comment by jess-cook03** [comment]
Confirming this ticket is completed
