### ISSUE TITLE
The "Find help" filed disappears after the browser window is resized

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#18]
STR: 

1. Go to Mozilla Support page
2. Resize the browser window, shrink it (until the browser window reaches less than 700 px width ).
3. Scroll the page and observe the "Find help" filed. 

ER: The filed is present. 
AR: The filed disappears.

**Comment by kkellydesign** [comment]
This has been fixed. 
<img width="478" alt="Screen Shot 2020-01-17 at 6 07 24 PM" src="https://user-images.githubusercontent.com/202590/72652309-3d7f2400-3954-11ea-9e11-db891f2afdc7.png">
