### ISSUE TITLE
Responsive Redesign // 404 Page Not Found

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#180]
@kkellydesign 
![Screen Shot 2020-02-20 at 2 36 24 PM](https://user-images.githubusercontent.com/54991698/74971668-79dbef00-53ee-11ea-98fa-d51a0c99afb4.png)
Can we populate this screen with our search page instead?
Not sure what the search default styling by Nukeador thing is all about?

When I search I then get this page?
![Screen Shot 2020-02-20 at 2 38 42 PM](https://user-images.githubusercontent.com/54991698/74971841-bb6c9a00-53ee-11ea-9cbe-5e17b9ef5195.png)
https://test.sumo.mozit.cloud/en-US/search?q=firefox

This is not part of advanced search and it seems not tied to current search feature either -- you can also navigate here by going to Advanced Search > select 'use basic search' button and you then land here:
https://test.sumo.mozit.cloud/en-US/search

![Screen Shot 2020-02-20 at 2 41 14 PM](https://user-images.githubusercontent.com/54991698/74972038-10101500-53ef-11ea-9b8e-1146b7d56515.png)

 @akatsoulas maybe can help provide context here with this? part of search upgrade?

**Comment by kkellydesign** [comment]
I gave these search pages a pass, and revised the 404 page. They'll be in here: 

https://github.com/mozilla/kitsune/pull/4193

**Comment by jess-cook03** [comment]
Confirming this is all set
