### ISSUE TITLE
Responsive Redesign // Tabs for Forum different for logged in users vs. not logged in

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#181]
In the design mocks we created two sets of tabs/filters based on whether the user is logged in vs. not logged in/signed up.

Currently on the testing site we have the old functionality for the forum landing pages (shown below)  -- OLD:
> when you click a product forum the landing page drops you within the 'attention needed tab'
![Screen Shot 2020-02-20 at 3 17 43 PM](https://user-images.githubusercontent.com/54991698/74974959-29679000-53f4-11ea-96e4-ee37f41287eb.png)
---> the same happens for the logged out user, which isn't the best UX solution for these users. See below current functionality:
![Screen Shot 2020-02-20 at 3 18 09 PM](https://user-images.githubusercontent.com/54991698/74975051-587e0180-53f4-11ea-9126-f43eb4663a65.png)

Ideally this is how the forum landing should work:
---> As a contributor/signed in user, when you click a product forum - the forum landing page drops you within the 'attention needed' tab (this is okay as before)
<img width="908" alt="Screen Shot 2020-02-20 at 3 21 33 PM" src="https://user-images.githubusercontent.com/54991698/74975244-c296a680-53f4-11ea-8151-4278734ef527.png">

---> Where the change should happen is here:
As a not signed in/up user, when you click a product forum - the forum landing page should drop you within the 'All' tab, as shown below:
<img width="969" alt="Screen Shot 2020-02-20 at 3 13 20 PM" src="https://user-images.githubusercontent.com/54991698/74975354-ee199100-53f4-11ea-85de-2213321d163b.png">

@kkellydesign and I realize this is old functionality carried over from current site -- is this something we will be able to change? @akatsoulas @madasan

**Comment by akatsoulas** [comment]
The test instance was updated yesterday with the latest changes which hide the filtering options for non logged in users. Moving this to QA.

**Comment by jess-cook03** [comment]
@kkellydesign @akatsoulas 
yes -- the filtering options are fine.

But I was referencing the tabs -- Attention Needed, All, Responded, Done, etc.
For non-logged in users you are still landing on the tab 'Attention Needed' (see image below)
![Screen Shot 2020-02-21 at 1 46 48 PM](https://user-images.githubusercontent.com/54991698/75062336-9f313180-54b0-11ea-8a7f-b3b15fd78454.png)

The issue is that when non-logged in users land here it will show them first unanswered questions or it will look blank. Instead I'm suggesting to rearrange the tabs for these users so they will open the forum and land on 'All Questions' or 'All' instead. (see image below)
<img width="969" alt="Screen Shot 2020-02-20 at 3 13 20 PM" src="https://user-images.githubusercontent.com/54991698/75062560-064ee600-54b1-11ea-9134-1416ce26001b.png">

**Comment by kkellydesign** [comment]
I just reordered the tabs and changed the label from "all questions" to the shorter "all" in the mockups. Per the conversation this morning, Tasos is going to take a look at this from the BE level and change the default active tab whether the user is logged in or not. I'm unassigning myself for now, but feel free to assign me again if more needs done on the frontend for this.

**Comment by akatsoulas** [comment]
This will not be fixed and the tabs will remain the same. The way questions are ordered is affected both by the tabs and the filtering which with the new designs is hidden for the non logged in users. After discussing this with @madasan, this issue will be tackled after the release and a new issue will be opened. 

In the new solution we should find a way to combine the data from both the filtering options and the tabs or restructure how the data are filtered.

For now we are keeping the filters hidden for non logged in users and tabs will remain the same with the production version.
