### ISSUE TITLE
Responsive Redesign // Forum landing pages missing search box

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#182]
@kkellydesign noticed that these pages don't have the search box in the upper left, is this something we can add to these templates?
See zeplin [design mockup](https://zpl.io/aBDOnJp) or screenshot below:
<img width="908" alt="Screen Shot 2020-02-20 at 3 21 33 PM" src="https://user-images.githubusercontent.com/54991698/74975663-6c763300-53f5-11ea-95e1-344e42c6313f.png">

**Comment by kkellydesign** [comment]
This will go in with https://github.com/mozilla/kitsune/pull/4193

<img width="1340" alt="Screen Shot 2020-02-26 at 9 56 18 PM" src="https://user-images.githubusercontent.com/202590/75408112-da819500-58e2-11ea-8b05-1466b038dd5d.png">

**Comment by jess-cook03** [comment]
@kkellydesign looks good --- I think this issue can be closed.
