### ISSUE TITLE
Responsive Redesign // Illustration Assets for Mozilla components

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#183]
**Uploading the asset folder here:** @kkellydesign 
[SUMO_selectedMozillaIllustrations.zip](https://github.com/mozilla/sumo-project/files/4233232/SUMO_selectedMozillaIllustrations.zip)

@madasan these have been approved by branding / confirmed we have legal writes to use across channels with no time constraints -- all good there!

@kkellydesign Design UI changes to this component card -- revert back to protocol default styling from moz.org :
- [x] remove drop shadow

- [x] remove rounded corners -- bring back to 0

- [x] make text link Blue -- hover underline -- remove purple link coloring

<img width="273" alt="Screen Shot 2020-02-20 at 5 34 01 PM" src="https://user-images.githubusercontent.com/54991698/74986257-35108200-5407-11ea-8e60-c522618ee404.png">

**Comment by jess-cook03** [comment]
@kkellydesign connecting this to ticket #135 -- sorry!

**Comment by kkellydesign** [comment]
@jess-cook03 design revisions are in here, but I still need to know which illustrations to use. https://github.com/mozilla/kitsune/pull/4193

**Comment by jess-cook03** [comment]
@kkellydesign 

- Volunteer --> use the hands -- (shown above in promo card option 04)
- Join Our Community --> use the people standing with dots --(shown above in promo option 01/default)

**Comment by jess-cook03** [comment]
@jonichan Can we get some copy for these two kinds of cards --- Volunteer and then Join the Community ?
Body copy and CTA primarily.

**Comment by kkellydesign** [comment]
She already provided that here: https://github.com/mozilla/sumo-project/issues/165#issuecomment-587959431

**Comment by kkellydesign** [comment]
This will go up with https://github.com/mozilla/kitsune/pull/4195

<img width="1334" alt="Screen Shot 2020-02-27 at 2 41 14 PM" src="https://user-images.githubusercontent.com/202590/75480559-7fe24a80-596f-11ea-8171-5f58ae3fe5de.png">
<img width="983" alt="Screen Shot 2020-02-27 at 2 41 52 PM" src="https://user-images.githubusercontent.com/202590/75480563-7fe24a80-596f-11ea-8928-1c07935612f0.png">

**Comment by jess-cook03** [comment]
Confirming this is all set
