### ISSUE TITLE
[ Featured Articles & Threads] The name of an Article is not displayed correctly 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#185]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/
2. Scroll down until the "Featured Articles & Threads" section
3. Observe the name of the articles displayed. 

ER: There are 4 articles displayed and the name of the articles is displayed correctly. 
AR: There are 4 articles displayed and the name of the articles is not displayed correctly. See the print scree with the actual result. 
![Screenshot 2020-02-24 at 11 57 05](https://user-images.githubusercontent.com/54845678/75143526-d5172580-56fd-11ea-8f65-cb3767dfdd9f.png)

**Comment by kkellydesign** [comment]
This is fixed – URLs or variable names that stretch more than the length of the line will break in the middle of the word on these cards only. It can have unintended consequenses if we apply this too globally, so I've made it specific. 

This will go up here: https://github.com/mozilla/kitsune/pull/4186

<img width="335" alt="Screen Shot 2020-02-24 at 3 41 51 PM" src="https://user-images.githubusercontent.com/202590/75189573-77460600-571c-11ea-8b45-47313fdfffb3.png">

**Comment by kkellydesign** [comment]
This is in. You may have to refresh a couple of times to get the offending card to show up, but you can see it here: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
I verified it and I can confirm the fix. I used FF and chrome with OS X 11.14, Windows 10.
