### ISSUE TITLE
Responsive Redesign / 'See All Products' page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#186]
![image](https://user-images.githubusercontent.com/54991698/75274908-a4a0bb80-57d1-11ea-8773-57777d71143a.png)
Can we remove 'Support forum from all of these product cards? We don't need it repeated for each one.
@kkellydesign

**Comment by kkellydesign** [comment]
@jess-cook03 This is a data issue – all I have in the template is `{{ product.name }}`, so you'd need to change it on the actual title of the forums in the database.

**Comment by akatsoulas** [comment]
Indeed this is coming from the DB entries. @jess-cook03 I am closing this issue. Please feel free to reopen/file a new one if this needs a change in the DB and tag Joni.

**Comment by jess-cook03** [comment]
@kkellydesign okay so new needs with this page (related to AAQ) 
-- Can this link in the nav say **_"See All Product Forums"_**
![Screen Shot 2020-02-27 at 10 06 08 AM](https://user-images.githubusercontent.com/54991698/75462724-ab0a7100-5952-11ea-8130-98f16b869c3b.png)

This page will remain --- there is an alternative view of this page that is used today for the AAQ product selection -- which we will be utilizing for that (those cards on that page will not say 'support forum' within each title).
URL I'm referencing is: https://support.mozilla.org/en-US/questions/new

**Comment by kkellydesign** [comment]
This will go in with the next PR. 

<img width="302" alt="Screen Shot 2020-02-27 at 4 34 53 PM" src="https://user-images.githubusercontent.com/202590/75488878-1ec27300-597f-11ea-93a9-2a78d9271bcb.png">

**Comment by jess-cook03** [comment]
This is resolved
