### ISSUE TITLE
Exclude thunderbird and Firefox for Amazon devices from featured articles.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#188]

**Comment by ovidiuboca1** [comment]
@akatsoulas do I need to verify this? If yes please give me some guidance.

**Comment by akatsoulas** [comment]
Knowledge base articles related to Amazon devices and Thunderbird should not be displayed in the featured articles.

**Comment by ovidiuboca1** [comment]
Thanks. I verified it and there are no articles related to Amazon devices and Thunderbird in the Featured Articles section.
