### ISSUE TITLE
The "Download Firefox" button appears even though the Firefox browser is used, on iPad device

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#19]
STR:

Prerequisites: 
Open the Firefox browser in  RDM mode. Menu -> Web Developer -> select Responsive Desing Mode -> select iPad device

STR: 

1. Go to Support Mozilla page
2. Pick a product from the "Pick your product" section 
3. Click on "Home" button 

ER: You are redirected on the Mozilla Support homepage and you don't see any "Download Firefox" button
AR: You are redirected on the Mozilla Support homepage and you see the "Download Firefox" button even though you are using the Firefox browser. 

Please see the screen recording: https://streamable.com/ohj88

NOTE: It doesn't meeter what product you choose to form the "Pick your product" section

**Comment by kkellydesign** [comment]
Watching your screen recording, I believe this is working as expected. Even though you're using Firefox, when you switch to the 'ipad' tab in Firefox, that emulates the iPad Safari user agent, which is what triggers the 'download firefox' button to be displayed.

**Comment by ovidiuboca1** [comment]
I also tested on Windows 10 and the download button is in the middle of the page, see the print screen - https://imgur.com/a/etF5tDX

**Comment by kkellydesign** [comment]
Some minor styling fixes are in for this component. Here's what it looks like in Chrome: 

<img width="821" alt="Screen Shot 2020-01-30 at 4 04 43 PM" src="https://user-images.githubusercontent.com/202590/73490325-402d4080-437a-11ea-9b2c-630327393ac0.png">

Note that this appears based on user agent, so if you switch to iPad in devtools, it should appear. I've been testing this component in Chrome, and it's working as expected there.

**Comment by ovidiuboca1** [comment]
> I also tested on Windows 10 and the download button is in the middle of the page, see the print screen - https://imgur.com/a/etF5tDX

I verified this and I can confirm the fix. The initial issue is happening because of the user agent.
