### ISSUE TITLE
Responsive Redesign // Products cards need enlarged logos/icons - home & product pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#191]
![IMG_3668](https://user-images.githubusercontent.com/54991698/75476875-59b9ac00-5969-11ea-9e3c-1af70416275b.PNG)
See cards above with very tiny logo -- this is on mobile.
But across breakpoints this is still an issue.
@kkellydesign

**Comment by kkellydesign** [comment]
duplicate of this issue: https://github.com/mozilla/sumo-project/issues/162#issuecomment-585819960

**Comment by kkellydesign** [comment]
See this comment for exactly where these logos need to go: https://github.com/mozilla/sumo-project/issues/162#issuecomment-592650851

**Comment by jess-cook03** [comment]
@akatsoulas @LeoMcA @kkellydesign
All Product logos to be uploaded:
SUMO_Product Logo Assets.zip

**Comment by jess-cook03** [comment]
UPDATED: 
[SUMO_Product Logo PNGs.zip](https://github.com/mozilla/sumo-project/files/4394642/SUMO_Product.Logo.PNGs.zip)
