### ISSUE TITLE
Respsonsive Redesign // Vertical Spacing - Global UI update

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#192]
@kkellydesign 
This folder has spacing specs across breakpoints...
[Spacing specs.zip](https://github.com/mozilla/sumo-project/files/4263968/Spacing.specs.zip)

Can this be applied generally across templates?
I am going to update this comment with outlines of general rules

**Comment by jess-cook03** [comment]
@kkellydesign 

- [ ] Page templates with breadcrumbs and search bar (small) in header
![Screen Shot 2020-02-27 at 3 40 06 PM](https://user-images.githubusercontent.com/54991698/75484818-7d83ee80-5977-11ea-9008-79776bc87836.png)

**Comment by kkellydesign** [comment]
This is in here: https://github.com/mozilla/kitsune/pull/4201
