### ISSUE TITLE
Responsive Redesign // answer thread on mobile, text stacking UI

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#193]
@kkellydesign 
Items are stacking so close together it looks jumbled ....
Increase the spacing vertical spacing between content -- as mentioned in specs

![Screen Shot 2020-02-27 at 4 27 08 PM](https://user-images.githubusercontent.com/54991698/75488409-4533de80-597e-11ea-8d61-69ded5a69cdd.png)

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4201

<img width="600" alt="Screen Shot 2020-03-02 at 12 32 47 PM" src="https://user-images.githubusercontent.com/202590/75701577-05bd0900-5c82-11ea-8ad4-1c933a67e843.png">

**Comment by jess-cook03** [comment]
Fixed
