### ISSUE TITLE
Responsive Redesign // subtopics remove from article list in topics page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#196]
@kkellydesign 
Remove these subtopics from showing in the content area:
<img width="1413" alt="Screen Shot 2020-02-28 at 10 33 09 AM" src="https://user-images.githubusercontent.com/54991698/75562015-ea4dc600-5a15-11ea-8071-7e1dc55c977c.png">
Should look more like this, only using the tabs to navigate and view them:
<img width="1433" alt="Screen Shot 2020-02-28 at 10 33 20 AM" src="https://user-images.githubusercontent.com/54991698/75562030-ef127a00-5a15-11ea-9b8e-f01a93221011.png">

**Comment by kkellydesign** [comment]
This will go in with https://github.com/mozilla/kitsune/pull/4201
<img width="624" alt="Screen Shot 2020-02-28 at 1 24 02 PM" src="https://user-images.githubusercontent.com/202590/75575158-9cdd5300-5a2d-11ea-8cc1-dffaf6ffc634.png">

**Comment by jess-cook03** [comment]
Fixed

**Comment by jess-cook03** [comment]
Fixed
