### ISSUE TITLE
Responsive Redesign // Typography across breakpoints - sizing/align styles

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#197]
@kkellydesign 
Outlining this in a way that hopefully is as clear and not confusing as possible (let me know if you need me to clarify anything).

- [x] See below for **Home & Product page templates:**
![Product Page_Desktop01](https://user-images.githubusercontent.com/54991698/75567687-ecb51d80-5a1f-11ea-83e0-63499692a71d.png)
![Product Page_Tablet01](https://user-images.githubusercontent.com/54991698/75567692-ee7ee100-5a1f-11ea-9e2f-7fea5573c8ac.png)
![Product Pages_Mobile01](https://user-images.githubusercontent.com/54991698/75567701-f0e13b00-5a1f-11ea-835d-e1c8336eaa07.png)
**Overview here:**
- Page titles / DKTP 56 / TBLT 48 / MB 32
- Section Headings (for 'Get help' and featured articles) stay 24 across all breakpoints.
- Headings in modules (community/volunteer DKTP 48 / TBLT 40 / MB 32 and then need more help DKTP 32 / TBLT 32 / MB 24) 
- Body copy should be fine -- standard across breakpoints being used are 16px and 14px.
- Tags (small UI) gets Body 12px
__________________________________________________________
See below for **All other page templates** (including **forum / search / profile / kb articles / topics** etc)
- [x] Headings are consistent across these templates, and they differ slightly from the breakdown used for the home/product pages above -- that is the main difference here between templates. 
DKTP 48 / TBLT 40 / MB 32
Below are only a few examples:
<img width="1148" alt="Screen Shot 2020-02-28 at 12 06 20 PM" src="https://user-images.githubusercontent.com/54991698/75569249-c349c100-5a22-11ea-98ad-fe7067343c07.png">
<img width="1061" alt="Screen Shot 2020-02-28 at 12 13 53 PM" src="https://user-images.githubusercontent.com/54991698/75569803-d27d3e80-5a23-11ea-874a-f47b3e482180.png">
<img width="1079" alt="Screen Shot 2020-02-28 at 12 18 40 PM" src="https://user-images.githubusercontent.com/54991698/75570119-7bc43480-5a24-11ea-8f63-df14657f95db.png">

**Comment by jess-cook03** [comment]
@kkellydesign please note -- majority of this is just cross checking.
The issues I have seen on the staging site reflect in the 24px vs. 18px type styles and sizes that are inconsisent --- and the **rule there is anything 24px should be metropolis -- anything 18px should be inter bold or regular.**

**Comment by kkellydesign** [comment]
I believe I got all of this. It was a huge amount of find/replace, so the commits are very large. But it should all be fixed in the next release, https://github.com/mozilla/kitsune/pull/4201. Let me know if I've missed anything. 

Kasey

**Comment by jess-cook03** [comment]
Confirming this fix
