### ISSUE TITLE
The "Log In/Sign up" button is replaced with a different icon - on Mobile devices

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#20]
STR:

Prerequisites: Open the Firefox browser in RDM mode. Menu -> Web Developer -> select Responsive Desing Mode -> select a mobile device, iPhone X for example

STR:

1. Go to Support Mozilla page

ER: The "Log In/Sign up" button is still there.
AR: The "Log In/Sign up" button is replaced with a different icon.

NOTE: This issue is similar to this one https://github.com/mozilla/kitsune/issues/4078

**Comment by kkellydesign** [comment]
The icon that you see is the default 'gravatar' icon for when a user isn't logged in. 

<img width="522" alt="Screen Shot 2020-01-17 at 4 43 07 PM" src="https://user-images.githubusercontent.com/202590/72649038-8500b280-394a-11ea-8225-13d95129aec4.png">

When it's clicked, you should get this:
<img width="487" alt="Screen Shot 2020-01-17 at 5 31 02 PM" src="https://user-images.githubusercontent.com/202590/72650729-4c170c80-394f-11ea-9724-a1f62821f995.png">

However the testing server is throwing some errors that I'm not getting locally: @akatsoulas I would guess this is related to the Protocol static files not being pulled into the static directory, as the error I'm seeing on the test server is this: 
<img width="389" alt="Screen Shot 2020-01-17 at 5 33 19 PM" src="https://user-images.githubusercontent.com/202590/72650866-bc259280-394f-11ea-86c9-e215c3a0d555.png">

Once a user is logged in and they have a gravatar, that will be their own photo, like this: 
<img width="438" alt="Screen Shot 2020-01-17 at 4 42 17 PM" src="https://user-images.githubusercontent.com/202590/72649506-dd847f80-394b-11ea-9133-bf64fca20330.png">

And then when that is clicked, you get this: 
<img width="555" alt="Screen Shot 2020-01-17 at 5 14 56 PM" src="https://user-images.githubusercontent.com/202590/72650908-deb7ab80-394f-11ea-8aed-bd6da4b887bf.png">

**Comment by kkellydesign** [comment]
I'll note that I can wrap a conditional around this icon to display a different default design if the user is logged out, and that will look a little nicer. I know I've seen a nice color version of this icon, but I can't seem to find it: 
<img width="78" alt="Screen Shot 2020-01-17 at 5 42 00 PM" src="https://user-images.githubusercontent.com/202590/72651239-c8f6b600-3950-11ea-839a-8b0136f41e9e.png">

@jess-cook03, if you could dig up a PNG or SVG for me, I can use that instead.

**Comment by kkellydesign** [comment]
This is ready to be tested again. https://test.sumo.mozit.cloud/en-US/ 

The JS is working now, and when logged out, the mozilla avatar is used instead of the default gravatar. Note though that when you're logged in, IF you're on a sumo account with an e-mail address that doesn't have a gravatar assigned, you'll see the gravatar default, as in the screenshot above. Here's a screenshot of the current logged-out view: 

<img width="633" alt="Screen Shot 2020-02-11 at 10 46 02 AM" src="https://user-images.githubusercontent.com/202590/74252452-b8b9c880-4cbb-11ea-80b7-67e67089cd44.png">

**Comment by ovidiuboca1** [comment]
I verified this on mobile devices with iOS and Android and the issue is fixed.
