### ISSUE TITLE
[Search] The text from the search bar overlaps the magnifying glass icon

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#202]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/
2. Focus the search bar and write a long text (more than 28 characters)
3. Scroll the page until the sticky bar is visible.
4. Look at the search bar.

ER: The text doesn't overlap the magnifying glass icon
AR: The text from the search bar overlaps the magnifying glass icon

Note: Here is a video with the actual result: https://streamable.com/s1r6n

**Comment by kkellydesign** [comment]
This fix will be in here: https://github.com/mozilla/kitsune/pull/4212
<img width="417" alt="Screen Shot 2020-03-06 at 9 44 06 AM" src="https://user-images.githubusercontent.com/202590/76093495-0bbb2e80-5f8f-11ea-9003-5afb1047b0d7.png">

**Comment by ovidiuboca1** [comment]
@kkellydesign On Windows 10 I see a close button in the search field but on Mac 10.14 the search field doesn't have any close button and the field can't be clear. Please let me know if this is intended based on the OS design or is a bug?

**Comment by kkellydesign** [comment]
clear button has been removed from both safari and edge: 

before: 
<img width="956" alt="Screen Shot 2020-03-11 at 10 34 40 AM" src="https://user-images.githubusercontent.com/202590/76428489-1d804580-6384-11ea-89c2-810d5e761662.png">
<img width="1182" alt="Screen Shot 2020-03-11 at 10 32 06 AM" src="https://user-images.githubusercontent.com/202590/76428491-1d804580-6384-11ea-9c6e-77ef1fcb1fd6.png">

after: 
<img width="932" alt="Screen Shot 2020-03-11 at 10 35 05 AM" src="https://user-images.githubusercontent.com/202590/76428509-22dd9000-6384-11ea-97de-1c63dec17eda.png">

**Comment by ovidiuboca1** [comment]
I verified this issue on desktop (Win 10 and Mac 10.14) and I can confirm the fix.
