### ISSUE TITLE
Need more help component / typography incorrect

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#203]
@kkellydesign 
Site wide we are almost always using the Firefox branded - purple/Metropolis/white skinned component NOT the mozilla Zilla slab one which is grey, that should only live within contributor pages and right now they only page that should be using the grey mozilla one is the 'volunteer/get involved page.

- [x] Right now site wide this is using Zilla with the purple Firefox branding - should be Metropolis:
<img width="1398" alt="Screen Shot 2020-03-05 at 10 53 32 AM" src="https://user-images.githubusercontent.com/54991698/75999760-b4ef1f80-5ed0-11ea-9c2a-70b76d8bffbf.png">

- [x] This is the correct styling for the mozilla branded one -- but this placement is wrong -- within search we dont use mozilla brand it should be the firefox one as shown above.
And right now within the search pages this grey one pops up and its touching the elements on the page -- spacing is also an issue here -- in this instance this should be the firefox branded one.
<img width="1439" alt="Screen Shot 2020-03-04 at 8 51 06 AM" src="https://user-images.githubusercontent.com/54991698/75999823-c89a8600-5ed0-11ea-9ce6-f4ca1d81c5d5.png">

Im linking this ticket so you can reference the designs #179

**Comment by kkellydesign** [comment]
This is fixed: https://github.com/mozilla/kitsune/pull/4212

<img width="1177" alt="Screen Shot 2020-03-06 at 12 29 22 PM" src="https://user-images.githubusercontent.com/202590/76107610-07027480-5fa7-11ea-8cec-4043ce31b64a.png">

**Comment by madasan** [comment]
@jess-cook03 can you confirm this is fixed?

**Comment by jess-cook03** [comment]
Yes this is fixed
@madasan
