### ISSUE TITLE
KB article pages / headlines are all the same large size, see specs

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#204]
@kkellydesign this is the current:
<img width="1458" alt="Screen Shot 2020-03-04 at 8 38 59 AM" src="https://user-images.githubusercontent.com/54991698/76000349-93dafe80-5ed1-11ea-8ffa-94c90deb227b.png">

See desired:
![image](https://user-images.githubusercontent.com/54991698/76000497-cb49ab00-5ed1-11ea-9f18-64c583b94277.png)

**Comment by kkellydesign** [comment]
This fix is in: 
https://test.sumo.mozit.cloud/en-US/kb/i-found-fake-firefox-update

**Comment by jess-cook03** [comment]
This is now fixed
