### ISSUE TITLE
Join our community & volunteer component spacing

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#205]
@kkellydesign with the type size increase the spacing as gotten compromised here across breakpoints, it feels crunched together and the image seems smaller:
<img width="320" alt="Screen Shot 2020-03-04 at 8 41 35 AM" src="https://user-images.githubusercontent.com/54991698/76000656-03e98480-5ed2-11ea-96bf-a494978739d9.png">
<img width="1432" alt="Screen Shot 2020-03-04 at 8 41 17 AM" src="https://user-images.githubusercontent.com/54991698/76000664-04821b00-5ed2-11ea-9e77-7f78b27b9619.png">

Can we add more spacing / padding between these elements?
The ideal look is to get as close to this spacing here as possible:
<img width="1274" alt="Screen Shot 2020-03-05 at 11 11 47 AM" src="https://user-images.githubusercontent.com/54991698/76001600-55464380-5ed3-11ea-99b1-4c26b0ca6dbc.png">
If that means dropping it back down to type sizes 40/40/32 thats fine too.

**Comment by kkellydesign** [comment]
This is in: https://github.com/mozilla/kitsune/pull/4212

<img width="1092" alt="Screen Shot 2020-03-06 at 12 53 12 PM" src="https://user-images.githubusercontent.com/202590/76109450-75950180-5faa-11ea-9c52-13db40c217fe.png">
<img width="427" alt="Screen Shot 2020-03-06 at 12 59 58 PM" src="https://user-images.githubusercontent.com/202590/76109457-77f75b80-5faa-11ea-972a-d18a497d112d.png">

**Comment by madasan** [comment]
@jess-cook03 is this fixed? Can we move this ticket?

**Comment by jess-cook03** [comment]
@madasan confirming yes this is fixed
