### ISSUE TITLE
Search fonts changing based on if there is a result or not

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#206]
@kkellydesign weirdly when you type something that has a result -- you get the correct fonts and styling, shown below:
<img width="1479" alt="Screen Shot 2020-03-04 at 8 50 37 AM" src="https://user-images.githubusercontent.com/54991698/76002586-d6520a80-5ed4-11ea-9c51-4d3582ec775a.png">

 -- when you input something else with no results you get this:
<img width="1426" alt="Screen Shot 2020-03-04 at 8 50 24 AM" src="https://user-images.githubusercontent.com/54991698/76002605-deaa4580-5ed4-11ea-8106-314af50b287c.png">

Also the spacing is compromised in this template as well:
Can we increase this top padding on this container under the grey box to be 48px -- too crunched right now. Should reflect the same spacing on the home page and within all pages using the grey box 
<img width="1047" alt="Screen Shot 2020-03-05 at 11 30 45 AM" src="https://user-images.githubusercontent.com/54991698/76003224-be2ebb00-5ed5-11ea-87d2-c5fca680b859.png">

**Comment by kkellydesign** [comment]
These fixes are in: https://github.com/mozilla/kitsune/pull/4212
<img width="1167" alt="Screen Shot 2020-03-06 at 11 47 59 AM" src="https://user-images.githubusercontent.com/202590/76103838-5f824380-5fa0-11ea-860a-ff1babdc5113.png">
<img width="1267" alt="Screen Shot 2020-03-06 at 11 48 05 AM" src="https://user-images.githubusercontent.com/202590/76103842-614c0700-5fa0-11ea-843b-622c51293345.png">

**Comment by jess-cook03** [comment]
confirming this is fixed
