### ISSUE TITLE
Responsive text alignment on home/product pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#207]
<img width="333" alt="Screen Shot 2020-03-04 at 8 52 35 AM" src="https://user-images.githubusercontent.com/54991698/76012179-dad1ef80-5ee3-11ea-9de8-27f39c174877.png">
<img width="327" alt="Screen Shot 2020-03-04 at 8 52 51 AM" src="https://user-images.githubusercontent.com/54991698/76012184-dc031c80-5ee3-11ea-8987-a10bf2c19ee3.png">
@kkellydesign
Seeing home pages with center and then product pages with left ----> lets just make this template all go center when responsive -- they should be consistent

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4212

<img width="483" alt="Screen Shot 2020-03-06 at 12 06 44 PM" src="https://user-images.githubusercontent.com/202590/76105511-14b5fb00-5fa3-11ea-9aae-2d11c40f9d68.png">

on Chrome, with the DL button: 
<img width="438" alt="Screen Shot 2020-03-06 at 12 06 49 PM" src="https://user-images.githubusercontent.com/202590/76105559-29928e80-5fa3-11ea-8c59-990868e909cd.png">

**Comment by jess-cook03** [comment]
Confirming this is fixed
