### ISSUE TITLE
Contributor pages -- typography not consisent 

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#208]
![Screen Shot 2020-03-04 at 9 26 00 AM](https://user-images.githubusercontent.com/54991698/76012463-52078380-5ee4-11ea-8c00-5355fd5e2507.png)
https://test.sumo.mozit.cloud/en-US/community
Mixing type here ^

@kkellydesign within these pages listed these are the only contributor pages using zilla slab -- i know we had wanted to change these to all mozilla branded -- but right now it just feels really inconsistent when navigating through all the pages.
- https://test.sumo.mozit.cloud/en-US/flagged
- https://test.sumo.mozit.cloud/en-US/community
- https://test.sumo.mozit.cloud/en-US/contributors

I think we just need to make a call - they either all get Zilla or they don't and revert back to default styling like the rest of the site...
@kkellydesign which is easier for you given the time we have left?

**Comment by jess-cook03** [comment]
@kkellydesign revert all pages back to default Firefox styling for now --- all pages except for https://test.sumo.mozit.cloud/en-US/get-involved and that family of pages

**Comment by kkellydesign** [comment]
This is in: https://github.com/mozilla/kitsune/pull/4212

<img width="885" alt="Screen Shot 2020-03-06 at 12 17 12 PM" src="https://user-images.githubusercontent.com/202590/76106381-ba1d9e80-5fa4-11ea-9584-3a0239bfd60f.png">

**Comment by jess-cook03** [comment]
Confirming this is all set
