### ISSUE TITLE
Forum question titles should be larger / 32 instead of 24 on larger breakpoints

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#209]
<img width="1421" alt="Screen Shot 2020-03-04 at 9 31 16 AM" src="https://user-images.githubusercontent.com/54991698/76013243-a0695200-5ee5-11ea-8cc0-9402f9bb0d32.png">
Also @kkellydesign here desktop using 24px should be 32 (dsktp 32 / tb 24 / mb 24) and  ^ there is there no line or divider between the # of replies and # of views ?? See mock below:
<img width="1020" alt="Screen Shot 2020-03-05 at 1 35 37 PM" src="https://user-images.githubusercontent.com/54991698/76013616-3a30ff00-5ee6-11ea-914e-54c6549972f7.png">

**Comment by kkellydesign** [comment]
This will be in here: https://github.com/mozilla/kitsune/pull/4212

<img width="973" alt="Screen Shot 2020-03-06 at 8 55 23 AM" src="https://user-images.githubusercontent.com/202590/76089966-afeda700-5f88-11ea-9a32-1554e8d3d00d.png">

**Comment by jess-cook03** [comment]
Confirming this fix
