### ISSUE TITLE
The URLs for "Nightly" and "Nightly for Android" are linked to a wrong page

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#21]
STR:

1. Go to Support Mozilla page
2. Scroll to the bottom of the page
3. Click on "Nightly" and "Nightly for Android" buttons

ER: The URLs are linked to the proper pages. 
AR: The URLs are linked to a wrong page.

**Comment by kkellydesign** [comment]
@ovidiuboca1 could you please provide the correct link? I'm seeing this for Nightly: 
https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly?utm_source=support.mozilla.org&utm_campaign=footer&utm_medium=referral

And this for Nightly for Android: 
https://www.mozilla.org/en-US/firefox/channel/android/#nightly?utm_source=support.mozilla.org&utm_campaign=footer&utm_medium=referral

Both of those appear correct to me.

**Comment by jess-cook03** [comment]
@jonichan adding you here to check this

**Comment by kkellydesign** [comment]
These fixes are in – the URLs were formatted incorrectly. The #nightly and #beta hashes needed to be after the query parameter. This will be ready to test when https://github.com/mozilla/kitsune/pull/4177 goes live.

**Comment by kkellydesign** [comment]
These are in – test in the footer here: https://test.sumo.mozit.cloud/

**Comment by jonichan** [comment]
Verifying that the links worked.

**Comment by ovidiuboca1** [comment]
I verified this and I can confirm the fix.
