### ISSUE TITLE
[AAQ] "Ask this" button doesn't work 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#211]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/questions/new/desktop/tips
2. Write a question 
3. Click on "Ask this" button

ER: The question is posted
AR: No action is performed

**Comment by akatsoulas** [comment]
@kkellydesign could you take a look at this?

**Comment by kkellydesign** [comment]
@ovidiuboca1 I believe this works as expected: 
1. Type "Firefox" and hit "ask this." 
2. The server takes one more guess at a question that would be helpful, so you get this screen: 
<img width="967" alt="Screen Shot 2020-03-11 at 1 02 34 PM" src="https://user-images.githubusercontent.com/202590/76443410-be78fb80-6398-11ea-9dd9-8e9d5dd399c5.png">
3. Hit "none of these solve my problem", and THEN you get the correct form.

**Comment by madasan** [comment]
This is working as expected. It will be addressed in the AAQ redesign project as it is not ideal.
