### ISSUE TITLE
[Article] The "Confusing" option can't be selected when you vote thumb down

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#212]
STR:

1. Go to an article, for example, https://test.sumo.mozit.cloud/en-US/kb/troubleshoot-SEC_ERROR_UNKNOWN_ISSUER#firefox:mac:fx69
2. Scroll the page until the voting UI is displayed
3. Click on  thumb down
4. Select "Confusing" option 

ER: The "Confusing" option can be selected.
AR: The "Confusing" option can't be selected.

Note: The issue is also repro on mobile devices.

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4212

<img width="300" alt="Screen Shot 2020-03-06 at 1 47 57 PM" src="https://user-images.githubusercontent.com/202590/76113045-62d1fb00-5fb1-11ea-9607-2c125824b043.png">
<img width="295" alt="Screen Shot 2020-03-06 at 1 48 47 PM" src="https://user-images.githubusercontent.com/202590/76113047-64032800-5fb1-11ea-9c24-ab68b0334b8e.png">

**Comment by ovidiuboca1** [comment]
I verified this on Mac OS X 10.14, Windows 10 and iPad with Firefox v73 and Chrome browsers and I can confirm the fix. 
During the verification, I spotted another issue, the text from the feedback box can't be selected using the mouse. I will log another issue for this.
