### ISSUE TITLE
Contributor accounts numbers for FxA switch

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#213]
As we're moving to FxA login only we need to understand how many contributor accounts have not yet made the switch: 

Please pull a report of active contributors who:
- Do not have FxA
- Have logged in at least once in the last year

**Definitions**:

A **contributor** is defined as having more than 5 contributions

An **active contributor** is defined as 
- Not marked as inactive
- Not a staff member
- Has made contributions in the last 2 years

A **contribution** is defined as:
- Answer to a thread in the support forum that was not created by them
- A revision, review or draft revision of  KB article (multiple revisions on one article counts as one contribution)
- Creation of a thread or post in the contributor forums

**Comment by akatsoulas** [comment]
These numbers have been shared in a doc.
