### ISSUE TITLE
Navigation menu language changes

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#214]
@kkellydesign 

- [x] Can we change this link to be: Contributor Forums instead of this -- > <img width="528" alt="Screen Shot 2020-03-05 at 1 27 07 PM" src="https://user-images.githubusercontent.com/54991698/76097459-be8e8b00-5f95-11ea-9df5-9766f07486c5.png">

- [x] Can we change this to say "Browse All Product Forums"
Body copy edits to say: "Create a thread and find answers by posting a question to any of our product support forums."
![Screen Shot 2020-03-06 at 9 54 41 AM](https://user-images.githubusercontent.com/54991698/76097757-3f4d8700-5f96-11ea-8175-c47371e2e159.png)

**Comment by kkellydesign** [comment]
This will go in here: https://github.com/mozilla/kitsune/pull/4212

<img width="620" alt="Screen Shot 2020-03-06 at 11 52 46 AM" src="https://user-images.githubusercontent.com/202590/76104258-0bc42a00-5fa1-11ea-8608-2c3a96c37137.png">
<img width="543" alt="Screen Shot 2020-03-06 at 11 52 52 AM" src="https://user-images.githubusercontent.com/202590/76104259-0c5cc080-5fa1-11ea-8cf8-1157ac09ff23.png">

**Comment by ovidiuboca1** [comment]
@jess-cook03 I verified this on Windows 10 and Mac OS X 10.14 with Firefox v73 and Chrome and I can confirm the fix, can we close this and move it to the ready to deploy?
