### ISSUE TITLE
Profile nav menu hover / 'x' not needed, sign out button spacing

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#215]
![Screen Shot 2020-03-09 at 4 08 49 PM](https://user-images.githubusercontent.com/54991698/76253093-64552a80-6220-11ea-916d-3dd1cd6d07f5.png)
I think we can kill this 'x' here as the the menu is on hover anyways? @kkellydesign 

Could we also space out the sign out button from the inbox section there? its too close, accidentally signed out when trying to view inbox.

**Comment by kkellydesign** [comment]
This is in: 
<img width="515" alt="Screen Shot 2020-03-11 at 1 13 08 PM" src="https://user-images.githubusercontent.com/202590/76444322-2a0f9880-639a-11ea-94b1-ba40efda4209.png">

**Comment by kkellydesign** [comment]
@jess-cook03 update on this: I need to put the X button back. Protocol is throwing errors now that I've removed it because the javascript assumes it's there. It's a straightforward fix in protocol, but I've made a point not to change those files so far to make upgrading easier in the future.

**Comment by ovidiuboca1** [comment]
@jess-cook03 please take a look at this and see if we can consider it done?

**Comment by jess-cook03** [comment]
@kkellydesign @ovidiuboca1 if we need to keep the x then thats fine -- we can consider this done.
