### ISSUE TITLE
[Mobile] Clicking on "Contributors Tools" you are redirected to /get-involved

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#216]
Prerequisites:

Use a mobile device
You need to be login

STR:

1. Go to https://test.sumo.mozit.cloud/en-US/
2. Click on menu icon
3. Click on "Contributor Tools" 

ER: The drop-down menu is displayed. 
AR: You are redirected to https://test.sumo.mozit.cloud/en-US/get-involved

NOTE: I'm not sure but this might be a regression.

**Comment by kkellydesign** [comment]
@ovidiuboca1 I like to put real links on top-level nav as a fallback, incase the hover state doesn't fire, and that's the link that seemed to make sense to me. 

So yes it was on purpose, but I don't have a strong opinion about it. I'm happy to change it back to "#" if you'd like, which is what the current site does. 

@jess-cook03, do you have an opinion about this one?

**Comment by kkellydesign** [comment]
This will be in here: https://github.com/mozilla/kitsune/pull/4228

**Comment by ovidiuboca1** [comment]
I tested this on a mobile device (iPhone 8plus) and I can confirm the fix.
