### ISSUE TITLE
Icons for featured articles is not correct

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#217]
@kkellydesign 
Icons for featured articles cards right now are the thread icons -- should look like this instead:
![Screen Shot 2020-03-10 at 12 06 08 PM](https://user-images.githubusercontent.com/54991698/76333117-8ce42f80-62c7-11ea-8e43-d97eaf04fe26.png)

**Comment by kkellydesign** [comment]
This will be in here: https://github.com/mozilla/kitsune/pull/4215
<img width="1300" alt="Screen Shot 2020-03-11 at 7 12 39 AM" src="https://user-images.githubusercontent.com/202590/76411484-4abefa80-6368-11ea-93f2-ad9749ee5b55.png">

**Comment by kkellydesign** [comment]
I also just fixed the alignment on these cards, per a conversation with Jess in Slack. 

<img width="1336" alt="Screen Shot 2020-03-11 at 11 57 03 AM" src="https://user-images.githubusercontent.com/202590/76437178-8e792a80-638f-11ea-8aa5-30e3ec342310.png">

**Comment by ovidiuboca1** [comment]
I verified this and I can confirm the fix. @jess can we close this?

**Comment by jess-cook03** [comment]
yes we can move this / done
