### ISSUE TITLE
AAQ / Error Messaging within the question form

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#219]
@akatsoulas 
This error message pops up, which is good, but it doesn't highlight the input field with red to show the user which field needs attention -- for a minute I couldn't figure out what needed more characters -- and it is also treated like a text link so I clicked it and it didnt do anything either ... ?
Is this something we can change? I know we have error states for the fields.
![Screen Shot 2020-03-10 at 12 35 54 PM](https://user-images.githubusercontent.com/54991698/76338087-9de46f00-62ce-11ea-862f-56f55eeae69e.png)
![Screen Shot 2020-03-10 at 12 39 10 PM](https://user-images.githubusercontent.com/54991698/76338104-a0df5f80-62ce-11ea-9a9d-400cf2e2f1cd.png)
If we outline the box here and point to the issue with the messaging underneath -- that helps users understand which field is needing attention in order to move forward

**Comment by kkellydesign** [comment]
BE validation is now cleaned up on this form. 
* I removed the error list at the top of the page 
* If there's an error on page load, I focus it with JS. It was doing that by default in Chrome, but not Firefox. Now it works everywhere. 

<img width="1024" alt="Screen Shot 2020-03-12 at 5 46 11 PM" src="https://user-images.githubusercontent.com/202590/76569414-74237780-6489-11ea-8524-3b175e176e60.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Win 10 and Mac OS X 10.14) and mobile device and I can confirm the fix. 
@jess-cook03 It's ok from your point of view to consider this as done? If yes please move it to the "Ready for deploy".

**Comment by jess-cook03** [comment]
@kkellydesign @ovidiuboca1 Im getting the red highlight but no error messaging underneath is coming up until I try and post the question.... is this what we want here? 
I would imagine it would have inline messaging ?
if not thats okay for now but just checking --- I can confirm the red highlight is working and text appears after hitting 'post'

**Comment by kkellydesign** [comment]
Yeah, it's backend validation, as that error message is coming from the server. There is minor HTML validation, but that doesn't give you a custom error message, just the little red highlight. That's a browser feature; there's no javascript validation system in place. So that would fall into "feature, not a bug" territory.
