### ISSUE TITLE
"Join the Community" and "Explore Help Articles" from the footer section are not linked anywhere.

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#22]
STR: 

1. Open the Support Mozilla page 
2. Scroll to the bottom of the page 
3. Click on "Join the Community" and "Explore Help Articles"

ER: The buttons are linked to specific pages.
AR: The buttons are not linked.

**Comment by kkellydesign** [comment]
Thanks for pointing that out – there are a handful of links in both the masthead nav and the footer that need actual links. If you could provide those for me, I can get them added.

**Comment by jonichan** [comment]
Join the Community: https://support.mozilla.org/get-involved
Explore Help Articles: https://support.mozilla.org/

@kkellydesign I noticed that the nav bar links are linking to the wrong pages. Are they still in progress or do you need the correct links for those?

**Comment by jess-cook03** [comment]
@jonichan could you post the updated links and confirm them?
Right now in the footer they are not linked at all.
In the navigation however we do have some links but need to clarify those as well:
Join the Community -- we currently have 'learn more' as the cta and right now and yes it links to /get-involved --- but please advise if that is not correct! 
Explore Help Articles link right now is wrong -- it links to common voice.
^ this link should either be a page anchor the the product cards on the home page OR open to your suggestions?

**Comment by jonichan** [comment]
> @jonichan could you post the updated links and confirm them?
> Right now in the footer they are not linked at all.
> In the navigation however we do have some links but need to clarify those as well:
> Join the Community -- we currently have 'learn more' as the cta and right now and yes it links to /get-involved --- but please advise if that is not correct!
> Explore Help Articles link right now is wrong -- it links to common voice.
> ^ this link should either be a page anchor the the product cards on the home page OR open to your suggestions?

I posted my feedback right before yours.

**Comment by kkellydesign** [comment]
These links are fixed, and will go up with https://github.com/mozilla/kitsune/pull/4177

**Comment by kkellydesign** [comment]
These can be seen in the footer here: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
I can confirm the fix for this issue.
