### ISSUE TITLE
Increase padding at the bottom of each page between content & footer

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#220]
@kkellydesign I know this is a minor design massaging thing -- wondering if we could increase overall padding between footer and content area across the site and across breakpoints. Something standard like 72px unit or 96??
![Screen Shot 2020-03-10 at 12 13 21 PM](https://user-images.githubusercontent.com/54991698/76338504-27943c80-62cf-11ea-931e-642717e06b6f.png)
Example above ^

**Comment by kkellydesign** [comment]
I think I got all of the major templates with this fix. It's now 96px on large screens and 72 on medium across the board. 

<img width="1296" alt="Screen Shot 2020-03-11 at 11 06 49 AM" src="https://user-images.githubusercontent.com/202590/76431945-aa2d0280-6388-11ea-906c-1648ed90718e.png">
<img width="570" alt="Screen Shot 2020-03-11 at 11 06 40 AM" src="https://user-images.githubusercontent.com/202590/76431947-aac59900-6388-11ea-93ee-13826cf19894.png">
<img width="1038" alt="Screen Shot 2020-03-11 at 11 06 25 AM" src="https://user-images.githubusercontent.com/202590/76431948-aac59900-6388-11ea-9044-1a93329da04b.png">

**Comment by ovidiuboca1** [comment]
@jess-cook03  can you please take a look at this? thanks

**Comment by jess-cook03** [comment]
done
