### ISSUE TITLE
[verify in prod] AAQ / question form, troubleshooting links and actions

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#221]
@akatsoulas @kkellydesign 
From what I have seen with these numerous links at the bottom of the current question form here 

- [x] I'm not certain that the troubleshooting info button works?

- [ ] We have 'this field was automatically populated and nothing shows up?

The guesses about the operating system is the only here that seems to be working properly.

**Comment by akatsoulas** [comment]
This [PR](https://github.com/mozilla/kitsune/pull/4227) removes the deprecated addon.

**Comment by akatsoulas** [comment]
Moving this to QA to test the removal of the plugin

**Comment by ovidiuboca1** [comment]
The "Share data" button doesn't work.

**Comment by akatsoulas** [comment]
We can consider this done for now but keep the ticket under the QA column. Probably we cannot get data from any environment apart from prod. We can retest this there.

**Comment by akatsoulas** [comment]
This is working fine in prod.
