### ISSUE TITLE
KB Article pages / content that can be removed?

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#222]
![Screen Shot 2020-03-10 at 2 22 35 PM](https://user-images.githubusercontent.com/54991698/76346023-b3f82c80-62da-11ea-9f43-f12166e51e6b.png)
@jonichan 
Wondering what this is? https://test.sumo.mozit.cloud/en-US/kb/get-started-firefox-overview-main-features
Both this button and theres an inline text link here that seem confusing ? They link to the firefox product page? 
Do we need these? can we remove them? 
Is this a button that is added within the DB or the CMS? 

@kkellydesign if this is a real button why is it skinned differently?

**Comment by kkellydesign** [comment]
@jess-cook03 I can confirm this is database content, and doesn't exist in the repo. The button is an image: https://user-media-stage-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2014-03-21-12-12-34-a682e1.png

**Comment by jonichan** [comment]
I can remove the button image manually through the CMS and I thought it was supposed to link to the ask a question page . It was used only in that one article; we removed it from the recent version on the live site so we don't need that button anymore.

**Comment by jess-cook03** [comment]
@jonichan yes - lets remove the button image through the CMS and edit that section to meet the needs of briefly explaining "get help' and how they can ask the community - maybe we put an inline link to the AAQ there if we wanted?
But overall - remove green button for sure.
