### ISSUE TITLE
Topics page -- More tab misaligned / responsive compromised

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#223]
@kkellydesign see here: https://test.sumo.mozit.cloud/en-US/products/firefox/manage-preferences-and-add-ons-firefox
![Screen Shot 2020-03-10 at 2 58 23 PM](https://user-images.githubusercontent.com/54991698/76349100-bc9f3180-62df-11ea-8577-da98b554ba1e.png)
![Screen Shot 2020-03-10 at 2 58 40 PM](https://user-images.githubusercontent.com/54991698/76349102-bc9f3180-62df-11ea-8548-da8088ea4a2e.png)

Not sure what is causing this?

**Comment by jess-cook03** [comment]
@kkellydesign adding to this:
![Screen Shot 2020-03-10 at 3 05 42 PM](https://user-images.githubusercontent.com/54991698/76349597-afcf0d80-62e0-11ea-93d3-9ab9b4e1eab6.png)
See here we have the privacy parent tab over the page title here --- i know its pink because we are trying to show that its been visited -- can we remove that pink styling here?

**Comment by kkellydesign** [comment]
Tabs are fixed at desktop and mobile both: <img width="907" alt="Screen Shot 2020-03-11 at 10 52 12 AM" src="https://user-images.githubusercontent.com/202590/76431021-68e82300-6387-11ea-835e-af14bdb71e2c.png">

Visited state removed from subtopic heading, and margin added
<img width="594" alt="Screen Shot 2020-03-11 at 10 59 04 AM" src="https://user-images.githubusercontent.com/202590/76431010-62f24200-6387-11ea-9156-09e522ee4134.png">

**Comment by ovidiuboca1** [comment]
@jess-cook03 can you please take a look at this and let me know if we can consider this as done?

**Comment by jess-cook03** [comment]
Done
