### ISSUE TITLE
Topics page / breadcrumbs and parent topics selection 

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#225]
@kkellydesign @akatsoulas 
See here the breadcrumb and the dropdown selector are the same -- I understand WHY this is happening but is there a way for it to not?
Ideally the main breadcrumb should still say Firefox to go back a page level -- if the user wants to navigate back and forth between parent and child tabs they should use the dropdown and inpage tabs.
Right now we are getting confused because its duplicating between the two.
![IMG_3701](https://user-images.githubusercontent.com/54991698/76354207-697dac80-62e8-11ea-8a6f-9d7929cdf722.PNG)

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4215

<img width="581" alt="Screen Shot 2020-03-11 at 8 58 28 AM" src="https://user-images.githubusercontent.com/202590/76427555-d6de1b80-6382-11ea-9148-8a36e2e44996.png">
<img width="574" alt="Screen Shot 2020-03-11 at 8 58 21 AM" src="https://user-images.githubusercontent.com/202590/76427556-d776b200-6382-11ea-84eb-5872d22d247a.png">

**Comment by ovidiuboca1** [comment]
@jess-cook03 please take a look at this and let me know if we can close this?

**Comment by jess-cook03** [comment]
@ovidiuboca1 this is good for now -- done. 
@madasan I'd like to mark this as a backlog item to revisit the ux here.
