### ISSUE TITLE
When you want to add a tag to a question the dropdown is not displayed correctly 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#226]
Prerequisites: 

You need to be in the post a question flow.  https://test.sumo.mozit.cloud/en-US/questions/1207019

STR:

1. Click on "Add a tag" and write "a"

ER: A drop-down is displayed, you can scroll through the many options and you can select a tag.
AR: A drop-down is displayed all over the page.
![Screenshot 2020-03-11 at 14 18 00](https://user-images.githubusercontent.com/54845678/76416661-28e36900-63a4-11ea-8515-e65a8e2fcdbf.png)

Maybe we can move it for the responsive redesign V2.

**Comment by kkellydesign** [comment]
tag list is fixed: 
<img width="381" alt="Screen Shot 2020-03-11 at 11 24 23 AM" src="https://user-images.githubusercontent.com/202590/76433602-ecefda00-638a-11ea-94be-3b4364a7bbf2.png">

**Comment by ovidiuboca1** [comment]
@kkellydesign I tested this and the first time when the drop-down is displayed the scroll bar is missing the second time the scroll bar is there, please see the screen recording - https://streamable.com/rzhk9

**Comment by kkellydesign** [comment]
This appears to be an issue with the jquery UI autocomplete plugin. It tries to calculate the width of the component based on the parent, and it doesn't do it correctly until you hit more than one character.

For the sake of launch, I think this is ok for now.
