### ISSUE TITLE
Submitting a new KB article does not work in the test env.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#227]
Users cannot create new articles under the `kb/new` url because the submit button in the modal does not post the question. The rest of the functionality under that url is *not* tested.

cc @ovidiuboca1 @kkellydesign @jess-cook03 @madasan

**Comment by akatsoulas** [comment]
@kkellydesign this [PR](https://github.com/mozilla/kitsune/pull/4220) is definitely not a fix but maybe part of it. What I observed is that the `kbox` class brings back the editor under the content form field to allow Markdown like syntax.

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and mobile (iPhone 8 plus) and I can confirm that the submit button is working and a new kb is submitted.
