### ISSUE TITLE
Raw content is displayed in the kbforums.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#228]
In posts like this, showfor functionality (Kitsune's markup) is rendered into the page.
https://test.sumo.mozit.cloud/en-US/kb/containers/discuss/7459

cc @ovidiuboca1 @kkellydesign @jess-cook03 @madasan

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/4223

**Comment by jess-cook03** [comment]
Sorry may have duplicated this here: #237

**Comment by kkellydesign** [comment]
commented here: https://github.com/mozilla/sumo-project/issues/237

**Comment by ovidiuboca1** [comment]
The issue is still there, I've just tested in on desktop.

**Comment by akatsoulas** [comment]
The raw content is not displayed any more.
