### ISSUE TITLE
[KB article] The contributors icons under the "Document Contributors" section are too large 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#229]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/kb/search-working-article-test/history#preview

ER: The contributors' icons are displayed correctly. 
AR: The contributors' icons are displayed incorrectly.

**Comment by kkellydesign** [comment]
This will be fixed in https://github.com/mozilla/kitsune/pull/4228

<img width="546" alt="Screen Shot 2020-03-13 at 1 00 55 PM" src="https://user-images.githubusercontent.com/202590/76643055-be106a00-652a-11ea-8ce5-70d98f5a453a.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and mobile (iPhone 8 plus) and I can confirm the fix.
