### ISSUE TITLE
[KB] The functionality of the buttons from "Watch" column is not working

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#231]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/kb/all/discussions
2. Click on the "X" button from the Watch column. 

ER: The button is actionable.
AR: The button can be clicked and no action is performed. 
Note: This works on staging.

**Comment by kkellydesign** [comment]
This will be fixed here: https://github.com/mozilla/kitsune/pull/4228

<img width="150" alt="Screen Shot 2020-03-13 at 12 36 24 PM" src="https://user-images.githubusercontent.com/202590/76641088-691f2480-6527-11ea-9b82-0daea093d06b.png">

**Comment by ovidiuboca1** [comment]
I tested this on desktop (Mac OS X 10.14) and mobile (iPhone 8 plus) and I can confirm the fix.
