### ISSUE TITLE
The Search from the "Page not found" is not working

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#233]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/forums/posttttt
2. Write something in the Search field 
3. Press "Enter" 

ER: The search results are displayed. 
AR: Nothing happens

**Comment by kkellydesign** [comment]
This now uses the standard /search URL, which is the same as the production site. 
<img width="999" alt="Screen Shot 2020-03-13 at 2 32 07 PM" src="https://user-images.githubusercontent.com/202590/76649674-8bb93980-6537-11ea-997e-f4a5beaa0118.png">

**Comment by ovidiuboca1** [comment]
I tested this on desktop (Mac OS X 10.14) and mobile (iPhone 8 plus) and I can confirm the fix.
