### ISSUE TITLE
The "en-US" tag overlaps the text

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#234]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/kb/revisions?locale=en-US
2. See the "en-US" tag

ER: The tag is displayed correctly.
AR: The tag overlaps the text.

**Comment by kkellydesign** [comment]
@ovidiuboca1 I'm having trouble reproducing this one. Can you give me a screenshot? I'm seeing this same behavior in Chrome and Firefox: 

<img width="559" alt="Screen Shot 2020-03-13 at 2 15 11 PM" src="https://user-images.githubusercontent.com/202590/76648471-22382b80-6535-11ea-9ad4-3ea9bb2ac285.png">

**Comment by ovidiuboca1** [comment]
I retested it on desktop and mobile and I can reproduce it. We can consider this done.
