### ISSUE TITLE
The Titles from "English Knowledge Base Discussions" section from staging environment are not the same with the ones from test site

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#235]
STR: 

1. Go to https://support-dev.allizom.org/en-US/kb/all/discussions
2. Go to  https://test.sumo.mozit.cloud/en-US/kb/all/discussions
3. Compare the Titles that are displayed 

NOTE: I'm logged with different accounts on the 2 sites. On the test, I'm using the SUMO account and on the staging, I'm logged in with the FXA
@akatsoulas do you think this is the reason? 

ER: The content of the Title section is the same on both sites.
AR: The content of the Title section is different.

**Comment by kkellydesign** [comment]
They're different databases, and neither one of them line up with production I think this is safe to close.

**Comment by ovidiuboca1** [comment]
Thanks Kasey, I will close this down.
