### ISSUE TITLE
Advanced search page broken UI

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#238]
https://test.sumo.mozit.cloud/en-US/search/advanced
Strange box happening around the content here.
![Screen Shot 2020-03-12 at 4 40 08 PM](https://user-images.githubusercontent.com/54991698/76565040-27876e80-6480-11ea-94c4-4f7828dc0223.png)

**Comment by kkellydesign** [comment]
Fixed: <img width="991" alt="Screen Shot 2020-03-12 at 5 07 08 PM" src="https://user-images.githubusercontent.com/202590/76566843-00cb3700-6484-11ea-827e-3698db895e4a.png">

**Comment by ovidiuboca1** [comment]
I tested this on desktop (Wid 10 and Mac OS X 10.14) and mobile device and I can confirm the fix.
