### ISSUE TITLE
Wrong links in Contributor Tools nav

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#239]
STR
Go to Nav Bar - Contributor Tools

**Community Discussions** links to /community, it should link to **/forums/contributors**
**L10n Discussions** links to /kb/dashboard/metrics/aggregated, it should link to **/forums/l10n-forum**

**Comment by madasan** [comment]
@jonichan can you confirm these are the right links?

**Comment by LeoMcA** [comment]
If those are the right links, this PR should implement them: https://github.com/mozilla/kitsune/pull/4235
