### ISSUE TITLE
Aggregated metrics broken UI?

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#240]
This looks strange
https://test.sumo.mozit.cloud/en-US/kb/dashboard/metrics/aggregated

**Comment by kkellydesign** [comment]
I fixed the sidebar here: 
<img width="326" alt="Screen Shot 2020-03-12 at 5 21 28 PM" src="https://user-images.githubusercontent.com/202590/76567871-0de92580-6486-11ea-98f4-571c3e549816.png">

As far as the content never loading, I'm getting the same result on prod: https://support.mozilla.org/en-US/kb/dashboard/metrics/aggregated?category=&product=firefox

**Comment by ovidiuboca1** [comment]
I've tested this on desktop(win 10 and Mac OS X 10.14) and mobile device () and the behaviour is similar to the one from production.
