### ISSUE TITLE
[KB] The Locals page displayed incorrectly 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#241]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/kb/locales/en-US/

ER: The page is displayed correctly.
AR: The page content is displayed incorrectly, the text font is too big, the users' icons are too big. 
NOTE: This is happening on all locales pages.

**Comment by kkellydesign** [comment]
This page is fixed and will go up with this PR: 
https://github.com/mozilla/kitsune/pull/4228

<img width="827" alt="Screen Shot 2020-03-13 at 12 22 23 PM" src="https://user-images.githubusercontent.com/202590/76639934-71766000-6525-11ea-9492-0cb4bb6a50af.png">
<img width="737" alt="Screen Shot 2020-03-13 at 12 22 19 PM" src="https://user-images.githubusercontent.com/202590/76639937-71766000-6525-11ea-99b4-21416f752a57.png">

**Comment by ovidiuboca1** [comment]
@akatsoulas The page is not loaded.

**Comment by kkellydesign** [comment]
I'm not seeing this here: https://test.sumo.mozit.cloud/en-US/kb/locales/en-US/
<img width="1331" alt="Screen Shot 2020-03-16 at 3 59 20 PM" src="https://user-images.githubusercontent.com/202590/76795258-25365480-679f-11ea-8367-f0088a03934e.png">

**Comment by ovidiuboca1** [comment]
I tested this and I can confirm that on desktop (Mac OS X 10.14) this is fixed. 
On mobile, I filed another ticket because the search for users functionality is not working https://github.com/mozilla/sumo-project/issues/250
