### ISSUE TITLE
The Locale Metrics page is not loaded all the time and the table form "Active Contributors" is not displayed for some products

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#242]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/kb/dashboard/metrics/en-US
2. From the [en-US] Locale Metrics drop-down choose a product (ex. Firefox for iOS)

ER: The page is loading, the text size is matching the rest of the page and under the Active Contributors you see a table. 
AR: Sometimes the page is not loaded, only after a refresh, the text size is too big and the table under the Active Contributors is not displayed. 
I saw the same issue if "Firefox for Android" was selected.

**Comment by kkellydesign** [comment]
Please try this again – it seems to be fixed with the current release here. If you're still having trouble with it, please provide a screenshot and which browser you're using. https://test.sumo.mozit.cloud/en-US/kb/dashboard/metrics/en-US

**Comment by ovidiuboca1** [comment]
@kkellydesign The UI looks good.
@akatsoulas If I select another product from the drop-down the page is not loaded.

**Comment by kkellydesign** [comment]
This is a server timeout issue. Hit refresh a couple of times.. otherwise, we might need to wait to test this again on staging/production.
