### ISSUE TITLE
The data from Recent Revisions test page are not the same with the ones from staging env.

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#244]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/kb/revisions?locale=ro&users=&start=&end=
2. Go to https://support-dev.allizom.org/en-US/kb/revisions?locale=ro&users=&start=&end=
3. Compare the data from the tables

ER: The data should be the same
AR: The data is different.

**Comment by akatsoulas** [comment]
The two environments are using different databases.
