### ISSUE TITLE
[Media Gallery] The functionality of the "Cancel" button from the Upload a new media file is not working 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#245]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/gallery/images
2. Click on "Upload a New Media File" button
3. On the modal window, please see that there is the "Progress" section - this is not on staging
4. Click on "Browse..." and add an image
5. Click on "Cancel" from the "Progress" section

ER: The text from the "Progress" section indicates that the action was canceled.
AR: The text from the "Progress" section indicates that the image is uploading.

**Comment by kkellydesign** [comment]
This had some hide/show functionality that was broken, so the dialog was confusing. This is fixed in https://github.com/mozilla/kitsune/pull/4228.

**Comment by ovidiuboca1** [comment]
@kkellydesign 
I can confirm that the "Progress" section is deleted but it's displayed on the next page where you need to add the title and the other details, see the video - https://streamable.com/qlyrs

**Comment by kkellydesign** [comment]
Here's what it does for me on localhost: 
https://www.dropbox.com/s/8a0ewzp2j57v1sc/upload-recording.mov?dl=0

So it ends up working, but only after throwing an error, and the "preview" function never actually works. 

Notice all of the "SecurityError: Permission denied to access property "document" on cross-origin object" errors. I'm not sure how to get around that, and I'm not sure if it's related. I think this will be easier to debug once we push to production, as I'm seeing the same permission issues on the test server here: https://test.sumo.mozit.cloud/en-US/gallery/images

that "cancel" button works for me on the test server – you have to click on it quickly, but then it gives you the input field again.

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and I can confirm the fix.
