### ISSUE TITLE
[Media Gallery] The UI from the uploaded image is broken 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#246]
Prerequisites: You need to upload an image

Look at the:
1. Title of the image, description, and articles 
2. The position of the "Upload a New Media File" button 
3. The details about the user
4. The "Delete this image" button

**Comment by akatsoulas** [comment]
@ovidiuboca1 can you maybe add a screenshot here?

**Comment by ovidiuboca1** [comment]
@akatsoulas here is a screen recording https://streamable.com/03nag

**Comment by akatsoulas** [comment]
@kkellydesign could you maybe take a look at this?

**Comment by kkellydesign** [comment]
This is fixed. 
<img width="922" alt="Screen Shot 2020-03-13 at 4 34 09 PM" src="https://user-images.githubusercontent.com/202590/76657604-992aef80-6548-11ea-8c8f-eaeccdf81a68.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop and I don't see the "Document Contributors" section, the rest is in place. @kkellydesign

**Comment by kkellydesign** [comment]
it took me a minute to figure out what was going on here... but that's a screenshot that I uploaded when testing the UI. See image number two in the list view here: 

<img width="1406" alt="Screen Shot 2020-03-16 at 3 15 47 PM" src="https://user-images.githubusercontent.com/202590/76792282-15b40d00-6799-11ea-9fa0-2c6d8d3bcc34.png">

So this is good to close. Sorry for the confusion!
