### ISSUE TITLE
The calendar is not displayed correctly

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#248]
STR:
First scenario:

1. Go to https://test.sumo.mozit.cloud/en-US/kb/new
2. Click on the "Expiry date"

Second scenario:

1. GO TO https://test.sumo.mozit.cloud/en-US/kb/how-save-web-page/edit
2. Click on the "Expiry date"

ER: The calendar is displayed correctly
AR: The calendar is cut off 
First scenario: 
<img width="392" alt="Screenshot 2020-03-16 at 16 06 48" src="https://user-images.githubusercontent.com/54845678/76766056-100df580-67a0-11ea-9c3a-5303ad10c233.png">

Second Scenario actual result: 
<img width="394" alt="Screenshot 2020-03-16 at 16 33 40" src="https://user-images.githubusercontent.com/54845678/76768394-9c6de780-67a3-11ea-978f-500dd8f9ee8e.png">

NOTE: Is reproducible on all browsers.

**Comment by kkellydesign** [comment]
This is fixed: https://github.com/mozilla/kitsune/pull/4232
<img width="372" alt="Screen Shot 2020-03-16 at 3 05 22 PM" src="https://user-images.githubusercontent.com/202590/76791587-9a059080-6797-11ea-8e73-df1391b0df1d.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and mobile device (iPhone 8 plus) and I can confirm the fix.
