### ISSUE TITLE
[Mobile]The "Search for a user" in not working on the kb/locales/en-US/ page

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#250]
Prerequisites:
Use a mobile device

STR:
1. Go to https://test.sumo.mozit.cloud/en-US/kb/locales/en-US/
2. Click on the "Locale Editors" search field and write "a"

ER: The search results are displayed.
AR: The search doesn't work.

**Comment by LeoMcA** [comment]
This works for me across mobile and desktop, I just have to wait a reasonably long time for the search results to appear.

**Comment by kkellydesign** [comment]
I'm seeing this hang on "searching" as well, but I'm not seeing any JS errors. I'm willing to blame this on a slow server as well – lets put this in the category to revisit on production. It's working reasonably well on desktop.

**Comment by ovidiuboca1** [comment]
I verified this and now the search is working much faster.
