### ISSUE TITLE
Add link modal too wide for mobile

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#253]
@ovidiuboca1 briefly mentioned this [here](https://github.com/mozilla/sumo-project/issues/159#issuecomment-598695260):
> but on mobile(tested on iPhone 8 plus) if I want to add a link the modal window is too large

This is quite an annoyance on mobile, requiring some side scrolling:

![Screen Shot 2020-03-17 at 16 29 37](https://user-images.githubusercontent.com/755354/76878293-87a95680-686c-11ea-9695-b7769caf4417.png)

**Comment by ovidiuboca1** [comment]
Tested on iPhone 8 plus and I can confirm the fix.
