### ISSUE TITLE
My questions page / UI regression?

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#254]
Go to profile > view profile > my questions
https://test.sumo.mozit.cloud/en-US/search/advanced?a=1&asked_by=iam_test&w=2
This seems like a regression in the UI since last time I have visited this page>?
@kkellydesign can you confirm?
![Screen Shot 2020-03-17 at 8 32 13 PM](https://user-images.githubusercontent.com/54991698/76913857-a28cc280-688e-11ea-967d-ca863d5aca73.png)

**Comment by kkellydesign** [comment]
This will be in https://github.com/mozilla/kitsune/pull/4246

<img width="968" alt="Screen Shot 2020-03-20 at 5 32 09 PM" src="https://user-images.githubusercontent.com/202590/77207862-d5be9400-6ad0-11ea-81e2-d781a9313c7d.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and mobile (iPhone 8 plus) and I can confirm the fix.
