### ISSUE TITLE
Posts don't render lists

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#255]
The editor offers options for unordered and ordered lists, and generates the appropriate html syntax, but these aren't rendered correctly:

![Screenshot from 2020-03-18 09-43-36](https://user-images.githubusercontent.com/755354/76947072-fd5d0300-68fc-11ea-8be4-def22eb94af5.png)

**Comment by ovidiuboca1** [comment]
I verified this on desktop and mobile and I can confirm the fix.
