### ISSUE TITLE
Read message compose box lacks styling

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#256]
Buttons lack styling, and there's a weirdly rendered item in the compose toolbar:

![Screenshot from 2020-03-18 11-07-00](https://user-images.githubusercontent.com/755354/76954704-b37a1a00-6908-11ea-918d-2948201df948.png)

**Comment by kkellydesign** [comment]
@LeoMcA Can you give me a URL for this?

**Comment by LeoMcA** [comment]
Fix ready: https://github.com/LeoMcA/kitsune/commit/9e3df1553b5d39698d1c4229459f7b4044c62aef, waiting for responsive-redesign to be merged into master before submitting a PR

**Comment by LeoMcA** [comment]
@kkellydesign it's on `/messages/read/<id>`, here's how my aforementioned commit styles it:

![Screenshot from 2020-03-18 14-35-27](https://user-images.githubusercontent.com/755354/76971932-cfd87f80-6925-11ea-9e79-5be0830f531e.png)

**Comment by ovidiuboca1** [comment]
@LeoMcA please past the URL that you are using for this.

**Comment by ovidiuboca1** [comment]
I verified this on desktop and mobile and I can confirm the fix.
