### ISSUE TITLE
Run svgo on svg assets in asset pipeline

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#257]

**Comment by mirunacurtean** [comment]
@LeoMcA  Anything in particular that I should verify is still working as expected after this change?

**Comment by LeoMcA** [comment]
It doesn't look like this is actually working, the hashed assets we're loading on stage haven't been run through svgo.

E.g. `view-source:https://static-media-stage-cdn.itsre-sumo.mozilla.net/static/protocol/img/icons/search.2741ad09efe8.svg` is different to `view-source:https://static-media-stage-cdn.itsre-sumo.mozilla.net/static/protocol/img/icons/search.svg`, so I'll need to fix this.

**Comment by LeoMcA** [comment]
My mistake, it *does* work, but because it runs after the collectstatic step in our asset pipeline, the hash appended to the filename doesn't change, so the non-svgo svg was being cached.

Now the cache has cleared (for me at least) you can see the two urls in my previous comment are identical.

@mirunacurtean if you can verify that no icons look very obviously wrong/different to prod, then we should be good to stick this in ready to deploy.

**Comment by mirunacurtean** [comment]
Looks good to me on both Desktop (Windows pro 10 64-bit) and mobile (Android 8.0.0)
I've compared the icons from the Get Help section and AAQ flow + articles and question threads, Contributor tools (all links), profile icons along with product, topic and article icons and they appear to be no different on stage from production.
![image](https://user-images.githubusercontent.com/53306802/83012601-4bd8fd00-a024-11ea-8115-52ee5a9d3324.png)
