### ISSUE TITLE
AAQ step 2 backend tasks

### ISSUE THREAD

**Issue by kkellydesign** [mozilla/sumo-project#259]
My first round of work is here: https://github.com/mozilla/kitsune/pull/4244

In general: This user flow heavily uses jinja macros and conditionals that I'm having a hard time wrapping my head around, so it's causing some problems. So far, here's the list of BE tasks that I've compiled. 

Step 1: http://localhost:3000/en-US/questions/new
All good! Nothing to do here. 

Step 2: http://localhost:3000/en-US/questions/new/desktop
- [ ] The product logo needs added. My attempts at trying to guess the correct template tag there have failed. 
- [ ] The "Ask a question" button in the masthead needs to go straight to the form, which currently has several additional steps between. Those steps need removed. 
- [ ] "Featured Articles" needs hooked up to the backend.
- [ ] "Popular Topics" list needs hooked up to the backend to link back out of this flow. Currently that list populates the next step in the AAQ process, and that's no longer correct.
- [ ] This page has the incorrect progress bar in the top, in a nested macro, but at the bottom all of the conditionals are working correctly. The one at the bottom is a mistake, and the one at the top is displaying the incorrect steps in the process, so I've left them both for now. The one on the bottom needs removed once the one on the top is working correctly.

**Comment by akatsoulas** [comment]
Thanks @kkellydesign for breaking this down to concrete tasks. I filed separate issues for all of the items mentioned here. @LeoMcA and I will start working on those and create any tickets we might need in order to complete this milestone.
