### ISSUE TITLE
The Product labels and descriptions are missaligned 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#26]
The Product labels and description should be displayed in the right part of the logo icon. Currently, the text is under the icon.

![imgonline-com-ua-twotoone-WSl1Cfh7L4](https://user-images.githubusercontent.com/5293100/70721940-1acb7100-1cff-11ea-845d-3032bda4ce6b.jpg)

**Comment by kkellydesign** [comment]
This is in: 

Tablet (with centered headlines and stacked cards):
<img width="766" alt="Screen Shot 2020-01-17 at 6 27 22 PM" src="https://user-images.githubusercontent.com/202590/72652996-10804080-3957-11ea-952f-066523583d5f.png">

Desktop (left-aligned text and image beside text)
<img width="990" alt="Screen Shot 2020-01-17 at 6 27 29 PM" src="https://user-images.githubusercontent.com/202590/72653010-1e35c600-3957-11ea-96c5-8f030fc677ce.png">

This fix is in this PR: https://github.com/mozilla/kitsune/pull/4130

**Comment by ovidiuboca1** [comment]
This is verified and fixed on the staging site https://test.sumo.mozit.cloud/en-US/
