### ISSUE TITLE
Add a pre-commit hook to run python black formatter.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#260]

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4408

**Comment by akatsoulas** [comment]
Moving this to blocked column until we have everything needed for the python3 upgrade merged.

**Comment by LeoMcA** [comment]
Read only hooks added in https://github.com/mozilla/kitsune/commit/35c578109b3a5f24af7d020cdada24b87efc4cb0 to ensure flake8 and others runs.

As discussed, we'll apply `reorder_python_imports` and `black` app by app so we can audit properly, putting this in blocked until then.

**Comment by akatsoulas** [comment]
This is done
