### ISSUE TITLE
[Staging] User icon is too large on the "Top Contributors" page 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#261]
STR:

1. Go to https://support.allizom.org/en-US/community/top-contributors/kb
2. Observe the user icon.

ER: The user icon is displayed correctly.
AR: Some icons are too large.

**Comment by LeoMcA** [comment]
This looks to have completely lost its styling, @jess-cook03 I don't imagine we have designs for this page?

I can attempt to make it look like a responsive version of [what currently exists in prod](https://support.mozilla.org/en-US/community/top-contributors/kb) without designs, if wanted.

**Comment by kkellydesign** [comment]
This layout is in here: https://github.com/mozilla/kitsune/pull/4246

<img width="968" alt="Screen Shot 2020-03-19 at 3 24 07 PM" src="https://user-images.githubusercontent.com/202590/77107236-c2d79100-69f6-11ea-8154-02c75f0a46d2.png">

**Comment by ovidiuboca1** [comment]
I tested on desktop and mobile and I can confirm the fix.
