### ISSUE TITLE
[Staging]The user can’t uncheck the items from the Manage Watch list

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#262]
Prerequisites: 
You need to be logged in.

STR:

1. Go to https://test.sumo.mozit.cloud/en-US/users/watches
2. Uncheck the boxes

ER: The action can be performed.
AR: The user can't uncheck the boxes. 
Note: This issue is also repro on test env.

**Comment by kkellydesign** [comment]
<img width="450" alt="Screen Shot 2020-03-19 at 11 40 15 AM" src="https://user-images.githubusercontent.com/202590/77085245-71b7a500-69d6-11ea-8b35-da65d097546d.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop and mobile and I can confirm the fix.
