### ISSUE TITLE
[Staging][Mobile][Search] The search can't be performed on mobile devices

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#263]
Prerequisites:
Use a mobile device.

STR:
1. Go to https://support.allizom.org/en-US/
2. Scroll the page until the sticky bar is displayed
3. Click on the magnifying glass and try to perform a search

ER: The search field is focused and the user can perform a search
AR: The search field is unfocused and the user can perform the search. See the screen recording https://streamable.com/in3f3
NOTE: The issue is intermittent. I tested this on the IOS device.

**Comment by ovidiuboca1** [comment]
@kkellydesign I thing we talked about this in a previous issue but I'm not sure that's why I filed this.

**Comment by kkellydesign** [comment]
@ovidiuboca1 I think you posted the wrong screen recording. Can you try again for me? I'm having trouble recreating the issue, this seems to be working for me.

**Comment by ovidiuboca1** [comment]
@kkellydesign I update this, here is another screen recording - https://streamable.com/in3f3
Also please note that the issue is intermittent.

**Comment by kkellydesign** [comment]
This should be much more stable now – the dropdown has been removed, and the regular search field is focused. This will go in with https://github.com/mozilla/kitsune/pull/4246

<img width="540" alt="Screen Shot 2020-03-20 at 3 00 48 PM" src="https://user-images.githubusercontent.com/202590/77197602-ddc00900-6abb-11ea-9a27-5395eb02e5dd.png">

**Comment by ovidiuboca1** [comment]
I verified it on a mobile device (iPhone 8 plus) and I can confirm the fix. 
The only thing that I want to mention is that the "Search" button from the keyboard doesn't do any action, I also mentioned this in another issue.

**Comment by kkellydesign** [comment]
fixed in https://github.com/mozilla/kitsune/pull/4261

I just added a line in the JS that says "if you try to submit the search form when the form is empty, focus the field."

**Comment by ovidiuboca1** [comment]
I retested this on mobile and if I click on the search key from the mobile keyboard the text from the search bar is deleted. See the screen recording https://streamable.com/rdvi9
@kkellydesign, @madasan @jess-cook03  Please take a look at this and let me know your thoughts, personally I don't think this behavior is the expected one.

**Comment by kkellydesign** [comment]
This is fixed in https://github.com/mozilla/kitsune/pull/4274

**Comment by ovidiuboca1** [comment]
Tested on desktop, Mac OS X 10.14 and Windows 10 and mobile device iPhone 8 plus and I can confirm the fix.
