### ISSUE TITLE
[Staging] The drop-down from "Customize this article" doesn't have the latest FF version displayed

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#265]
STR:

1. Go to https://support.allizom.org/en-US/kb/fxa-managing-devices
2. From the dropdown select the latest FF version

ER: The option is available.
AR: The option is not available.
<img width="418" alt="Screenshot 2020-03-19 at 15 12 56" src="https://user-images.githubusercontent.com/54845678/77071268-65dadb80-69f4-11ea-96a3-b0af20e1d1e6.png">
NOTE: On production you have available version 73.

**Comment by kkellydesign** [comment]
This is a database issue that will be fixed when the production database is used.
