### ISSUE TITLE
[Staging] Explore Help Articles link is not redirected to the proper page 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#266]
STR:

1. Go to https://support.allizom.org/en-US/
2. Scroll to the bottom of the page and click on the "Explore Help Articles"

ER: The link is redirected to https://support.allizom.org/en-US/products
AR: The home page is open.

**Comment by kkellydesign** [comment]
fixed in https://github.com/mozilla/kitsune/pull/4246

**Comment by akatsoulas** [comment]
I would argue that `home` is the link that should be opened. Home page allows the user to select products similar to `/products` but also has the featured articles that we are missing from the later. I am closing this PR and removing the commit from the pending PR. @kkellydesign thanks for taking the time to fix this.

**Comment by LeoMcA** [comment]
FWIW under the "Get Help" menu, "Explore our Help Articles" and "See all help articles" both point to https://support.allizom.org/en-US/products
