### ISSUE TITLE
[Staging] The UI of the "Top Contributors - Support Forum" page is different from the production page

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#267]
STR:

1. Go to https://support.allizom.org/en-US/community/top-contributors/questions
2. Compare it with https://support.mozilla.org/en-US/community/top-contributors/questions

ER: The page is populated with the information related to contributors.
AR: The page doesn't have any info about the contributors.
This is related to the different DB's? 

Note: This page didn't load on the test env.

**Comment by kkellydesign** [comment]
This layout is in here: https://github.com/mozilla/kitsune/pull/4246

<img width="968" alt="Screen Shot 2020-03-19 at 3 24 07 PM" src="https://user-images.githubusercontent.com/202590/77107349-ef8ba880-69f6-11ea-9630-7736241772a3.png">

**Comment by ovidiuboca1** [comment]
@kkellydesign I don't see the "Days since last activity:" on Leo's profile. 
Also on your profile, it says "Days since last activity: 53" but I saw that you answered a question 17 hours ago, so I'm not sure what time is counted in the "Days since last activity" @akatsoulas do you have any idea?

**Comment by ovidiuboca1** [comment]
I tested this on desktop and mobile and I can confirm the fix. I also see the info about the "Days since last activity:" on Leo's profile.
