### ISSUE TITLE
[Staging] There are 2 search fields displayed

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#268]
STR:
Scenario 1

1. Go to https://support.allizom.org/en-US/products
2. Type something in the search field 

ER: The search is performed and there is only one search field. 
AR: After you start to type there are 2 search fields displayed. Screen recording https://streamable.com/fgipd

Scenario 2

1. Go to https://support.allizom.org/en-US/products
2. Scroll the page until the sticky bar is displayed 
3. Perform a search from the search field that is in the sticky bar. 

ER: The search is performed and there is only one search field. 
AR: After you start to type there are 2 search fields displayed. Screen recording https://streamable.com/45935

**Comment by kkellydesign** [comment]
This is fixed in https://github.com/mozilla/kitsune/pull/4246

<img width="961" alt="Screen Shot 2020-03-20 at 12 44 48 PM" src="https://user-images.githubusercontent.com/202590/77185977-9c722e00-6aa8-11ea-8f55-ee388bc20d7f.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) with FF and Chrome browsers and I can confirm the fix.
