### ISSUE TITLE
[Staging] The search results from /community page are displayed differently compared with the support page. 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#269]
STR:

1. Go to https://support.allizom.org/en-US/community/
2. Perform a search after a contributor (for ex. "test")
3. Compare the UI page with the https://support.mozilla.org/en-US/community/search?q=test

ER:  The search results are displayed similar to the results from the support page.
AR: The search results are displayed differently compared with the support page.

**Comment by LeoMcA** [comment]
@kkellydesign I'll style this to match your styling of the top contributors page in https://github.com/mozilla/kitsune/pull/4246

**Comment by LeoMcA** [comment]
@kkellydesign I've opened a PR against your branch: https://github.com/lincolnloop/kitsune/pull/5

Feel free to merge it there, or I can wait until your branch is merged and rebase against master.

**Comment by kkellydesign** [comment]
I just made a minor edit here, so this should be good in https://github.com/mozilla/kitsune/pull/4254

<img width="1029" alt="Screen Shot 2020-03-23 at 11 18 02 AM" src="https://user-images.githubusercontent.com/202590/77332153-0cc2be80-6cf8-11ea-8a31-b677c443827b.png">

**Comment by ovidiuboca1** [comment]
@kkellydesign 

I verified this on desktop (Mac 10.14) with Firefox and there is a different behavior comparing with Chrome. 
Here is the print screen from FF: 
<img width="918" alt="Screenshot 2020-03-24 at 08 01 46" src="https://user-images.githubusercontent.com/54845678/77393398-a1cfc100-6da5-11ea-8895-ce324806d2f6.png">

**Comment by kkellydesign** [comment]
Those are image 404s. If those images appear on production, they'll appear when this code is merged there.

**Comment by ovidiuboca1** [comment]
> Those are image 404s. If those images appear on production, they'll appear when this code is merged there.

Thanks for the updates, I will consider this as resolved.
