### ISSUE TITLE
Responsive Redesign // Search Pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#27]

**Comment by jess-cook03** [comment]
Updating Zeplin link by end of day here: https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5e1895eda13eea0232692323

- Main search typeahead: **done**
- search results page (landing page for when you use smaller search bar across site): **done**
- empty state / no results for both ^ : WIP
- tablet & mobile breakpoints for each : WIP

**Comment by jess-cook03** [comment]
@kkellydesign all search designs updated in [zeplin](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5e1895eda13eea0232692323) **done**

**Comment by kkellydesign** [comment]
This is in! I piggybacked this work on the PR that is still pending here: https://github.com/mozilla/kitsune/pull/4115

<img width="1373" alt="Screen Shot 2020-01-15 at 3 56 30 PM" src="https://user-images.githubusercontent.com/202590/72471137-0bcd5800-37b0-11ea-95e4-7cabe198b9cc.png">
<img width="1380" alt="Screen Shot 2020-01-15 at 3 56 44 PM" src="https://user-images.githubusercontent.com/202590/72471138-0bcd5800-37b0-11ea-90a6-a119950fae7e.png">
<img width="410" alt="Screen Shot 2020-01-15 at 3 57 01 PM" src="https://user-images.githubusercontent.com/202590/72471139-0bcd5800-37b0-11ea-81ea-ec97d5c2d987.png">

**Comment by jess-cook03** [comment]
@kkellydesign minor updates here: 
- 'search mozilla support' should just be search support.
- 'show everything' should be view all
- hint text / supportive text under the search bar that gives results -- the type style here feels off. I think we change it to inter regular weight or use metropolis at 24px like in the mockups. 
On this same note / the mobile type scale is feeling a little unbalanced -- I need to relook at this system wide, should I check within the styleguide?

**Comment by ovidiuboca1** [comment]
Tested on staging site and the 'search mozilla support' and 'show everything' issues are still there.

**Comment by ovidiuboca1** [comment]
We did some testing around search functionality and we found several issues: https://github.com/mozilla/sumo-project/issues/128
https://github.com/mozilla/sumo-project/issues/129
https://github.com/mozilla/sumo-project/issues/130
https://github.com/mozilla/sumo-project/issues/131
https://github.com/mozilla/sumo-project/issues/132
https://github.com/mozilla/sumo-project/issues/133
https://github.com/mozilla/sumo-project/issues/134

**Comment by kkellydesign** [comment]
Typography adjustments are in ^^

<img width="812" alt="Screen Shot 2020-01-27 at 11 24 41 AM" src="https://user-images.githubusercontent.com/202590/73192907-c8e87a00-40f7-11ea-8eed-b16d929add57.png">
<img width="408" alt="Screen Shot 2020-01-27 at 11 24 50 AM" src="https://user-images.githubusercontent.com/202590/73192908-c8e87a00-40f7-11ea-8a7c-3d82f74525e3.png">

**Comment by kkellydesign** [comment]
This is ready for design review again, so I'm going to add the tag back to this. But @ovidiuboca1 raised some valid tickets/concerns about some UI issues with the frontend search. @madasan, Lets discuss this ticket in our next standup.

**Comment by ovidiuboca1** [comment]
I want to do a follow up on this ticket, it was discussed (I don't remember)?

**Comment by kkellydesign** [comment]
@ovidiuboca1 All of the design revisions from this ticket are in, so I think this one is safe to close. From our previous discussion, we decided that as long as these issues are also present in the production environment, we're going to table this work until the search upgrade project, where the instant-search is replaced by a more traditional search page. All of the tickets in the with the `search upgrade` tag fall into that category.

**Comment by jess-cook03** [comment]
@kkellydesign @ovidiuboca1 confirming that the design edits have been made search looks good from design UI perspective -- we can probably close this ticket.

**Comment by jess-cook03** [comment]
@kkellydesign @ovidiuboca1 actually one last design tweak here with the type:
![Screen Shot 2020-02-24 at 1 05 34 PM](https://user-images.githubusercontent.com/54991698/75178635-71ddc100-5706-11ea-8b41-35a3928d3d83.png)
Right now the search items have a heading that is 20px and Metropolis -- should be Body LG 18px Inter Bold

**Comment by kkellydesign** [comment]
This is finished and will go up in https://github.com/mozilla/kitsune/pull/4193

**Comment by ovidiuboca1** [comment]
@jess-cook03 do you think we can close this and move it to done?

**Comment by jess-cook03** [comment]
@ovidiuboca1 yes confirmed this is fixed
