### ISSUE TITLE
The title font size from the kb article is too big

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#271]
STR:

1. Go to https://support.allizom.org/ro/kb/recovering-important-data-from-an-old-profile/translate

Also, the same issue can be found here: https://support.allizom.org/ro/kb/test-test-test/edit. 
@kkellydesign for the button that overlaps the text should I file a new issue? 

ER: The title has a normal size, similar to the one from prod.  https://support.mozilla.org/ro/kb/recovering-important-data-from-an-old-profile/translate
AR: The title font size is too big.

**Comment by kkellydesign** [comment]
This is updated in https://github.com/mozilla/kitsune/pull/4246

<img width="1328" alt="Screen Shot 2020-03-20 at 12 01 57 PM" src="https://user-images.githubusercontent.com/202590/77182110-a09b4d00-6aa2-11ea-979f-512591d5d4c7.png">

**Comment by ovidiuboca1** [comment]
@kkellydesign @jess-cook03  please look at the print-screen 
<img width="759" alt="Screenshot 2020-03-24 at 09 45 38" src="https://user-images.githubusercontent.com/54845678/77400604-20335f80-6db4-11ea-9007-694c0f1118ff.png">
In my opinion there are sections on the page that are very crouded.

**Comment by jess-cook03** [comment]
@ovidiuboca1 This does look different than the image Kasey posted above, I would agree the button + headlines are a bit cramped together.
@akatsoulas @kkellydesign I'll let you both decide the level of priority of this edit/change.

**Comment by kkellydesign** [comment]
fixed in https://github.com/mozilla/kitsune/pull/4261

<img width="961" alt="Screen Shot 2020-03-24 at 1 32 36 PM" src="https://user-images.githubusercontent.com/202590/77458131-0dc91e00-6dd4-11ea-8972-bc4768b29ce4.png">

**Comment by ovidiuboca1** [comment]
@kkellydesign In the print screen that I've attached, you can see a blue button, on the current behaviour I can't see it, using the same link that is in the description.
