### ISSUE TITLE
Related dropdown on question page doesn't reflect contents

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#272]
Calling the collapsed sidebar "Related" is quite confusing, as it contains much more than just the related articles, but this isn't obvious unless you open it:

![Screen Shot 2020-03-20 at 09 57 42](https://user-images.githubusercontent.com/755354/77153182-404fdf80-6a91-11ea-9237-446001d481ea.png)

This has confused contributors: https://bugzilla.mozilla.org/show_bug.cgi?id=1623788

Could we call this something else, like "More Details"? "More Information"?

**Comment by kkellydesign** [comment]
The way that works is as follows: 
* If there's a `is-current` link on a given sidebar nav item, that's the label for the dropdown on mobile. [example](https://support.allizom.org/en-US/kb/test-pilot-firefoxs-experimental-features)
* If not, it uses the text for the first heading in the list (what's happening in your link)

If there are particular templates that shouldn't behave like that, we can maybe put another conditional in the JS that pulls text from another hidden element. Alternatively, I think an argument could me made to remove 'related' or at least move it to the bottom of this list. That might make more sense on desktop anyway. Then, 'question tools' would be the top, and that makes more sense. @jess-cook03 do you have any thoughts on this?

**Comment by jess-cook03** [comment]
@kkellydesign @LeoMcA Looking at this now ....
I agree this is funky.
I think we could do as Kasey mentioned above: 
> 'question tools' would be the top, and that makes more sense.
Put question tools at the top of that side bar stack..... and then in general I think we need to rename that 'related' to '**related articles'**

**Comment by kkellydesign** [comment]
✅ 
<img width="430" alt="Screen Shot 2020-03-20 at 5 09 32 PM" src="https://user-images.githubusercontent.com/202590/77206616-bc681880-6acd-11ea-9c4a-a6ceefe6d033.png">

**Comment by ovidiuboca1** [comment]
I verified this on mobile (iPhone 8 plus) and I can confirm the fix.
