### ISSUE TITLE
[Staging] The UI from /badges page is broken 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#275]
STR:

1. Go to https://support.allizom.org/en-US/badges/
2. Compare it with https://support.mozilla.org/en-US/badges/

ER: The page UI is displayed correctly. 
AR: The page UI is borken. 
Note: Tested also on mobile and it's reproducible.

**Comment by ovidiuboca1** [comment]
duplicate on bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1623776

**Comment by kkellydesign** [comment]
This will go up with https://github.com/mozilla/kitsune/pull/4246

<img width="1141" alt="Screen Shot 2020-03-20 at 10 41 41 AM" src="https://user-images.githubusercontent.com/202590/77175079-6af16680-6a98-11ea-9f0f-e24f6423a18c.png">

**Comment by ovidiuboca1** [comment]
When I will verify this I need to check also the badges from users pages -   ex. 
 https://support.allizom.org/en-US/user/buluma_michael

**Comment by ovidiuboca1** [comment]
@kkellydesign The first badge icon is not displayed 

<img width="1167" alt="Screenshot 2020-03-24 at 09 56 03" src="https://user-images.githubusercontent.com/54845678/77401729-1e6a9b80-6db6-11ea-8a2b-8af5573303e1.png">

The same issue on mobile and desktop.

**Comment by kkellydesign** [comment]
That's a data issue – a broken image link coming from the CDN. If all of the images are good on production, they'll be good when we push this code to production as well.

**Comment by ovidiuboca1** [comment]
Based on 

> That's a data issue – a broken image link coming from the CDN. If all of the images are good on production, they'll be good when we push this code to production as well.

Based on this info I will consider this as resolved.
