### ISSUE TITLE
[Staging] Top contributors page doesn’t have any users displayed

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#277]
STR:

1. Go to https://support.allizom.org/en-US/community/top-contributors/questions?product=firefox

ER: On the page, there are displayed the top contributors
AR: No contributor is displayed on the page.

**Comment by kkellydesign** [comment]
I just made a comment on a forum post, so you can see one at this URL: https://support.allizom.org/en-US/community/top-contributors/questions?locale=en-US&product=firefox

I'm not sure why that doesn't show up in the 'all locales' list. On my local environment, it works correctly: the 'en-US' and 'all locales' lists are identical.

**Comment by akatsoulas** [comment]
This seems to be working fine. Moving this to the QA column

**Comment by ovidiuboca1** [comment]
I verified this on desktop and mobile and I can confirm the fix.
