### ISSUE TITLE
The Common Responses are not highlighted

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#278]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/questions/1207028
2. Click on "Common Responses"
3. Hover over the "Categories"

ER: The hovered element from the category is highlighted.
AR: The hovered element from the category isn't highlighted.

**Comment by kkellydesign** [comment]
This should be fixed, but my local instance looks like this, so I'm not sure: 

<img width="838" alt="Screen Shot 2020-03-20 at 12 27 59 PM" src="https://user-images.githubusercontent.com/202590/77184578-6469eb80-6aa6-11ea-84fc-807aa0794653.png">

I faked a bit of the markup from production with devtools, so it should look like this: 

<img width="828" alt="Screen Shot 2020-03-20 at 12 28 12 PM" src="https://user-images.githubusercontent.com/202590/77184730-967b4d80-6aa6-11ea-9fcb-d1be4766be0f.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop and mobile and I can confirm the fix.

@kkellydesign I saw that on mobile the "Common Responses" button label is cut off and the actual button label is "Common".

**Comment by kkellydesign** [comment]
fixed in https://github.com/mozilla/kitsune/pull/4261
<img width="444" alt="Screen Shot 2020-03-24 at 12 25 36 PM" src="https://user-images.githubusercontent.com/202590/77451157-aeb2db80-6dca-11ea-87e3-2255a65f3327.png">

**Comment by ovidiuboca1** [comment]
I verified this and I can confirm the fix.
