### ISSUE TITLE
The "Quote" option doesn't work

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#279]
STR:

1. Go to https://support.allizom.org/en-US/forums/buddies/712902?last=73466#thread-reply
2. Click on the 3 dots icon 
3. Select "Quote"

ER: The quoted text is autofill in the reply section.
AR: Nothing happens.

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4254

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and mobile (iPhone 8 plus) and I can confirm the fix. 

@kkellydesign After I select an option from the three dots icon the drop-down is still there, I think the drop-down should be dismissed after you select an action.

**Comment by kkellydesign** [comment]
@jess-cook03 you've mentioned this one too. Is there a good way to submit this as an issue to the protocol team?

**Comment by ovidiuboca1** [comment]
I filed a new ticket for the drop-down issue. https://github.com/mozilla/sumo-project/issues/293
I will close the current ticket because the described issue is fixed.

**Comment by LeoMcA** [comment]
I'm pretty sure this was deployed to prod earlier this week.
