### ISSUE TITLE
Responsive Redesign // Contributor Pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#28]
Currently on hold, as we need to discuss as team the pages that are priority for responsive redesign.

**Comment by jess-cook03** [comment]
@kkellydesign note: reskin as many as possible...
Using the[ IA](https://miro.com/app/board/o9J_kw7SwCM=/) as a guide 

- All discussions (outlined in map) will be skinned with the forum/thread template that will be developed within the new AAQ flow. This template will be its own for forums and threads

- Advanced search will follow search template
- Dashboards  **reskin***
- Media Gallery **reskin**
- All metrics pages **reskin**
- Community hub -- needs new design
- News and Resources -- use article page template
- Support forum home -- should follow home/category page template
- Recent revisions - **reskin**
- ?Templates not sure need to check this
- ? tag admin not sure need to check this

**Comment by jess-cook03** [comment]
@madasan linking card from @akatsoulas https://github.com/mozilla/sumo-project/projects/1#card-31236992

On hold as of now as we work through the this list ^

**Comment by jess-cook03** [comment]
@kkellydesign updated ticket with links to pages here ^

**Comment by jess-cook03** [comment]
@kkellydesign @akatsoulas @madasan  **Note:** need to discuss in Wednesday standup details around certain pages and potential for things to be broken when reskinned + made responsive.

Marked for implementation for now -- per our stand up tomorrow.

**Comment by madasan** [comment]
Updated list of pages that need to be reskinned:

Knowledge base Dashboard: https://support.mozilla.org/en-US/contributors 
Community hub: https://support.mozilla.org/en-US/community
Media Gallery: https://support.mozilla.org/en-US/gallery/images
Recent Revisions: https://support.mozilla.org/en-US/kb/revisions
English Knowledge Base Discussions: https://support.mozilla.org/en-US/kb/all/discussions (reskinned as per contributor discussion forum)
News and resources: https://support.mozilla.org/en-US/kb/contributor-news-resources (reskinned using article page template)
Templates: https://support.mozilla.org/en-US/kb/category/60
Quickstart guide/Get involved page: https://support.mozilla.org/en-US/get-involved
Groups page: https://support.mozilla.org/en-US/groups
Documents page: https://support.mozilla.org/en-US/user/madasan/documents
Contributor Forums: https://support.mozilla.org/en-US/forums
Moderate forum content: https://support.mozilla.org/en-US/flagged
Support Forum metrics: https://support.mozilla.org/en-US/questions/dashboard/metrics
Localization metrics: https://support.mozilla.org/en-US/kb/dashboard/metrics/aggregated

**Comment by AliceWyman** [comment]
> 
> 
> Updated list of pages that need to be reskinned:
> 
> Knowledge base Dashboard: https://support.mozilla.org/en-US/contributors
> Community hub: https://support.mozilla.org/en-US/community
> Media Gallery: https://support.mozilla.org/en-US/gallery/images
> Recent Revisions: https://support.mozilla.org/en-US/kb/revisions
> English Knowledge Base Discussions: https://support.mozilla.org/en-US/kb/all/discussions (reskinned as per contributor discussion forum)
> News and resources: https://support.mozilla.org/en-US/kb/contributor-news-resources (reskinned using article page template)
> Templates: https://support.mozilla.org/en-US/kb/category/60
> Quickstart guide/Get involved page: https://support.mozilla.org/en-US/get-involved
> Groups page: https://support.mozilla.org/en-US/groups
> Documents page: https://support.mozilla.org/en-US/user/madasan/documents
> Contributor Forums: https://support.mozilla.org/en-US/forums
> Moderate forum content: https://support.mozilla.org/en-US/flagged
> Support Forum metrics: https://support.mozilla.org/en-US/questions/dashboard/metrics
> Localization metrics: https://support.mozilla.org/en-US/kb/dashboard/metrics/aggregated

Templates page should be https://support.mozilla.org/en-US/contributors/templates
See my post in the related discussion,
https://support.mozilla.org/en-US/forums/contributors/713879?#post-77431 Are you using any of the contributor metrics in Kitsune?
:

**Comment by kkellydesign** [comment]
These will be in this PR: 
https://github.com/mozilla/kitsune/pull/4166

contributor page: 
<img width="1339" alt="Screen Shot 2020-02-07 at 3 22 44 PM" src="https://user-images.githubusercontent.com/202590/74064305-65483180-49c0-11ea-83c1-a21a5dd76044.png">

**Comment by kkellydesign** [comment]
The following pages will be ready to test when https://github.com/mozilla/kitsune/pull/4170 hits the server. 

https://test.sumo.mozit.cloud/en-US/kb/all/discussions
<img width="1299" alt="Screen Shot 2020-02-11 at 3 06 01 PM" src="https://user-images.githubusercontent.com/202590/74274925-eebd7380-4ce0-11ea-82ab-48c5b709b433.png">

**Comment by kkellydesign** [comment]
This uses the document template, so it's set: 
https://test.sumo.mozit.cloud/en-US/kb/contributor-news-resources

**Comment by kkellydesign** [comment]
The localization metrics page is throwing database errors for me locally. I just pushed some frontend changes that may need additional work after we can see it on the test server. 

This will be in when https://github.com/mozilla/kitsune/pull/4170 goes live.

**Comment by jess-cook03** [comment]
@kkellydesign https://test.sumo.mozit.cloud/en-US/get-involved
This page should be skinned with Mozilla / Zilla Slab heading typography being a moz branded page

**Comment by jess-cook03** [comment]
@kkellydesign what is the level of effort (time/budget) to revert the typography and color styling to Mozilla brand on these pages?
If we can do them all, great. But if not we have a shot list of priority pages to be Zilla branded:
- Get involved page
- Community Hub
These are top of mind.
@jonichan feel free to comment with more if needed.

**Comment by kkellydesign** [comment]
@jess-cook03 no problem. I just took care of several of them, but let me know of specific links you want me to tackle if I've missed any. 
<img width="1241" alt="Screen Shot 2020-02-19 at 4 48 01 PM" src="https://user-images.githubusercontent.com/202590/74880774-f3fe6c00-5339-11ea-8dc7-e18a118ec8e6.png">

**Comment by jonichan** [comment]
> @kkellydesign what is the level of effort (time/budget) to revert the typography and color styling to Mozilla brand on these pages?
> If we can do them all, great. But if not we have a shot list of priority pages to be Zilla branded:
> 
>     * Get involved page
> 
>     * Community Hub
>       These are top of mind.
>       @jonichan feel free to comment with more if needed.

I commented here: https://github.com/mozilla/sumo-project/issues/63

**Comment by jess-cook03** [comment]
@kkellydesign refer to ticket #179 
Replace this component on the bottom of the page with the mozilla branded (grey one) pictured in that ticket ^

**Also -- refer to global rule noted there as well all mozilla branded type (zilla) should be BLACK not ink or grey.** 

Is this something that we can change globally? Can we have two skins / colors and type for Firefox/Mozilla?

**Comment by jess-cook03** [comment]
@kkellydesign @madasan 
Mocked up a new design for this Volunteer page https://test.sumo.mozit.cloud/en-US/get-involved .... are we able to reconfigure this or not? If not we have this for backlog.
[See spec here](https://zpl.io/2pevemE)
<img width="498" alt="Screen Shot 2020-02-21 at 3 30 56 PM" src="https://user-images.githubusercontent.com/54991698/75069438-2c7b8280-54bf-11ea-8945-eb2532390feb.png">

**Comment by kkellydesign** [comment]
All of these will go it with https://github.com/mozilla/kitsune/pull/4190

https://test.sumo.mozit.cloud/en-US/get-involved/questions
https://test.sumo.mozit.cloud/en-US/get-involved/kb
https://test.sumo.mozit.cloud/en-US/get-involved/l10n

**Comment by jess-cook03** [comment]
Confirming this is complete --- @akatsoulas @madasan could be something we want to track for the backlog or P2 ?
