### ISSUE TITLE
Some users icons are not displayed 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#282]
STR: 

1. Go to https://support.allizom.org/en-US/forums/knowledge-base-articles/712230?last=73422
2. Scroll down and observe the users icons. 

ER: All the icons are displayed. 
AR: Some icons are not displayed. 
Note: I think the problem is with users that have the default icon.

**Comment by ovidiuboca1** [comment]
Here is a print-screen 
<img width="321" alt="Screenshot 2020-03-23 at 16 26 30" src="https://user-images.githubusercontent.com/54845678/77326813-072e9e00-6d23-11ea-8727-c4f0523746d3.png">
From what I saw this is not reproducible very easy.

**Comment by kkellydesign** [comment]
Since this isn't consistent on a page refresh, I assume this is an issue with how the CDN interacts with the staging server. I think we ought to keep this open and check again on prod

**Comment by kkellydesign** [comment]
This appears to be fixed: https://support.allizom.org/en-US/forums/knowledge-base-articles/712230?last=73422

**Comment by ovidiuboca1** [comment]
I verified this on desktop, Mac OS X 10.14, Windows 10 with FF and chrome and I can confirm the fix.
Also, on mobile, the issue is fixed. 

NOTE: I search after the user that has the icon broken but I couldn't find him.
