### ISSUE TITLE
The page numbers are overlay 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#283]
STR:

1. Go to https://support.allizom.org/en-US/kb/revisions?page=1
2. Scroll to the bottom of the page 
3. Select page number 7299

ER: The page numbers are displayed correctly. 
AR: The page numbers are overlay.

<img width="497" alt="Screenshot 2020-03-23 at 09 53 20" src="https://user-images.githubusercontent.com/54845678/77293935-00386900-6cec-11ea-8179-b6dea9af4e47.png">

**Comment by kkellydesign** [comment]
fixed: https://github.com/mozilla/kitsune/pull/4254

<img width="671" alt="Screen Shot 2020-03-23 at 11 01 32 AM" src="https://user-images.githubusercontent.com/202590/77330503-d3894f00-6cf5-11ea-8bd9-b2c9288b08ec.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop Mac OS X 10.14 and I can confirm the fix. 
@kkellydesign @jess-cook03 On mobile the results are displayed differently from the prod page, here is a print screen with the actual result from the phone - 
![Skype_Picture_2020_03_24T06_12_45_503Z](https://user-images.githubusercontent.com/54845678/77393973-ec057200-6da6-11ea-8958-46392ef64af8.jpeg)
Please let me know if this is expected, thanks.

**Comment by kkellydesign** [comment]
I've cleaned this up a little to keep the dates from stacking, but all of these contributor tools could use a proper design pass in the next phase. 
<img width="414" alt="Screen Shot 2020-03-24 at 12 17 13 PM" src="https://user-images.githubusercontent.com/202590/77450423-98f0e680-6dc9-11ea-9064-352698cc4830.png">

**Comment by ovidiuboca1** [comment]
We can consider this as fixed.
I filed another issue https://github.com/mozilla/sumo-project/issues/294. This is not very important so it can be moved on the next release.
