### ISSUE TITLE
UI spacing issue // sidebar menus globally

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#285]
Noticing this cramped spacing on majority of pages where the sidebar is present, primarily forum pages and articles pages:
![Screen Shot 2020-03-23 at 9 08 32 AM](https://user-images.githubusercontent.com/54991698/77333302-9aeb7480-6cf9-11ea-95c4-d871c0a02f02.png)

**Comment by kkellydesign** [comment]
This is fixed on staging: 

https://support.allizom.org/en-US/kb/new-test-pilot-experiments
https://support.allizom.org/en-US/questions/1207023

<img width="407" alt="Screen Shot 2020-03-23 at 4 48 50 PM" src="https://user-images.githubusercontent.com/202590/77361822-5d511080-6d26-11ea-991c-0bfc0100a4a2.png">
<img width="404" alt="Screen Shot 2020-03-23 at 4 48 58 PM" src="https://user-images.githubusercontent.com/202590/77361827-5de9a700-6d26-11ea-8d80-8c65bc538c41.png">

**Comment by ovidiuboca1** [comment]
I verified this on the mobile iPhone 8 plus and I can confirm the fix. 
@jess-cook03 please take a look at this and tell me if it's ok with you to consider this as done?

**Comment by jess-cook03** [comment]
Confirmed -- moving this to deploy @ovidiuboca1
