### ISSUE TITLE
AAQ Step 3 (form) backend tasks

### ISSUE THREAD

**Issue by kkellydesign** [mozilla/sumo-project#286]
Step 3: http://localhost:3000/en-US/questions/new/desktop/download-and-install/form?search=test&step=aaq-question

Some fields need added to this form, according to [the final mockup](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e79017e860445627a3984ac/):
- [x] "Question" label needs changed to "Subject"
- [x] "Details:" should be changed to "How can we help?"
- [x] For non-required fields, add "(optional)" at the end of the label
- [x] Add "Which topic best describes your question?" select field
- [x] Add "Email me when someone answers the thread" field (and functionality)
- ~[ ] Add "Submit a Crash Report" checkbox (and functionality – another textarea?)~ https://github.com/mozilla/sumo-project/issues/405

Then: 
- [x] test whether "submit troubleshooting information" field is populated on production

**Comment by jess-cook03** [comment]
@kkellydesign @akatsoulas @LeoMcA 
Updated link to the question form/ step 3 -- [ is here](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e79017e860445627a3984ac/)
We collapsed the 'what platform..' into the section where we take some educated guesses about the system...which should look like the current staging just adding that platform field:
![Screen Shot 2020-03-23 at 2 47 11 PM](https://user-images.githubusercontent.com/54991698/77353066-aef19f00-6d16-11ea-9413-7bee26514fc0.png)

Note: need to still add the product link / change product link here, as discussed.

**Comment by kkellydesign** [comment]
ok, I've updated the mockup link and the action items in the ticket to reflect the new mockup.

**Comment by LeoMcA** [comment]
As discussed in today's design review, we'll move the "Which topic best describes your question?" field underneath the "Subject" field, and add help text if a user tries to submit without a choice being made.

**Comment by mirunacurtean** [comment]
Verified on Dev environment on Desktop across Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10. 
For the time being I am leaving this in QA as it also needs to be tested for the "Email me when someone answers the thread" functionality on mobile.
No reply has been yet received to post on android but that could be because of latency issues on dev environment as mentioned in https://github.com/mozilla/sumo-project/issues/427.

**Comment by mirunacurtean** [comment]
As discussed on slack, email notifications are only received on stage, so we'll test the "Email me when someone answers the thread"  functionality over there.

**Comment by mirunacurtean** [comment]
Email notifications does not appear to be functioning in stage either. 
Documented the issue in https://github.com/mozilla/sumo-project/issues/433
