### ISSUE TITLE
FxA Banner Typography Change

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#287]
![Screen Shot 2020-03-23 at 9 11 04 AM](https://user-images.githubusercontent.com/54991698/77350570-1ad20880-6d13-11ea-9301-288c4b4d0c04.png)
@kkellydesign @LeoMcA 
Tagging you both here, just realizing this typography within this banner should be Metropolis family not Inter... I realize its probably because this is 18px type. Which I'm thinking lets make it same size but Metropolis to match moz.org

**Comment by kkellydesign** [comment]
This is in here: 
https://github.com/mozilla/kitsune/pull/4258

<img width="847" alt="Screen Shot 2020-03-23 at 5 18 21 PM" src="https://user-images.githubusercontent.com/202590/77364139-51ffe400-6d2a-11ea-827e-f85f01d1ffe7.png">

**Comment by jess-cook03** [comment]
Yes I can confirm this style is now changed - thanks!
