### ISSUE TITLE
Responsive Redesign // Topic Selection Pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#29]

**Comment by jess-cook03** [comment]
@kkellydesign designs are up in [Zeplin](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5df92699bdb90d17d29cabdd)

**Comment by kkellydesign** [comment]
These changes will be ready for design review when this PR is deployed: https://github.com/mozilla/kitsune/pull/4150

https://test.sumo.mozit.cloud/en-US/products/firefox

<img width="1482" alt="Screen Shot 2020-01-30 at 5 05 14 PM" src="https://user-images.githubusercontent.com/202590/73494643-e67d4400-4382-11ea-93f3-bf82adfdc027.png">

**Comment by kkellydesign** [comment]
This is in, and now all icons are working: 
https://test.sumo.mozit.cloud/en-US/products/firefox

**Comment by jess-cook03** [comment]
@kkellydesign @ovidiuboca1 
Certain product pages like Firefox for example -- you click the topics and you get this error?
![Screen Shot 2020-02-24 at 1 51 20 PM](https://user-images.githubusercontent.com/54991698/75181963-6641c880-570d-11ea-9ab5-53f9a57c4b09.png)
Is this a data back end thing?

**Comment by jess-cook03** [comment]
![Screen Shot 2020-02-24 at 2 01 16 PM](https://user-images.githubusercontent.com/54991698/75185190-a6a44500-5713-11ea-8a30-ccd7fc89397f.png)
@kkellydesign

- [ ] Volunteer button should be mozilla volunteer component 

- [ ] filters here -- these should reflect any sub topics that a selected topic may have from the [mocks](https://zpl.io/VO810dX) and heres an example from the current site:
![Screen Shot 2020-02-24 at 2 42 22 PM](https://user-images.githubusercontent.com/54991698/75185386-fdaa1a00-5713-11ea-98ec-8a0cdc8e78ac.png)

**Comment by kkellydesign** [comment]
>  Certain product pages like Firefox for example -- you click the topics and you get this error?

Yes, I ran that by Tasos a couple of weeks ago and it's some sort of timeout issue. I'm not getting it locally with a stripped-down database. He said it's safe to ignore

**Comment by kkellydesign** [comment]
This is fixed, and will go up with https://github.com/mozilla/kitsune/pull/4193

<img width="499" alt="Screen Shot 2020-02-26 at 11 40 48 AM" src="https://user-images.githubusercontent.com/202590/75366521-ddea3180-588c-11ea-98f4-b1fb71cddca3.png">

**Comment by jess-cook03** [comment]
Confirming this is all resolved
