### ISSUE TITLE
[Mobile] The text size is too big 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#291]
Prerequisites:
Use a mobile device

1. Go to https://support.allizom.org/en-US/kb/new-test-pilot-experiments/locales

ER: The text size feets the rest of the design.
AR: The text size is too big. 

Note: This is also on desktop.

**Comment by kkellydesign** [comment]
fixed in https://github.com/mozilla/kitsune/pull/4261

<img width="1216" alt="Screen Shot 2020-03-24 at 12 39 36 PM" src="https://user-images.githubusercontent.com/202590/77452766-b4112580-6dcc-11ea-8174-04bd281640e5.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and mobile device (iPhone 8 plus) and I can confirm the fix.
