### ISSUE TITLE
The sticky bar is not displayed on some pages

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#295]
STR:
1. Go to https://support.allizom.org/en-US/kb/new-test-pilot-experiments
2. Scroll the page

ER: The sticky bar is displayed
AR: The sticky bar is not displayed. See the screen recording - https://streamable.com/7vxie

Scenario 2

1. Open FF and go to https://support.allizom.org/en-US/kb/scan-qr-codes-firefox-ios/edit
2. Scroll the page
3. Open Chrome and go to https://support.allizom.org/en-US/kb/scan-qr-codes-firefox-ios/edit
4. Scroll the page

ER: The sticky bar is displayed
AR: The sticky bar is not displayed. See the screen recording - https://streamable.com/bhc9v

Note: It seems from the second screen recording that the sticky bar sometimes is stuck and after a refresh it works.

**Comment by kkellydesign** [comment]
@ovidiuboca1 can you test this again? I'm not able to reproduce this error on production.

**Comment by kkellydesign** [comment]
@ovidiuboca1 Nevermind, I'm able to reproduce this here: https://support.mozilla.org/en-US/kb/scan-qr-codes-firefox-ios/edit

@LeoMcA or @akatsoulas can either of you take a look at this one? You'll find evidence of this in `ui.js` and `scrollTo.es6.js`, though the es6.js file isn't included in `bundles.py`, so I assume the jquery bit is the only one that is being used anywhere. I can't find a reason why this would work sometimes and not others.
