### ISSUE TITLE
[Accounts] The "See our FAQ” is not linked

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#296]
STR: 
1. Go to https://support.allizom.org/en-US/users/auth
2. Click on the "See our FAQ"

ER: You are redirected to /kb/firefox-accounts-mozilla-support-faq
AR: 404 Error is displayed.

**Comment by LeoMcA** [comment]
This article exists on prod: https://support.mozilla.org/en-US/kb/firefox-accounts-mozilla-support-faq

**Comment by ovidiuboca1** [comment]
@LeoMcA So this will work when the staging will go to prod?

**Comment by LeoMcA** [comment]
Yep, the article is stored in DB, and it doesn't exist in staging because staging is using an old DB dump.
