### ISSUE TITLE
[Accounts] The "All you need is an account" is not linked to the log in page

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#297]
STR:
1. Go to https://support.allizom.org/en-US/kb/improve-knowledge-base#w_create-an-account-and-say-hello
2. Click on  "All you need is an account" link

ER: You are redirected to log in page
AR: Page not found.

**Comment by LeoMcA** [comment]
The article text is outdated due to an old kb article. [On prod](https://support.mozilla.org/en-US/kb/improve-knowledge-base#w_create-an-account-and-say-hello), the link goes to https://support.mozilla.org/users/auth

https://support.allizom.org/users/auth works, so closing.

**Comment by ovidiuboca1** [comment]
@LeoMcA this will work only when this will be uplifted to prod?

**Comment by LeoMcA** [comment]
Yes, this will work on prod.
