### ISSUE TITLE
The selection from the Report abuse doesn't work 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#300]
STR:

1. Go to https://support.allizom.org/en-US/forums/l10n-forum/712908?last=73530#post-73500
2. Click on the three dots icon 
3. Select "Report Abuse"
4. From the modal window select a reason 

ER: You can select a reason from the available options. 
AR: The selection doesn't work.

**Comment by kkellydesign** [comment]
IDs weren't actually unique, which is required for the custom radio elements. Fixed. https://github.com/mozilla/kitsune/pull/4270

<img width="857" alt="Screen Shot 2020-03-27 at 12 33 14 PM" src="https://user-images.githubusercontent.com/202590/77778412-54fb1d00-7027-11ea-99ef-9978878444ac.png">

**Comment by ovidiuboca1** [comment]
Tested on mobile (iPhone 8 plus) and the page looks broken - 
![Skype_Picture_2020_03_30T09_13_53_599Z](https://user-images.githubusercontent.com/54845678/77895920-2461f000-7280-11ea-876d-75b2b31e69ef.jpeg) 
To be able to reproduce this, you need to be logged out. If I'm logged in the issue is not reproducible. 
On the desktop, everything looks as expected. 
@kkellydesign @madasan @akatsoulas

**Comment by LeoMcA** [comment]
This is odd, it can be reproduced on desktop (logged out) if you load the page with a small enough viewport. The browser console then spits out this message:

```
TypeError: can't access property "innerHTML", button is null common-min.5eac0d23e30d.js:1:356644
    swapMobileSubnavText https://static-media-stage-cdn.itsre-sumo.mozilla.net/static/build/common-min.5eac0d23e30d.js:1
    detailsInit https://static-media-stage-cdn.itsre-sumo.mozilla.net/static/build/common-min.5eac0d23e30d.js:1
    <anonymous> https://static-media-stage-cdn.itsre-sumo.mozilla.net/static/build/common-min.5eac0d23e30d.js:1
```

**Comment by ovidiuboca1** [comment]
I verified this on desktop Mac OS X 10.14 and Windows 10 and mobile iPhone 8 plus, and I can confirm the fix.
