### ISSUE TITLE
[Accounts] Some editing tools from kb/new are not working

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#303]
STR:

1. Go to https://support.allizom.org/en-US/kb/new
2. Scroll to the "Content" section 
3. Try to use the "Insert Media", "Numbered List", "Bulleted List" options

ER: The options are working. 
AR: The options are not working.

**Comment by LeoMcA** [comment]
Those options all work for me - in terms of inserting markup to the compose box - but then when I click preview they're not displayed properly. Is that what you mean by not working?

**Comment by ovidiuboca1** [comment]
Yes, also if you compare the behavior with the one from here [https://support.allizom.org/en-US/questions/1207019/edit](url) you will see that when you insert the markup options this works differently, the inserted numbered list is not highlighted.

**Comment by kkellydesign** [comment]
This is related to this fix: https://github.com/mozilla/kitsune/pull/4270

**Comment by ovidiuboca1** [comment]
On the desktop this works but on mobile the carrot is displayed in front of the inserted markup, we can fix this later. The inserted markup is displayed after I click preview.
