### ISSUE TITLE
Users clicking "you must log in to reply" aren't redirected back after logging in

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#305]
eg: https://support.allizom.org/en-US/questions/1207021

All we need is a `?next=` parameter on the link.

**Comment by LeoMcA** [comment]
Fixed in https://github.com/mozilla/kitsune/pull/4268

**Comment by ovidiuboca1** [comment]
Tested on desktop and mobile and I can confirm the fix.
