### ISSUE TITLE
[Accounts] I'm logged out from my account if I try to click on "Edit in admin" from groups page

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#306]
Prerequisites: 
You need to be logged in.

STR: 

1. Go to https://support.allizom.org/en-US/groups/accessibility
2. Click on "Edit in admin" button

ER: I'm able to perform this action.
AR: I'm prompted with a message https://imgur.com/a/QYELSD0 and if I go back I'm logged out from my account.
NOTE: I'm using the FxA account that has admin rights.

**Comment by akatsoulas** [comment]
That's the normal behavior. Admin access is handled by a different backend and you need to use LDAP to login.
