### ISSUE TITLE
Responsive Redesign // Profile Pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#31]

**Comment by viorelaioia** [comment]
Profile pages still need to be updated for sumo accounts (not migrated to fxa), as they currently don't have the existing functionality and they don't match the designs.

![image](https://user-images.githubusercontent.com/5293100/72454392-7212a480-37c9-11ea-9955-fb6b1edbe7ff.png)

**Comment by kkellydesign** [comment]
TODO: move sidebar to the right, per conversation with Jess.

**Comment by kkellydesign** [comment]
@akatsoulas The gravatar is still showing up as 48px here. I'm ok with ignoring this if it's only a sumo-account problem, but it is a deviation from the design that QA will catch. 

https://test.sumo.mozit.cloud/en-US/user/iam_test

<img width="742" alt="Screen Shot 2020-02-11 at 9 31 56 AM" src="https://user-images.githubusercontent.com/202590/74245720-74292f80-4cb1-11ea-8e43-4a2907ee5170.png">

**Comment by jess-cook03** [comment]
@kkellydesign 
@akatsoulas @madasan 
I have a question here about the FxA integration with the profile page and the username bug solution that we worked on a while back.
The mockups on [Zeplin here](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5dea5cd80ca72e4a341ccd09) are not 1:1 reflected here.
Right now we are just reskinning and pulling over old design.
I want to clarify which direction we are moving towards production for the profile pages?
- A) are we just going to leave the reskin for now, include the banner for FxA transition and leave the display name / username issue as is for now?
OR
- B) implement new designs where we show the FxA account and we get rid of the display name? There are also changes in the new design that simplify the page, and add copy that addresses the privacy issue with the username.

**See examples below:
CURRENT/OLD**
![Screen Shot 2020-02-20 at 4 59 18 PM](https://user-images.githubusercontent.com/54991698/74982563-5a4ec180-5402-11ea-9fdc-62e844b3dd4f.png)

**NEW**
<img width="975" alt="Screen Shot 2020-02-20 at 5 00 21 PM" src="https://user-images.githubusercontent.com/54991698/74982644-810cf800-5402-11ea-9995-ccc6f1d6e115.png">
<img width="974" alt="Screen Shot 2020-02-20 at 5 00 01 PM" src="https://user-images.githubusercontent.com/54991698/74982645-81a58e80-5402-11ea-9a2b-321a263dddbd.png">

**Comment by jess-cook03** [comment]
@kkellydesign @akatsoulas @madasan 
Per our conversation this morning -- I'm marking this as blocked for now as the username/display name changes are to be included with FxA rollout

**Comment by jess-cook03** [comment]
#75 looping this ticket with this one to be addressed in responsive v2

**Comment by jess-cook03** [comment]
Looping this with ticket #580 
-- Currently being working on right now from dev side with updates provided in that ticket ☝️

**Comment by akatsoulas** [comment]
Closing as stale
