### ISSUE TITLE
Product logos not updated across site

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#310]
- still seeing old product logos within the individual product pages, KB articles and Forums, as well as these other product selection grids on these pages: https://support.allizom.org/en-US/questions/new , https://support.allizom.org/en-US/questions

**Comment by jess-cook03** [comment]
@kkellydesign

**Comment by kkellydesign** [comment]
@jess-cook03 I can't get into django on that server, so I can't tell what's going on. Sorry I'm no help here.

**Comment by jess-cook03** [comment]
@kkellydesign no worries! I copied you on here per comments from this morning! Thanks for taking a look.

@LeoMcA @akatsoulas can you take a look at this? Thanks!
Basically home page is fine, everywhere else the product logos need to be updated across the site.

**Comment by akatsoulas** [comment]
@jess-cook03 I am working on it

**Comment by akatsoulas** [comment]
This is now fixed.
