### ISSUE TITLE
On Tracking Protection kb article the shield icon is not displayed. 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#313]
STR: 

Go to https://support.allizom.org/en-US/kb/tracking-protection
Observe that in the first part of the article you should see some shield icons. 

ER: The icons are displayed.
AR: The icons aren't displayed. See the print-screen, there is some different behaviour depending on the browser. 
<img width="1281" alt="Screenshot 2020-03-30 at 11 00 56" src="https://user-images.githubusercontent.com/54845678/77889257-43f41b00-7276-11ea-8b6c-3f4935e2630b.png">

**Comment by akatsoulas** [comment]
This is coming from the db. Staging instance does not have the full set of icons that production has.
