### ISSUE TITLE
Product logos not showing up within AAQ

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#315]
https://support.allizom.org/en-US/questions/new
@akatsoulas @LeoMcA 
Firefox for Amazon Devices missing here:
![Screen Shot 2020-03-31 at 11 10 39 AM](https://user-images.githubusercontent.com/54991698/78044846-2fca1f80-7343-11ea-85e1-4e14dd7bbaa2.png)

Also -- can we change the 'other products' from the old mozilla logo to this moz 'm' favicon?
![moz](https://user-images.githubusercontent.com/54991698/78047094-f515b680-7345-11ea-9259-a572ccb57f49.png)

**Comment by akatsoulas** [comment]
Firefox device is coming from the DB. In production this won't be a problem. I will update the other products.

**Comment by akatsoulas** [comment]
The logo for `Other Mozilla products` is updated.

**Comment by ovidiuboca1** [comment]
I verified this on desktop and mobile and I can confirm the fix.
