### ISSUE TITLE
The drop-downs are missing on staging site

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#316]
cc @kkellydesign 
STR:

1. Go to https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections
2. Go to https://support.allizom.org/en-US/kb/how-stop-firefox-making-automatic-connections
3. Compare the pages

ER: The pages are displayed similar, you can see the drop-downs
AR: The pages are displayed differently, on staging the drop-downs are missing.

**Comment by kkellydesign** [comment]
This is in: https://github.com/mozilla/kitsune/pull/4280

<img width="1007" alt="Screen Shot 2020-04-01 at 11 30 12 AM" src="https://user-images.githubusercontent.com/202590/78157130-9a479200-740d-11ea-8c02-5be3c7c9981c.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop, Mac OS X 10.14 and Windows 10 and mobile device, iPhone 8 plus, and I can confirm the fix.
