### ISSUE TITLE
Change link for 'Ask the Community' button within forum page / logged out user

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#317]
This button CTA should link to the start of AAQ to align with the rest of these buttons on the site -- all linking to the AAQ.
Currently it links to a KB article and we are no longer going to link to those hidden articles.
![Screen Shot 2020-04-01 at 10 12 52 AM](https://user-images.githubusercontent.com/54991698/78147708-e42a7b00-7401-11ea-884b-c1c7908ccecd.png)

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4278

This is live on staging: https://support.allizom.org/en-US/questions/firefox

**Comment by akatsoulas** [comment]
The change has been reverted. There is a detailed explanation from Chris in the support-platform slack channel why we cannot change just this link and more changes need to be introduced into the platform. 

The short version is that not all locales have AAQ forums and such a change would introduce many problems for that locales.

**Comment by ovidiuboca1** [comment]
I verified this on Mac OS X 10.14 and Windows 10 and I can confirm that the "Ask the community" button is linked to https://support.allizom.org/en-US/kb/get-community-support.

On mobile, the "Ask the community"  button is not displayed. CC @jess-cook03  This is intended?

**Comment by jess-cook03** [comment]
**_NOTE:_**
Moving this to v2 milestone, UX wise I would like to take a second look at this and see if there are any future changes we can make/improvements.

**Comment by AliceWyman** [comment]
> 
> The change has been reverted. There is a detailed explanation from Chris in the support-platform slack channel why we cannot change just this link and more changes need to be introduced into the platform.
> 
> The short version is that not all locales have AAQ forums and such a change would introduce many problems for that locales.

Related bug report:
[Bug 1630517](https://bugzilla.mozilla.org/show_bug.cgi?id=1630517) Opened 2020-04-16 03:06 EDT Hide direct aaq links in "Get Help" header for locales without product forums

**Comment by jess-cook03** [comment]
@akatsoulas circling back to this again -- is there a way for the locales who DO have support forums to have this link directly bring them into the AAQ flow?

I understand we need to link to the  https://support.allizom.org/en-US/kb/get-community-support for the locales that need this page, which is fine, but for the others is there a way around needing to land on this page and instead by-pass to the flow.

But for sake of linking to the AAQ and having these links across the site, I think we need to know what we can do per use case here.

**Comment by LeoMcA** [comment]
> @akatsoulas circling back to this again -- is there a way for the locales who DO have support forums to have this link directly bring them into the AAQ flow?

I touched on this here: https://github.com/mozilla/sumo-project/issues/397#issuecomment-617695849, but yes that is possible.

However I think delaying the "link" (which would technically be a redirect) to this page as much as possible is preferable. Since we present a number of opportunities for users to leave the AAQ flow and enter the KB in their locale we should only redirect a user to the get-community-support page when we know they're trying to ask a question about a product in a locale which doesn't have a forum for that.

**Comment by akatsoulas** [comment]
Closing this issue as stale
