### ISSUE TITLE
The /flagged page is not properly styled.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#319]

**Comment by kkellydesign** [comment]
I made a minor fix here, so this looks ok to me: https://github.com/mozilla/kitsune/pull/4312

Let me know if you had something else in mind. 

<img width="1010" alt="Screen Shot 2020-04-15 at 12 21 41 PM" src="https://user-images.githubusercontent.com/202590/79361904-e9b0b680-7f13-11ea-8ade-edd5be5186b2.png">

**Comment by ovidiuboca1** [comment]
I tested this and I can confirm that I have the same result like the one provided by Kasey.

**Comment by akatsoulas** [comment]
Deployed in prod.
