### ISSUE TITLE
Connect popular articles in the new AAQ flow.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#320]

**Comment by mirunacurtean** [comment]
Checked by QA in dev environment with Firefox 76 and Chrome on Mac OS X 10.14 and Windows 10. and Android 8.0.0 and Popular/ Featured Articles have been added in several product categories. 

![image](https://user-images.githubusercontent.com/53306802/81312166-fba6f480-908e-11ea-9078-756268ab5b56.png)

To note that not all product categories have articles listed, for example Firefox Focus. 
![image](https://user-images.githubusercontent.com/53306802/81313995-41fd5300-9091-11ea-9480-7dc9e5c062af.png)

**Comment by akatsoulas** [comment]
As discussed in slack the behavior described in the comment is only happening in the dev cluster due to limited content in the DB.

**Comment by mirunacurtean** [comment]
Confirmed in Dev environment after testing with Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10 and also on Android/iOS devices across FF, Chrome and Safari browsers. 
@mirunacurtean Should retest in stage environment where DB is better populated.
