### ISSUE TITLE
Fix product logo in the new AAQ flow.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#321]

**Comment by mirunacurtean** [comment]
@akatsoulas or @LeoMcA 
 Which product logo does this refer to? Is it correct to assume it means one/some of these?
![image](https://user-images.githubusercontent.com/53306802/81174111-e7d59280-8fa9-11ea-9f95-d99169b1d4d9.png)

Could you please provide more details on how and where will the fix be applied before this is deployed?
Thank you

**Comment by akatsoulas** [comment]
Thanks @mirunacurtean for flagging this. This issue is fixed in responsive and it was misplaced in the aaq. Closing.
