### ISSUE TITLE
Link "Ask a question" button to the form submission page.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#322]
The "Ask a question" button in the masthead needs to go straight to the form, which currently has several additional steps between.

**Comment by mirunacurtean** [comment]
For now this can only be confirmed as applied on Desktop on dev environment with Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10. 

![Ask a question  redirect to form](https://user-images.githubusercontent.com/53306802/81314521-e4b5d180-9091-11ea-8fda-10ae80395cfd.gif)
