### ISSUE TITLE
Display "popular topics" in the new AAQ flow.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#323]
"Popular Topics" list needs hooked up to the backend to link back out of this flow. Currently that list populates the next step in the AAQ process, and that's no longer correct.

**Comment by mirunacurtean** [comment]
Confirmed in Dev environment after testing with Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10 and also on Android/iOS devices.
![image](https://user-images.githubusercontent.com/53306802/81409704-420c5a00-9148-11ea-969b-83224f69e6dd.png)
