### ISSUE TITLE
Fix the progress bar in the new AAQ flow.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#324]
This page has the incorrect progress bar in the top, in a nested macro, but at the bottom all of the conditionals are working correctly. The one at the bottom is a mistake, and the one at the top is displaying the incorrect steps in the process, so I've left them both for now. The one on the bottom needs removed once the one on the top is working correctly.

**Comment by mirunacurtean** [comment]
@akatsoulas 
Does this concern the progress bar which has, for now, only been implemented on dev?
![image](https://user-images.githubusercontent.com/53306802/81178715-51a56a80-8fb1-11ea-89b3-8df7a5acaf71.png)

**Comment by mirunacurtean** [comment]
Verified by QA on https://support-dev.allizom.org/ with Firefox 76 and Chrome on Mac OS X 10.14 and Windows 10. 
Progress bar is shown at the top of the page and is updated after each step to indicate finished steps. 
![Progress bar](https://user-images.githubusercontent.com/53306802/81309672-df558880-908b-11ea-8950-545fd43827a4.gif)

**Comment by mirunacurtean** [comment]
Moving this in Ready for deploy as 428 has been closed and verified.
