### ISSUE TITLE
The check box functionality is broken on the /kb/new page RTL locals. 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#325]
Prerequisites: 

Use Chrome browser

STR: 

1. Go to https://support.allizom.org/fa/kb/new
2. Expend a Topic and check a check-box

ER: The check-box is marked and the page is displayed properly.
AR: The page is broken. Screen recording- https://streamable.com/iq7e2v

NOTE: On Firefox you can't see this issue but if you go to https://support.allizom.org/fa/kb/new you will see that there is a horizontal scroll, on the en-US local the horizontal scroll doesn't exist.

**Comment by ovidiuboca1** [comment]
The same issue with the check-boxes from https://support.allizom.org/he/messages

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4288

<img width="372" alt="Screen Shot 2020-04-06 at 10 34 58 AM" src="https://user-images.githubusercontent.com/202590/78570785-6ac0cd00-77f3-11ea-8af1-4159a9e3013e.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop and on chrome browser the issue is still there, please see this screen recording - https://streamable.com/ehgt0q
On Firefox the issue seems to be fixed, I can't reproduce it. 
CC @kkellydesign @akatsoulas

**Comment by kkellydesign** [comment]
This is fixed here, along with some minor RTL issues in the navbar. 

https://github.com/mozilla/kitsune/pull/4296

**Comment by ovidiuboca1** [comment]
I tested this on Mac OS X 10.14 and on chrome the first check-box is partially cut off when is checked, see the print screen 
<img width="938" alt="Screenshot 2020-04-10 at 14 44 28" src="https://user-images.githubusercontent.com/54845678/78988572-f8752300-7b39-11ea-9b04-2942ef0ecf71.png">
Also here is a screen recording. - https://streamable.com/4gytan
On Firefox the issue is not reproducible. 
CC @akatsoulas @madasan, please take a look at this and let me know your opinion. From my point of view, this is not a major issue so I will move this to the done column.

**Comment by kkellydesign** [comment]
I can't _not fix_ dumb CSS bugs like this. 

https://github.com/mozilla/kitsune/pull/4298

<img width="970" alt="Screen Shot 2020-04-10 at 9 53 49 AM" src="https://user-images.githubusercontent.com/202590/78995846-43c70b80-7b11-11ea-89dd-f7e14570c100.png">

**Comment by ovidiuboca1** [comment]
This is verified.
