### ISSUE TITLE
Hook up product title and image on AAQ form

### ISSUE THREAD

**Issue by kkellydesign** [mozilla/sumo-project#327]
From this mockup: 
https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e79017e860445627a3984ac

And this conversation in Slack: 
https://lincolnloop.slack.com/archives/CHP020EJX/p1586180008037800?thread_ts=1586179145.035500&cid=CHP020EJX

I've come up with the following: 
- [x] The image needs hooked up to the backend: https://github.com/lincolnloop/kitsune/commit/49947c7b18de5c36294dcac314c1e462b5d1030d#diff-32603c10deee3afc0c906878870f68d7R75-R76
- [x] The title underneath needs hooked to the backend: https://github.com/lincolnloop/kitsune/commit/49947c7b18de5c36294dcac314c1e462b5d1030d#diff-32603c10deee3afc0c906878870f68d7R90
- [ ] When subproducts go live, this conditional will need checked and the dropdown will need populated from the backend. https://github.com/lincolnloop/kitsune/commit/49947c7b18de5c36294dcac314c1e462b5d1030d#diff-32603c10deee3afc0c906878870f68d7R78

This is the only thing that should be visible at launch: 
<img width="1001" alt="Screen Shot 2020-04-06 at 11 42 14 AM" src="https://user-images.githubusercontent.com/202590/78577557-3dc4e800-77fc-11ea-965f-f7b9c80c193e.png">

And when subproducts are ready, this conditional will need set up, but the markup is in now. 
<img width="346" alt="Screen Shot 2020-04-06 at 11 42 57 AM" src="https://user-images.githubusercontent.com/202590/78578020-ea9f6500-77fc-11ea-945f-bb71b367e398.png">

**Comment by LeoMcA** [comment]
The commit referenced above got lost in the ether, I just cherry-picked it on top of `aaq-redesign`: https://github.com/mozilla/kitsune/commit/e3ed73dfad2a615d63f86c6d66b449759e6ad514

**Comment by LeoMcA** [comment]
As discussed in today's design review, we decided to make the pre-subproduct product display a non-link.

**Comment by mirunacurtean** [comment]
Confirmed in Dev environment that the corresponding product image and title is hooked to the AAQ form. 
![image](https://user-images.githubusercontent.com/53306802/81409980-b34c0d00-9148-11ea-8bd8-17c38fbfded6.png)
![image](https://user-images.githubusercontent.com/53306802/81410020-c4951980-9148-11ea-9d4e-bb9efdc93552.png)
