### ISSUE TITLE
aaq.isFirefoxOS is not a function

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#330]
When asking a non-desktop non-android question on staging (e.g: https://support.allizom.org/en-US/questions/new/ios) the browser console spits out this error:

> TypeError: aaq.isFirefoxOS is not a function

**Comment by ovidiuboca1** [comment]
I tested this on Mac OS X 10.14 and Windows 10 with FF and chrome and I can't see the error: TypeError: aaq.isFirefoxOS is not a function, as expected.
