### ISSUE TITLE
Fix "Reverse for 'users.fxa_authentication_init' not found." in frankfurt

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#338]
When we switch over to frankfurt, we get a number of "Reverse for 'users.fxa_authentication_init' not found." errors.

This is because `OIDC_ENABLE` is set to false, so that url isn't registered. This causes any template which attempts to link to that url with `url('users.fxa_authentication_init')` to fail to render.

**Comment by akatsoulas** [comment]
This can be tackled in #490
