### ISSUE TITLE
Community hub link / add to navigation

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#339]
Seburo made a really great point that navigating to the community hub is not that accessible anymore. I think we may have left out some of the links under contributor section of the nav --- and in general lets take a second evaluation of what goes there and any additional links we may need to add.

https://support.mozilla.org/en-US/community

**Comment by jess-cook03** [comment]
@LeoMcA @akatsoulas 
Updates / confirmed changes:
"Contributor Forums" link becomes the "Discussions" one, and Community Hub exist under Tools.
It should look like this:
<img width="1029" alt="Screen Shot 2020-04-15 at 11 25 14 AM" src="https://user-images.githubusercontent.com/54991698/79355620-e7e2f500-7f0b-11ea-98f5-c970eaaca2e6.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop and mobile and I can confirm the fix.
