### ISSUE TITLE
Aggregated Dashboards / side bar navigation issues

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#340]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1631165

https://support.mozilla.org/en-US/kb/dashboard/metrics/aggregated

Seems here that the sidebar changes when trying to use it to navigate btween dashboards listed.
@madalina @tasos per patrick's comment about the dashboards.... i'm looking into this now and it seems something buggy might be going on : https://support.mozilla.org/en-US/kb/dashboard/metrics/aggregated
When you are here in 'aggregated metrics' you see the other side bar menu items above: 'localization dashboard, locale metrics, etc"
If you click to navigate to those pages the menu totally changes and populates different items, and then with recent revisions it disappears altogether.

**Comment by kkellydesign** [comment]
I added the sidebar to the 'recent revisions' page, and I may have fixed the issue on the aggregated sidebar page... but I'm getting the same error on local and prod on the aggregated URL that you lined above, so I can't test that one. 

@akatsoulas The error that I'm getting locally is `b2a_base64() argument 1 must be string or buffer, not None`, so this might be a data or BE issue. 

Here's the revisions page with the sidebar added. https://github.com/mozilla/kitsune/pull/4312

<img width="1421" alt="Screen Shot 2020-04-15 at 3 50 04 PM" src="https://user-images.githubusercontent.com/202590/79382981-6c486e80-7f32-11ea-8cf0-5b7b2d8daaef.png">

**Comment by akatsoulas** [comment]
@kkellydesign this is happening b/c the GA credentials are missing from your local env. There is also an error in that functionality which is fixed here https://github.com/mozilla/kitsune/pull/4321

**Comment by kkellydesign** [comment]
ok, it looks like I got the fixes right anyway. This is ready for QA: 

https://support.allizom.org/en-US/kb/dashboard/metrics/aggregated

<img width="945" alt="Screen Shot 2020-04-16 at 11 05 03 AM" src="https://user-images.githubusercontent.com/202590/79472722-30fd7c80-7fd2-11ea-947a-b024914d114b.png">

**Comment by ovidiuboca1** [comment]
On mobile, the "Aggregated Metrics" drop-down can't be condensed, here is a screen recording - https://streamable.com/y93uo2
On desktop the issue is fixed. I see the sidebar menu in the recent revision page and also the "Aggregated metrics" is there.

**Comment by ovidiuboca1** [comment]
Retested on mobile and I can confirm the fix, the Aggregated Metrics" drop-down can be condensed.
