### ISSUE TITLE
Dashboard links / add to sidebar navigation but not in main nav

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#341]
Contributor Tools > dashboards it only seems like the localization dashboards made it across. 
Are the other dashboards hidden somewhere or did they not make the migration?

We just don’t link to all of them from the Nav anymore, users can access them via the URL....

Do we want to consider adding any of these links back into the site -- via side bar of the dashboards section or something?

**Comment by akatsoulas** [comment]
Closing this issue as stale
