### ISSUE TITLE
<Enter> key is ignored when responding to a question.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#347]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1630036

**Comment by mirunacurtean** [comment]
@LeoMcA  When using the "enter" key in any new replies, even when they contain common responses, the text is added on a new line which is displayed correctly once previewed or posted. 

![Enter key performs as line break](https://user-images.githubusercontent.com/53306802/87321664-33219980-c535-11ea-9894-8e4561e9c359.gif)

As for quoted replies, the new line seems to be applied successfully when using enter after them of when quoting responses that have been formatted using bulleted or numbered list, but it still streamlines responses that do not use either. See second attached GIF>

![Quote reply new line](https://user-images.githubusercontent.com/53306802/87323184-1be3ab80-c537-11ea-9af2-25d1cf99700a.gif)

Based on the SUMO forum discussion https://support.mozilla.org/en-US/forums/contributors/714315?last=79039#post-79036, this also seemed like something that could be improved.

**Comment by LeoMcA** [comment]
> As for quoted replies, the new line seems to be applied successfully when using enter after them of when quoting responses that have been formatted using bulleted or numbered list, but it still streamlines responses that do not use either.

Great catch, should be a quick fix!

**Comment by mirunacurtean** [comment]
Verified fixed on Desktop (windows pro 10) with Firefox and Chrome and on Android 9.0.0 on Firefox. 
![Enter tests](https://user-images.githubusercontent.com/53306802/88052130-71850d00-cb62-11ea-8715-2a06d48f9c0b.gif)
