### ISSUE TITLE
Optimize questions_list view

### ISSUE THREAD

**Issue by jgmize** [mozilla/sumo-project#360]
We had an outage this weekend related to slow DB performance, and the culprit this time appears to have been the questions_list view, which can generate very expensive queries under certain circumstances.

https://rpm.newrelic.com/accounts/1299394/applications/45097089/datastores#/overview/MySQL/trace/?id=3f10c9b5-ea8c-11e8-be82-0242ac110007_0_4094&metric=Datastore%252Fstatement%252FMySQL%252Fquestions_question%252Fselect

**Comment by akatsoulas** [comment]
This issue is no longer relevant.
