### ISSUE TITLE
<pre> tag is causing text overflow

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo-project#364]
If you go to [this contributor forum page](https://support.mozilla.org/en-US/forums/contributors/714004?last=78023#post-77988), the text is overflowing to the right. I believe this is because of the "pre" tag that was available in the previous editor. 

![Screenshot_2020-04-15 Firefox 75 for Desktop - Release Notes Issues Discussions SUMO community discussions Forums Mozilla S](https://user-images.githubusercontent.com/4922388/79416601-3b237900-7fda-11ea-9f69-ef4660c05cfe.png)

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4318

**Comment by akatsoulas** [comment]
This is fixed both in staging and prod thus I am closing the issue
