### ISSUE TITLE
The article preview is not displayed correctly on mobile device

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#366]
CC @LeoMcA, @akatsoulas 
This is a follow up from issue - https://github.com/mozilla/sumo-project/issues/346

Prerequisites:
Test on a mobile device

STR:

1. Go to https://support.allizom.org/ro/kb/change-your-default-search-settings-firefox/translate?discard=%C3%8Enl%C4%83tur%C4%83#preview
2. Scroll to the bottom of the page and click on "Previzualizeaza continutul" similar to "Preview Changes"

ER: The preview changes are displayed correctly. 
AR: The preview changes are displayed incorrectly.

**Comment by kkellydesign** [comment]
This is in: https://github.com/mozilla/kitsune/pull/4322

<img width="1058" alt="Screen Shot 2020-04-16 at 9 39 40 AM" src="https://user-images.githubusercontent.com/202590/79463001-47054000-7fc6-11ea-98c5-63112b6a7790.png">
<img width="560" alt="Screen Shot 2020-04-16 at 9 39 48 AM" src="https://user-images.githubusercontent.com/202590/79463019-4a98c700-7fc6-11ea-9de2-99dd9188fa6a.png">
<img width="655" alt="Screen Shot 2020-04-16 at 9 39 54 AM" src="https://user-images.githubusercontent.com/202590/79463032-4e2c4e00-7fc6-11ea-919e-f30c1cfdc86b.png">

**Comment by ovidiuboca1** [comment]
I tested this and I can confirm the fix.
