### ISSUE TITLE
Responsive Redesign // Home, Product Hub Page Designs 

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#37]
Wireframes in progress view [Miro board here](https://miro.com/app/board/o9J_kwU3_B4=/)

**Comment by viorelaioia** [comment]
Opened: 

- https://github.com/mozilla/sumo-project/issues/125
- https://github.com/mozilla/sumo-project/issues/124

**Comment by kkellydesign** [comment]
@jess-cook03 Navigation is switched to the large breakpoint (`

<img width="760" alt="Screen Shot 2020-01-30 at 3 11 03 PM" src="https://user-images.githubusercontent.com/202590/73486274-ccd40080-4372-11ea-80fb-8c708f696ac0.png">
768px`), which means tablets get the mobile style.

**Comment by kkellydesign** [comment]
This should be safe to close.

**Comment by ovidiuboca1** [comment]
CC @jess-cook03 and @kkellydesign 
The size of the icons from the home page, desktop version, shouldn't be larger? 
![Screenshot 2020-02-13 at 11 51 52](https://user-images.githubusercontent.com/54845678/74436752-9ec0e700-4e6f-11ea-8aaf-c12842f32741.png)

**Comment by jess-cook03** [comment]
@kkellydesign @ovidiuboca1 confirming -- > yes these do need to be made larger on the home page cards.

**Comment by kkellydesign** [comment]
This is a duplicate of this issue – I explained the problem here: https://github.com/mozilla/sumo-project/issues/162#issuecomment-585819960

**Comment by akatsoulas** [comment]
Closing as duplicate per last comment
