### ISSUE TITLE
Only use username when quoting not additional info

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#370]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1630396
PR: https://github.com/mozilla/kitsune/pull/4319

**Comment by ovidiuboca1** [comment]
Tested on desktop using these links: 
https://support.allizom.org/en-US/kb/troubleshoot-time-errors-secure-websites/discuss/6631#post-preview
https://support.allizom.org/en-US/forums/off-topic/710704?last=73499#post-preview
https://support.allizom.org/en-US/questions/1207034#answer-preview 
I can confirm the fix.
