### ISSUE TITLE
use prefers-reduced-motion media query to disable animation

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#371]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1630825

**Comment by LeoMcA** [comment]
Due to a quirk in our build pipeline, this is already deployed in production.

**Comment by LeoMcA** [comment]
@ovidiuboca1 in order to test this you'll need to enable the reduced motion preference as described here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#User_Preferences

**Comment by ovidiuboca1** [comment]
I tested this on Mac OS X 10.14 and Windows 10 with Firefox and chrome and I can confirm the fix. 
@LeoMcA thanks for the link,  should I comment also in Bugzilla?

**Comment by LeoMcA** [comment]
Thanks @ovidiuboca1, I commented in bugzilla including instructions on how to enable the feature.

As mentioned above:
> Due to a quirk in our build pipeline, this is already deployed in production.

So closing this issue.
