### ISSUE TITLE
Fix some lost KB article styling

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#373]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1630800

Markup chart: https://support.mozilla.org/en-US/kb/markup-chart

How it used to look: [Screenshot_2020-04-17 Markup chart Contributors Help - prod-frankfurt sumo mozit cloud](https://user-images.githubusercontent.com/755354/79577272-59fa3c00-80bc-11ea-8bea-fb2f76352028.png)

**Comment by ovidiuboca1** [comment]
I verified this on desktop, Mac OS X 10.14, and Windows 10 and I can confirm the fix.
Verified also on mobile.
