### ISSUE TITLE
Article History is now missing the "X" for reviewers to delete individual revisions

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#374]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1630303

**Comment by ovidiuboca1** [comment]
I tested this on desktop, Mac OS X 10.14, and Windows 10 and I can confirm the fix. I visited https://support.allizom.org/en-US/kb/forum-response-firefox-crashes/history and I saw a "trash can" symbol that allows you to delete and article.
