### ISSUE TITLE
 Download Firefox links appearing underneath the article title

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#376]
https://bugzilla.mozilla.org/show_bug.cgi?id=1631389

**Comment by jess-cook03** [comment]
@LeoMcA this also ties into a bigger issue that I think Alice ^ in the bug pointed out... which I already flagged in this ticket as a v2 change: #224 

We have very inconsisent and invasive placement of this download button that needs to be refined. 

I agree with proposed solution mentioned this bugzilla link... having it appear in the header only. 
This requires also getting rid of the other links that surround the button. 
I'm marking this as review for now and we should discuss this together.

Other than moving the button out of the article content area itself -- have you made any other changes to this so far?

**Comment by LeoMcA** [comment]
> Other than moving the button out of the article content area itself -- have you made any other changes to this so far?

Aside from properly styling it as a button, that's the only change I've made in this PR: https://github.com/mozilla/kitsune/pull/4334

**Comment by LeoMcA** [comment]
Standup notes:

**Current logic:**

In non-Firefox browsers, every page other than Firefox KB pages have a "Download Firefox" button in the header. On Firefox KB pages, in non-Firefox browsers, there's a "Download Firefox" button with additional "Systems and Languages", "What's New" and "Privacy" links below.

On the Thunderbird KB home page, there's an unstyled "Download Thunderbird" link with "Systems and Languages", "Release Notes" and "Privacy" links below.

**Fix for Thursday:**

Keep the same logic, ensure all buttons are styled appropriately.

With @jonichan's approval, remove the extra "Systems and Languages" etc. links underneath the KB buttons.

**Questions for the future:**

* Should we remove these in-page buttons altogether and just rely on the header button everywhere?
* What does this mean for Thunderbird, do we keep that button on its KB home page?
* Should other products (e.g. FPN) also get a download button on their KB home page?
* Should those Thunderbird/other product download buttons also appear in KB articles, like they currently do with Firefox?

**Comment by ovidiuboca1** [comment]
I will move this to implementation due to the fact that there is an issue whit the buttons display on pages that have long titles. We talked yesterday with Leo about this, @LeoMcA please let me know when this is fixed and I can verify it.

**Comment by akatsoulas** [comment]
Closing this as it's been deployed already to prod along with the fix for long article titles. The discussion about the Download buttons throughout the site will be continued in issue #224
