### ISSUE TITLE
Make Question Details section open by default

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#377]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1630499

@jess-cook03 thoughts on this?

**Comment by jess-cook03** [comment]
@LeoMcA 
I appreciate this feedback from a contributor's perspective, but I don't necessarily think that preference alone is enough of a reason to revert to the previous way when these details were exposed before.

I can see the point mentioned where if this information is the top priority for contributors and they are looking for that first above all else then yes, we can adjust some of the UI/functionality on that sidebar.

The rationale for allowing users to open and close that info was for simplicity sake and informational organization to best utilize the real-estate in the sidebar. We wanted to create more space for the relevant/related content to appear.

I'd like to know how many contributors feel that this information is top priority and if they feel they need to have it exposed or not?

**Comment by jess-cook03** [comment]
Parking this in the backlog for now.

Per comment above @madasan .... the design intent holds true for keeping it as is, accommodating both public browsing user as well as the contributor. 

We can potentially investigate further to see how many community members are effected by this (ie not just a preference of a few).

Maybe think further about how this can be a part of the contributor onboarding project.
Preferences for contributors who are signed up/registered as volunteers... do we attach this kind of view based preference to those users?

**Comment by jess-cook03** [comment]
Closing this as it doesn't seem to have enough grounds to change... seems like a preference this one user had.... no issues have come up around this since.
