### ISSUE TITLE
"Related Articles" heading is not accurate

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#378]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1631287

@jess-cook03 should we be changing the heading to something more generic, or the content to just include articles?

**Comment by jess-cook03** [comment]
@LeoMcA getting @jonichan to take a look at this.

But here are my solutions/thoughts:
Language change is minor -- I agree we should make this change.
Maybe something like 'Related to this topic' or just 'Related to this' ?

Looking at how others are doing this:
- Google serves up related articles/threads but the section title is just general 'help' .... we could do something similar like ... 'More help' or 'Related Help' ... 'Also helpful' ?

-Adobe titles theirs 'More like this' 
👆I think this one could work for us.

**Comment by jonichan** [comment]
How about "See also"?

It's short and open-ended enough that we can recommend both articles, topics, etc.

My concern with "More help" is that it sounds like we're offering help beyond articles and support forums (i.e. phone calls or live chats). "More like this" could work but "See also" is shorter.

**Comment by ovidiuboca1** [comment]
I tested this on desktop, Mac OS X 10.14, and Windows 10 with FF and chrome and also on the mobile device and I can confirm the fix. I used this link https://support.allizom.org/en-US/questions/1207034

**Comment by akatsoulas** [comment]
Deployed to prod.
