### ISSUE TITLE
Misplaced support requests in the contributor forums

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#379]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1631250

**Comment by jess-cook03** [comment]
@LeoMcA 
I agree with solutions mentioned, specifically these: 

> 

- Only display the "contributor tools" menu and/or the discussions section to users who are logged in AND who have signed up as volunteers (=part of the "Registered as contributor" user group).

-  Display the contributor tools to everyone but make the contributor forums section read-only for users who have not signed up as volunteers.

**Comment by jess-cook03** [comment]
@madasan 
Need to investigate this issue more.
Next steps:
- [ ] follow up with kiki and community managers on this bug

- [ ] understand and evaluate if/how we want move forward with possible solutions

**Comment by akatsoulas** [comment]
Closing this issue as stale
