### ISSUE TITLE
Allow moderators/admins to edit user profiles.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#386]

**Comment by ovidiuboca1** [comment]
I verified this on staging using my account that has admin privileges mozillatest1234@yahoo.com and I was able to edit the user profile from my other account sumoallizom@gmail.com. 
Tested on desktop and mobile. 

@akatsoulas 
Question: Shouldn't we mark somehow or notify the user that some changes where made on his profile?

**Comment by akatsoulas** [comment]
This is usually used for deactivated/spam accounts so in that case there is no need for notifications. The patch has been deployed to prod.
