### ISSUE TITLE
Option to mark an article for localization from the history page is gone.

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#387]
When you visit the article history (example: https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect/history) there was a button under the "R" column for each revision that let you mark that revision ready for localization. 

That button is now replaced by a non-functional pencil icon.

**Comment by ovidiuboca1** [comment]
I tested this on desktop, Mac OS X 10.14, and Windows 10 and mobile device and I can confirm the fix. 
I used this link https://support.allizom.org/en-US/kb/get-started-firefox-overview-main-features/history

**Comment by AliceWyman** [comment]
Related bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1630315
