### ISSUE TITLE
 Featured article tiles don't show up localised

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#393]
https://bugzilla.mozilla.org/show_bug.cgi?id=1631591

**Comment by mirunacurtean** [comment]
Verified fixed on Desktop FF and Chrome and mobile on Android on the following pages: 
https://support.allizom.org/fr/
https://support.allizom.org/de/products/mobile
https://support.allizom.org/fa/products/contributor

Tested on almost all available languages and I can confirm that the tile link is functional and directs to the appropriately translated articles. 
If there are no articles in a particular language the section is hidden.
