### ISSUE TITLE
'Get Help' and 'Ask Community' links in navigation / review

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#396]
https://bugzilla.mozilla.org/show_bug.cgi?id=1630720
Mentioned again here: https://bugzilla.mozilla.org/show_bug.cgi?id=1631250
👆looping these bugs to here as part of discussion about this.

There are a few things happening here, all valid points, but some clarity needs to be provided:

- Users are not used to having a link to the forums for both contributors and non-contributors, before a link for users to just access and browse the forums was not clear it was hidden. Now with the 'Browse all product forums' link we are allowing all users to access and view the forums through their different lenses. We have different views/tooling that is shown or hidden based on logged in and logged out users. I understand that may be confusing, but it is not just for contibutors and we are providing an AAQ link in those forum pages. Right now we provide that button to the AAQ only for non-logged in users, I think we need to evaluate if we want to provide it in the logged in user view of the forum as well.

- 'Get Help' context click --- I think we should evaluate if we want this link to go to https://support.mozilla.org/en-US/questions or to https://support.mozilla.org/en-US/questions/new

**Comment by LeoMcA** [comment]
> Right now we provide that button to the AAQ only for non-logged in users, I think we need to evaluate if we want to provide it in the logged in user view of the forum as well.

I think this would be good, as it would give logged-in non-contributors an "escape" out of the browsing flow to the asking flow.

**Comment by jess-cook03** [comment]
Stand by -- as I believe this may get resolved after the fix to #398 ... backlogging this for now.
