### ISSUE TITLE
UI + copy changes to https://support.mozilla.org/en-US/questions page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#398]
- [x] Page title: 'Support Forums' (add 's')

- [x] Subheader: 'Browse by product' instead of pick your product

![Screen Shot 2020-04-21 at 4 33 05 PM](https://user-images.githubusercontent.com/54991698/79911172-ed4dad00-83ed-11ea-8e23-758d64d3cdd5.png)

**Comment by jess-cook03** [comment]
@jonichan Lets review this together!

**Comment by jess-cook03** [comment]
This has been confirmed and I'm going to move this towards dev @LeoMcA @akatsoulas

**Comment by LeoMcA** [comment]
@jess-cook03 we have a breadcrumb element with "Support Forum" in it to, should that also be updated to "Support Forums"?

e.g: on https://support.allizom.org/en-US/questions/1207043:

![Screenshot_2020-05-12 indexing - question 2 Firefox Support Forum Mozilla Support - support allizom org](https://user-images.githubusercontent.com/755354/81714994-99276d00-946f-11ea-8764-cc6b926df60c.png)

**Comment by jess-cook03** [comment]
@LeoMcA I would say yes, it makes most sense to keep these consistent.

**Comment by ovidiuboca1** [comment]
We can confirm the fix. The issue was tested on desktop, Mac OS X 10.14 and Windows 10, mobile devices Andriod and iOS using the Firefox, chrome and safari browsers.
