### ISSUE TITLE
Forums - quoting functionality 

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#399]
https://support.mozilla.org/en-US/questions/1284541

https://bugzilla.mozilla.org/show_bug.cgi?id=1630396

@LeoMcA @akatsoulas thoughts on this?

**Comment by LeoMcA** [comment]
We fixed the quoting bug with the last release, is there something else from that thread you wanted our thoughts on?

**Comment by jess-cook03** [comment]
@LeoMcA nope! sorry, didn't realize this was already addressed!
