### ISSUE TITLE
Forums UI + UX fixes / Helpful, Solved Problem functionality 

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#400]
https://bugzilla.mozilla.org/show_bug.cgi?id=1566350

👆lots of things mentioned here but certain things I would like to address/discuss and potentially explore new improved solutions for:

- helpful? vote up and down.  

- solves the problem button

- permissions for tooling for different users (moderator vs. OP.... etc)

**Comment by jess-cook03** [comment]
https://support.mozilla.org/en-US/questions/1284541

**Comment by akatsoulas** [comment]
Closing this issue as stale
