### ISSUE TITLE
AAQ search implementation

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#406]
https://mozilla.invisionapp.com/share/QSWDARJJRDT#/screens/410503893

- [x] add "Found X results for Y" text
- [x] make "ask the community" button when search finds nothing link to the next step of the AAQ

**Comment by mirunacurtean** [comment]
Confirmed in Stage environment after testing with Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10 and also on Android/iOS devices.
![image](https://user-images.githubusercontent.com/53306802/81668919-0924fb80-944e-11ea-8ed1-c77c8a3b3935.png)
![image](https://user-images.githubusercontent.com/53306802/81668936-0f1adc80-944e-11ea-9c8b-acc719e1403f.png)

Tapping on the "Ask the community" button while outside AAQ flow takes the user to the first step, of selecting a product, on AAQ flow. 
If a product is already selected, tapping on the "Ask the community" button will redirect to ASk your Question form.
