### ISSUE TITLE
Research "Other Mozilla products" page

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#407]
Currently in the AAQ when choosing a product you have the option to select "Other Mozilla products" which links to Seamonkey and Lightning support. As part of the redesigned AAQ flow we need to re-evaluate this page:

- Should we keep this page? Why?
- What should this link to?
- Are there any common themes in the Fx forums that indicate possible non-supported products that we could link to?

**Comment by jess-cook03** [comment]
Do we add Pocket or any other products or link to other services here on the ‘other products’ page ?

**Comment by jess-cook03** [comment]
@madasan @akatsoulas @LeoMcA 
Since this is still WIP ---->
for the release can we hide this / remove this 'other product' selection from the 1st step of aaq for now?

**Comment by akatsoulas** [comment]
Sorry I missed that. The `Other Products` link has been removed from the new AAQ.

**Comment by jess-cook03** [comment]
Backlog for v2 of AAQ

**Comment by akatsoulas** [comment]
Closing this issue as stale
