### ISSUE TITLE
Move login page to step 3 of AAQ

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#408]
As discussed in today's design review, we should move the login step to just before step 3 of the AAQ rather than before step 1, since step 2 has multiple paths to the KB and authentication isn't required to browse that.

@jess-cook03 we were pushed for time at the end, so I didn't think to ask, should we modify the authentication page at all when presented as part of the AAQ flow? Currently the user will see this:

![Screenshot_2020-04-30 Log In Sign up Mozilla Support - 127 0 0 1](https://user-images.githubusercontent.com/755354/80733782-14029680-8b06-11ea-9f1e-367e038c15ef.png)

Perhaps, at the very least, we should show the AAQ progress bar above?

**Comment by jess-cook03** [comment]
@jonichan within the AAQ flow we would like to edit some of the copy within this screen, something that speaks to asking a question, letting users know they will return to enter their question afterward signing in/signing up. 

Any thoughts on new copy for this?

**Comment by LeoMcA** [comment]
From poking around in the FxA code in kitsune, I realised new users are redirected to their profile settings after logging in rather than where they were before. In AAQ that's very disruptive, because they're completely torn out of the flow, so we'll need to fix that too.

**Comment by jonichan** [comment]
Suggested copy:
"Never miss an answer. A free Firefox Account lets you view your question history and track or post responses."

This message is open-ended enough for both contributors and question-askers as well as notifcation method (i.e. email vs notification)

**Comment by akatsoulas** [comment]
The copy will be dealt with in issue 425

**Comment by mirunacurtean** [comment]
Confirmed in Dev environment after testing with Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10 and also on Android/iOS devices. 
Tested flow with existing account and also created a new account as well. 
After clicking on the "Ask Now" button the user is directed to "Log in/ Sign up with Firefox Account"  page and after sign in the AAQ form page is reached, as expected.  Account is signed in and profile name is displayed alongside avatar .

**Comment by mirunacurtean** [comment]
Depends on https://github.com/mozilla/sumo-project/issues/429 and should be retested when 429 is fixed in order to ensure no regressions have been introduced.

**Comment by mirunacurtean** [comment]
#429 will be deployed directly to stage so I am setting this as ready to deploy from dev with the note @mirunacurtean  to re-test when both tickets have been pushed to stage.
