### ISSUE TITLE
Change "select product" to "change product" when passed

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#409]
As discussed in today's design review, once a user has passed the "select product" step of the AAQ, we should change that text to "change product" in the progress bar.

**Comment by mirunacurtean** [comment]
Change applied as expected across Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10 and Android/ iOS devices.
Tested by selecting Get Help> Ask the Community and selecting a product card and also verified that "Change product" is shown when clicking/ tapping on links like Get Help> Ask the Community> Firefox Browser. 
"Change Product" string is applied for the rest of the AAQ flow. 

![Select product to change product applied ](https://user-images.githubusercontent.com/53306802/81407225-b42e7000-9143-11ea-8189-1c43cd3d0b48.gif)
