### ISSUE TITLE
Explore / Product based download buttons, contextual

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#412]
Product download buttons — per product pages - consistent treatment/uniform.

Research & then discover some solutions for how we would want to reccomend this potentially to product teams.

- where would they be placed? how are they treated across product? how do these download prompts work with fx download button?

- Are we able to know contextually what products users already have or dont have and be smart about the products we prompt them to download?

- could this be more than a button? a banner? an inpage module? something else?

**Comment by jess-cook03** [comment]
Backlog item --- need to see what product team comes up with their OKRs and focuses for H2 -- could be opportunity to collab on this as well as other opportunities.

 
Carrying this over into this ticket -- initially this is what sparked this conversation :
- [ ] Links to download across different devices - making sure these links are going to the correct places, contextually... (ie Android goes to Firefox for Android, etc)

**Comment by akatsoulas** [comment]
Closing this issue as stale
