### ISSUE TITLE
Explore / editing questions (forum + AAQ)

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#413]
Plans for tagging within AAQ question form input? Have preloaded tags — priority when could this be implemented ? Tags/topics/etc?

- edits to question form in aaq flow and also to the editing mode for questions within the forum

- changing tags and topics? who does this? how often are they doing it? identify these use cases.

- Discuss at the sumo team whole platform meeting

**Comment by akatsoulas** [comment]
Closing this issue as stale
