### ISSUE TITLE
"This account is not active" error message is received when trying to sign up/ sign in in the same session on FF Stage

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#415]
CC: @akatsoulas , @LeoMcA 

Affected platforms:
Windows 10 64-bit
Android 8.0.0

Firefox version:
76.0 (20200429185419) on Stage 
Firefox 68.7.0

Does not occur on Chrome. 

**Steps to reproduce:**
1. Load https://support.allizom.org/en-US/. 
2. Click on Sign In/Up button and proceed through the Sign up flow with a new account. 
3. Verify account. 

Expected result: 
Account is signed in, and user profile is visible. 

**Actual Results:**
The "This account is not active. Please contact an administrator if you believe this is an error" error message is received. 

**Note: When I try to sign in in the same session I receive the same error.  If I restart the browser  I can manage to sign in using the previously created account.** 

![Sign up error](https://user-images.githubusercontent.com/53306802/81081987-4ee83e00-8efb-11ea-98bc-568d8e978e91.gif)

**Comment by mirunacurtean** [comment]
Occurs again on stage environment when trying to login with new or existing accounts 
![image](https://user-images.githubusercontent.com/53306802/82454056-ff3c7180-9ab9-11ea-9c59-9c8e6baa7ff8.png)
![image](https://user-images.githubusercontent.com/53306802/82454252-31e66a00-9aba-11ea-9639-9a3d0e5a4de5.png)
Tested on Windows pro 10 64-bit and Mac OS X 10.14 on FF and chrome browsers.

**Comment by mirunacurtean** [comment]
These are the errors received on stage in the page's console log 
![image](https://user-images.githubusercontent.com/53306802/82454700-bfc25500-9aba-11ea-8bcd-cc55121a6d3b.png)

**Comment by Toad-Hall** [comment]
This bug effected me today. 18th June 2020
Windows 10 64bit
Using FF77.01 64bit

I was active and logged into Thunderbird Support forum responding to a question, when I clicked on 'Post a Reply', I was suddenly kicked out of forum and cannot log back. I'm seeing identical issue. Created a bug report in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1646717

Restarting FF had no effect. Signing out of FF account and resigning in had no effect.

**Comment by mirunacurtean** [comment]
@Toad-Hall 
Thank you for the detailed bugzilla report and also for updating this issues. It was closed due not not being to reproduce it anymore. 
I've retested on both production https://support.mozilla.org and staging https://support.allizom.org with new and existing accounts and have posted replies to questions successfully so unfortunatelt I could not reproduce. 

Tested this on Windows pro 10 on FF  77.0.1 (64-bit) and Chrome  83.0.4103.106 and also on Android 9.0 on FF and Chrome browsers. 

![Post reply without getting signed out](https://user-images.githubusercontent.com/53306802/85120843-7c2f4800-b22c-11ea-940d-ba56f69f8182.gif)

Could you please provide the email address of the account you have trouble logging in with?

**Comment by akatsoulas** [comment]
This issue is only related to the staging instance of SUMO and we believe it's related to infrastructure changes that happened only in staging for testing. This issue might still valid but it's not related to the deactivation events that occurred in the production environment.

**Comment by mirunacurtean** [comment]
Closing this as it has not been reproduced and the account deactivation was due to the restrictions implemented by the anti-spam measures. 
See: https://support.mozilla.org/en-US/forums/contributors/714221?utm_campaign=forums-post&utm_medium=email&page=3&utm_source=notification#post-78805
