### ISSUE TITLE
AAQ / design tweaks for question form page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#418]
@LeoMcA @akatsoulas 
Take a look at the notes inside this screenshot:
![Screen Shot 2020-05-06 at 12 10 34 PM](https://user-images.githubusercontent.com/54991698/81205135-4560e380-8f98-11ea-8496-03282609f0a2.png)

**Comment by jess-cook03** [comment]
Here is the example of what the bottom of the page with the buttons should look like:
<img width="633" alt="Screen Shot 2020-05-06 at 12 04 47 PM" src="https://user-images.githubusercontent.com/54991698/81224096-26bd1580-8fb5-11ea-8f2e-8c5f7f5df4f6.png">

**Comment by jess-cook03** [comment]
3rd step on progress bar needs copy change, instead of 'create question' it should read: 'Ask question'
![Screen Shot 2020-05-06 at 4 19 28 PM](https://user-images.githubusercontent.com/54991698/81224297-7e5b8100-8fb5-11ea-8e5b-68a092189044.png)

**Comment by jess-cook03** [comment]
Also @LeoMcA @akatsoulas this edit/text input (used in forums as well)
I think having the user be able to stretch the box to the right over the 2nd column of the page is a bit jarring. If they do this they also cover the content we have on that sidebar and it breaks the structure of the page layout.
Can we fix this to only allow the user to drag and enlarge the box length and not the box width?
Thoughts on this?
![Screen Shot 2020-05-06 at 12 07 20 PM](https://user-images.githubusercontent.com/54991698/81225511-59680d80-8fb7-11ea-9ccd-bd178a652070.png)

**Comment by ovidiuboca1** [comment]
@jess-cook03 we tested this on desktop and mobile everything looks ok, except the fact that the "Cancel" and "Post a question" have a different position on mobile comparing with desktop, here is a print screen from a mobile device.
![processed](https://user-images.githubusercontent.com/54845678/81670947-0d064d00-9451-11ea-81b5-f2fff8f62bcf.jpeg)
Please let us know what is the desired display on mobile devices.

**Comment by jess-cook03** [comment]
@ovidiuboca1 thanks for flagging this! 
@LeoMcA @akatsoulas I would say, we should have the mobile buttons follow the same order as desktop that would be ideal! Post question on right as the primary action, and cancel on left. 👍

**Comment by LeoMcA** [comment]
We'll follow up on this site wide in: https://github.com/mozilla/sumo-project/issues/434

Moving this to ready to deploy
