### ISSUE TITLE
AAQ email notification of responses 

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#419]
<img width="633" alt="Screen Shot 2020-05-06 at 12 04 47 PM" src="https://user-images.githubusercontent.com/54991698/81200315-ccf72400-8f91-11ea-8905-2777a7aa23f3.png">

@akatsoulas @LeoMcA 
Spoke about this in design review today: general thoughts are to keep it there in the question form and also have it in the settings as well for users to then opt out if they choose.
Other things that need to be considered here are as follows:

- [x] having it auto selected when submitting a question (like we have it now) or optional. There is good rationale to keep it pre-selected as most users at that point will likely skip over it if we dont, and then there is a fear that users will not then know how/where to follow up on their question.

- [ ] can be there a time limit to when notifications for old posts stop? does your subscription to getting emails/notifications expire after the forum post goes stale for a while?

- [ ] Need to confirm if there is currently an email system for when a user gets a response to their question? if something already is in place, we need to refine the copy and content inside those emails. 
Side note is the addition of having a confirmation email after your question is submitted in the aaq flow itself. Which could hopefully come in v2

**Comment by jess-cook03** [comment]
Email templates are outdated this is something we can look at for v2.

**Comment by akatsoulas** [comment]
Closing this issue as stale
