### ISSUE TITLE
AAQ / copy updates for step 2, solutions page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#420]
@LeoMcA @akatsoulas 
Primary updates to this page are copy/content related:

- [x] cta for ask the community widget should be ' Ask Now '

- [x] under the search bar should read: 'Enter your question or keywords to find solutions in the knowledge base or forms'

- [x] 'popular articles' to become ' Featured Articles '

See design mock below:
<img width="810" alt="Screen Shot 2020-05-06 at 4 22 01 PM" src="https://user-images.githubusercontent.com/54991698/81224759-36892980-8fb6-11ea-91bf-87b4566dcb86.png">

**Comment by jess-cook03** [comment]
Also please see here the spacing needs to increase between the section title for topics and the topic cards, right now they are crunched together:
![Screen Shot 2020-05-06 at 11 55 07 AM](https://user-images.githubusercontent.com/54991698/81224845-54568e80-8fb6-11ea-8ed5-ac3f74c0f927.png)

**Comment by mirunacurtean** [comment]
Updates applied as expected across Firefox 76 and Chrome 81 on Mac OS X 10.14 and Windows 10 and Android/ iOS devices. 
![image](https://user-images.githubusercontent.com/53306802/81406918-22befe00-9143-11ea-972d-05986f66dec8.png)
