### ISSUE TITLE
AAQ / copy, content changes to step 1, product selection page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#421]
@LeoMcA 

- [ ] change 'see all product forums' to same copy as in the navigation menu : 'Browse All Product Forums'
![Screen Shot 2020-05-06 at 11 56 38 AM](https://user-images.githubusercontent.com/54991698/81225200-d777e480-8fb6-11ea-9f7c-469f2682d682.png)

- [ ] Hide/remove 'Other mozilla products' card for now
![Screen Shot 2020-05-06 at 4 30 42 PM](https://user-images.githubusercontent.com/54991698/81225270-f2e2ef80-8fb6-11ea-91b9-e53b17e47e2b.png)

**Comment by ovidiuboca1** [comment]
This issue was tested on the dev environment on desktop Mac OS X 10.14 and Windows 10 and mobile device Android and iOS and I can confirm the fix.
