### ISSUE TITLE
Using nav bar search box doesn't work in AAQ

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#422]
Using the search box in the sticky nav in the AAQ doesn't work, in various different ways in each step:

Step 1:

![Screenshot_2020-05-07 Ask a Question Mozilla Support - support-dev allizom org](https://user-images.githubusercontent.com/755354/81300771-043c0280-9070-11ea-8567-31bff4a54148.png)

Step 2:

![Screenshot_2020-05-07 Ask a Question Mozilla Support - support-dev allizom org(1)](https://user-images.githubusercontent.com/755354/81300780-0aca7a00-9070-11ea-82e6-194ee1e12a56.png)

Step 3:

![Screenshot_2020-05-07 Ask a Question Mozilla Support - support-dev allizom org(2)](https://user-images.githubusercontent.com/755354/81300807-15850f00-9070-11ea-936a-2a8584628a24.png)

**Comment by ovidiuboca1** [comment]
We tested this on desktop Mac OS X 10.14, Windows 10 and mobile Andriod and iOS using the Firefox and Chrome and we can confirm the fix, on all three aaq steps the search nav bar is working.
