### ISSUE TITLE
AAQ / open in new tab - all content accessible from step 2, solutions page

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#423]
When selecting anything -- article, thread, or topic in the solutions page... we should have it open in a new tab so it doesn't take over the flow for the user and they can easily return/understand they are not necessarily taken out of the flow.

Same goes for anything user selects from search as well.

**Comment by mirunacurtean** [comment]
This works as expected. Tested across Windows PRO 10, Mac OS X 10.14 and on android and iOS mobile devices using Firefox, Chrome and Safari browsers.
