### ISSUE TITLE
AAQ / Widget design fixes

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#426]
![Screen Shot 2020-05-06 at 12 18 25 PM](https://user-images.githubusercontent.com/54991698/81231258-dcda2c80-8fc0-11ea-8c54-c7a17cd713a3.png)

@LeoMcA 

- [x] Button CTA change to 'Ask Now'

- [x] For users who are logged in, when they go through the flow, can the copy here change conditionally? ...it doesn't need to say sign in/up to post your question to those users, so instead we could drop that and say something like - 'Continue to post your question and get help."

- [x] Functionality wise: are we able to have this widget follow the users when they click an article, thread or topic?

**Comment by LeoMcA** [comment]
Decision from today's stand-up:

Make this follow 1-level deep for now, we can iterate on this in future versions.

Add a GA event to see how users interact with this button.

**Comment by mirunacurtean** [comment]
@LeoMcA 

While testing in stage we have encountered several issues:
1. On Android on FF browser, when opening a featured article or topic or search result - the Ask the Community widget is not present at the top of the page as expected. 
![Android FF and Chrome discrepancy](https://user-images.githubusercontent.com/53306802/81804919-a3ef0a00-9522-11ea-8f8d-b2efa72ac248.gif)


2. On mobile, while compared to Desktop, when opening Find help search results the widget is not present. 
![mobile search results no widget](https://user-images.githubusercontent.com/53306802/81805330-5626d180-9523-11ea-8f47-a3d27a694eb3.gif)


3. on Windows and Android (but not on macOS) if you're not signed in and in the AAQ Explore solution step you search ofr a topic and then open a posted question thread then it can be seen that the Ask the Community Widget is not available. 
![Should widget show for question threads when not signed in](https://user-images.githubusercontent.com/53306802/81805522-ab62e300-9523-11ea-87cc-b820a7310d1f.gif)

4. tested across desktop and mobile we noticed that the widget does not show on a new tab if the articles/ post has already been opened in a tab with a copied url. See steps and video:

1.Go to https://support.allizom.org/en-US/questions/new/desktop -> 
2. Click on any article/topic ( in a new tab the page is opened and also the widget is visible) 
3. Copy the url and open a new tab and past the copied url (the page is open but the widget is not displayed) 
4. Close this tab
5. Go to the tab from the step 1 and open again another article/topic or search result (the page is opened in a new tab but the widget is not displayed)
NOTE: doesn't matter if you are logged in or not

![Widget disappears when opened in copied url](https://user-images.githubusercontent.com/53306802/81806032-8d49b280-9524-11ea-8078-017ed2565238.gif)

**Comment by LeoMcA** [comment]
1+2 should be fixed with https://github.com/mozilla/kitsune/pull/4378

3 stumped me for a while, I'm sure it happens across all platforms (so including macOS), but *only* when you click on a question from search (I was busy clicking kb articles and topics) - we don't have the logic in that page yet, so I'll have to fix that with another PR.

4 is "intended" behaviour, or more a known limitation of the approach we've taken (which depends on the referer header) so we won't be fixing this in this iteration.

**Comment by mirunacurtean** [comment]
Verified fixed on Desktop on Chrome and Firefox and on mobile on android and iOS across FF, chrome and safari browser.
