### ISSUE TITLE
[AAQ] Posted question  shows with great delay on My Questions list

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#427]
**Affected platforms:**
MacOS X 14.0
Windows 10 64-bit
Android 8.0.0

**Firefox version:**
76.0 on Dev environment
Firefox 68.8.0
Chrome 81

**Precondition:** 
Create account and sign in on either dev or Stage

**Steps to reproduce:**

1. Go to **https://support-dev.allizom.org/en-US/** or **https://support.allizom.org/en-US/**
2. Navigate to Get Help> Ask the Community and select a product card. 
3. From the Ask the Community widget click on "Ask Now" and reach the AAQ form. 
4. Enter valid data in the required fields and click on "post question"
5. Once the green banner that confirm the successful posting appears click on the "My questions" link and view questions list.

**Expected results:**
The posted question is rendered successfully in the My Questions> All products list

**Actual Results:**
Even after refreshing the page, sign out and sign in from the user account or accessing the My Questions through the Profile> My Questions link, the question list is not updated with the most recently posted question. 
The question is posted with significant delay, over 1 hour on stage and several hours on some cases on dev.

![question Not listed ](https://user-images.githubusercontent.com/53306802/81394254-55103180-912a-11ea-944e-ae23f2e9feab.gif)

**NOTE: Question posted on mobile was only just listed in My questions after a 40 minute delay.**

**Comment by akatsoulas** [comment]
This is working in prod. Closing
