### ISSUE TITLE
[AAQ] "Page not Found" message shows at click on Get Help> Ask the Community link on FF browser

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#428]
**Affected platforms:**
Android 8.0.0

**Firefox version:**
Firefox 68.8.0

**Steps to reproduce:**
1. Go to https://support-dev.allizom.org/en-US/. 
2. Tap on the hamburger menu icon right next to avatar icon. 
3. Select "Get Help" > Ask the Community" 

**Expected results:**
https://support-dev.allizom.org/en-US/questions/new / "Ask the Community > Which product do you need help with?" page should be loaded. 

**Actual Results:**
"Page not found" result is received. 

Note: This issue does not occurs on Chrome browser on the same android device. 

![Page not found](https://user-images.githubusercontent.com/53306802/81399172-38c4c280-9133-11ea-8940-4bfa30e609ac.gif)

**Comment by akatsoulas** [comment]
This is happening only in the dev cluster because the DB either is missing a product (Firefox Preview) or the slug for Firefox for Android was not the right one. This is not an issue related to the AAQ. Both products have been fixed in the DB.
