### ISSUE TITLE
Mobile / Topics - child topics are showing underneath parent selector

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#432]
I thought we addressed this previously? Might be a regression, not sure -- or is this something we discussed about wanting to change and punted to v2.....? Either way I wanted to file it as an issue.

Currently in mobile the parent topic selector is showing the child options, when user can use the other tabs and 'more' dropdown to select the child topics. See image
![Screen Shot 2020-05-11 at 4 54 39 PM](https://user-images.githubusercontent.com/54991698/81611150-8dbd3e80-93a8-11ea-8d4d-815302ff8afe.png)

**Comment by jess-cook03** [comment]
@LeoMcA @akatsoulas take a look when you get the chance.

**Comment by LeoMcA** [comment]
Removing this should be relatively quick and easy, but I'm a little hung up on the fact that its implementation seems very intentional - the child products (in this dropdown/sidebar) are only shown on mobile, they're hidden on larger screen sizes.

So just to clarify: the child products should only be shown in the tabs and "more" dropdown and nowhere else?

**Comment by jess-cook03** [comment]
@LeoMcA I would say yes. Child products should only be shown in the tabs and 'more' dropdown and nowhere else.

But since this has been out now for a while .... I would like to inform this decision with some user feedback... as in ... I'm trying to think of ways we could gather data on this, how users are using it now? If possible. Do they know to go to 'More' to see the rest? Thats my only draw back.

I would say lets discuss with @akatsoulas @madasan and see what their thoughts are as well.

My main point/concern for changing it is just make the experience more seamless... not having duplicate interactions/info in the same instance/page... not the end of the world. Double access to the child topics may be a good thing to keep in mobile sizes.
