### ISSUE TITLE
Global change of buttons order on tablet/mobile

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#434]
@akatsoulas @LeoMcA 
Global change:
Anytime across the site we have two buttons stacked together like the forums or aaq question form we should have the mobile buttons follow the same order as desktop.
Post question on right as the primary action, and cancel on left. 👍

Rule of thumb all primary buttons/actions fall to the right - secondary on the left.

See the image below to see an example of what needs to be switched:
![Screen Shot 2020-05-13 at 9 26 17 AM](https://user-images.githubusercontent.com/54991698/81818673-565fa680-94fc-11ea-9191-8bdfa0f264ea.png)

**Comment by LeoMcA** [comment]
On mobile should buttons expand to the full width of the screen?

Like this (but with the order reversed):

![Screenshot from 2020-05-13 14-41-20](https://user-images.githubusercontent.com/755354/81819988-ea933300-9527-11ea-81f4-4c51e7a5a92d.png)

**Comment by jess-cook03** [comment]
@LeoMcA yes thats fine + order reverse! 👍

**Comment by akatsoulas** [comment]
Closing as there are no plans to work on this at the moment
