### ISSUE TITLE
The Modify date from a question is not updated after the edit 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#436]
Tested on staging on Mac OS X 10.14 with Firefox release 76 and Chrome browsers. 

STR: 

1. Go to a question that was posted by you (or use an admin account and choose what question you want) and needs to be older than 1 month (15.5.2020) before the new aaq flow was implemented.
2. Click on "Edit this question"
3. Edit the question
4. Click on "Save Question"
5. Observe the date that is posted at the bottom of the question, look for "Modify" and compare the date that is displayed with the date when the edit was made. 

ER: The dates should be the same.
AR: The date is not updated. 
After some time and some other edit actions on the question, I saw that the date is changed to the correct one.
I did soma changes in 15 of May and here is the actual date that was displayed - 
<img width="580" alt="Screenshot 2020-05-15 at 12 41 34" src="https://user-images.githubusercontent.com/54845678/82039544-cfeac680-96ad-11ea-8bc7-915ce6ebf465.png">

NOTE: The issue is reproducible also on production. 
CC @LeoMcA

**Comment by akatsoulas** [comment]
Fixed in prod
