### ISSUE TITLE
An error occurs if the "Invite to share screen" button is clicked 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#437]
Tested on staging on Mac OS X 10.14 with Firefox 76 release and Chrome browsers. 

STR: 
Prerequisites: You need to use and account that has admin privileges. 

1. Go to https://support.allizom.org/en-US/questions/1207029
2. Click on "Invite to share screen” button 
3. Post the invite.
4. From the same question click again on "Invite to share screen"

ER: The reply form is open and you can post the invite. 
AR: The "An Error Occurred" message is displayed. 
<img width="916" alt="Screenshot 2020-05-15 at 13 34 44" src="https://user-images.githubusercontent.com/54845678/82041409-cdd63700-96b0-11ea-902d-130f40a6eb8e.png">
CC @LeoMcA

**Comment by LeoMcA** [comment]
@akatsoulas I seem to remember us discussing that we should just remove this link and functionality. Considering the link mentions Firefox Hello in the pre-composed message, I guess my memory is correct.

**Comment by mirunacurtean** [comment]
Verified fixed.  
'Invite to share screen' option no longer shows on question threads and functionality no longer exists. 
Tested across Windows pro 10 64-bit, macOS 10.14 and Android 9.0 on Firefox / Safari browsers. 
https://support.allizom.org/en-US/questions/1207029 was already archived so this was verified on questions previously posted before the changes and new ones, using regular contributor and moderator accounts. The invite options is not available for question owners nor contributors who post a reply.
https://support.allizom.org/en-US/questions/1207117
https://support.allizom.org/en-US/questions/1207118
