### ISSUE TITLE
Hide featured articles for Firefox Focus

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#440]

**Comment by mirunacurtean** [comment]
Verified that hiding Featured articles on Firefox Focus works as expected on both Firefox Focus Support and Solutions pages and no errors are received when changing the locale to languages such as fr, de and It.
https://support.allizom.org/en-US/questions/new/focus
https://support.allizom.org/en-US/products/focus-firefox

Tested across Windows PRO 10 with 64-bit and Mac OS X 10.14 and iOS and Android mobile devices on FF, Chrome and Safari browsers.
