### ISSUE TITLE
Direct support // Premium services user flows

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#442]
We need a clear idea on how premium support integrates with sumo and what are the correct user flows we should implement

**Comment by jess-cook03** [comment]
Latest direct support experiences flow documentation is [here](https://www.figma.com/file/V5Yo3L3BPh7kvBCKdfj8JB/Direct-Support_Experience-Journey-Analysis?node-id=0%3A1)

**Comment by akatsoulas** [comment]
Closing this issue as stale
