### ISSUE TITLE
Move "Moderate Forum content" under the tools section.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#445]
There is a proposal from the community in the form of a PR to move the `moderate forum content` under the tools section. @jess-cook03 @jonichan can you please provide some feedback on this proposal?

Proposed change: https://github.com/mozilla/kitsune/pull/4315

**Comment by jess-cook03** [comment]
@akatsoulas I can confirm with Joni that yes -- we should make this change.
After reviewing the issue.... we are okay with moving the 'Moderate Forum Content' link to the Tools section of the navigation as suggested.

I didn't realize this was viewable only to moderators -- so I was unable to see the issue at first.
All good --- I say go ahead and allow the PR.

**Comment by mirunacurtean** [comment]
@akatsoulas 
This should be under Contributor Tools> Tools, no?
Have not seen it yet on either desktop or mobile.
![No Moderate form content link](https://user-images.githubusercontent.com/53306802/83531439-a88d5980-a4f5-11ea-8d25-ebee90b7b42b.gif)

**Comment by mirunacurtean** [comment]
@akatsoulas Further Update 
- double checked with Ovidiu and on his devices (MAc and iMac) on FF and Chrome he can see the link in the Tools section and it redirects to this link https://support.allizom.org/en-US/flagged. The account used is mozillatest1234@yahoo.com. 
- On neither of my devices, Windows, Mac or android - has the "Moderate Forum Content" link shown up. I am logged in with mcurtean4@mailinator.com, if it helps investigate this. 
When testing on FF I've cleared all browsing data and created a new account to sign up with but I still cannot see the link. 
Are there any preconditions that should have been achieved?

**Comment by LeoMcA** [comment]
@mirunacurtean apologies, that'll be because you're not a Forum Moderator. I added your `mcurtean+1@mozilla.com` account to the Forum Moderators group on staging, so you should be able to see the link with that account now.

**Comment by mirunacurtean** [comment]
@LeoMcA Awesome. I see it now. Should it have been localized for all languages?

**Comment by LeoMcA** [comment]
It's possible that it hasn't been localised into any language yet, as I believe the string was introduced in Responsive Redesign.

**Comment by mirunacurtean** [comment]
Alright, thanks. It is already localized in DE, FR, ES but not in AR so I was wondering if it should have been. 
Confirmed that link is available when logging in with moderator account on Windows (FF and Chrome, MAC (FF and Safari) and mobile android (FF and Chrome). Redirect is performed towards https://support.allizom.org/en-US/flagged.
