### ISSUE TITLE
[Python3 upgrade] Adding a question in Dev environment results in 500 error

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#454]
**Affected platforms:**
Windows 10 64-bit
Android 8.0.0

**Browser version:**
77.0 on Dev environment
Firefox 68.6.0
Chrome 83.1

**Precondition:** 
Create account and sign in on either DEV

**Steps to reproduce:**

1. Go to https://support-dev.allizom.org/en-US/questions/new/desktop
2. From the Ask the Community widget click on "Ask Now" and reach the AAQ form. 
3. Enter valid data in the required fields and click on "post question".

**Expected results:**
Question is posted. Successful green banner is displayed. 

**Actual Results:**
500 Internal server error is received. 
Initially, when double checking My question, the questions is not listed, but after a while (at most 30 minutes) it will be added to the result list. 
![android 500 error when posting a question](https://user-images.githubusercontent.com/53306802/83725490-b0aadd80-a64a-11ea-9495-845559fd922d.gif)

![image](https://user-images.githubusercontent.com/53306802/83725546-c6200780-a64a-11ea-81fd-06233be19626.png)

Note: The Second post might be done due to refreshing the internal error page.

**Comment by LeoMcA** [comment]
Looks like another celery issue, let's re-test after that upgrade is done.

**Comment by LeoMcA** [comment]
@mirunacurtean looks like this is fixed, can you confirm?

**Comment by mirunacurtean** [comment]
@LeoMcA Cheked on both Desktop and mobile and while the internal server error is no longer received now I get the Access denied message as a results - see gif. 
Account used is mcurtean+2@mozilla.com. 

![Access denied when trying to post question](https://user-images.githubusercontent.com/53306802/83880474-dd90ea80-a747-11ea-906e-cf051451f51b.gif)

**Comment by mirunacurtean** [comment]
Re-tested this today on Desktop and mobile and I can successfully add a new question. 
![image](https://user-images.githubusercontent.com/53306802/84131061-bcccdb80-aa4c-11ea-9fd6-6671f85e76dd.png)

**Comment by mirunacurtean** [comment]
This issue has started occurring again.  The Questions are not posted at all. 
When pressing the "Post Question" button the page that loads contains the " An error has occured" message. 
![image](https://user-images.githubusercontent.com/53306802/86118649-cc829180-bad9-11ea-9b07-3f8a4c4643a5.png)

**Comment by LeoMcA** [comment]
@mirunacurtean I think this is just a misconfiguration on dev, rather than a py3 issue. Posting under Focus with the iOS topic works on dev: https://support-dev.allizom.org/en-US/questions/1251016, and on staging posting under Focus with the Android topic (what you tried above) works: https://support.allizom.org/en-US/questions/1207085

**Comment by mirunacurtean** [comment]
@LeoMcA Thank you for the examples. I double checked as well on dev and stage and the issues seems to be only on dev when choosing the Firefox Focus for Android topic.  That being said, it become rather obvious that it's not a python3 issue since it's not occurring in stage as well after merge.
