### ISSUE TITLE
[Python3 upgrade] Trying submit an article results in 500 internal server error on dev environment

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#455]
**Affected platforms:**
Windows 10 64-bit
Android 8.0.0

**Browser version:**
77.0 on Dev environment
Firefox 68.6.0
Chrome 83.1

**Precondition:** 
Create account and sign in on DEV

**Steps to reproduce:**

1. Go to https://support-dev.allizom.org/en-US/kb/new
2. Fill in required fields with valid info. 
3. Select Submit for Review.

**Expected results:**
Article is submitted to review and while content is not available until approved it can still be accessed.

**Actual Results:**
500 Internal server error is received.

![ChromeAdding an article results in 500 error](https://user-images.githubusercontent.com/53306802/83727342-91fa1600-a64d-11ea-810a-7114ef9bcc48.gif)

**Comment by LeoMcA** [comment]
Looks like another celery issue, this should be retested once we've upgraded.

**Comment by LeoMcA** [comment]
Looks to me like this has been fix, @mirunacurtean can you confirm?

**Comment by mirunacurtean** [comment]
Confirmed fixed on Windows 10, Mac 14.10 and mobile Android 9 on FF, Safari, and respectively, Chrome. 
![Article submitted fix ](https://user-images.githubusercontent.com/53306802/83877088-96ecc180-a742-11ea-80d6-e87c9daa63ac.gif)
