### ISSUE TITLE
[Python3 Upgrade] Edit profile results in blank page when updating multiple fields on dev environment

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#456]
**Affected platforms:**
Windows 10 64-bit
Android 8.0.0

**Browser version:**
77.0 on Dev environment
Firefox 68.6.0

**Precondition:** 
Create account and sign in on either DEV

**Steps to reproduce:**

1. In https://support-dev.allizom.org/en-US/ go to  View Profile> Edit Profile. 
2. Update multiple fields info or input info into clear ones and modify drop down menu info. 
3. Select to Update.

**Expected results:**
Redirect to My profile page where the info has been correctly updated. 

**Actual Results:**
After some processing, a blank page loads. 
When refreshed, the My profile page where the info has been correctly updated loads. 

![Edit profile results in blank page when updating multiple fields](https://user-images.githubusercontent.com/53306802/83734916-4ef17000-a658-11ea-86fb-4afa83c623eb.gif)

**Comment by LeoMcA** [comment]
@mirunacurtean looks like this is now resolved due to the partial celery update, can you confirm?

**Comment by mirunacurtean** [comment]
Re-tested on Windows and Android on Ff and Chrome and on macOS on Safari and it works smoothly now. 
![Edit profile fix](https://user-images.githubusercontent.com/53306802/83873473-8b969780-a73c-11ea-8cee-3f45714d4121.gif)

Marking is as closed.
