### ISSUE TITLE
Point Respond to Fenix Beta ID

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#458]
We're planning to organize a campaign for answering Play Store reviews via Respond for Fenix Beta starting with June 15. 

For this we need to point respond.mozilla.org to the right Play Store ID so that we can start pulling in Fenix Beta reviews.

**Comment by LeoMcA** [comment]
Quickly looking at this at the end of day, looks like we just have to add a new Application instance with the correct play store ID to fetch reviews for it:

https://github.com/mozilla/m-response/blob/2a41b1184619c9056f02d84539a4dbb60ca2eb97/mresponse/reviews/management/commands/fetch_reviews.py#L125-L127

I guess we also need to remove the old application to ensure we don't pull in reviews for it? What do we do with the reviews and responses associated with that application?

**Comment by akatsoulas** [comment]
This is now fixed. Respond points to the Fenix Beta. Also archive functionality has been added which hides the non active Application from the tool
