### ISSUE TITLE
[Pyhton3] When posting a new thread in forum an internal server error is received

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#464]
**Affected platforms:**
Windows 10 64-bit
Android 8.0.0
macOS 14.10.6

**Browser version:**
77.0 on Dev environment
Firefox 68.6.0
Chrome 83.1
Safari

**Precondition:** 
Create account and sign in on DEV

**Steps to reproduce:**

1. Go to https://support-dev.allizom.org/en-US/forums/l10n-forum or 
https://support-dev.allizom.org/en-US/forums/social-media  or 
https://support-dev.allizom.org/en-US/forums/contributors. 
2. Select to Post a new thread.
3. Fill in 'Create a new thread' Title and Content fields and Post Thread.

**Expected results:**
Thread has been submitted and can be viewed as the latest post, right after, in the chosen forum. 

**Actual Results:**
500 Internal server error is received.
When return to chosen forum it can be seen that the thread is listed in it and that the title and content on it are correct. 

![Posting a thread on social support forum](https://user-images.githubusercontent.com/53306802/83851128-9a6c5280-a71a-11ea-9f38-d010766fb97f.gif)

![Thread is posted despite 500 error](https://user-images.githubusercontent.com/53306802/83851148-9f310680-a71a-11ea-8406-94251556852b.PNG)

**Comment by LeoMcA** [comment]
Looks like the server is timing out while trying to connect to celery, and then throwing the 500. We should retest this after the celery upgrade is done on dev.

**Comment by LeoMcA** [comment]
Looks like this is resolved, @mirunacurtean can you confirm?

**Comment by mirunacurtean** [comment]
@LeoMcA  While the error is no longer received now I'm blocked by this "You have exceeded the number of threads and replies that can be posted in a given amount of time. Please try again shortly. " response. 
![image](https://user-images.githubusercontent.com/53306802/83880937-a111be80-a748-11ea-8757-0e695a0a9318.png)

**Comment by mirunacurtean** [comment]
Re-tested today and managed to add new posts from both Desktop and mobile successfully.
Also edited post, locked and deleted threads.
