### ISSUE TITLE
Version control Respond common responses

### ISSUE THREAD

**Issue by rtanglao** [mozilla/sumo-project#478]
Instead of using a Google Doc, could we please use a version controlled document for canned responses? This way, we can do pull requests any time we want to update it and all the normal git behaviour and see the history, etc.

**Comment by SeburoSUMO** [comment]
I think this would be a very useful and practical feature (as it has been in the first iteration of the tool) to enable necessary quick edits to common responses, to write new common resposes as required and remove old content without needed developer support.
