### ISSUE TITLE
Cannot post file names, preferences or replies containing certain punctuation marks due to anti spam measures

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#482]
**Affected platforms:**
All

**Environment:** 
Production   suport.mozilla.org
Stage support.allizom.org

**Preconditions:**
Create a contributor account. 

**Steps to reproduce:**
1. Go to SUMO product forum and select any of them, for example https://support.allizom.org/en-US/questions/firefox
2. Select a question to reply to. 
3. In the 'Post a Reply"  post a message that contains a file name, a preference or any text that makes use of a dot.
Ex: keyword.enabled 
userChrome.css
“test.”

**Expected result:** 
Reply is posted successfully and the text is displayed as was intended. 

**Actual Results:**
Reply is not posted and "Links are not allowed in the forums" error message is displayed as a response. 

![image](https://user-images.githubusercontent.com/53306802/85427364-54214b00-b584-11ea-8223-c9c06b8f7e7e.png)

![image](https://user-images.githubusercontent.com/53306802/85427489-7c10ae80-b584-11ea-9464-80dcb357b700.png)

Notes:
1. This issue does not apply to moderator accounts as they have been allowed to post links and as such it does not apply the same restrictions overall. 
2. This issue was created to keep track of and retest when needed issues brought up by user's feedback such as:
 https://support.mozilla.org/en-US/forums/contributors/714221?utm_campaign=forums-post&utm_medium=email&page=2&utm_source=notification#post-78746

**Comment by mirunacurtean** [comment]
Related bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1647091

**Comment by LeoMcA** [comment]
PR merged: https://github.com/mozilla/kitsune/pull/4427

**Comment by mirunacurtean** [comment]
Verified fixed on stage environment across desktop on Windows pr 10 64-bit and Android 9.0 on Ff and Chrome browsers. 
Responses following the something.anything format are no longer marked as spam and file names and preferences and abbreviations can be posted successfully. 
ex: https://support.allizom.org/en-US/questions/1207045#answer-1082361
