### ISSUE TITLE
Add scam banner to private messages

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#485]

**Comment by mirunacurtean** [comment]
Verified it shows on both Desktop and mobile. The banner is dismissed when selecting the "x" button. Learn more button redirected when clicked to corresponding article,https://support.mozilla.org/en-US/kb/avoid-and-report-mozilla-tech-support-scams,  as expected
![Spam banner in private messages](https://user-images.githubusercontent.com/53306802/85751195-08e97280-b713-11ea-90b5-5172a107c36d.gif)
