### ISSUE TITLE
Automatically add the is_spam in replies under certain criteria

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#489]
These will trigger the results described in https://github.com/mozilla/sumo-project/issues/483 for non-moderators or users not in the trusted contributors group:

* [NANP numbers](https://en.wikipedia.org/wiki/North_American_Numbering_Plan)
* Toll free numbers
* [Links](https://github.com/mozilla/sumo-project/issues/482)

PR: https://github.com/mozilla/kitsune/pull/4426

**Comment by mirunacurtean** [comment]
My strategy here was to create a question thread for each type of account and try to reply using the same NANP or toll free numbers and links. Responses that trigger the anti-spam measures are marked as spam and hidden so they can only be viewed using a moderator account. 

Contributor account replies:
https://support.allizom.org/en-US/questions/1207076

Trusted contributor account replies:
https://support.allizom.org/en-US/questions/1207077#answer-1082423

Moderator account replies:
https://support.allizom.org/en-US/questions/1207078#answer-1082398

As for links, outside the verification of issue #482 I've also verified using these and provided the results:
- insert support article - can be added by all types of accounts
- insert external link (example.com) - can only be added using a moderator account 
- add a common response   - responses that contain non-mozilla links can only be posted by moderator accounts
- https://www.mozilla.org/  - can be posted by all types of accounts
- [[Troubleshoot Firefox issues using Safe Mode]]  - can be posted by all types of accounts
- 'Test address donate@mozilla.org' message   - can only be posted by moderator account
- Sumo link posted without link insertion https://support.mozilla.org/en-US/questions/new   - can be posted by all accounts
- ex ending with use of TLD: layout.display-list.retain.chrome  - can only be posted by moderator account.

@akatsoulas As far as what should be posted only by regular contributors or moderators behave as expected but for the trusted contributor account (mcurtean+2@mozilla.com) the same rules as for a regular contributor account apply, meaning that some responses are marked as spam. To my understanding this is not supposed to occur - could you please verify?

**Comment by akatsoulas** [comment]
The fix for the trusted contributors is deployed in staging. The permission that we were queyring against needed update.
