### ISSUE TITLE
Automatically remove is_spam flag 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#491]
If a reply is removed from the moderation queue as valid (not spam) by a moderator, we should also remove the is_spam flag automatically in order to make it visible in the thread.

**Comment by LeoMcA** [comment]
Updated the moderation docs to reflect this change: https://docs.google.com/document/d/1iEQiVOQm9FE9ioYdtYh_XQ0mj3olaW9na1nObQK8C-I/edit

**Comment by mirunacurtean** [comment]
Tested successfully across windows pro 10 on FF and Chrome and Android 9.0. 
When the status update is set to "The flag is invalid", making the reply valid the "Marked as spam" flag is removed at page refresh on moderator account thread and on a regular user account thread the reply is visible and does not display the "Marked as spam" flag either.
