### ISSUE TITLE
Make 'a moderator must approve your post' message a warning

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#492]
https://github.com/mozilla/kitsune/pull/4431

Makes it a bit more visible, should now appear as a yellow message rather than a grey one.

**Comment by mirunacurtean** [comment]
Verified on both Desktop and mobile (Windows, MacOS and Android) across FF and Chrome browsers and Safari browsers and the warning shows as expected and the user is directed to it when trying to post a message that is marked as spam. 
The warning colour is yellow and. no layout issues occur and the banner can be dismissed successfully.
