### ISSUE TITLE
Contributor Project // Changes to URLs, slugs, and page naming structures

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#493]
As part of the contributor onboarding project the team hopes to re-work the page titles and naming that would also mean changing the URLs to match this.

The suggested/desired renaming would be as follows: 
<img width="659" alt="Screen Shot 2020-06-25 at 3 21 11 PM" src="https://user-images.githubusercontent.com/54991698/85785663-84d5c180-b6f7-11ea-8e24-2f7fd8e23294.png">

As per discussion, we are proposing to wrap this into the changes that will happen within the IA milestone.

**Comment by jess-cook03** [comment]
@jonichan would you be able to take a look at these from an IA and copy perspective ? No timeline for this as of right now.
Just would like to keep it on your radar as well.

**Comment by akatsoulas** [comment]
Closing this issue as stale.
