### ISSUE TITLE
Contribution Areas, individual child page designs

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#494]
Link to design file is [here](https://www.figma.com/file/5cpK7svIqTV45t5xQx1YDz/Contributor-Onboarding-Explorations-Working-File?node-id=0%3A1) 

Each contribution area has its own landing page. Users can navigate here via the flyout menu, the contribute home page, or from the onboarding flow and vice versa.

Each page will share the same template, only the content differs between pages.

**Comment by jess-cook03** [comment]
Link to final production ready designs in Figma 👉 [HERE](https://www.figma.com/file/FrX6SzjObAUpPJHSsIlj2N/Contributor-Onboarding-Production-File?node-id=1%3A3) 👈

**Comment by akatsoulas** [comment]
Closing this issue as stale
