### ISSUE TITLE
'Contribute' Home page designs

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#495]
Link to design [production ready file is here](https://www.figma.com/file/FrX6SzjObAUpPJHSsIlj2N/Contributor-Onboarding-Production-File?node-id=1%3A2)

Volunteer / Future-'Contribute' home page designs.

We have registered and non-registered view for this page. Content changes between the two.

Content document is [here.](https://docs.google.com/document/d/1DYOBe_ZCnlqjiTpMb41_cF3NrqD_7pC3gMrX8nNzHwU/edit?usp=sharing)

**Comment by akatsoulas** [comment]
Closing this issue as stale
