### ISSUE TITLE
'Contribute' navigation flyout menu

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#496]
Link to design file is [here.](https://www.figma.com/file/5cpK7svIqTV45t5xQx1YDz/Contributor-Onboarding-Explorations-Working-File?node-id=60%3A629)
New flyout menu to be added underneath the 'volunteer' (future 'contribute') part of the navigation.

We have 3 potential options for how the content/info can be organized
See image below:
<img width="553" alt="Screen Shot 2020-06-25 at 3 46 22 PM" src="https://user-images.githubusercontent.com/54991698/85788473-0a0ea580-b6fb-11ea-8a8e-1eacc0e07a3e.png">

Depending on how we can manipulate the flyout menu within the protocol design system -- ie are we able to alter this component to have it be a 2/3 - 1/3 layout instead of the usual 3 column layout? This would be for desktop sizes only -- mobile will stay as is.

If not it will just follow the default layout like the rest of the menus for desktop and mobile.

**Comment by jess-cook03** [comment]
Link to production ready designs in Figma 👉 [HERE ](https://www.figma.com/file/FrX6SzjObAUpPJHSsIlj2N/Contributor-Onboarding-Production-File?node-id=0%3A1)👈

**Comment by akatsoulas** [comment]
Closing this issue as stale
