### ISSUE TITLE
Registration modals (contributor sign up)

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#497]
Link to design file is [here.](https://www.figma.com/file/5cpK7svIqTV45t5xQx1YDz/Contributor-Onboarding-Explorations-Working-File?node-id=0%3A1)

These represent the registration onboarding flow for when a user is registering or signing up as a contributor.
These slides are introductions and are non-dismissable.
Each of the text links that are present in various modals here will all open in a new tab if the user decides to click on any of them. 
This modal is used within PMO for reference.

**Comment by jess-cook03** [comment]
Link to production ready designs in Figma 👉 [HERE ](https://www.figma.com/file/FrX6SzjObAUpPJHSsIlj2N/Contributor-Onboarding-Production-File?node-id=1%3A4)👈

**Comment by akatsoulas** [comment]
Closing this issue as stale
