### ISSUE TITLE
Profile indicator of contribution status

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#498]
This is WIP -- this will be a new piece of UI within the existing profile and profile pages.

**Comment by jess-cook03** [comment]
Link to production ready designs in Figma 👉 [HERE ](https://www.figma.com/file/FrX6SzjObAUpPJHSsIlj2N/Contributor-Onboarding-Production-File?node-id=1%3A5)👈

**Comment by jess-cook03** [comment]
Same as ticket #499 looping these together

**Comment by akatsoulas** [comment]
Closing this issue as stale
