### ISSUE TITLE
Profile settings, opt in/out of contributor status + contribution areas of interest checkboxes (multi-select)

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#499]
Toggle opt in-out of contributor in settings page -- -also with this add affordance to check multiple contribution areas or areas of interest to collect data that can be used in the future

**Comment by jess-cook03** [comment]
Link to production ready designs in Figma 👉 [HERE](https://www.figma.com/file/FrX6SzjObAUpPJHSsIlj2N/Contributor-Onboarding-Production-File?node-id=1%3A5) 👈

**Comment by akatsoulas** [comment]
Closing this issue as stale
