### ISSUE TITLE
Send an email notification when a post in the moderation queue is approved.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#501]

**Comment by AliceWyman** [comment]
Related bug report, filed today: https://bugzilla.mozilla.org/show_bug.cgi?id=1665113

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4700

**Comment by mirunacurtean** [comment]
@LeoMcA [Test cases](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=1890517993&range=B4:B10) so far, as I might need to update this list. These should cover the basic use cases and I added several cases for forum threads as well.

**Comment by LeoMcA** [comment]
The spam check isn't implemented for community forum threads, so I haven't done those test cases. I did the AAQ tests involving email notifications, and all but two passed - but those failures were expected, to me - I'll let you confirm.

**Comment by mirunacurtean** [comment]
Yes, Looks good to me. Thank you for your work.
