### ISSUE TITLE
Optimise image assets

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#506]
https://bugzilla.mozilla.org/show_bug.cgi?id=1646357

I'll just run svgo against any *.svg files, and optipng against any *.png files.

**Comment by mirunacurtean** [comment]
Verified on stage (https://mresponse-staging.herokuapp.com/) on Windows pro 10 on FF and Chrome and on macOS 10.14.6 on Safari. The image has been optimized. 
![Image being optimised ](https://user-images.githubusercontent.com/53306802/87424851-63287580-c5e5-11ea-96b3-ee727bf91a03.png)
