### ISSUE TITLE
"Get Troubleshooting" button broken on prod

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#507]
Clicking the button just causes the field to disappear:

![Peek 2020-07-02 10-18](https://user-images.githubusercontent.com/755354/86340858-746c9c00-bc4d-11ea-880a-d07f6f080718.gif)

Looking through the DOM, the field doesn't seem to be just hidden but totally deleted. The about:support info isn't anywhere to be seen.

The about:support API still works (when triggering it from devtools) so this is probably just a selector issue.

**Comment by mirunacurtean** [comment]
@LeoMcA  Button is now on Desktop (Windows 10, on Firefox and Chrome) but it  does not work the way the way it is explained in  the text below it. "A window will open in the top corner. Click Allow, and then click Install."  Also, selecting "try these manual steps" only redirects to user to the top of the page. 
Is this working differently in stage from the way it is supposed to in production?
![Desktop Share data ](https://user-images.githubusercontent.com/53306802/87146237-4f160880-c2b3-11ea-8f19-8a6ab9f2783b.gif)
A second concern is that the button does not show on mobile at all in Stage or DEV environment- checked on two android devices on Firefox (version 68.10.1). At this point I am unsure if it did show up before, so I wanted to confirm with you. Is it supposed to be available on mobile as well? 
![Mobile no SHARE data button](https://user-images.githubusercontent.com/53306802/87146594-debbb700-c2b3-11ea-823d-72912d635516.JPEG)

**Comment by LeoMcA** [comment]
> but it does not work the way the way it is explained in the text below it

Yes, that text is wrong and confusing, I'll open a PR to update it.

> Is it supposed to be available on mobile as well?

The field should only appear on /questions/new/desktop/form. But confusingly it'll appear even when there's no chance of getting that data (like in Chrome), I'll open a PR to fix that as well.

**Comment by LeoMcA** [comment]
@mirunacurtean with my last PR I've updated the behaviour a bit, I still need to deploy it to staging.

The "show info" link is removed, and the textbox should just be shown when a user clicks "Share Data". If we successfully get data, it should just be shown in the box. If not, we should show a message saying we couldn't with a link (that works) to the KB article explaining how to get the data manually.

> Is it supposed to be available on mobile as well?

This should only be shown under the Firefox Desktop AAQ form, but for all browsers. So, for instance, if you visit the Desktop AAQ on Mobile or Chrome, you'll see the button, but the message described above saying that we couldn't get the data should be shown if you click on it.

You'll also need to follow these instructions on how to enable the Remote Troubleshooting API for staging, so that it has permissions to actually fetch the data: https://github.com/mozilla/kitsune/blob/98f9ce40f6ac85ea3fd0f68336466a1a64e833ca/docs/browser_permissions.md#remote-troubleshooting-aboutsupport-api (and if you notice anything wrong or confusing in that doc, please let me know!)

**Comment by mirunacurtean** [comment]
Managed to test this using the temporary remote troubleshooting solution  on Windows with Firefox. Thanks so much @LeoMcA 

![Share data in Stage](https://user-images.githubusercontent.com/53306802/89038902-d94d0c00-d349-11ea-84f2-dbfcd661fdac.gif)

Also confirmed that when using clicking/ tapping on the Share Data button in Chrome or on mobile (Android 9.0.0) from the desktop page https://support.allizom.org/en-US/questions/new/desktop/form, the "We can't automatically get your browser's troubleshooting data, please [try these manual steps](https://support.mozilla.org/en-US/kb/use-troubleshooting-information-page-fix-firefox)." message will show instead. 
![Could not show data in Chrome and KB link](https://user-images.githubusercontent.com/53306802/89039149-3a74df80-d34a-11ea-84b4-4d3f60aae8df.gif)
