### ISSUE TITLE
 User is asked to enter Name and Language 2 times in the sign up flow 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#515]
**STR:**
1. Login to respond.mozilla.community with a new unused email
2. Fill in your name in "Name" input field and click "Next"

**Expected:**
It shows step 2 out of 2

**Actual:**
It shows step 2 out of 3. 
After tapping Finish, user is asked to enter name and language again.

![photo_2019-07-11_16-21-32](https://user-images.githubusercontent.com/5293100/61056556-39e66f80-a3fc-11e9-9f4f-994d86cb90c9.jpg)

**Comment by mirunacurtean** [comment]
Verified this by creating a new google account (skipped capturing that).
![Respond sign up fix](https://user-images.githubusercontent.com/53306802/87161462-3e728c00-c2cd-11ea-8f43-f121d892c2b0.gif)
