### ISSUE TITLE
[Enhancement]:  Reject the response as soon as the moderation received doesn't meet minimum requirements to be approved

### ISSUE THREAD

**Issue by rleitan** [mozilla/sumo-project#519]
[STR]:
1.Go to moderate and select "No" for Does this response feel friendly? 
2.Select feedback for "technically accurate" and "Would you reuse this response" 
3.Submit

[Expected result]:
The response should be automatically rejected ( currently it is rejected only after 3 moderations)

[Actual result]:
The response is marked as rejected only after 3 moderation, but the minimum requirements are not met from step 1

@madasan, thoughts?

**Comment by LeoMcA** [comment]
https://github.com/mozilla/m-response/blob/d1e146afba9da97d4d85dcc784e23e0090748379/mresponse/moderations/tests/test_create_moderation_api.py#L138
