### ISSUE TITLE
Can not access to the full content of long questions in Moderate view

### ISSUE THREAD

**Issue by Mozinet-fr** [mozilla/sumo-project#522]
When the content of a long question exceeds the box in Moderate view, it is impossible to access it with the mouse or keyboard.

![2019-12-11 13_49_03-Outils de développement - Mozilla_ Respond - https___respond mozilla community_m](https://user-images.githubusercontent.com/8845401/70631562-a1b01900-1c2d-11ea-84a5-7175646789bf.png)

Firefox 71, Windows 7

**Comment by LeoMcA** [comment]
Fixed and deployed to prod.
