### ISSUE TITLE
Login from pages that requires login redirects to HomePage, instead of the initial page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#53]
**STR:**
1. Navigate to https://support.allizom.org/en-US/questions/new
2. Click "Log in / Sign up" button
3. Enter your fxa credentials

**Expected:**
User is redirected to the initial page https://support.allizom.org/en-US/questions/new

**Actual:**
User is redirected to HomePage https://support.allizom.org/en-US/

**Note:**
This happens for all locales
Other pages that encounter this issue:
https://support.allizom.org/en-US/forums/contributors/new 
https://support.allizom.org/en-US/kb/new
https://support.allizom.org/en-US/messages/new?to=MA_ma
https://support.allizom.org/en-US/messages 
https://support.allizom.org/en-US/kb/firefox-page-info-window/edit
https://support.allizom.org/en-US/kb/get-started-firefox-overview-main-features/edit/152007

**Comment by akatsoulas** [comment]
This is deployed to prod
