### ISSUE TITLE
[Python Upgrade][DEV] Email notification links redirect to about:blank new tab instead of question thread

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#530]
**Affected platforms:**
Windows 10 64-bit
Android 8.0.0

**Browser version:**
FF Release 78.0.1
Firefox 68.10.0
Chrome 83.0.4

**Environment:** 
DEV

Preconditions. 
Create and login with account A and post a question in one of the product sections. AAQ form: https://support-dev.allizom.org/en-US/questions/new/desktop/form
Create and login in with a regular contributor account B.
Create account C and login on a different browser or profile.

With both account A and B navigate to Get Help section search in the expected forum for the question posted by account A.

**Steps to reproduce:**
 
1. With account B go to the question thread posted by account A and select from Question Tools to Get mail> when anybody replies. 
2.With account C go to the question thread posted by account A and post a reply. 
3.Verify account B's inbox and view email notification received. 
4. Select to "Post a Reply". 

**Expected results:**
Links (buttons) that are found in the email notifications should, when selected, redirect to the new tab containing the question thread.

**Actual Results:**
New tab loads an about:blank page which times out after loading for a while. 

Note: This also occurs when account B is subscribed to receive an email notification when a solution is chosen. 
Clicking on "view solution" link from the email notification opens and about:blank new tab. 

![Email notifications links are not redirecting to question thread](https://user-images.githubusercontent.com/53306802/86853267-d9e1e200-c0be-11ea-8106-a2a8f8415560.gif)

**Comment by LeoMcA** [comment]
This was a misconfiguration on dev, the emails it was sending had links to "support-local.allizom.org", now they link to "support-dev.allizom.org".

**Comment by mirunacurtean** [comment]
Re-tested in dev. I can confirm the redirect now works as expected and the question thread is opened in the last used browser. 
![image](https://user-images.githubusercontent.com/53306802/86926039-42ba7000-c13a-11ea-86e4-d6604642deb1.png)
![image](https://user-images.githubusercontent.com/53306802/86926093-52d24f80-c13a-11ea-81a0-fbd6b155fb5c.png)

Tested for both 'Post a Reply' and 'View the solution' redirects.
