### ISSUE TITLE
[Python Upgrade] Flagging a user results in 500 error when trying to access Moderate Forum Content page

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#534]
**Affected platforms:**
Windows 10 64-bit
Android 9.0

**Browser version:**
FF Release 78.0.1
Firefox 68.10.0
Chrome 83.0.4

Environment:
Stage

**Precondition:** 
Be logged in with a moderator account so that Contributor Tools> Moderator Forum Content link is available. 
Create a secondary test account. 

**Steps to reproduce:**

1. With the moderator account search for the secondary test account's profile (can be found through community hub search)
2. Once on the secondary's account profile page select to Report Abuse. 
3. Send abuse report. 
4. Go to https://support.allizom.org/en-US/flagged in order to view reported spam. 

**Expected results:**
Moderator Forum Content page is loaded and last spam report is added in the spam list.

**Actual Results:**
"An Error Occurred" message after the page is loaded. 

![report abuse and error](https://user-images.githubusercontent.com/53306802/86929610-b3fc2200-c13e-11ea-84ea-d46c56d2df39.gif)

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4449 should fix this

**Comment by mirunacurtean** [comment]
Verified fixed on Stage on Windows 10 and Android 9.0. 
Tested with all report Abuse options and also verified that updating the status in Moderate Forum Content dismissed the report from the list. 
Once a user has reported another user, they cannot flag them again. The "You already flagged this content" message is received, however, another user can freely do so.  
![Profile report abuse invalid](https://user-images.githubusercontent.com/53306802/87149611-41638180-c2b9-11ea-8394-3ec5eb5abdfd.gif)
