### ISSUE TITLE
Update apple touch icon from old Firefox logo

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#540]
https://static-media-prod-cdn.itsre-sumo.mozilla.net/static/sumo/img/apple-touch-icon.png

This appears on the newtab page:

![Screen Shot 2020-07-10 at 17 54 52](https://user-images.githubusercontent.com/755354/87179336-7b8f4c00-c2d6-11ea-89ec-f811b60b049e.png)

**Comment by mirunacurtean** [comment]
Verified as updated on iPhone & (13.4.1) and Android 9.0. 
![apple touch icon in newtab page](https://user-images.githubusercontent.com/53306802/87547922-78200a00-c6b4-11ea-9f0e-cf737466bcdf.png)
