### ISSUE TITLE
Update Popular searches for Mozilla VPN KB

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#541]
Since the FPN extension and Mozilla VPN are now separate products, I'd like to change the popular searches that appear in https://support.mozilla.org/en-US/products/firefox-private-network-vpn to the following:

Manage devices
Download VPN
Limits

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/4465

**Comment by mirunacurtean** [comment]
Verified in stage environment on Windows pro 10 on FF and Chrome and macOS 10.14.6 on Safari on multiple locales (en, fr, de, es, cs)
Popular searches are not present on product page on mobile on either stage or production.

![image](https://user-images.githubusercontent.com/53306802/88056707-a6e12900-cb69-11ea-91de-127708f2a4a0.png)
