### ISSUE TITLE
Update popular searches for FPN

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#542]
I'd like to update the popular searches for FPN Browser extension (on this page: https://support.mozilla.org/en-US/products/firefox-private-network)  to the following:

Activate add-on
Update add-on
Manage devices  (same)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/4465

**Comment by mirunacurtean** [comment]
Verified in stage environment on Windows pro 10 on FF and Chrome and macOS 10.14.6 on Safari on multiple locales (en, fr, de, es, cs)
Popular searches are not present on product page on mobile on either stage or production.
![image](https://user-images.githubusercontent.com/53306802/88056282-fc690600-cb68-11ea-92ea-72c7fb73b466.png)

There are no featured articles or search results for popular searches for this product in stage.
