### ISSUE TITLE
Update spam banner text

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#544]
https://bugzilla.mozilla.org/show_bug.cgi?id=1647741

**Comment by mirunacurtean** [comment]
Verified that new copy is present throughout the AAQ flow and on the product support forum pages as well. Tested on Windows pro 10 and Android 9.0 on FF and Chrome browsers. 
Banner and english copy are displayed even when changing the locale in support forum pages. 
'Learn more' button redirects to the expected page: https://support.mozilla.org/en-US/kb/avoid-and-report-mozilla-tech-support-scams
banner can be closed but will show up again when user logs out/ logs in. 
![anti scam banner new copy](https://user-images.githubusercontent.com/53306802/88053075-e9076c00-cb63-11ea-9722-631e48577646.gif)

![aaq flow new banner copy](https://user-images.githubusercontent.com/53306802/88053101-f3296a80-cb63-11ea-8376-fdc42f9b7194.gif)
