### ISSUE TITLE
Update product descriptions in AAQ 

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#545]
1. See https://support.mozilla.org/en-US/questions/new.

Some of the products are showing the product name in their description (Mozilla VPN, Firefox Preview, Firefox Lockwise, Firefox Private Network Browser Level)

Expected result: Show the same product descriptions as the ones that appear on the KB product tiles: https://support.mozilla.org/en-US/

**Comment by akatsoulas** [comment]
Related PR
https://github.com/mozilla/kitsune/pull/4464

**Comment by mirunacurtean** [comment]
From the ticket description it can be understood that the request applies to all product descriptions on the AAQ product tiles. 
There is one minor difference remaining, highlighted in the attached screenshots. 
https://support.allizom.org/en-US/questions/new
![image](https://user-images.githubusercontent.com/53306802/88055259-55379f00-cb67-11ea-9104-fceec2499f5b.png)

https://support.mozilla.org/en-US/
![image](https://user-images.githubusercontent.com/53306802/88055350-83b57a00-cb67-11ea-8ee3-854407388da3.png)

@akatsoulas Could this also be updated on stage?

**Comment by akatsoulas** [comment]
This should have been closed as it's already deployed in prod. @mirunacurtean probably it will get updated with the next push.
