### ISSUE TITLE
An internal error is received when trying to edit or access various articles's links

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#551]
**Affected platforms:**
Windows 10

**Browser version:**
Firefox Release 78.0.2

**Environment:**
Production  - issue reported first in Production https://support.mozilla.org/en-US/forums/contributors/714366?utm_campaign=forums-thread&utm_source=notification&utm_medium=email
Stage

**Precondition:** 
Be signed in. 

**Steps to reproduce:**

1. Go https://support.allizom.org/en-US/kb/install-older-version-of-firefox
2. From Editing Tools select to Edit Article. 
3. Select the "See history" hyperlink. 
4. Return back to edit page and add a new line to the content table and Submit Review. 

**Expected results:**
User is redirected to view edit history and any edit done to the article can be successfully submitted to review. 

**Actual Results:**
"An error occurred"/ 500 Internal server error is received when trying to perform steps 3 and 4. 

![Install an older version Edit error](https://user-images.githubusercontent.com/53306802/88543498-b9070f80-d020-11ea-8e2d-0a143e3e4b42.gif)

**Notes: Successfully seen history and edited other articles in stage.** 
ex: https://support.allizom.org/en-US/kb/test-article-number-3/edit
https://support.allizom.org/en-US/kb/stage-test-owl/edit
https://support.allizom.org/fr/kb/add-french-article/edit

Update:  Also occurs  when trying to access [Markup cheat sheet](https://support.mozilla.org/en-US/kb/markup-cheat-sheet) article History.

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4483

**Comment by AliceWyman** [comment]
Kiki wrote in https://support.mozilla.org/en-US/forums/contributors/714366 _This happened to https://support.mozilla.org/en-US/kb/firefox-preview-upgrade-faqs/history as well. The devs said that it relates to the redirect setting. And changing the slug seems to solve it for now._

I changed the slug from /install-older-version-of-firefox to /install-older-version-firefox but it didn't help. I still can't view https://support.mozilla.org/en-US/kb/install-older-version-firefox/history

**Comment by kelimuttu** [comment]
Hey @mirunacurtean, @AliceWyman finds a way to approve the changes through a direct link https://support.mozilla.org/en-US/forums/contributors/714366?last=79239#post-79237. Can we approve it now or should we wait for it to pass QA?

**Comment by mirunacurtean** [comment]
@kelimuttu @AliceWyman Hello. I also say to approve it if it can be, because currently the fix is pending deploy to stage still, and QA will also take a little while.

**Comment by kelimuttu** [comment]
Great! It should've been approved by now.

**Comment by mirunacurtean** [comment]
Looks good to me now. 
Tested across Desktop (Windows pro 10 with FF Release 79.0 and Chrome 84.0.4147 and macOS 10.14.6 on Safari) and mobile (Android 9.0.0 on FF 68.11.0). 

Tested with Regular contributor account:
Article> Edit Article> See history 
Article Revisions, Editor and Edit comment. 
Article> Show history 
Redirect from Recent Revisions page 

With moderator account: 
Article> edit Article > See history 
Article> edit article > edit content > Preview changes > Submit for Review
Article> Show history > status review  > Unreviewed versions links. 
Article> Show history > status review > Review particular change> Defer change 
Article> Show history > status review > Review particular change > cancel review
Article> Show history > status review > Review particular change > Approve review
Article> Show history > Delete revision 
Article> Translate Article > Approved translation. 

Links and page links redirects tested:
https://support.allizom.org/en-US/kb/install-older-version-of-firefox/edit
https://support.allizom.org/en-US/kb/install-older-version-of-firefox/history
https://support.allizom.org/en-US/kb/markup-cheat-sheet/edit
https://support.allizom.org/en-US/kb/markup-cheat-sheet/history
https://support.allizom.org/en-US/kb/markup-cheat-sheet/revision/157507/delete
https://support.allizom.org/en-US/kb/revisions
https://support.allizom.org/en-US/kb/test-article-number-3/edit
https://support.allizom.org/en-US/kb/Installing%20a%20previous%20version%20of%20Firefox/history

Translated
https://support.allizom.org/ca/kb/install-older-version-of-firefox/translate
https://support.allizom.org/ca/kb/test-translate-article-ca
https://support.allizom.org/ca/kb/test-translate-article-ca/edit


![Edit and see history from article page](https://user-images.githubusercontent.com/53306802/89034606-fd0c5400-d341-11ea-88f0-59bf41a2ef37.gif)


NOTES: I could not find the article Firefox preview upgrade FAQS in stage but considering that the other links and actions work, I am counting on this working as well in prod. 
https://support.mozilla.org/en-US/kb/firefox-preview-upgrade-faqs
 or https://support.mozilla.org/en-US/kb/firefox-preview-upgrade-faqs/history
