### ISSUE TITLE
Report for GA release

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#552]
We need a report to monitor GA release via the Respond tool. The report should have the following segments:

1. Number of reviews fetched from the Play Store in the last 24 hrs

2. % of responded reviews in 72 hours (% of reviews in Respond that have been replied to and uploaded back in the Play Store). This should be reported separately for EN, ES and DE

3. number of active contributors /week. An active contributor = a minimum of 5 responses and 15 moderation done in a week.

**Comment by akatsoulas** [comment]
Basic reporting has been released to prod. New issues will be opened if any more work is required on reporting.
