### ISSUE TITLE
Edit profile -- change input fields

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#555]
Edit profile fields some of them are no longer being used, can we replace them with more relevant links?

Community team would like to make changes to the following fields:
![Screen Shot 2020-07-30 at 4 03 41 PM](https://user-images.githubusercontent.com/54991698/88970176-f4534980-d27f-11ea-810b-89249fd05900.png)

**Comment by mirunacurtean** [comment]
Verified as changed in Stage on Windows pro 10 with FF and Chrome and on Android 9.0 on FF browser. 
The fields have been updated to: 'Community Portal Username', 'People Directory Username' and 'Matrix Nickname'. 
Adding, updating or erasing the username info (username, profile page links) adds/updates/removes the corresponding fields and info from the My profile section as well. 
![Profile fields update](https://user-images.githubusercontent.com/53306802/91825681-3f78c780-ec45-11ea-904e-34f48c29d3ac.gif)
