### ISSUE TITLE
Remove services endpoint from the project

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#556]
The following URLs are removed
* services/error
* services/monitor
* services/version

**Comment by mirunacurtean** [comment]
Confirmed that URLs are removed and manually entering them results in a 404 page not found. 
Tested on desktop (Windows pro 10 FF 79.0 (64-bit) and Chrome 84.0.4147.105 and macOS 10.14.6 on Safari) and on mobile (Android 9.0.0 and iPhone 13.4.1 on Firefox)
![image](https://user-images.githubusercontent.com/53306802/89022526-db53a280-d32a-11ea-848a-8b2f7d917363.png)
