### ISSUE TITLE
[Volunteer] 'An error occurred' when signing up from "Pick a way to get involved" links and at first sign in the "this account is not active" banner is displayed

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#563]
**Affected platforms:**
Windows 10 64-bit
Android 9.0.0

**Browser version:**
FF Release 79.0
FF 68.11.0

**Environment:** 
Stage and Production

**Steps to reproduce:**
1. Go to https://support.allizom.org/en-US/get-involved
2. Select any of the hyperlinks from the "Pick a way to get involved" section. 
3. Navigate to and select the "Sign me up" button. 
4. Create a new account and verify it. 

**Expected results:**
User is signed in with new account and is redirected to Homepage. 
Successful green banner is displayed with working links to account profile and support article. 

**Actual results:**
"An error occurred' message is received and account is not signed in (as evidenced by the Sign up button".  Green banner links redirect to login page. 
When trying to login with newly create account for the first time, the red warning banner with ""this account is not active. ..." message is displayed. 
Account is successfully and error free logged in on the second try. 

![Create account error ](https://user-images.githubusercontent.com/53306802/89410073-bb0d5480-d72b-11ea-9c3f-194788d8a1be.gif)

**Comment by jess-cook03** [comment]
@madasan @mirunacurtean 
This is something I want to flag as maybe putting in product review or team review in relation to the contributor onboarding work (when we are able to implement it) and in general the account creation (sign in/up) redirects. 
I'm questioning the expected results here.

**Comment by mirunacurtean** [comment]
@jess-cook03  Unless it's considered a priority to get it fixed before any of the work you've mentioned is implemented (contributor onboarding or general account creation redirects) the expected results can be updated, as far as I am concerned.

**Comment by mirunacurtean** [comment]
@mirunacurtean Re-test #308  when this is fixed.

**Comment by mirunacurtean** [comment]
Confirmed fixed. Successfully created sumo accounts using mozilla and non-mozilla emails from Volunteer pages. 
The accepted criteria for this has changed, as the user should not be redirected to homepage after account creation, but expected to remain on the same page where they have selected so sign up. See #308. This works as expected, 

![create account from volunteer pages](https://user-images.githubusercontent.com/53306802/98017319-bd08b180-1e07-11eb-809f-74c2651e2086.gif)

Verified successfully on both desktop (windows pro 10) and mobile (Android 9.0.0) across Firefox and Chrome browsers. 
Tests performed are documented [here](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=0&range=A13:A19).
