### ISSUE TITLE
Some FPN articles aren't showing up in their topics

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#564]
Some FPN articles aren't showing when you browse to their topic. 

STR:
1. Go to https://support.mozilla.org/en-US/products/firefox-private-network
2. Click on any of the topics.
3. Some articles are missing from list view.

However, when you do a search for Private Network, the missing articles show up in search results. Here are the topics and their missing articles: 

**Technical**
- https://support.mozilla.org/en-US/kb/firefox-private-network-free
- https://support.mozilla.org/en-US/kb/which-browsers-work-firefox-private-network
- https://support.mozilla.org/en-US/kb/install-uninstall-firefox-private-network-extension
- https://support.mozilla.org/en-US/kb/what-countries-will-firefox-private-network-extens
- https://support.mozilla.org/en-US/kb/what-permissions-does-firefox-private-network-requ
- https://support.mozilla.org/en-US/kb/bad-request-error-firefox-private-network-extensio
-https://support.mozilla.org/en-US/kb/will-firefox-private-network-slow-down-my-browser
-https://support.mozilla.org/en-US/kb/how-do-i-turn-firefox-private-network-or
-https://support.mozilla.org/en-US/kb/how-do-i-update-firefox-private-network-extension
-https://support.mozilla.org/en-US/kb/video-calls-fpn
- https://support.mozilla.org/en-US/kb/change-my-ip-address-firefox-private-network
- https://support.mozilla.org/en-US/kb/how-do-i-sign-out-firefox-private-network
- https://support.mozilla.org/en-US/kb/website-problems-firefox-private-network

**Accounts**
- https://support.mozilla.org/en-US/kb/firefox-account-firefox-private-network
-https://support.mozilla.org/en-US/kb/firefox-account-firefox-private-network
- https://support.mozilla.org/en-US/kb/will-i-have-sign-firefox-private-network-same-fire

**Payments**
- https://support.mozilla.org/en-US/kb/how-much-does-firefox-private-network-cost

**Troubleshooting**
-https://support.mozilla.org/en-US/kb/firefox-private-network-crashes-file-transfer

**Comment by LeoMcA** [comment]
The issue was that when we renamed the topics, the articles which already existed within those topics weren't re-indexed in elasticsearch, and so didn't appear in the topic listing. Edited or newly added articles were indexed, so those were the ones appearing.

I triggered a re-index specifically for FPN articles with the following in `./manage.py shell_plus`:
```
In [1]: from kitsune.search.utils import to_class_path                                                                                      

In [2]: from kitsune.search.tasks import index_task                                                                                         

In [3]: from kitsune.wiki.models import Document                                                                                            

In [4]: from kitsune.products.models import Product                                                                                         

In [5]: index_task.delay(to_class_path(Document.get_mapping_type()), list(Document.objects.filter(category__in=settings.IA_DEFAULT_CATEGORIE
   ...: S, products=Product.objects.filter(slug="firefox-private-network").get()).values_list("pk", flat=True)))    
```

Everything seems to be appearing as expected now.
