### ISSUE TITLE
Update ES when indexed field is updated, in real time

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#565]
Ensure we update ES documents when fields are updated.

This includes denormalised fields, to avoid problems like this: https://github.com/mozilla/sumo-project/issues/564

We probably want to hook into the pre_save signal of all indexed and denormalised objects.

**Comment by akatsoulas** [comment]
this can be closed as done when we have smaller tasks for all of our indices.

**Comment by LeoMcA** [comment]
Done in https://github.com/mozilla/kitsune/pull/4590
