### ISSUE TITLE
Remove top_contributors_new and deps

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#574]
https://github.com/mozilla/kitsune/pull/4482

I think that's the last of our legacy react code gone.

Once in staging we should do some limited testing to ensure that the "Top Contributors" section under `/community` (and the pages it links off to) are unaffected.

**Comment by mirunacurtean** [comment]
Top contributors filtering by locale and Product are still working as expected and "See all" links along with selection of the contributor avatar icons redirects are not affected by changes. 
Tested on French and German localized community hub page as well.
