### ISSUE TITLE
Desktop Browser" item is missing from the Firefox section from the footer of the Support home page

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#58]
STR:

1. Go to Support home page
2. Scroll down the page and look over the Firefox section from the footer area. 

ER: There should be 5 items: Download, Desktop Browser, Android Browser, iOS Browser, Focus Browser
AR: The Desktop Browser is missing. 
Note: please see the print-screen for a better understanding. 
![Screenshot 2019-12-12 at 15 53 17](https://user-images.githubusercontent.com/54845678/70718587-287df800-1cf9-11ea-87dc-f4b322f331f3.png)

**Comment by kkellydesign** [comment]
I assume the "download" link replaced that, as the download button goes here: 

https://www.mozilla.org/en-US/firefox/new/?utm_campaign=footer&utm_medium=referral&utm_source=support.mozilla.org

@madasan, please confirm what you'd like this link to be, if it's necessary.

**Comment by jonichan** [comment]
The "Download" link should  be "Firefox Desktop" and it should link to that same link.

**Comment by kkellydesign** [comment]
This will go up with https://github.com/mozilla/kitsune/pull/4177

<img width="511" alt="Screen Shot 2020-02-13 at 2 19 59 PM" src="https://user-images.githubusercontent.com/202590/74470198-112fc800-4e6c-11ea-836b-5c48b9d42a20.png">

**Comment by kkellydesign** [comment]
This can be seen in the footer here: https://test.sumo.mozit.cloud/en-US/

**Comment by ovidiuboca1** [comment]
I verified this issue on Mac OS X 10.14 and Windows 10 and I can confirm the fix.
