### ISSUE TITLE
Simplify profile_avatar jinja helper

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#581]
`profile_avatar` in `kitsune/users/templatetags/jinja_helpers.py` has a lot of logic to handle non-fxa accounts. Since those should now all have been migrated, we should probably tear that logic out and simplify the logic here.

@akatsoulas thoughts? this might be a nice contributor issue

**Comment by akatsoulas** [comment]
Sounds good to me! This helper definitely needs some cleaning up

**Comment by akatsoulas** [comment]
Duplicate of #430
