### ISSUE TITLE
Local development/debug authentication method

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#583]
@finn0 pointed out that it's not possible to login as a non-superuser locally without FxA creds, because the admin interface will show an error.

We should add a non-fxa authentication method only available when DEV and DEBUG are true. Since it'll only be available locally I see no need to actually authenticate users, and instead we could just match on username, allowing you to log in as anyone, like:

```python
from django.contrib.auth import login

def debug_login(request):
    user = User.get(username=request.POST["username"])
    login(request, user)
    ... handle errors, redirect on success ...
```

I've had problems before wrestling with FxA while trying to log in as multiple users, so the ability to just enter their username and be logged in as them would be very useful.

@akatsoulas thoughts?

**Comment by akatsoulas** [comment]
How about changing the order of the Auth backends in case you are in a dev environment or if a flag is set?

**Comment by akatsoulas** [comment]
Tested this locally to login and it's working fine.
In staging it's returning a 404 as it should
https://support.allizom.org/en-US/user/akatsoulas/become

@mirunacurtean I am not moving this to the next column in case you would like to take a look.

**Comment by mirunacurtean** [comment]
Same for me in stage with https://support.allizom.org/en-US/user/SuperMC/become. Setting it as  Ready for Release.
