### ISSUE TITLE
Provide more report options for the respond tool.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#585]
After discussing with @kelimuttu through email, we need to expose the following metrics

- Total responses + breakdown per locale (published or not published)
- How many responses published coming from super moderator account as opposed to the normal moderation process if possible
- Reviews with a response awaiting community approval 
-  Reviews with a response awaiting staff approval 
- % of EN reviews answered in 72 hours
- % of DE and ES reviews answered in 72 hours

Metrics within 3 working days
- How many new users on Respond Tool
- How many contributors answered
- How many contributors performed reviews
- How many active (previous definition of active is still accurate) contributors.

**Comment by akatsoulas** [comment]
@kelimuttu please let us know if this is accurate or if there is anything missing

**Comment by kelimuttu** [comment]
Hi Tasos, 

Let me clarify my request. 

First, these following data are the P1 and I need them for the duration of the campaign (3-30 Aug):
* % of EN reviews answered in 72 hours
* % of DE and ES reviews answered
* Total new users on the Respond Tool 
* Total active contributors (at least 5 responses and 15 moderations in a week)

Then I also need the following data to further explore the effectiveness of moderation (also for the duration of the campaign): 
* Total responses + breakdown per locale (published or not published)
* Total reviews with a response awaiting community approval (+ breakdown pre locale)
* Total Reviews with a response awaiting staff approval (+ breakdown pre locale)
* How many responses published coming from super moderator account as opposed to the normal moderation process (only if it's possible)

I hope that clarifies everything.

**Comment by akatsoulas** [comment]
Thanks @kelimuttu for the clarifications. We are updating our queries to reflect the revised set of data.

**Comment by LeoMcA** [comment]
I've shared a google doc containing the data with you.

**Comment by kelimuttu** [comment]
Thanks, both! Much appreciated.
