### ISSUE TITLE
SUMO profile - UI changes and 404 error

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#586]
Opening new ticket to tackle Profile UI changes slightly out of scope of the Edit username ticket. 
**Note 1** -clicking on the "click here" hyperlink results in a 404 request.  

![404 not found](https://user-images.githubusercontent.com/53306802/92125963-4996f380-ee08-11ea-8caf-d683f60ad9d3.gif)

Cannot write in or copy more than 150 characters in the username field and if trying to save a symbol that's not accepted the "Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters." warning message will show. 
**Note 2** -  could update the "and @/./+/-/_ characters" part of the message as well to "Letters, digits and @.+-_ only. " - should we leave it off as a new ticket or part of a still open Responsive redesign one? 
**Note 3** - When trying to update the profile after erasing the username the jump to the required field is not made properly and the tooltip is not attached to that field when scrolling (see GIF below).  - Should I add another ticket for it? 
**Note 4** -  The right top of the page avatar has been compressed to less than half it's initial size and shape.  (this one might be a regression caused by #580 changes)

![warning message and tooltip](https://user-images.githubusercontent.com/53306802/92126793-494b2800-ee09-11ea-9c4b-adfa6e57f37b.gif)

_Originally posted by @mirunacurtean in https://github.com/mozilla/sumo-project/issues/580#issuecomment-686525385_

**Comment by akatsoulas** [comment]
PR with fixes https://github.com/mozilla/kitsune/pull/4523

**Comment by LeoMcA** [comment]
> Note 1 -clicking on the "click here" hyperlink results in a 404 request.

wfm with the changes

> Note 2 - could update the "and @/./+/-/_ characters" part of the message as well to "Letters, digits and @.+-_ only. " - should we leave it off as a new ticket or part of a still open Responsive redesign one?

The permanent message was updated to show the same "@/./+/-/_" formatting as the one which pops up when there's an error.

> Note 3 - When trying to update the profile after erasing the username the jump to the required field is not made properly and the tooltip is not attached to that field when scrolling (see GIF below). - Should I add another ticket for it?

I think setting `scroll-padding-top` on the `<html>` element fixes this, I'll open another issue.

> Note 4 - The right top of the page avatar has been compressed to less than half it's initial size and shape. (this one might be a regression caused by #580 changes)

This is fixed with the changes

Looks good to me! I think we're ready to deploy.

**Comment by jess-cook03** [comment]
@LeoMcA @akatsoulas has this been deployed yet? Just coming back from PTO and having a look at the recent changes.

**Comment by akatsoulas** [comment]
@jess-cook03 this is deployed in staging. Pending a deployment to production next week. Please let us know if there is anything that should block the release.

**Comment by jess-cook03** [comment]
@akatsoulas 
See comment here >>> https://github.com/mozilla/sumo-project/issues/580#issuecomment-691216731

Was able to take a deeper dive and I have a few edits, I think we will need to discuss together Monday before release @madasan
