### ISSUE TITLE
Location display doesn't appear in all profiles

### ISSUE THREAD

**Issue by couci** [mozilla/sumo-project#597]
We have noticed that on some community members their location doesn't appear on their profile even when they have set it public. After some investigation, @fiji-flo found out that this only happens when the community member has also set a city.

This affects us especially when the community managers are looking at contacting community members in specific countries and not the full list of contributors appears.

Screenshots provided for reference

![image](https://user-images.githubusercontent.com/7702955/93217931-ed1dc780-f769-11ea-9ee2-ec468a059fe9.png)
This is an example from my profile

![image](https://user-images.githubusercontent.com/7702955/93218065-16d6ee80-f76a-11ea-867f-49d3f21f6fd8.png)
My location doesn't appear in my information card

**Comment by akatsoulas** [comment]
Flagging @fiji-flo for visibility.

**Comment by fiji-flo** [comment]
https://github.com/mozilla/community-portal/blob/aeac4936b51e8a2033c3fe7faf36f3d437ed1064/buddypress/members/single/profile.php#L103

and 

https://github.com/mozilla/community-portal/blob/aeac4936b51e8a2033c3fe7faf36f3d437ed1064/lib/members.php#L427

seem to be the issue. We store `"DE, Berlin"` and later try to resolve a country from that string.

**Comment by akatsoulas** [comment]
This is now solved
