### ISSUE TITLE
https://support.mozilla.org/en-US/products/contributor is not showing any topics 

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#643]
STR:
Visit https://support.mozilla.org/en-US/products/contributor 

Expected result: show topics like "Respond Tool," "Localization," etc with articles in them.

Actual result: Topics are not showing up at all.

The articles are showing up in "Featured" articles but not in their topics. That's because these contributor articles are grouped under "How to contribute" which we've hidden from navigation in the past. Now that only registered users can access the Contributor page anyway, we don't need to hide these articles anymore.

**Comment by mirunacurtean** [comment]
Still no topics on stage. 
![image](https://user-images.githubusercontent.com/53306802/108385748-a64e6500-7214-11eb-92ea-8d0fe821e194.png)
Similarly it can be seen that there are no topics when opening a featured article page, for example https://support.allizom.org/en-US/kb/localize-mozilla-support and following the breadcrumbs back to what should be a topic page. 
![image](https://user-images.githubusercontent.com/53306802/108387138-fd086e80-7215-11eb-85f5-64ffe28e1a43.png)

**Comment by LeoMcA** [comment]
Ah the issue was we didn't toggle the visibility of some contributor topics on staging (joni has already done this on prod). @mirunacurtean looks like topics are now showing up, can you confirm?

**Comment by mirunacurtean** [comment]
Looks good to me now. 

![image](https://user-images.githubusercontent.com/53306802/108502989-57f4a100-72bc-11eb-9f80-b95c149b011c.png)

![image](https://user-images.githubusercontent.com/53306802/108503035-65119000-72bc-11eb-99c8-408633ffedac.png)


![image](https://user-images.githubusercontent.com/53306802/108502949-4a3f1b80-72bc-11eb-8d9f-12ea6573e991.png)
