### ISSUE TITLE
[Comms Placeholder] Communicate 1st release for Redesigned search

### ISSUE THREAD

**Issue by madasan** [mozilla/sumo-project#647]
This issue is a placeholder to help organize comms about the first release for the new redesigned search. New issues will be created for each upcoming releases.

**Release goals**
- achieve 1:1 parity with the existing search implementation 
- fix current bugs  

**Target release date**
- TBD  (currently aiming towards the 2nd half of November)

As we are getting closer to this date, @LeoMcA, @madasan and @akatsoulas  will constantly update this ticket with details about the implementation and potential features that might be worth communicating.

@kelimuttu please use this issue to track all the work for the upcoming release. It should provide all the necessary information for a comms plan, if needed.

**Comment by kelimuttu** [comment]
Thanks, @madasan, and @akatsoulas 

That'll be helpful as well to update this issue once the changes hit our staging site so I can test on my own and get a better understanding of the changes.

**Comment by kelimuttu** [comment]
Is there any ETA for this release now? @madasan
