### ISSUE TITLE
After clicking the "Sign me up" button from Get involved pages, users are redirected to Homepage, instead of the corresponding pages

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#65]
**STR:**
1. Navigate to HomePage
2. Click "Volunteer" button
3. Click "Answer questions in the support forum" link => User arrives on page with url https://support.allizom.org/en-US/get-involved/questions 
4. Click "Sign me up" button
5. Enter fxa credentials

**Expected:**
User is redirected to initial page https://support.allizom.org/en-US/get-involved/questions

**Actual:**
User is redirected to HomePage

**Note:**
Same happens if selecting "Write help articles" or "Translate help to your languages" link in step 3.

**Comment by mirunacurtean** [comment]
**No longer occurs when logging in with existing accounts**. Verified across Desktop (Windows 10 with FF 79.0 and and Chrome 84) and mobile (Android 9.0.0 with FF 68.11.0)
Tested from all 'sign me up' entry points: "Answer questions in the support forum", "Write help articles" and "Translate help to your languages"  with EN and ES locales. 
One thing that could be improved is that the homepage locale is the same as before sign in, as right now the homepage language defaults to EN-US after sign in, but another ticket should be added for that. 

![volunteer sign me up redirect to homepage](https://user-images.githubusercontent.com/53306802/89407594-be064600-d727-11ea-8d92-89e51bcb293a.gif)

When trying to **sign up by creating a new firefox account**, an error is received.  A new issues was logged for it - https://github.com/mozilla/sumo-project/issues/563
