### ISSUE TITLE
Consider denormalising user data in other indexes to perform ES-only agreggations

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#654]
If user profile data were completely denormalised in the questions index https://github.com/mozilla/sumo-project/issues/652 could be achieved without the need for a DB query. If we want to implement dashboards in Kibana, for instance, we'll need to have aggregations which don't require any DB lookups.

However, a balance must be struck with the data we denormalise. For instance, if we were to denormalise all profile data - in order to achieve https://github.com/mozilla/sumo-project/issues/652 without a separate DB query - then all a user's replies must be re-indexed if they change any of their profile data.

**Comment by akatsoulas** [comment]
Closing this for now. We can revisit if we need more denormalization
