### ISSUE TITLE
Community portal, activities page - card UI fixes

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#655]
https://community.mozilla.org/en/activities/

Flagging this page for some UI changes:

- [ ] check the assets (images) inside each of these cards..... ie. Common voice looks stretched out 

- [ ] assign and update assets for each of these cards to align with sumo and https://www.mozilla.org/en-US/contribute/ ..... I will provide assets ..... can someone let me know the ideal sizing for these card components ?? @akatsoulas @LeoMcA Thank you! 

cc: @flekkowich

**Comment by akatsoulas** [comment]
No plans to work on this issue at the moment
