### ISSUE TITLE
User is redirected to homepage after changing the locale

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#66]
**STR:**
1. Navigate to [homepage](https://support.allizom.org/en-US/), when locale is EN 
2. Click "Firefox" product
3. Click a topic (e.g.: "basic browsing") => user is taken to page with url https://support.allizom.org/en-US/products/firefox/basic-browsing-firefox
4. Change the locale to "ES"

**Expected:**
User remains on same page, with content in Spanish and url https://support.allizom.org/es/products/firefox/basic-browsing-firefox

**Actual:**
User is redirected to homepage in Spanish, url https://support.allizom.org/es/

**Comment by akatsoulas** [comment]
PR opened here 
https://github.com/mozilla/kitsune/pull/4098

**Comment by ovidiuboca1** [comment]
Tested on staging site and the issue is still reproducible. I've tried also with fr locale and I can reproduce it.

**Comment by akatsoulas** [comment]
That was a misconfiguration of the stage and dev environments. Both had the site domain point to support.mozilla.org so the next_url was set to `None` as the domains did not match. I updated the stage server and this bug is no longer reproducible.
