### ISSUE TITLE
Consider adjusting the refresh interval

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#668]
The default configuration is likely to hurt our indexing speed: https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#_unset_or_increase_the_refresh_interval

We might consider permanently increasing the interval to something higher, or replicate what we do with ES2 which is turn auto-refreshing off while doing bulk updates, then turn it back on after: https://github.com/mozilla/kitsune/blob/4cf90d03f9543dcfad31240183e0eda5f95aca6f/kitsune/search/es_utils.py#L532-L537

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4756

**Comment by akatsoulas** [comment]
QA-
