### ISSUE TITLE
[AAQ] Browse and Share Data functionalities are not working on Edit page mode

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#669]
Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1672326

**Environment:** 
Production and Stage (to reproduce this issue a test has been performed in stage)

Browser:
Firefox (share data button is only functional there)
Firefox and Chrome (for the Browse image functionality)

**Precondition:** 
If not editing your own question then a moderator account should be used. 
In stage, order to be able to use Share Data button, enable the Remote Troubleshooting API for staging https://github.com/mozilla/kitsune/blob/98f9ce40f6ac85ea3fd0f68336466a1a64e833ca/docs/browser_permissions.md#remote-troubleshooting-aboutsupport-api

Steps:
1.  Post a question https://support.allizom.org/en-US/questions/new/desktop/form 
2.  From question tools select "Edit this question" option and reach the edit page, ex. https://support.allizom.org/en-US/questions/1207121/edit. 
3. Try to Share data - the button is unresponsive. 
4. Browse and upload an image and then save the question. 

**Expected result:** 
In edit mode the Share data button should also be functional and results in the data field showing up and populated with the requested info. 
The uploaded image should be posted along the description/ reply after the changes are saved. 

**Actual result:**
The Share Data button is not functional and the uploaded image is not posted after the changes are saved. 

![edit mode](https://user-images.githubusercontent.com/53306802/96695512-696f8000-1392-11eb-80d8-0d3b08ce80aa.gif)

**Comment by mirunacurtean** [comment]
Verified fixed.  Test cases are [here.](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=0&range=A37:A42) 
Example question thread https://support.allizom.org/en-US/questions/1207124. 

@LeoMcA  I have one question - Is the share date info supposed to still be available on each subsequent edit (while on the same browser) without selecting to "Share data"? See the following GIF for an example. 
![AAq edit mode tests](https://user-images.githubusercontent.com/53306802/98139912-6ebde600-1ecd-11eb-94e8-80fa5f893886.gif)

**Comment by LeoMcA** [comment]
> @LeoMcA I have one question - Is the share date info supposed to still be available on each subsequent edit (while on the same browser) without selecting to "Share data"? See the following GIF for an example.

Yep, that was intended, to allow users to remove the data on edit if they want to.
