### ISSUE TITLE
Responsive Redesign // Forum, thread pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#67]

**Comment by jess-cook03** [comment]
[Forum / thread page templates](https://zpl.io/2pXvZ1r) large breakpoint
@kkellydesign

**Comment by jess-cook03** [comment]
@kkellydesign updates to design posted to Zeplin [here](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5e3056416f562257af070e90)

**Comment by jess-cook03** [comment]
@kkellydesign updating this ticket with remaining views for the forum uploaded to zeplin [here](https://zpl.io/aBGGENL)
^ this is the view when you select a thread -- states shown are for the different functionality on the pages and signedin users vs. not signed in.

**Comment by jess-cook03** [comment]
@kkellydesign can the text tool bar become active once the user activates the field ? example from the mock up:
![Screen Shot 2020-01-31 at 5 07 58 PM](https://user-images.githubusercontent.com/54991698/73577901-412ea280-444c-11ea-9551-d17b8aa70d8f.png)
On mobile -- we will use native text/keyboard features, correct?

**Comment by jess-cook03** [comment]
All breakpoints for each view are now posted to Zeplin [here](https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/dashboard?seid=5e3056416f562257af070e90)

**Comment by kkellydesign** [comment]
There are a couple of forms and deep views that could use a little love, but the public-facing pages are ready for a pass. This will be in when https://github.com/mozilla/kitsune/pull/4156 goes live. 

<img width="1448" alt="Screen Shot 2020-02-07 at 1 54 35 PM" src="https://user-images.githubusercontent.com/202590/74057247-82293880-49b1-11ea-85ac-275b446d206c.png">

<img width="1399" alt="Screen Shot 2020-02-07 at 1 55 50 PM" src="https://user-images.githubusercontent.com/202590/74057275-94a37200-49b1-11ea-8a10-a3d1ab8bcae0.png">

**Comment by kkellydesign** [comment]
> @kkellydesign can the text tool bar become active once the user activates the field ? example from the mock up:
> On mobile -- we will use native text/keyboard features, correct?

@jess-cook03 I can't make that adjustment to the toolbar without making some major changes to the JS. I did update the icons, however. Mobile will work as expected with native tools. 

<img width="1015" alt="Screen Shot 2020-02-07 at 2 00 06 PM" src="https://user-images.githubusercontent.com/202590/74057558-2f9c4c00-49b2-11ea-83bb-290346b68bce.png">

**Comment by kkellydesign** [comment]
These are all on now on the test server. 

https://test.sumo.mozit.cloud/en-US/questions
https://test.sumo.mozit.cloud/en-US/questions/firefox?show=done
https://test.sumo.mozit.cloud/en-US/questions/1206913

**Comment by ovidiuboca1** [comment]
FIRST:
https://test.sumo.mozit.cloud/en-US/questions  I have a different result when I visit this page compared with the spec https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e2b5fbbb530e498135fcc92
Here is my result: 
![Firefox Support Forum](https://user-images.githubusercontent.com/54845678/74336844-ca789a00-4da7-11ea-823a-39d84393d809.png)

SECOND:
I can't access this link https://test.sumo.mozit.cloud/en-US/questions/firefox?show=done

THIRD:
I visited https://test.sumo.mozit.cloud/en-US/questions/1206913and there are some differences compared with the spec: https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e349d0fdcdbeaaecdc2c44c
I think I will log the issues separately because there will be too many discussions. @madasan I think we need to talk about this in the meeting.

**Comment by ovidiuboca1** [comment]
Issues that are related to Forum pages: 

https://github.com/mozilla/sumo-project/issues/155
https://github.com/mozilla/sumo-project/issues/156

**Comment by kkellydesign** [comment]
the logged-out sidebar and blue button are now fixed in logged-out mode, which you'll be able to see when https://github.com/mozilla/kitsune/pull/4177 goes up. 
![logged-out](https://user-images.githubusercontent.com/202590/74567834-ab633f00-4f44-11ea-922f-39c3ce88c92b.png)

**Comment by jess-cook03** [comment]
@kkellydesign a few design changes here:

- [ ] Currently the forum component has extra lines in it -- below is an example of what it should look like, kill the divider lines between the replies and votes on top right, and then kill the line above the main title and under the tags.

![Screen Shot 2020-02-19 at 8 18 45 AM](https://user-images.githubusercontent.com/54991698/74841249-62213f80-52f6-11ea-8a72-94e759485701.png)

- [ ] keep the archive icon -- looks good

- [ ] can this collapse on hover -- ? right now it stays open unless you click the icon again, would it be possible to have it close when you take your mouse off the menu? Otherwise you can end up with many open at a time 
![Screen Shot 2020-02-18 at 5 13 51 PM](https://user-images.githubusercontent.com/54991698/74841506-c7753080-52f6-11ea-8c99-eb410df188a1.png)

- [ ] Post a reply -- are we saying that we will have the text editor open all the time? Meaning in the [mock ups on Zeplin](https://zpl.io/aN84Wye) (click left and right to see states) -- there was a button to post then it opened the text editor, with options to post or cancel -- I like that we have preview there now, but I just want to confirm the UX of this interaction?
I understand the ease and quickness of having the text editor all the time, but in the usecases in which you are not logged in or signed up it should be closed and we just show the button. Then in order to reply the user will create or log in with their account in order to post.
@kkellydesign let me know if you want me to walk you through this?

- [ ] Do we not need this button anymore? I have this problem too? @madasan @akatsoulas 
<img width="605" alt="Screen Shot 2020-02-19 at 9 40 52 AM" src="https://user-images.githubusercontent.com/54991698/74844761-f17d2180-52fb-11ea-8b44-8e03a7d27678.png">

- [ ]

**Comment by jess-cook03** [comment]
@kkellydesign a few design changes here:

- [ ] Currently the forum component has extra lines in it -- below is an example of what it should look like, kill the divider lines between the replies and votes on top right, and then kill the line above the main title and under the tags.

![Screen Shot 2020-02-19 at 8 18 45 AM](https://user-images.githubusercontent.com/54991698/74841249-62213f80-52f6-11ea-8a72-94e759485701.png)

- [ ] keep the archive icon -- looks good

- [ ] can this collapse on hover -- ? right now it stays open unless you click the icon again, would it be possible to have it close when you take your mouse off the menu? Otherwise you can end up with many open at a time 
![Screen Shot 2020-02-18 at 5 13 51 PM](https://user-images.githubusercontent.com/54991698/74841506-c7753080-52f6-11ea-8c99-eb410df188a1.png)

- [ ] Post a reply -- are we saying that we will have the text editor open all the time? Meaning in the [mock ups on Zeplin](https://zpl.io/aN84Wye) (click left and right to see states) -- there was a button to post then it opened the text editor, with options to post or cancel -- I like that we have preview there now, but I just want to confirm the UX of this interaction?
I understand the ease and quickness of having the text editor all the time, but in the usecases in which you are not logged in or signed up it should be closed and we just show the button. Then in order to reply the user will create or log in with their account in order to post.
@kkellydesign let me know if you want me to walk you through this?

- [ ] Do we not need this button anymore? I have this problem too? @madasan @akatsoulas 
<img width="605" alt="Screen Shot 2020-02-19 at 9 40 52 AM" src="https://user-images.githubusercontent.com/54991698/74844761-f17d2180-52fb-11ea-8b44-8e03a7d27678.png">

- [ ]

**Comment by kkellydesign** [comment]
> can this collapse on hover -- ? right now it stays open unless you click the icon again, would it be possible to have it close when you take your mouse off the menu? Otherwise you can end up with many open at a time
This is the default behavior for the [protocol menu list component](https://protocol.mozilla.org/patterns/molecules/menu-list.html). I can rip this out, or help improve the plugin, but it's out-of-scope for the moment. 

> I understand the ease and quickness of having the text editor all the time, but in the usecases in which you are not logged in or signed up it should be closed and we just show the button. 

Yes, the form is there all the time when you're logged in. In the logged-out view, you get this card – both of these behaviors are just a reskin of the current functionality:

<img width="936" alt="Screen Shot 2020-02-20 at 10 37 14 AM" src="https://user-images.githubusercontent.com/202590/74950570-4f2d6e80-53cd-11ea-8fcf-436fe8efe822.png">

All of the design revisions have been made to the forum list page: 
<img width="1326" alt="Screen Shot 2020-02-20 at 11 04 36 AM" src="https://user-images.githubusercontent.com/202590/74954327-eea03080-53d0-11ea-91bd-615b9c79348f.png">

I added some extra space above the headline for this. I had made the type adjustments throughout, but we can refine further if you'd like next week. The issue for this particular page is that there's no breadcrumb, so the headline was closer to the top than normal. I added an extra class to deal with this scenario. If we need to revisit other pages next week, we can. 

I think that covers it for this ticket. Reassigning to @jess-cook03 – let me know if there's anything I missed. This will go up with https://github.com/mozilla/kitsune/pull/4184

**Comment by jess-cook03** [comment]
@kkellydesign this all looks good.
For the Reply button -- keep for now. May look to change UX in the future to be more simplified 
Note: Backlog UX/UI improvement area for @jess-cook03 

**New Changes**

- [ ] remove helpful blue tag

- [ ] helpful widget -- remove card style, drop down the body sizing, keep in right hand bottom corner of content. Adjust vertical spacing between comment - helpful - and dividing line of next comment. See image below.
<img width="974" alt="Screen Shot 2020-02-20 at 2 16 12 PM" src="https://user-images.githubusercontent.com/54991698/74969972-9165a880-53eb-11ea-9136-be60d98973b4.png">

- [ ] tags -- change hover state -- make pill darker shade
hex #E0E0E6
![Screen Shot 2020-02-19 at 2 29 39 PM](https://user-images.githubusercontent.com/54991698/74970004-9e829780-53eb-11ea-8704-86f0b9f0e895.png)

- [ ] Move 'question owner' to be labels instead of tags -- treat like 'moderator' label next to username 

- [ ] **BUG** Solution chosen indicator showing up when the user is not logged in see below:
![Screen Shot 2020-02-20 at 11 38 25 AM](https://user-images.githubusercontent.com/54991698/74972495-cb38ae00-53ef-11ea-9ce5-ae01aebe9782.png)

**Comment by jess-cook03** [comment]
@kkellydesign 
Forum checkmark and green color make sure its using the functional green color -- see below:
<img width="343" alt="Screen Shot 2020-02-20 at 2 51 15 PM" src="https://user-images.githubusercontent.com/54991698/74972848-7b0e1b80-53f0-11ea-8ead-330407ed699d.png">

- [ ] Chosen Solution tag with icon -- keep border treatment
<img width="771" alt="Screen Shot 2020-02-20 at 2 53 33 PM" src="https://user-images.githubusercontent.com/54991698/74973079-ce806980-53f0-11ea-8f55-44dd2ba47977.png">

**Comment by jess-cook03** [comment]
![Screen Shot 2020-02-20 at 5 02 46 PM](https://user-images.githubusercontent.com/54991698/74982844-d9dc9080-5402-11ea-818e-7d207e090737.png)
@kkellydesign for this indicator -- can we move the text to the right hand side with the button next to each other side by side not stacked? Also can we make this 'undo' button tertiary button style?

**Comment by kkellydesign** [comment]
@jess-cook03 
>  BUG Solution chosen indicator showing up when the user is not logged in see below:

I think it's a good idea to keep it. It's not so much for the question owner as for the googler who lands on this page. It indicates where in the conversation the correct answer happened. I can remove it if you want, but I want to double-check.

**Comment by kkellydesign** [comment]
All these design edits are in, and will be ready for QA when https://github.com/mozilla/kitsune/pull/4186 goes up.

**Comment by kkellydesign** [comment]
design edits ready for testing. They can be seen here: 
https://test.sumo.mozit.cloud/en-US/questions/firefox-fire-tv?show=all
https://test.sumo.mozit.cloud/en-US/questions/1206250

**Comment by ovidiuboca1** [comment]
@jess-cook03  This is a ticket that involves a lot of discussions and I want to be sure that I verify the correct thing, what exactly needs to be verified here?

**Comment by jess-cook03** [comment]
@ovidiuboca1 @madasan i can confirm that this ticket can be marked complete as of right now for the release.
There is a good bit of conversation here though and good to track this for future improvements ? can we backlog track this
