### ISSUE TITLE
Remove Elastic 2.x from "my questions" and user question/answer contributions pages

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#670]
It should be possible to get similar performance in DB by adding an index on the `user_id` column, without the downside of potentially delayed updates in ES confusing users (*"where did the question I just posted go?!"*).

**Comment by LeoMcA** [comment]
Here's the original bug adding the feature: https://bugzilla.mozilla.org/show_bug.cgi?id=1011179

Noah proposed using this link (which still works): https://support.mozilla.org/en-US/questions/all?owner=mine&show=all

One difference between that and the "my questions" link which ended up being implemented is that it shows replies you made, as well as questions you asked. The "my questions" link just shows questions you asked.

Performance is also (obviously) far better with the "my questions" link, because its indexed by user id. We should be able to get similar performance through Noah's link by adding indexes for question author and answer author in the db.

However, I think we should probably look at eventually backing those question listing pages with elastic. We'll probably need to set up a lot of different indexes to support the different filtering that can happen on them efficiently, all of which is already being done in ES, and the listings on those pages doesn't need to be 100% real time. If there's even up to a minute of lag between someone asking a question and it appearing for contributors to answer, that's not going to be a problem.

So, I would propose replacing the "my questions" link with a link to a (very simple) custom built view, styled to look more like the existing "my profile" pages (which neither the existing link, nor Noah's link have), backed by the DB, setting up an index on the author column in the questions table to give us similar performance to ES (but without any update lag).

**Comment by LeoMcA** [comment]
In the end we added a couple of routes: https://support.allizom.org/en-US/user/leo_/questions and https://support.allizom.org/en-US/user/leo_/answers

**Comment by mirunacurtean** [comment]
With the mentions that the Latest Answer list is not paginated was a choice and that each answer is listed separately even if the belong on the same thread, the test results are successful. 
The number of questions and answers is updated successfully when a new one is added and and they show at the top of their respective list. 
The My Questions or Latest Answer lists are not, however, updated, when when using the Edit this question functionality. 
See TestRail [test run](https://testrail.stage.mozaws.net/index.php?/runs/view/42408&group_by=cases:title&group_order=asc&group_id=-1).
