### ISSUE TITLE
Filter out deactivated accounts when searching for recipients in the messaging app.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#673]

**Comment by akatsoulas** [comment]
We should also block sending messages to deactivated accounts altogether

**Comment by LeoMcA** [comment]
PR doing the title merged: https://github.com/mozilla/kitsune/pull/4567

> We should also block sending messages to deactivated accounts altogether

Tracking this separately: https://github.com/mozilla/sumo-project/issues/677

**Comment by LeoMcA** [comment]
Just deployed this to staging, man it's **so** noticeably faster than on prod. :racing_car:

Some pointers for QAing this:

* The autocomplete drop-down appears across a few pages:
  * The group add user form: https://support.allizom.org/en-US/groups/quality-assurance
  * The message form: https://support.allizom.org/en-US/messages/new
  * The wiki add contributor form: https://support.allizom.org/en-US/kb/get-started-firefox-overview-main-features/history#contributors
* Results won't always be the same as currently exist on prod (this is one of the performance optimisations we made), but if there is an exact match it should always appear
* Results should also be relatively fast (<1 second or so), any query which causes slower performance than this would be intriguing to know. It may only be that slow on the first query, the SQL query cache might speed it up on a second attempt, even across page refreshes.

**Comment by mirunacurtean** [comment]
Testing for the deactivated account (deactivated by a superuser or deactivated by the account owner) filtering has been successful:
1. "No results" are found when performing a search in the group add user form (member or group leader) through using either username or display name  - https://support.allizom.org/en-US/groups/quality-assurance
2. "No results" are found when searching for the deactivated account in the article history page using either the username or the display name of the account - https://support.allizom.org/en-US/kb/get-started-firefox-overview-main-features/history#contributors
3. "No results" are found when searching for a user in the new message form - https://support.allizom.org/en-US/messages/new
4. The deactivated account cannot be found in community hub using the username/display name or twitter handle, with the exception of some older mcurtean+84 deactivated profiles (user1470092 and user1470153) that still show up. The latest one was however, deleted.

**Comment by LeoMcA** [comment]
> with the exception of some older mcurtean+84 deactivated profiles (user1470092 and user1470153) that still show up

This is related to ES indexing, and should be fixed with Search v2
