### ISSUE TITLE
Add a reindexing cronjob for our frankfurt prod cluster

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#697]
Follow-up to https://github.com/mozilla/sumo-project/issues/667:

In that issue/PR we opted to just add the updated before/after functionality to the es7_reindex command, which is useful by itself, and not add the cronjob, since our signals should make it unnecessary.

If we wanted to re-add the cronjob, this commit should do it: https://github.com/LeoMcA/kitsune/commit/a4686689d12ea160b54546d2a9a641ea509fae1f

My preference is to not fallback to a cronjob, so as to not obscure any problems in our signals. If we're not confident enough in our signals, I'd prefer to have a cronjob which periodically compares what we have in DB to what we have in ES and raises an error if something doesn't match.

**Comment by akatsoulas** [comment]
@LeoMcA we should add a cronjob for our FRA cluster. How about modifying the commit you reference in here to work for that case?

**Comment by akatsoulas** [comment]
After the release to FRA, this was verified through DMS
