### ISSUE TITLE
Implement user search as a SumoSearch class

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#699]
Originally migrated to elastic 7 here: https://github.com/mozilla/kitsune/commit/9ffb53cf3f89ddf712f333ccd1ec44f772929be6#diff-9eee23518953c40aac4f53575041f361a496dc07a8bdbd66184386529e9b7fe7R88-R90

Reimplement this as a SumoSearch class, introduced here: https://github.com/mozilla/kitsune/pull/4554

**Comment by LeoMcA** [comment]
Verified on staging, community searching is working as it was before.

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4712
