### ISSUE TITLE
'Find Help' searchbar and sumo navigation container are stuck at the top of the page

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#702]
**Environment:**
Stage

**Browsers:**
Firefox 
Chrome

Devices:
Windows 10 pro
Android 9.0.0

**Steps to reproduce:** 
1. Go to https://support.allizom.org/en-US/ and view 'Find Help' search bar. 
2. Scroll down the page. 

**Actual result:**
The Find help search bar is normally hidden when as it would come down right on top of the Sign In/Up button but in this case it has replaced it as the top right page element. 
When scrolling down, the navigation bar does not move and so the 'Find Help' field is only traveling along the page with it. 
![Find help search bar](https://user-images.githubusercontent.com/53306802/101844946-36f23000-3b56-11eb-878a-27dfebd709da.gif)
On mobile the Sign up button and Find Help search bar are stuck together underneath an open Get help menu. 

**Expected result:**
Find Help search bar is hidden unless scrolling through the page and moving along with the navigation bar. 
https://support.mozilla.org/en-US/

Note: This occurs when signed in as well. 
@akatsoulas @LeoMcA Please take a look at this.

**Comment by LeoMcA** [comment]
This was caused by a temporary JS error as a result of deploying a non-master branch to staging.
