### ISSUE TITLE
Cannot sign out from Stage account

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#703]
**Environment:**
Stage

**Browsers:**
Firefox 
Chrome

**Devices:**
Windows 10 pro
Android 9.0.0

**Steps to reproduce:** 
1. Go to https://support.allizom.org/en-US/ and view 'Find Help' search bar. 
2. Sign in.
3. Open profile menu panel and try to sign out. 
4. Go to View profile page and try to sign out from there too.

**Actual result:**
No response is received when trying to sign out from either location.
![Cannot sign out in stage](https://user-images.githubusercontent.com/53306802/101845664-e4197800-3b57-11eb-9577-c879e6336c3c.gif)

**Expected result:**
Account is signed out.

**Comment by LeoMcA** [comment]
This was caused by a temporary JS error we had while deploying to stage from a non-master branch
