### ISSUE TITLE
Remove REDIRECT articles from search

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#705]
We could either exclude these in our search query, or not index them in the first place.

If we don't index them then we can't put them in topic listings, or anywhere else elastic is used in a non-search capacity, once we've migrated those to elastic 7 as well.

**Comment by mirunacurtean** [comment]
Precondition:  Account with permission to modify and approve article updates is signed in. 

Steps that results in the creation of a redirect article:
1. Create a new test article https://support.allizom.org/en-US/kb/new or pick an existing one to modify.
2. Perform a search based on title or keyword to verify that the original article shows up in search results. 
3. Back on the article page select to Edit Article and from the Edit Description rename the Title.  Save Description and return to Article and submit for Review. 
4. After approval return to article page and check to see that title has been updated. 
![repro rename article issue](https://user-images.githubusercontent.com/53306802/102252191-7500a280-3f0e-11eb-9908-ddbb9d805288.gif)


5. wait for a few minutes to make sure the info updated ha been properly applied (indexed) and then search for that new article using it's keyword. 
6. Notice that the previous and the new results show up in search results. 

![modified article duplicate rticle and redirect](https://user-images.githubusercontent.com/53306802/102252232-834ebe80-3f0e-11eb-95e5-e249c5016c2d.gif)

**Comment by LeoMcA** [comment]
Done in https://github.com/mozilla/sumo-project/issues/736

**Comment by mirunacurtean** [comment]
Re-tested the[ scenario in my previous comment](https://github.com/mozilla/sumo-project/issues/705#issuecomment-745456455) and also with other search data that used to bring up REDIRECT search results. 
For example, [this article](https://support.allizom.org/en-US/kb/firefox-and-dragonfly?redirect=no) would show up in previous search results when using the "dragonfly" search word, while now only the expected results show up (updated articles and questions)
![image](https://user-images.githubusercontent.com/53306802/106152745-79afac00-6186-11eb-9dc0-da996c37b2fa.png)
