### ISSUE TITLE
Out of order search API responses confuses instant search

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#707]
This is behaviour I've observed locally with queries taking wildly different times, but theoretically could also be happening on prod.

Instant search seems to render API responses in the order that they return, rather than the order they were sent in. So if:

1. Instant search sends a query for "fire"
2. Instant search sends a query for "firefox"
3. The server sends a response for the "firefox" query
4. The server sends a response for the "fire" query

It's the "fire" query response, from 4, which is rendered.

Instant search should always render the most recently sent query, and could even abort old requests if they haven't received a response yet.

**Comment by akatsoulas** [comment]
Adding here for reference the content of issue #708

```
Currently if a search gets sent midway through a word some pretty terrible (or no) results can be returned.

For instance, "fir" (imagine I was midway through typing firefox) returns no results.

Appending a wildcard to the end of any query ending in non-whitespace should greatly increase the usefulness of these partial searches.

We may want to only enable this for a proportion of users to begin with, to ensure all the wildcard searches we'll be doing don't put elastic under heavy load.
```

**Comment by mirunacurtean** [comment]
Still seems to be a lag in responsiveness, both with search and a bit as well when selecting a new page. 

![Performing search and selecting a new page occur with a noticeable lag](https://user-images.githubusercontent.com/53306802/108387985-d434a900-7216-11eb-89ab-c0f65203c90a.gif)

**Comment by LeoMcA** [comment]
The lagginess is expected on staging, since we have a very small ES cluster there. However, searches should now render in the order they're typed (which seems to be the case in that recording).
