### ISSUE TITLE
Unmaintained articles appear in search

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#709]
Such as https://support.allizom.org/en-US/kb/marketplace-apps-firefox-desktop when searching for "firefox accounts"

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4642

**Comment by mirunacurtean** [comment]
Confirmed fixed using other examples using partial or entire title through https://support.allizom.org/en-US/questions https://support.allizom.org/en-US/products pages. 
For English locale: 
https://support.allizom.org/en-US/kb/Favicons%20do%20not%20display
https://support.allizom.org/en-US/kb/Firefox%20displays%20files%20as%20text
For non-English locale (on non-English pages)
https://support.allizom.org/de/kb/Einf%C3%BChrung%20in%20den%20Chat
https://support.allizom.org/es/kb/novedades-de-firefox-focus
All articles in search results are maintained.
