### ISSUE TITLE
Searches containing stop words return no results in KB

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#710]
* https://support.allizom.org/en-US/search/v2/?format=json&w=1&q=customize+the
* https://support.allizom.org/en-US/search/v2/?format=json&w=1&q=private+browsing+on

This seems to happen if the query contains a stopword, but only in the KB - not in question search.

**Comment by mirunacurtean** [comment]
Verified fixed across desktop and mobile. 
Tested on English, German and Romanian locale. 
![image](https://user-images.githubusercontent.com/53306802/104938893-62b7cf80-59b8-11eb-84cf-a639eef54501.png)

![710 fix example 4](https://user-images.githubusercontent.com/53306802/104938958-795e2680-59b8-11eb-9d43-1d3849de2edd.PNG)
The examples have been verified across AAQ(english), on product forums search support, the KB pages and in the Contributor support search. 

![710 fix example 1](https://user-images.githubusercontent.com/53306802/104939357-fe494000-59b8-11eb-9a62-67f32d8ed41c.PNG)

![image](https://user-images.githubusercontent.com/53306802/104939333-f5586e80-59b8-11eb-8d0d-68a3cdb67d85.png)
