### ISSUE TITLE
non-en stopwords aren't being filtered in our locale-specific analyzers

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#712]
It doesn't look like we're correctly applying locale-specific stopword filters:

```
POST sumo_wiki_document/_analyze
{
  "analyzer": "de",
  "text": "the der"
}
```
returns:
```
{
  "tokens" : [
    {
      "token" : "der",
      "start_offset" : 4,
      "end_offset" : 7,
      "type" : "<ALPHANUM>",
      "position" : 1
    }
  ]
}
```

However, `der` is in the german snowball stopwords list:
https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/resources/org/apache/lucene/analysis/snowball/german_stop.txt#L52

**Comment by LeoMcA** [comment]
@mirunacurtean this should be possible to test in Romanian as well - any of the words in this list should be ignored when searching: https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/resources/org/apache/lucene/analysis/ro/stopwords.txt

That is to say: a search for "firefox" and one for "acea firefox" should return the same results.

It would also be interesting to know if stemming is working/improved in Romanian - that is to say (giving an English example) a search for "customized" returns results containing "custom" (or vice-versa).

**Comment by mirunacurtean** [comment]
**Verified fixed. Results are listed even when using non-english stopwords 
DE locale example**
![image](https://user-images.githubusercontent.com/53306802/104947062-c72c5c00-59c3-11eb-80eb-4af52b479345.png)






**Romanian example "oricând instalez firefox" meaning "anytime I install firefox"**
![image](https://user-images.githubusercontent.com/53306802/104947187-08bd0700-59c4-11eb-8b69-e463fcaf1a50.png)

![image](https://user-images.githubusercontent.com/53306802/104947661-c516cd00-59c4-11eb-93f8-f760237a71d7.png)

And a check on English locale as well. 
![image](https://user-images.githubusercontent.com/53306802/104948211-9d743480-59c5-11eb-820e-d8f008a2334f.png)
