### ISSUE TITLE
Last search keyword gets cut off in Find Help search bar occasionaly

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#713]
**Potentials Steps to reproduce:**
1. Perform a search on the main search bar, for example on the homepage https://support.allizom.org/en-US/. 
2.  Scroll and check that Find help field text is the same. 
3.  Update the main search bar keywords/ phrase so that 0 results are received. Try multiple combinations until the last keyword is cut off in the Find Help search field. 

![Find Help keyword cut off repro](https://user-images.githubusercontent.com/53306802/102454651-0a06b700-4047-11eb-8660-4cbd0548f3fa.gif)

![image](https://user-images.githubusercontent.com/53306802/102453719-741e5c80-4045-11eb-95e2-0898aae492e6.png)

Please note that this is not a 100% repro and that these are the best steps found so far.

**Comment by mirunacurtean** [comment]
Just managed to reproduce it once again although again, the steps are 
![image](https://user-images.githubusercontent.com/53306802/107366345-b4023d00-6ae6-11eb-8d6e-8ad88effbc39.png)
Steps:
1. Search for "fire" spelled incorrectly "fiere". 
2. Correct misspelling and update the word to "firefox" scroll down to see Find Help search bar and view the keywords used in it.

**Comment by mirunacurtean** [comment]
I almost did not manage to reproduce this anymore, until it occurred at the end of a series of search query updates, the last one resulting in a time out. 
![image](https://user-images.githubusercontent.com/53306802/110485649-8bc12a80-80f4-11eb-8876-fece1113c3e5.png)

**Comment by mirunacurtean** [comment]
I cannot manage to reproduce this anymore despite numerous tries, so even if it might happen in some circumstances again, it would have a very low repro.

**Comment by mirunacurtean** [comment]
Ironically, I just managed to encounter this issue again, after a multitude of search phrase updates (around 20).
![image](https://user-images.githubusercontent.com/53306802/110961001-00e06a00-8358-11eb-8158-5d806f4b580e.png)

There's no way to reproduce this in consistently, it just occurs from time to time after a certain amount of stress, if I can call it that. @LeoMcA what do you think we should keep this in QA still?

**Comment by LeoMcA** [comment]
There's a few async things happening with instant search, so I guess sometimes events get out of order and we end up with a slightly outdated query in the other search boxes. If this isn't happening particularly often, I think it's safe to close as WONTFIX.

**Comment by mirunacurtean** [comment]
Honestly I feel the same at this point, as it is rare and not particularly bothersome. 
Status: WONTIFX.
