### ISSUE TITLE
Cannot find original or renamed articles by searching with full title

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#715]
**Steps to reproduce:**
1. Open page in browser https://support.allizom.org/en-US/kb/modify-article-title-redirect-issue#focus-firefox:win10:
2. Copy title. 
3. Paste title in Find Help search field and check results. 
4. Copy previous title as well ' Reproduce the issue with redirect'  https://support.allizom.org/en-US/kb/modify-article-title-redirect-issue?redirectslug=reproduce-issue-redirect&redirectlocale=en-US#focus-firefox:win10:

**Actual results:**
0 results are found. 
Note:
1. The search is not performed instantly either, when the title is copied into the find help search field or the main search bar, and instead adding a space will start the search request. 
2. If the page is refreshed and the "modify" word is typed in the search bar, both the original and the renamed article will be listed. 

![no results on copied title](https://user-images.githubusercontent.com/53306802/102596751-4e1aba00-4122-11eb-8ebf-0d60ac65df6a.gif)

**Expected results:**
Searched based on copied or typed in phrases is performed correctly. 
Search based on full title is performed correctly and results are listed.

**Comment by LeoMcA** [comment]
> Search based on full title is performed correctly and results are listed.

I believe this is this bug: https://github.com/mozilla/sumo-project/issues/710

> Searched based on copied or typed in phrases is performed correctly.

I've opened a more specific issue for this: https://github.com/mozilla/sumo-project/issues/720
