### ISSUE TITLE
Handle auto archiving of questions in search v2

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#727]
Currently auto archiving questions is done with a raw SQL query:

https://github.com/mozilla/kitsune/blob/db42cf7841b75ff0d4b6d3b21ac2524636110429/kitsune/questions/management/commands/auto_archive_old_questions.py#L37-L43

This means our signals won't be triggered.

**Comment by akatsoulas** [comment]
@LeoMcA is this done? If not please move it under the `General release` milestone

**Comment by LeoMcA** [comment]
I want to wait until tomorrow to check that the questions in tonight's cronjob are successfully updated in ES 7.x.

**Comment by LeoMcA** [comment]
Yep this is working on prod. :+1: 

This has 0 hits:

```
GET /sumo_prod_questiondocument_read/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "question_created": {
              "lte": "2020-08-20"
            }
          }
        },
        {
          "term": {
            "question_is_archived": "false"
          }
        }
      ]
    }
  },
  "size": 0
}
```

Whereas a date of `2020-08-21` has 286 hits.

```
>>> datetime.now() - timedelta(days=180)
datetime.datetime(2020, 8, 21, 12, 49, 7, 135635)
```

So this is expected.
