### ISSUE TITLE
Image markup in forums adds many line breaks

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#728]
https://bugzilla.mozilla.org/show_bug.cgi?id=1019998#c14

I imagine these are line breaks in one of our templates not being collapsed because of our `white-space` css on forum posts.

**Comment by mirunacurtean** [comment]
Verified fixed while testing on AAQ and Community discussion forum posts. 
https://support.allizom.org/en-US/questions/1207155#answer-1082569
https://support.allizom.org/en-US/forums/contributors/712928?last=73568#post-73568
