### ISSUE TITLE
Archived documents ranking higher than other relevant results

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#730]
**Precondition:**
Enable instant search v2. 
https://kitsune.readthedocs.io/en/latest/search-v2.html#testing-on-staging

**Steps to reproduce:**
1.  Go to https://support.allizom.org/en-US/. 
2.  Search for "thimble".
3. Open first results in new tabs and look at them. 

**Actual results:**
The first ranked search result is an archived question. 
![Archived docs in search results](https://user-images.githubusercontent.com/53306802/104467517-1129d200-55bf-11eb-9fb4-e0e6238f5f5a.gif)

**Expected result:** 
Based on https://github.com/mozilla/sumo-project/issues/729:
Archived articles shouldn't appear in search results
Archived questions shouldn't appear in search results

@LeoMcA  Added this as an example and to keep keep track and verify when this no longer occurs.

**Comment by akatsoulas** [comment]
This should be fixed. @mirunacurtean can you verify please if this is the case?

**Comment by mirunacurtean** [comment]
Verified fixed now on English locale. 
![image](https://user-images.githubusercontent.com/53306802/106492312-7424cf80-64c0-11eb-87f7-536d47891261.png)
For example when dealing with AAQ archived threads that are specifically about "Blocklist", the search results still rank the related article higher. 
https://support.allizom.org/en-US/questions/1206602
![image](https://user-images.githubusercontent.com/53306802/106495290-26aa6180-64c4-11eb-9291-503271644b39.png)

Also on non-English locale. 
![image](https://user-images.githubusercontent.com/53306802/106494217-d2eb4880-64c2-11eb-8724-999419480bb5.png)
