### ISSUE TITLE
Question title is not updated in Profile View results after being edited

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#732]
**Precondition:** 
Sign in on https://support.allizom.org/en-US/ and add a question. 

**Steps to reproduce:** 
1. Go to account avatar and the to Profile View. 
2. From Contributions select to view the questions added by the user. 
3.  Select the recently added question and and on the question thread choose to Edit this question. 
4. Modify save updated question title. 
5. Return to profile view and check question list. 

**Actual result:**
The question's title is not updated in the profile view search results list.
![question title is not updated after being edited in profile view results](https://user-images.githubusercontent.com/53306802/104589914-3f68e980-5673-11eb-99de-fb4e38effe17.gif)

**Expected result:**
When the question title is updated it should be updated in the profile search results (currently behaves as expected in Search Support results).

**Comment by akatsoulas** [comment]
@mirunacurtean this seems to be working fine now. Can you verify? Moving it under the QA column. 
I used the staging env for testing.

**Comment by mirunacurtean** [comment]
Verified fixed. 
After being edited the 1st time, the question title is updated in the profile view as well. 
![image](https://user-images.githubusercontent.com/53306802/107966169-24f89780-6fb4-11eb-8ca9-cf11792908df.png)

Question title is updated again after the 2nd edit. 
![image](https://user-images.githubusercontent.com/53306802/107966349-61c48e80-6fb4-11eb-8ebc-ac367cb27f4e.png)

**Comment by akatsoulas** [comment]
Thanks @mirunacurtean. Closing this as stage is on par with prod.
