### ISSUE TITLE
Filter spam questions in AAQ search query

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#733]
We don't want questions with `is_spam=True` to appear in search results

**Comment by mirunacurtean** [comment]
This only applies to questions that have been marked as spam by moderators and not questions flagged through the Report Abuse feature (a separate ticket will be added for discussing that). 
Verified fix across desktop and mobile platforms successfully. View high level test cases [here](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit#gid=0&range=A48).
Questions that have been marked as spam do not show up on search results. If the question is unmarked then it will be listed in the related search results.

**Comment by mirunacurtean** [comment]
This has started occurring again. 
![image](https://user-images.githubusercontent.com/53306802/107198177-7aa1d280-69fd-11eb-9ca6-35d6adc7cbb5.png)
![image](https://user-images.githubusercontent.com/53306802/107198217-8392a400-69fd-11eb-8800-64e66bd5b55a.png)

Setting it back in QA to re-test after @tasos will trigger a re-index.

**Comment by mirunacurtean** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/53306802/107365024-e743cc80-6ae4-11eb-90d0-86a4a7aa759e.png)

Re-tested using [previous data](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit#gid=0&range=A48) as well.
