### ISSUE TITLE
Exclude spam answers in QuestionDocument answer_content field

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#737]
A little care will be needed to ensure we don't N+1

**Comment by LeoMcA** [comment]
Once deployed, this can be tested by replying to a question with an answer with some unique string it in it. When that answer is marked as spam, searching for that unique string shouldn't return the question. When the answer isn't marked as spam, searching for that unique string should return the question.

**Comment by mirunacurtean** [comment]
Works as expected across AAQ and KB (showing in search results for all products/ articles or in the specific product section where the question was added). This example has the searched for phrase in both question replies but one of them is marked as spam. 
It is clear that after deleting the non-spam answer, the question is no longer shown in the search results. 

![questions threads with answers marked as spam are not showing in search results](https://user-images.githubusercontent.com/53306802/106625233-29b65800-657f-11eb-9e6b-689909662c07.gif)

When the reply is "unmarked as spam" then the questions does show in search results for the specific phrase used. 
![image](https://user-images.githubusercontent.com/53306802/106625654-8ade2b80-657f-11eb-93a7-88f348545aa5.png)
