### ISSUE TITLE
Support Integration Documentation

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#74]
Ongoing conversations and concept creation for an icon that will be used across product whenever there is a link to SUMO.

Tracking Progress here:
- narrowed down two concepts (search glass & search bubble) 
- feedback sessions
- align with latest icon/illustration set being created (TBD -- schedule meeting)
- less logo mark and more function based product icon/glyph

**Comment by madasan** [comment]
Let's split this into multiple tickets and close it
