### ISSUE TITLE
Show questions from last 2 years in search

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#740]

**Comment by mirunacurtean** [comment]
This is pretty self-explanatory. 
Questions threads that are older than 2 years time should not show in search results and this is has been verified in the English and Spanish AAQ and product forums. 
![questions older than 2 years do not show in search results](https://user-images.githubusercontent.com/53306802/106587334-248ee400-6552-11eb-88bc-fdcdfaf40223.gif)

Question threads that are below that time period should show in search results.

![questions under 2 years appear in search results](https://user-images.githubusercontent.com/53306802/106587703-99fab480-6552-11eb-8446-50e4e9827f4a.gif)

Tested across AAQ. product forums and KB sections.
