### ISSUE TITLE
Investigate the relevance of the results originating from different indices

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#743]
We should investigate and tune if needed/applicable the relevance of the results by focusing our efforts on self serve content from the KB.

**Comment by mirunacurtean** [comment]
Boosted value tests have been performed for https://github.com/mozilla/sumo-project/issues/730, but another stage example is a search for "keyword" where there are multiple articles with the term added to their summary or keyword field which boosts them above a [question ](https://support.allizom.org/en-US/questions/1207147)that contains it in its title. 
![image](https://user-images.githubusercontent.com/53306802/106638921-0eeae000-658d-11eb-8b5f-f515c3da47a0.png)
