### ISSUE TITLE
Prevent add-on being tokenized into ["add", "on"]

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#748]
With our current en-US analysis chain, the string `add-on` gets tokenized into two tokens: `add` and `on`.
`on` then gets removed by the stop-word filter, and so the string becomes just `add`.

This is particularly apparent when implementing synonyms in https://github.com/mozilla/sumo-project/issues/721, as creating a synonym like `extension, add-on, add on` also get analysed and so any query for `extension` also becomes a query for simply `add`.

I reckon it should be possible to add a [mapping char_filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-mapping-charfilter.html) for `add- => add`, which would transform any instance of `add-on` into `addon`, and it would then be tokenized as such.

This is the approach recommended upstream: https://discuss.elastic.co/t/configuring-the-standard-tokenizer/8691

**Comment by mirunacurtean** [comment]
This is impacted right now by https://github.com/mozilla/sumo-project/issues/793 which prevents getting the expected results while in View All section - which is the default. 


@LeoMcA Skipping over the issues encountered right now on View All search, are these the expected results, in general?

When starting tests from a previous "saved search point", so to speak, meaning when we start while already on the Help Articles section or Community Discussion Only, the results are the following: 



**1. searching for "addon" or "add-on" gives the same results, which are relevant and related to add-ons and extensions.**
![Addon tokenization test](https://user-images.githubusercontent.com/53306802/110136860-e0089980-7dd8-11eb-81c4-6779c7b7a0c9.gif)






**2. test search "add"** 
Highly ranked results are the ones that recognize the word as standing on its own and not part of a compound. 
![image](https://user-images.githubusercontent.com/53306802/110144790-64f7b100-7de1-11eb-9cb9-9de6201d8244.png)



**3. In a search phrase use "add":**
**Case 1 - "how to add bookmarks"** 
Shows results relevant for "bookmarks" search. 
![image](https://user-images.githubusercontent.com/53306802/110145398-0da61080-7de2-11eb-8ea8-f28f75916acc.png)




**Case 2 - "how to add themes"**  
In this case themes are interpreted as synonyms for "add-ons" and as such the results are focused on that. 
![image](https://user-images.githubusercontent.com/53306802/110145006-a2f4d500-7de1-11eb-8bd0-96d0d111d27d.png)

**Comment by LeoMcA** [comment]
Yes, these are expected. `theme` is currently set up as a synonym with `addon`, which may be something we want to revisit with Joni.

**Comment by mirunacurtean** [comment]
Another test example is "pop-ups", "popups" and "pop ups". 
The same number of examples and results ranking is received for all of them, and probably due to the synonymous meaning the results include links where "pops up" was identified as the search word, which in this case is valid. 
![image](https://user-images.githubusercontent.com/53306802/110477766-3c76fc00-80ec-11eb-96b6-dcb743d8b5dd.png)

**Comment by mirunacurtean** [comment]
Re-tested the examples above again and they delivered the same results so marking this as Ready for Release.
