### ISSUE TITLE
Username Bug UX Implementation

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#75]
**Designs here:**
[Link to Zeplin](https://app.zeplin.io/project/5c940ea1d154600581d4377b/dashboard?seid=5da101f04cc7b62fe458c649)

**Implementation of UX solutions created in response to previously filed issue:** [Add an option to modify username mozilla/kitsune#3896](https://github.com/mozilla/kitsune/issues/3896)

Notes:
- When a user selects anonymity, will we propagate this everywhere (eg old answers)? - **Backlog (?) decide priority**
- KB article for “What does anonymize my username mean?” is WIP - Jess & Joni
- Display name mandatory only if users selects to anonymize

**Comment by madasan** [comment]
Next steps on this: re-evaluate what needs to happen and scope it out

**Comment by akatsoulas** [comment]
ticket for the first iteration which only makes the field editable: https://github.com/mozilla/sumo-project/issues/580

**Comment by jess-cook03** [comment]
This has been solved part one at least with allowing users to edit their username..... with ticket #580 

That being said there is still a need to implement a solution for the display name.
The UX proposal suggested we move away from having a display name and I think we need to solve for that as next steps for this.

I will create a new ticket for solving the UX for display names.
