### ISSUE TITLE
Implement the ability to do a staged rollout of the new Instant Search API

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#753]
Also collect some basic distinguishing metrics in GA

**Comment by akatsoulas** [comment]
Short list of libs to use:
* Django waffle 
* Mozilla's [trafficcop](https://github.com/mozilla/trafficcop)
* Something else?

**Comment by LeoMcA** [comment]
Enabled on staging at 50% in [rollout mode](https://waffle.readthedocs.io/en/stable/types/flag.html#rollout-mode).

**Comment by mirunacurtean** [comment]
Checked - search v2 is present and functional (article, question and community user search providing the expected results in English and non-English locale) where dwf_instant_search_v2:"True". 
Old search is still available where dwf_instant_search_v2:"False" and results are not particularly relevant but if instant search v2 is enabled the results are on the topic. 
![v2 on waffle false](https://user-images.githubusercontent.com/53306802/109801401-14d4ef00-7c27-11eb-94c6-c3e2cb43dff5.gif)

Out of 5 test profiles the rollout was the following:
1. 1 old profile where dwf_instant_search_v2:"True" on return sessions. 
2. 1 old profile where dwf_instant_search_v2:"False"
3. 1 new profile where dwf_instant_search_v2:"False"
4. 2 new profiles where dwf_instant_search_v2:"True"
