### ISSUE TITLE
Remove ES2.x code from forums app

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#759]
* `kitsune.forums.models.ThreadMappingType`

**Comment by mirunacurtean** [comment]
Search from[ Support forums](https://support.allizom.org/en-US/questions) collective and individual pages is functional. 
Search across [Contributor forums](https://support.allizom.org/en-US/forums/) is also working and delivering relevant results (even if the search terms are not highlighted)
![image](https://user-images.githubusercontent.com/53306802/114905669-e0f20980-9e21-11eb-837a-7a3d5f818396.png)
