### ISSUE TITLE
Remove ES2.x code from community app

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#762]
* ~`kitsune.community.api.TopContributorsBase`~ https://github.com/mozilla/kitsune/pull/4735
  * `kitsune.community.api.TopContributorsQuestions`
  * `kitsune.community.api.TopContributorsLocalization`
* ~`kitsune.community.utils._get_creator_counts`~ https://github.com/mozilla/kitsune/pull/4734

**Comment by mirunacurtean** [comment]
Setting this as Blocked until https://github.com/mozilla/sumo-project/issues/831 is fixed.

**Comment by mirunacurtean** [comment]
Removing this from Blocked as #831 has been fixed.

**Comment by mirunacurtean** [comment]
Overall KB and Localization updates work as expected and there are some issues on Support Forum updates which are not recent. 
Filtering issues have been filed in separate tickets. 
See tests results:
https://testrail.stage.mozaws.net/index.php?/runs/view/42770&group_by=cases:title&group_order=asc&group_id=-1
Setting this as Ready for Release.
