### ISSUE TITLE
Upgrade MySQL from 5.6

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#765]
Adding this to track the progress of work regarding this upgrade. 
cc @The-smooth-operator

**Comment by akatsoulas** [comment]
@The-smooth-operator please comment here about any developments on this.

**Comment by sciurus** [comment]
We have until Aug 3 2021 to do this, so we're going to hold off for a while.

**Comment by akatsoulas** [comment]
This is done
