### ISSUE TITLE
Filter the top-contirbutors page by the contributors group.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#770]

**Comment by mirunacurtean** [comment]
Verified for following situations:

1. A [user that provides responses is but not part of a Contributo](https://support.allizom.org/en-US/user/mc896)r group is not listed in the [Top Contributor page](https://support.allizom.org/en-US/community/top-contributors/questions). 
2. Verified through [787](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=0&range=A60) that a contributor belonging to a group, is indeed represented on the Top Contributor pages.
