### ISSUE TITLE
Filters on instant search aren't localised

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#775]
Looks like our tabs (View All, etc.) and "Filter by product" section don't have localised strings, or the localised strings aren't being used.

**Comment by LeoMcA** [comment]
The problem seems to be that we're baking the english strings into the pre-compiled template, but we need to pass the strings in as context at render-time instead.

**Comment by LeoMcA** [comment]
The issue for the tabs was actually this: https://github.com/mozilla/sumo-project/issues/780

However, we can still pass localised product strings.

**Comment by mirunacurtean** [comment]
Verified fixed - tested on windows Firefox and iOS/ android Firefox using  es, fr, de and ca locales. 
![image](https://user-images.githubusercontent.com/53306802/108979872-c4441b80-7693-11eb-9b9a-25b248b695df.png)
![image](https://user-images.githubusercontent.com/53306802/108980255-26048580-7694-11eb-839a-3d2b83595c2d.png)
