### ISSUE TITLE
Tweak community search

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#779]
It cuts off at 10 results, that should be a little higher.

We might also want to rank users in the contributor group above those not in it.

**Comment by mirunacurtean** [comment]
Confirmed, now I have seen up to 30 results listed. What took longer was finding user profiles that had similar names, in stage - in this case, the simpler, the better :)

https://support.allizom.org/de/community/search?q=tom
https://support.allizom.org/en-US/community/search?q=harry
https://support.allizom.org/en-US/community/search?q=mary
https://support.allizom.org/en-US/community/search?q=anna

As for users in contributor groups ranking higher, I see in here an inconsistency https://support.allizom.org/en-US/community/search?q=raul, as the 6th user profile "None" is ranked above the one following it, although the former does not belong to any groups and the latter does. 
@LeoMcA Any thoughts on why is that?

**Comment by LeoMcA** [comment]
I'd guess it's because the 6th profile has an exact match for the username. The "users in contributor groups rank higher" isn't absolute, it just doubles their score, so it's still possible for contributors to rank below non-contributors if the search is a bad match.

**Comment by mirunacurtean** [comment]
> I'd guess it's because the 6th profile has an exact match for the username. The "users in contributor groups rank higher" isn't absolute, it just doubles their score, so it's still possible for contributors to rank below non-contributors if the search is a bad match.

In that case, there's no other issue. Marking this as Ready for Release.
