### ISSUE TITLE
Explore server-side rendering Instant Search

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#783]
Currently we have a separate set of templates for instant search and for the server-rendered search routes like https://support.mozilla.org/en-US/search?q=firefox

It would be great to just use one set of templates for our search interface, rendering them client side when using instant search, and server side when directly visiting the search routes.

We might want to use a framework for this.

**Comment by akatsoulas** [comment]
We are moving away from server side rendering with the ES7 enhancements and the new UI. Closing this
