### ISSUE TITLE
Fix the contributor count on the AAQ top contributor page

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#787]
On https://support.mozilla.org/community/top-contributors/questions

It says "There are more than 100 users with at least one contribution in the last 90 days.", despite only listing 97 users below.

**Comment by LeoMcA** [comment]
It's looking like this will be fixed by my solution to https://github.com/mozilla/sumo-project/issues/770 as well

**Comment by mirunacurtean** [comment]
Verified fixed; re-tested the Top Contributors KB and Localization pages as well. Test case results are [here](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=0&range=A60).
