### ISSUE TITLE
Deleted firefox account is not signed out and on subsequent account creation previous username and display name are asigned

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#789]
**Affected platforms:**
Windows 10 64-bit

**Browser version:**
FF 86

**Environment:**
Stage
This issue could not be reproduced on prod. 

**Accounts:**
mc23@mailinator.com
mc24@mailinator.com

**Steps to reproduce:**
1. Sign up with an account and update the username and display name.
2. From the Manage Firefox Account page, https://accounts.firefox.com/settings, delete the account.
3. Return to SUMO page and refresh/navigate to a different page/ exit and re-enter profile page. 
4. Sign out from SUMO and sign in again with the same account. Notice you have to sign up again but upon checking the account profile the previous username and display name are still there. 

**Expected results:**
Account is deleted and signed out from SUMO. Upon creating the same account the username is derived from the created account and there is no display name yet. 
![deleted account expected results](https://user-images.githubusercontent.com/53306802/109165438-385dec80-7784-11eb-8756-eed3bcba78fd.gif)

**Actual Results:**
The account is still signed in on SUMO pages after being deleted from fxa and upon checking the account profile the previous username and display name are still used.

![deleted account is not signed out and profile is preserved](https://user-images.githubusercontent.com/53306802/109164108-b8835280-7782-11eb-9b28-95e7ee7d5a9e.gif)

**Note:** 
I reproduced this issue with the accounts I was testing [Remove invalid characters from auto-created usernames](https://github.com/mozilla/sumo-project/issues/739) by constantly updating the username with valid and invalid characters, so it's possible this may have affected the account.

**Comment by akatsoulas** [comment]
The staging environment is not receiving notifications from FxA. I am moving this under QA for now and we will validate the deactivation in prod where notifications are currently working fine.

**Comment by mirunacurtean** [comment]
Does not occur on support.mozilla.org. 
Created, updated profile username and display name for mc23@mailinator.com and after deleting the account through Manage Firefox Account page, the account was signed out from it, and also from the sumo site upon further navigation. 
Upon signing up with the account again, the username has been set by default as in the previous account creation and no display name had been set yet, 
Closing this as it is probably caused by the fxa notification staging issue.
