### ISSUE TITLE
Remove marketplace and zendesk integration.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#79]

**Comment by akatsoulas** [comment]
For testing we should focus on that the AAQ works as before and it's not affected by this removal

**Comment by mirunacurtean** [comment]
Tested successfully on Desktop Windows pro 10 64- bit and MacOS X 10.14 and mobile android and iOS devices on FF and Chrome browsers. 
Checked that flow can be enter signed in and not, choosing selecting product, changing product, exploring articles and topics on Solutions page and testing that Ask the Community widget message and functionality behave as expected depending on user being signed in or not.  
Also tested search functionality and opening results (articles,threads) or selecting the "Ask the community" button from the banner if that shows when there are 0 results. 
Posted/ edited and replied to questions on both desktop and mobile successfully. 
https://support.allizom.org/en-US/questions/1207055#answer-1082290
https://support.allizom.org/en-US/questions/1207054
