### ISSUE TITLE
Exempt certain groups from the spam filter

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#791]
https://bugzilla.mozilla.org/show_bug.cgi?id=1690914

**Comment by mirunacurtean** [comment]
Confirmed fixed for group members or group leaders belonging to:

- [SUMO Locale Leaders](https://support.allizom.org/en-US/groups/sumo-locale-leaders)
- [Knowledge Base Reviewers](https://support.allizom.org/en-US/groups/knowledge-base-reviewers)
- [Reviewers](https://support.allizom.org/en-US/groups/reviewers)

Users belonging to other groups cannot post the same response without it being marked as spam. 
The contribution of users that do not belong to any group, or that were deleted from the groups mentioned will have their posts marked as spam. 
Test cases [here](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=1890517993&range=B19).
