### ISSUE TITLE
Tapping on the Mozilla support logo does not return the user by default to homepage

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#795]
**Environment:**
Stage - suppot.allizom.org

**Device:**
Windows 10 64-bit

**Browsers:**
Firefox 86.0 (64-bit)
Version 89.0.4389.72 (Official Build) (64-bit)

**Preconditions:**
https://github.com/mozilla/sumo-project/issues/793
Note that this issue is only sometimes reproducible, possibly only after multiple search attempts. 

**Steps to reproduce:**

1. Go to https://support.allizom.org/en-US/.
2. In the search bar type at a normal speed a keyword or phrase to fin, for example "disable cookies". 
3. Possibly due to https://github.com/mozilla/sumo-project/issues/793 the search will fail.  If not, perform multiple search queries in order to get stuck in a page that only returns results for cutoff search keywords. 
4. When that occurs, try to refresh the page by tapping on the "Support Mozilla" logo or use the page refresh option. 

**Actual result:**
Page is not refreshed and the search bar with the types input is still displayed. 
![Refresh page does not default to homepage](https://user-images.githubusercontent.com/53306802/110142091-7be8d400-7dde-11eb-98a3-6dccd83464d6.gif)

Another example, using different steps. When returning the results for page 2 was lagging, the page was refreshed in order to return to homepage for a new search. 
![another refresh issue example](https://user-images.githubusercontent.com/53306802/110144362-ec90f000-7de0-11eb-88c1-e8af5732fa5c.gif)

**Expected result:**
Return to homepage. Clear search bar,

**Comment by LeoMcA** [comment]
After the history API addition, refresh re-opening search is expected: just as back/forward can take you in/out of search, refresh should re-load whatever the current search state is.

But the Chrome behaviour of search re-opening when clicking on the homepage link isn't expected, https://github.com/mozilla/kitsune/pull/4706 should fix that.

**Comment by mirunacurtean** [comment]
**To clarify the Expected Results:** 
1. As Leo mentioned, the refresh part is supposed to re-open the search the user is undergoing at the moment. 
This is was working as intended, and quick check did not reveal any new issues. 
2. The actual issue in this case was that selecting the homepage link while in the midst of a search, would not redirect to homepage,
This has been verified fixed - on Desktop (Windows 10 64-bit) across Firefox and Chrome and on Android on Firefox. 

![Redirect to homepage working as expected](https://user-images.githubusercontent.com/53306802/110950546-a5f54580-834c-11eb-8837-c39c5a2e352a.gif)
