### ISSUE TITLE
Exempt question owner from spam filtering 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#796]

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4705
https://bugzilla.mozilla.org/show_bug.cgi?id=1675424

**Comment by mirunacurtean** [comment]
Verified. Question owner initial post and replies are exempted from spam filtering.
Test cases [here](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=1890517993&range=B30).
