### ISSUE TITLE
Split ES query for each index

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#797]
We should split the search query so that will only query the relevant to each index fields instead of having one big for everything. By spiting we are expecting significant performance gains that will offset to a certain degree the performance penalty that we are monitoring in staging from the synonyms field expansion

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4711

**Comment by akatsoulas** [comment]
This should yield a 2-3x better performance when it comes to synonyms. Regarding verification, search should behave as before and have no errors.

**Comment by mirunacurtean** [comment]
Tested extensively in throughout re-tests of https://github.com/mozilla/sumo-project/issues/721, https://github.com/mozilla/sumo-project/issues/748 and https://github.com/mozilla/sumo-project/issues/795 and no issues were encountered.  Will also be closing https://github.com/mozilla/sumo-project/issues/793 as a result.
