### ISSUE TITLE
Link to profile contribution document fails when the profile username contains a "+" character

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#802]
**Environment:**
Only tested in stage

**Steps to reproduce:** 
1. Go to https://support.allizom.org/en-US/user/mcurtean%2041. 
2. Click on the document link. 

**Actual results:**
404 Page not found,.

**Expected result:** 
Redirect to article page. 

Note:  @mirunacurtean This issue should be investigated further in production and also to check if it occurs using other symbols in the username

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4714

**Comment by mirunacurtean** [comment]
Verified fixed using all accepted symbols and performed a bit of regression testing on username field to verify that other types of symbols and blank spaces are not accepted when updating the username. Test cases linked [here](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit#gid=0&range=A77).
