### ISSUE TITLE
[regression] Posts from trusted contributors are marked as spam

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#804]

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4719

**Comment by mirunacurtean** [comment]
Fix verification and regression testing covered in [Test Rail test run](https://testrail.stage.mozaws.net/index.php?/runs/view/41375&group_by=cases:section_id&group_order=asc&group_id=125912).
