### ISSUE TITLE
Remove ES 2.x from kitsune.wiki.facets.documents_for

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#806]
We use ES 2.x in `kitsune.wiki.facets.documents_for` to fetch documents ordered by their last 30 days of helpful votes.

This is used on topic listings like https://support.mozilla.org/en-US/products/firefox/basic-browsing-firefox, and on the fallback results we return when a search has 0 results.

We have a couple of options here:

**Add `recent_helpful_votes` field to `WikiDocument` in ES 7.x:**

This would also require a daily job to update the values (since we can't rely on a signal triggering every day and making this count accurate).

Iterating over parents in that job, and submitting an update like this, should be pretty low-impact on ES performance (unlike a full wiki re-index would be every day):
```
{
  "recent_helpful_votes.en-US": 30,
  "recent_helpful_votes.de": 15,
  ...
}
```

Having this field may also prove useful in future metrics.

**Do this in SQL instead:**

`documents_for` already falls back to SQL if the ES operation errors out. It doesn't currently attempt to order by helpful votes, but this is perfectly possible with an aggregation like this:

```
.annotate(
    annotated_recent_helpful_votes=Subquery(
        HelpfulVote.objects.filter(
            revision_id=OuterRef("current_revision__id"),
            created__gt=datetime.now() - timedelta(days=30),
            helpful=True,
        )
        .order_by()
        .values("revision")
        .annotate(count=Count("*"))
        .values("count"),
        output_field=IntegerField(),
    )
)
.order_by("annotated_recent_helpful_votes")
```

(This seems rather long-winded, but it's what django recommends upstream for annotating with a `Subquery`: https://docs.djangoproject.com/en/2.2/ref/models/expressions/#using-aggregates-within-a-subquery-expression)

Performance will be worse than ES because it's a relatively heavy aggregation, however we're caching these views, and this is the only place I can see that we currently use `recent_helpful_votes`, so do we want to clutter our ES mapping with it?

Thoughts @akatsoulas?

**Comment by LeoMcA** [comment]
Expected behaviour:

Topic pages (like https://support.allizom.org/en-US/products/firefox/basic-browsing-firefox) have their documents ordered by their ascending `display_order` (set through https://support.allizom.org/admin/wiki/document/), and when display orders are equal, their their descending positive votes (the thumbs up icon in the document sidebar).

We're heavily caching these pages: 5 minutes for the list of documents itself (i.e. a new document won't appear for at worst 5 minutes), and the votes for 24 hours (i.e. new votes won't affect the ordering for at worst 24 hours, new documents' votes won't appear for at worst 24 hours).

So, precisely verifying the ordering will be quite tricky, however I'm pretty confident it's working as intended from introspecting things locally, so testing can focus on more general things like: testing the correct documents appear for a topic, testing new documents appear (once the cache has expired), testing no errors appear and there's no obvious performance problems.

**Comment by mirunacurtean** [comment]
So far I've:
- successfully created a [new article](https://support.allizom.org/en-US/kb/helpful-votes) and verified it showed under the selected topic. As expected, being a new article without any votes, it showed last in the list. 
![image](https://user-images.githubusercontent.com/53306802/115358484-641ab300-a1c6-11eb-8f9a-9468b6f8f06b.png)
- changed [another article](https://support.allizom.org/en-US/kb/search-based-one-keyword-test)'s product/topic and verified it shows under the new product/ topic and not the old one anymore. 
![image](https://user-images.githubusercontent.com/53306802/115358859-c378c300-a1c6-11eb-8bee-b5994941a01d.png)

-I've added helpful and unhelpful votes to some articles but so far their order has not been affected. Waiting to check again after the 24 hour period has elapsed. 
![image](https://user-images.githubusercontent.com/53306802/115359029-edca8080-a1c6-11eb-9340-b8a253162a3b.png)

No other issues have occurred.

**Comment by mirunacurtean** [comment]
**Expected results:**
Only positive votes are counted towards making a changing in the article descending order.

Voted again +1: for _helpful votes_ and _plushies are awesome test - wildcard test?_ and one +1: + one :thumbsdown: for Search based on content (which does not impact the count)
![image](https://user-images.githubusercontent.com/53306802/115520320-b5907400-a292-11eb-9d10-8007d47e1fea.png)
