### ISSUE TITLE
Get baseline metrics for Play Store transition

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/sumo-project#811]
We need the following data as baseline metrics to measure the success of the transition from Respond to Conversocial: 

* Total users/contributors (all time)
* Total replies made (Since July 28, 2020)
* Total moderation (Since July 28, 2020)
* Total replies approved and published (Since July 28, 2020)
* Total review replied (approved and published) per month from July 2020-Feb 2020 (breakdown per locale)

**Comment by LeoMcA** [comment]
@kelimuttu I've compiled the data here: https://gist.github.com/LeoMcA/7ef01b8f5df9df4304503a180cb8b50d

**Comment by kelimuttu** [comment]
Thank you as always, Leo.
