### ISSUE TITLE
Use ES 7.x in "See Also" section on questions

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#817]
https://github.com/mozilla/kitsune/pull/4738

**Comment by mirunacurtean** [comment]
An equal number of questions and articles are linked in See Also section for English and Non-English questions. 
Redirects are functional. 

![image](https://user-images.githubusercontent.com/53306802/114424523-e0a70380-9bc0-11eb-82ea-0515f620d01f.png)

![image](https://user-images.githubusercontent.com/53306802/114424548-e7357b00-9bc0-11eb-9116-1a0849bb11f5.png)
