### ISSUE TITLE
ES 7.x search html route

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#818]
Hook up a html version of the `/search/v2` route, which can replace the `/search` html route once we remove all of search v1's routes.

Nothing as involved as https://github.com/mozilla/sumo-project/issues/783

**Comment by LeoMcA** [comment]
Expected behaviour: https://support.allizom.org/en-US/search/v2/ behaves like https://support.allizom.org/en-US/search, however has the same results as instant search v2.

**Comment by mirunacurtean** [comment]
It certainly looks like the results in https://support.allizom.org/en-US/search/v2/ and https://support.allizom.org/en-US/#search receive the same results:
![image](https://user-images.githubusercontent.com/53306802/115234404-aa6a0680-a121-11eb-8247-1a63a8372b1c.png)


I am wonder @LeoMcA if in this case the search results should be so restricted, to only the exact results, and without offering any alternative results that contain, if not all, the some of the search words. 
Search v2
![image](https://user-images.githubusercontent.com/53306802/115234385-a5a55280-a121-11eb-858a-8339e1f0cb1a.png)

https://support.allizom.org/en-US/search results  - no other results contains all search terms but they do have at least one. 
![image](https://user-images.githubusercontent.com/53306802/115234583-e00eef80-a121-11eb-9371-4930c1845864.png)

**Comment by LeoMcA** [comment]
> I am wonder @LeoMcA if in this case the search results should be so restricted, to only the exact results, and without offering any alternative results that contain, if not all, the some of the search words.

Yes, something like this is a feature I think we want to explore in the next phase, I've opened an issue here: https://github.com/mozilla/sumo-project/issues/832
