### ISSUE TITLE
Images in Gallery are zoomed in and partially displayed

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#82]
**STR:**
1. Login to Sumo staging
2. Navigate to Gallery page (/gallery/images)

**Expected:**
Images are displayed entirely in the page

**Actual:**
Images are displayed partially in the page, they are zoomed in.
This is not happening in production. 

![Screenshot_2019-10-08 Media Gallery Mozilla Support](https://user-images.githubusercontent.com/5293100/66387630-043a2e00-e9cd-11e9-8ea5-c2fced6cf8da.png)

**Comment by mirunacurtean** [comment]
No longer occurs on either Stage or Production. Tested across windows pro 10 with FF 79 and Chrome 84 and on mobile Android 9.0.0 on FF 68.11.0. 
Marking this as closed. 
![image](https://user-images.githubusercontent.com/53306802/89545558-2e869300-d80c-11ea-8f1a-059c6b2c09b7.png)
![image](https://user-images.githubusercontent.com/53306802/89545603-3f370900-d80c-11ea-830e-ea575ad3f9e8.png)
