### ISSUE TITLE
Exclude wiki articles belonging to the Administration category from search

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#824]

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4749

**Comment by mirunacurtean** [comment]
@akatsoulas I was not entirely sure how to verify if the articles belonged to the Administration category, but as a workaround I performed and advanced search using the "Administration" category. 

![image](https://user-images.githubusercontent.com/53306802/115022115-9b871800-9ec5-11eb-8aab-6fc5ccc7d09a.png)

Then I've taken the titles of the search results for "firefox" and used them in instant search.
![image](https://user-images.githubusercontent.com/53306802/115022225-c5403f00-9ec5-11eb-98bc-ead6e638e21e.png)

No results or not the same results found in advanced search was listed when using their titles across:

- https://support.allizom.org/en-US/
- https://support.allizom.org/en-US/products#search
- https://support.allizom.org/en-US/questions

Is this the intended behavior?
