### ISSUE TITLE
Implement paginator for ES 7.x search classes

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#825]

**Comment by mirunacurtean** [comment]
Wroks as expected in:

-  community search 

![image](https://user-images.githubusercontent.com/53306802/115025396-f589dc80-9ec9-11eb-9d74-7f7f8a538b33.png)

- forums
![image](https://user-images.githubusercontent.com/53306802/115029654-df324f80-9ece-11eb-8b4e-242df4831752.png)

- homepage 
![image](https://user-images.githubusercontent.com/53306802/115029927-2ddfe980-9ecf-11eb-8139-1de1933aaae4.png)

- forum support
![image](https://user-images.githubusercontent.com/53306802/115030033-4bad4e80-9ecf-11eb-8d39-d89106f52001.png)

-wiki
![image](https://user-images.githubusercontent.com/53306802/115030157-75667580-9ecf-11eb-8c75-5466283a3a05.png)
