### ISSUE TITLE
Deprecate advanced search (ES2)

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#826]

**Comment by mirunacurtean** [comment]
Link is no longer available in Tools section.
![Advanced search link no longer available](https://user-images.githubusercontent.com/53306802/116533731-6679bd00-a8ea-11eb-9a6e-781aa7fa394f.png)
Typing in the url redirects to Page not found.
![image](https://user-images.githubusercontent.com/53306802/116533872-8a3d0300-a8ea-11eb-9a11-d819c72dc376.png)

Did not see other advanced search links while testing https://github.com/mozilla/sumo-project/issues/842
