### ISSUE TITLE
Date modified after a question is edited is not correct in some cases

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#827]
**Environment:**
Stage

**Platform:**
Windows

**Browsers tested on** 
Firefox 81.0
Chrome

**Preconditions:**
Sign in with an account that is either a superuser/moderator that can edit other accounts profiles.

**Steps to reproduce:** 

1. Go to https://support.allizom.org/en-US/questions/1207128. 
2. Select to edit the question. 
3. Update issue description and then save it. 
4. View modified date. 

**Actual results:**
Date modified is not the actual date. 
![image](https://user-images.githubusercontent.com/53306802/114418957-abe47d80-9bbb-11eb-87ee-ab8be4cabcae.png)

**Expected results:**
Question https://support.allizom.org/en-US/questions/1207173 was also modified and the date is correct in its case. 

![image](https://user-images.githubusercontent.com/53306802/114418909-a2f3ac00-9bbb-11eb-8197-c07aca47ca3e.png)

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/4759

**Comment by mirunacurtean** [comment]
Looks good to me now. See https://support.allizom.org/en-US/questions/1207177#answer-1082623.
Time of edit and.for eaxh post id updated as well when the user changes their profile timezone.
