### ISSUE TITLE
Results pages containing questions on /search/v2 error

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#833]
The template is trying to load an attribute we no longer store for questions in ES.

E.g. https://support.allizom.org/en-US/search/v2/?q=spam+test

**Comment by mirunacurtean** [comment]
Simple Search made from url is successful
![image](https://user-images.githubusercontent.com/53306802/115418550-3eab9a80-a202-11eb-89ab-3e05ac1e6906.png)

multi keyword search will bring most relevant and closest exact match to the top
![image](https://user-images.githubusercontent.com/53306802/115419604-21c39700-a203-11eb-87d9-aceca40f6746.png)

If there is no close match the results will be the ones including at least one keyword or their synonyms. 
![image](https://user-images.githubusercontent.com/53306802/115421959-1c674c00-a205-11eb-9ff1-dbfc9de327ed.png)

Functionality is ensured for non-English languages as well
![image](https://user-images.githubusercontent.com/53306802/115422230-618b7e00-a205-11eb-84ea-a6665c3dd9d6.png)
