### ISSUE TITLE
KB Top Contributor profile is not updated with new article contribution

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#835]
**Environment:**
Stage

**Preconditions:**
Account A adds a new article. 
Account B (that must be at least a KB reviewer with permissions) approves of the article. 

**Steps to reproduce:**
1. Go to https://support.allizom.org/en-US/community/top-contributors/kb
2. Note MC.5 profile card and the number of contributions in the last 90 days. 
3. View https://support.allizom.org/en-US/user/MC.5 the 2 documents added and their history. 

**Actual results:**
Both documents have been added in the last 90 days but only one is counted in the KB top contributor page profile. 
The most recent article https://support.allizom.org/en-US/kb/helpful-votes/history is not counted in the number of contributions made. 

**Expected result:**
All reviewed and approved articles should count as a contribution in the user's profile in the Top contributors page.

**Comment by LeoMcA** [comment]
Looks like this was a caching issue, the count is displaying correctly now.
