### ISSUE TITLE
Filtering by product on Top Contributors - Localization shows no (or hardly any) results

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#837]
Found by @mirunacurtean, affects prod too:

https://support.mozilla.org/en-US/community/top-contributors/l10n?product=firefox

The issue is the same as one we faced when migrating topic listings to the DB, most localised documents won't have the product set on them, but instead the product is set on their parent. So filtering must happen against `document__products` OR `document__parent__products`.

**Comment by mirunacurtean** [comment]
Sorting from Community hub pages or directly from Top contri9butor page is successful using:

- filter by language
![image](https://user-images.githubusercontent.com/53306802/116094779-7dcd6600-a6b0-11eb-8c69-a745705371ed.png)


- filer by product

![image](https://user-images.githubusercontent.com/53306802/116094945-a2c1d900-a6b0-11eb-9f5b-dd0a476ebaad.png)


- filter by language and product
- 
![image](https://user-images.githubusercontent.com/53306802/116094868-92116300-a6b0-11eb-9cdb-93e55704b999.png)

![image](https://user-images.githubusercontent.com/53306802/116094680-6b532c80-a6b0-11eb-95d8-527b7c0cf816.png)
