### ISSUE TITLE
Some account contributions do not show in Support Forum Top Contributors page

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#838]
**Environment:**
Stage

**Preconditions:**
Create a new account and respond to some questions in support forum. 

**Steps to reproduce:**
1. Respond to questions in support forum. 
2.  View that responses show in [latest answers](https://support.allizom.org/en-US/user/mercredi73/answers) list.
3. Wait a few minutes to check [Support Forum Top Contributors page](https://support.allizom.org/en-US/community/top-contributors/questions).
4. Verify that account profile card is showing in forum and the number of contributions is updated.

**Expected results:**
Profile card is showing in forum and the number of contributors is updated.
Number of contributions made is also synched with account profile (without counting spam posts)

**Actual result:**
Account still does not show in Support Forum Top Contributors page. 

![image](https://user-images.githubusercontent.com/53306802/115513618-eae59380-a28b-11eb-8ce4-af399061c0cb.png)

This also occurs with contributions made by https://support.allizom.org/en-US/user/profile_update_2/answers. 
Maybe the common thread here is that neither account is part of a Group.

**Comment by akatsoulas** [comment]
This should be now fixed
