### ISSUE TITLE
Support sub-products in the project

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#84]
We should provide the ability to add a product under a category of products. This change should respect the following requirements:

- [ ] The product url schema must remain the same
- [ ] Extra validation should make sure that no nested products will have the same title and slug with the parent product.

**Comment by ovidiuboca1** [comment]
@akatsoulas  please let me know how can I test this? Do I need to have an admin account?

**Comment by akatsoulas** [comment]
Moving this to backlog. We can revisit this in the next sprint.

**Comment by akatsoulas** [comment]
Closing for now until we have a more detailed plan for IA.
