### ISSUE TITLE
Move /search endpoint to ES7

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#842]
Drop search/v2 endpoint

**Comment by mirunacurtean** [comment]
Verified in:

- Support homepage 

![image](https://user-images.githubusercontent.com/53306802/116530328-91faa880-a8e6-11eb-87b8-c706874c848d.png)
![image](https://user-images.githubusercontent.com/53306802/116530054-434d0e80-a8e6-11eb-881e-449f3a321bc7.png)
![image](https://user-images.githubusercontent.com/53306802/116530206-71cae980-a8e6-11eb-84ad-8ef06e2b9814.png)

- AAQ search:
- general aaq search
![image](https://user-images.githubusercontent.com/53306802/116530656-f1f14f00-a8e6-11eb-8f31-76e529c62c22.png)

- specific product 
![image](https://user-images.githubusercontent.com/53306802/116530879-341a9080-a8e7-11eb-9dc7-d2ec3f9bba73.png)

- in KB support pages
![image](https://user-images.githubusercontent.com/53306802/116531773-34675b80-a8e8-11eb-8964-965ce23a5751.png)
![image](https://user-images.githubusercontent.com/53306802/116531920-582aa180-a8e8-11eb-8168-0fd667b2126b.png)

- in Discussion forums 
![image](https://user-images.githubusercontent.com/53306802/116532183-a50e7800-a8e8-11eb-81ae-478dc048ac95.png)

![image](https://user-images.githubusercontent.com/53306802/116532096-8e682100-a8e8-11eb-9dbb-fc1c7b4eca19.png)

![image](https://user-images.githubusercontent.com/53306802/116532994-8f4d8280-a8e9-11eb-830f-82e955512ec3.png)


- Contributors Support
![image](https://user-images.githubusercontent.com/53306802/116532889-72b14a80-a8e9-11eb-8640-ee70b8bc4d2c.png)

- Community Hub
![image](https://user-images.githubusercontent.com/53306802/116533119-ad1ae780-a8e9-11eb-831a-1e499f29e676.png)
![image](https://user-images.githubusercontent.com/53306802/116533183-bd32c700-a8e9-11eb-9f44-24beec2b2a4b.png)

-Media Gallery search 
![image](https://user-images.githubusercontent.com/53306802/116533293-dfc4e000-a8e9-11eb-9588-c062bd2680e2.png)
