### ISSUE TITLE
Advanced search syntax

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#843]

**Comment by LeoMcA** [comment]
QA: the priority here is verifying that simple search works as it did before, if/when you find bugs with the advanced search syntax itself please file them, but if they don't affect simple search then we'll fix them after release.

More docs coming, but at a high level:

* This allows special syntax in all search fields (instant, /search/, forum and user)
* Syntax adds:
  * Boolean operators (`AND`/`OR`/`NOT`) (this replaces the `+ | -` syntax we used to have)
  * Field operator (`field:field_name:query`) to do a query on a different field
  * Exact token (`exact:field_name:query`) to do an exact match on a field
  * Range token (`range:field_name:operator:query`) to do a range search on a field
* `"quoted phrase"` queries should still work as they did before (matching the phrase, and turning off synonyms)

**Comment by mirunacurtean** [comment]
@LeoMcA It was my understanding that using the AND operator will actually show less results as both/all search terms should be present in each search result found. 
And yet in the example below I get more results when using AND, while not all results contain the expected second term "tracking". Am I misunderstanding something about this functionality?
![AND operator](https://user-images.githubusercontent.com/53306802/119656518-75915380-be33-11eb-981d-4d791a6d4e14.gif)

**Comment by LeoMcA** [comment]
This looks to be the same issue as https://github.com/mozilla/sumo-project/issues/836. Good catch, I'll add it to the docs for now as a known (but potentially useful) quirk.

**Comment by mirunacurtean** [comment]
All tests across AAQ, Product, Forum or user search have been passed. A combination of all new operators have been used: Boolean, Field operators, exact tokens and the Range field queries. 
See [Advanced Search Test Run](https://testrail.stage.mozaws.net/index.php?/runs/view/44111&group_by=cases:title&group_order=asc&group_id=-1) for more details.
