### ISSUE TITLE
Product page links from German page defaults to browser language 

### ISSUE THREAD

**Issue by dalexsy** [mozilla/sumo-project#845]
While on https://support.mozilla.org/de/ product pages linked at the top of the page (e.g. https://support.mozilla.org/products/firefox) redirect to en-US (https://support.mozilla.org/en-US/products/firefox) instead of de when browser language is set to en-US.

**Comment by mirunacurtean** [comment]
Works as expected for all Product (Explore our Help Articles) links. Verified on DE, FR, ES, CH and AR. 
This seems to be partial issue of https://github.com/mozilla/sumo-project/issues/711, but it seems the fix applies overall so I will close that too after a few more tests.
![FF Product](https://user-images.githubusercontent.com/53306802/119821687-85746a80-befb-11eb-815f-5189859cdc3b.gif)

@LeoMcA One things that could also be translated are the page breadcrumbs.  Is this up to the specific localization team or something I should add an issue for?

**Comment by LeoMcA** [comment]
> @LeoMcA One things that could also be translated are the page breadcrumbs. Is this up to the specific localization team or something I should add an issue for?

I think they are translated, "Start" is German for begin, and I think we go for the shorter form "Firefox" rather than "Firefox Help" in breadcrumbs to save space.
