### ISSUE TITLE
????

### ISSUE THREAD

**Issue by andrewhager9** [mozilla/sumo-project#849]
Not sure what's going on with this. Someone is hacking my network

**Comment by LeoMcA** [comment]
Hi Andrew,

I think you might be accidentally subscribed to notifications for this repository and https://github.com/mozilla/kitsune/.

You can unfollow notifications on these repositories by following the instructions here: https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions

Thanks,
Leo
