### ISSUE TITLE
"An error occurred" /500 Internal server error is received when using a gte/gt date range search on forum posts

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#855]
**Environment:**
Stage

**Precondition:**
Account is logged in. 
Documentation for using the correct range format: https://kitsune.readthedocs.io/en/latest/advanced-search.html#range-query

**Steps:**
1. Go to https://support.allizom.org/en-US/forums/contributors/.
2. Use the range:updated:gte:2021-01-01 querry. 
3. View result. 

**Expected result:**
If there are no posts that fit in that range "0 results" should be listed. 

**Actual result:**
An internal server error is received.

![image](https://user-images.githubusercontent.com/53306802/120683027-cfce8c00-c4a5-11eb-9f14-381438f4752f.png)

**Note:**
**Using the same range in Products search or AAQ get successful results.** 

![image](https://user-images.githubusercontent.com/53306802/120683329-2c31ab80-c4a6-11eb-80e8-40e8910e3ae5.png)
![image](https://user-images.githubusercontent.com/53306802/120683366-3489e680-c4a6-11eb-969f-79f18e1ee47f.png)

**Using `lt/lte` operator values in the range query is successful.** 

![image](https://user-images.githubusercontent.com/53306802/120683611-8599da80-c4a6-11eb-915f-dca4b1b41dbb.png)

**Comment by akatsoulas** [comment]
This is now fixed. It turns out that we hadn't updated the index after slightly changing the ForumDocument. FYI, for the prod release!

**Comment by mirunacurtean** [comment]
Verified fixed using all operator values (lt, lte, gt, gte).
![image](https://user-images.githubusercontent.com/53306802/120787871-7a8f8a80-c538-11eb-96a4-f8a8c70a6c32.png)
