### ISSUE TITLE
Gracefully handle errors in the search time range operators

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#871]

**Comment by mirunacurtean** [comment]
This will need to be retested when the fix for https://github.com/mozilla/sumo-project/issues/931 is done so I'd rather keep it in QA still.

**Comment by mirunacurtean** [comment]
Verified fixed along with #931 
![image](https://user-images.githubusercontent.com/53306802/132232620-a07095a0-3925-49f9-840a-49ab54246181.png)
[Regression testing](https://testrail.stage.mozaws.net/index.php?/runs/view/47571&group_by=cases:section_id&group_order=asc&group_id=189817
) revealed no issues either.
