### ISSUE TITLE
"WAS THIS HELPFUL TO YOU?" is capitalized on all responses

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/sumo-project#90]
On this page:
https://support.mozilla.org/en-US/questions/1262513

"Was this helpful to you?" has "text-transform: uppercase;"

**Comment by mirunacurtean** [comment]
Can no longer be reproduced. Thread was archived. 
Current message on showing underneath question replies is just "Helpful?" and it does not use uppercase for the whole text. 
![image](https://user-images.githubusercontent.com/53306802/89547017-e9636080-d80d-11ea-9622-96f92c151ed0.png)

Marking this as closed.
