### ISSUE TITLE
Update copy in templates for Zendesk

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#913]
We need to update the copy in:

- Ask the community central banner in the topic selection under a product
- Update the Ask the Community button
- Update text under the product selection in `/questions`
- Anything else here?

Specs: https://www.figma.com/file/wBfU2L6jfX6hAac1QPg2Bq/Zendesk-Integration-%2F-Copy-Updates?node-id=0%3A1

**Comment by LeoMcA** [comment]
Partially done in https://github.com/mozilla/kitsune/pull/4876.

Waiting to hear what we should do with the "Ask the community" text and description in the navbar.
