### ISSUE TITLE
Redirect to the second step of the AAQ flow when the `Ask the Community` button is used 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#914]
In the central banner in each product, under the topic selection, we should redirect users directly to the second step of the AAQ without asking them to re-select a product

**Comment by mirunacurtean** [comment]
No issues in this regard across Desktop and mobile (Windows 10 and Android 9.0.0) with Firefox and Chrome browsers. 
Tests are included In [this](https://testrail.stage.mozaws.net/index.php?/runs/view/47041&group_by=cases:section_id&group_order=asc&group_id=223193) suite.
