### ISSUE TITLE
Handle external to SuMo AAQs

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#915]
Some locales have external AAQs. For such locales, we need to redirect users to the internal AAQ if the product is backed by Zendesk

1. [x] Move en-US redirect to just before AAQ step 3 (in locales which don't have an internal forum for the product)
2. [x] For non-premium products*, redirect to the special KB article, instead of the en-US AAQ
3. [x] Remove direct links to the special KB article from the main navigation bar, link to the step 1 of the locale’s AAQ instead
4. [x] Show the product-specific AAQ banner on all products regardless of locale

\* to know if a product is premium or not, we need to do https://github.com/mozilla/sumo-project/issues/917 - but we can implement this before then, and just have a block of code not called until after implementing that

**Comment by mirunacurtean** [comment]
**Tested successfully on Desktop (Windows 10) and mobile (android and iOS) . 
TestRail test run for [Sumo to Zendesk flows](https://testrail.stage.mozaws.net/index.php?/runs/view/47041&group_by=cases:section_id&group_order=asc&group_id=223193)** 
**Related bugs added:**
https://github.com/mozilla/sumo-project/issues/935
https://github.com/mozilla/sumo-project/issues/938

**Comment by mirunacurtean** [comment]
Verified related bug fixes.: https://github.com/mozilla/sumo-project/issues/938, https://github.com/mozilla/sumo-project/issues/939, https://github.com/mozilla/sumo-project/issues/943
Preformed feature/ regression: [Test Rail ](https://testrail.stage.mozaws.net/index.php?/runs/view/47572&group_by=cases:title&group_order=asc&group_id=-1)
Markinng this as Ready for Release.
