### ISSUE TITLE
Reflect subscription status in user profiles

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#919]
We should keep the profiles updated with the sub status of each user

**Comment by dalexsy** [comment]
We can integrate subscriptions into a user's profile by adding a "My Subscriptions" tab where all subscriptions are listed.
[Integration mockups](https://www.figma.com/file/FYZ3LobijtNg4PT9OGjP65/User-Profile-Updates-My-Subscriptions?node-id=0%3A1)

**Comment by mirunacurtean** [comment]
User profile > My subscriptions shows which product/ products the user is subscribed to. 
![image](https://user-images.githubusercontent.com/53306802/134036801-b1debf42-b0a1-40b6-9a41-a6756ca92c6e.png)
![image](https://user-images.githubusercontent.com/53306802/134036825-ff79e630-c928-45a5-99b0-8d5b1470fe98.png)
