### ISSUE TITLE
Create all the attributes that are needed in Zendesk for tickets

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#923]
relevant information 
https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/routes/subscriptions/support.ts

**Comment by LeoMcA** [comment]
Not entirely clear on what this issue entails, but I presume it's done in https://github.com/mozilla/kitsune/pull/4876

**Comment by mirunacurtean** [comment]
Zendesk successfully receives data concerning user (username, display name, language. and email) and their updates and also all the information from the sumo Get support form is associated with a field in zendesk (topic, platform, subject, message)
