### ISSUE TITLE
Support user ops in Zendesk

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#924]
* User creation
* Keep data up to date
* User browser locale for user language

**Comment by mirunacurtean** [comment]
Confirmed.  
Account is created successfully and can submit tickets immediately. 
Account language is connected to browser language and this is reflected in zendesk. Updating the language from account profile before submitting a new ticket is as well reflected back in zendesk. 
https://user-images.githubusercontent.com/53306802/134141432-547662bc-0de5-4ee7-8fbe-b5924158a399.mp4

![image](https://user-images.githubusercontent.com/53306802/134142218-dd714c1b-483a-45e5-9d0e-559aecbc1e0f.png)

Updating email or account username is as well updated in zendesk in the ticket listings and all tickets submitted by the same user can be viewed together by select the user in zendesk, even after update. 
User ID is unchanged and can be verified against admin.
