### ISSUE TITLE
Do not show scam banner to products that don't have a public forum

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#929]

**Comment by LeoMcA** [comment]
Done in https://github.com/mozilla/kitsune/pull/4876

**Comment by mirunacurtean** [comment]
**premium product**
![image](https://user-images.githubusercontent.com/53306802/134036977-ea4ed251-c62e-4d45-ab64-2616119653a3.png)

![image](https://user-images.githubusercontent.com/53306802/134037098-cd625eec-6360-45c5-89b4-f40513a290ae.png)


**Non-Premium product**
![image](https://user-images.githubusercontent.com/53306802/134037042-8191b02c-506b-46e3-a5a4-0cc91e94b64b.png)
