### ISSUE TITLE
Do not show the AAQ banner under each product in readonly envs

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#933]

**Comment by mirunacurtean** [comment]
AAQ banner shows in regular stage environment. 
![image](https://user-images.githubusercontent.com/53306802/132354518-800ed7e4-0099-48d5-b7fa-0aff7d850059.png)

Does not show in stage readonly environment for any of the products. Tested on English and non-English locales. 
![image](https://user-images.githubusercontent.com/53306802/132354577-535eea87-343c-4816-bb93-eb8560522ce9.png)
