### ISSUE TITLE
Act upon profile-change FxA events

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#934]
We didn't do this when first implementing FxA events, because we need to get/store refresh_tokens for all users to support "offline" profile fetching.

However, we now need this for Zendesk integration.

**Comment by LeoMcA** [comment]
For QA: It doesn't look like this is working properly at the moment, as we don't seem to be getting the events from Firefox Accounts when we should. I'll update this card when we've heard back from the FxA team.

When it does start working: this means that updating an attribute in Firefox Accounts like email or profile picture should (near instantly) appear on your profile (after refreshing the page) without having to log out/in again.

Display name won't automatically update, because users can override this and we don't currently know if they have.

**Comment by akatsoulas** [comment]
This is working fine in prod.
