### ISSUE TITLE
Update products on staging to reflect prod AAQ

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#937]

**Comment by LeoMcA** [comment]
@mirunacurtean I've updated all the products on staging to have the same premium status as the ones on prod.

I've also added the products missing from the AAQ.

I *haven't* updated the topics to match those on prod, as there's rather a lot, and that's quite an involved process - so while the forms for all products should now load, submitting a form may fail as it tries to place the question in a topic which doesn't exist. If you'd like me to make sure all the correct topics exist for a set of products so you're able to test the full AAQ flow (now or in future) let me know for which, and I'll do it for those products.

**Comment by LeoMcA** [comment]
@mirunacurtean all the topics which exist for VPN and FPN should now exist on stage too - while they'll work for posting questions, they won't appear on step 2 of the aaq until they have at least on KB within them. You should have permissions to create the KB articles, so I'll leave that to you to do as and when you need them - if that's alright.

**Comment by akatsoulas** [comment]
Since this was about editing the products through the admin interface, I am closing the issue as done
