### ISSUE TITLE
Update user's primary email in zendesk

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#944]
When a user updates the primary email in FxA, we should propagate that change to Zendesk too (if there is an account).

**Comment by mirunacurtean** [comment]
Verified. Updated FxA primary email in FxA settings and they change has been propagated to the summited ticket in zeendesk (that was submitted under a different primary email) 
![image](https://user-images.githubusercontent.com/53306802/134036165-aed48d64-63b3-4159-9bdc-a342f9afeed7.png)
