### ISSUE TITLE
Remove existing 'Contact Us' button

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#947]

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/4892

**Comment by ameenamohsen94** [comment]
Why did you remove my zen desk ... mme Ameena true owner of the account Ian isn't he's my bf he's not supposed to have access or be part of my account... can you give me back control my phone isn't under my control tells me I'm childlocked sometimes he controls my phone now :/

**Comment by mirunacurtean** [comment]
![image](https://user-images.githubusercontent.com/53306802/134034648-f74fbf1d-0b7e-4052-81f1-8b29995e595e.png)
