### ISSUE TITLE
Add UITour.openPreferences button to KB markup

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#950]
At the request of the Firefox Suggest team: https://mozilla-hub.atlassian.net/browse/SNT-31

**Comment by LeoMcA** [comment]
Enable UITour on staging by adding the following about:config prefs:

`browser.uitour.testingOrigins` set to `https://support.allizom.org`
`browser.uitour.requireSecure` set to `false` (boolean)

I created https://support.allizom.org/en-US/kb/uitour-test to test the different syntax we have

**Comment by dadaa** [comment]
It works fine on my Nightly as well!

**Comment by chrisilias** [comment]
Yesterday, I asked people in the sumo matrix room to test this. So far, every report is that it works.

**Comment by mirunacurtean** [comment]
Verified by QA as well. 
![UITour works](https://user-images.githubusercontent.com/53306802/134328163-9d513293-8867-4e8e-b3b2-bfd81113524a.gif)
Had to do the refresh at the end, since it wiped out all other settings made in about:config.
