### ISSUE TITLE
accessibility keyboard and preferences

### ISSUE THREAD

**Issue by Pascale22** [mozilla/sumo-project#98]
keyboard navigation is not fully working in firefox preferences.

On MacOs Mojave using the keyboard to access Firefox preferences (shorcut command + ,).
Going through the preferences with the TAB key, when the wanted preference is highlighted, the return key is not selecting the preference in order to modify it.

Regards

**Comment by akatsoulas** [comment]
This doesn't seem like an issue of the SUMO platform but like an issue related to Firefox. Please use Bugzilla if this is the case or reopen if it's related to support.mozilla.org
